In [31]:
import pandas as pd
import numpy as np
import os

In [32]:
df = pd.read_csv("../data/raw/APY.csv")

print("Original shape:", df.shape)

Original shape: (345336, 8)

In [33]:
df.columns = df.columns.str.strip()

print(df.columns.tolist())

['State', 'District', 'Crop', 'Crop_Year', 'Season', 'Area', 'Production', 'Yield']

In [34]:
text_columns = ["State", "District", "Crop", "Season"]

for col in text_columns:
    df[col] = df[col].astype("string").str.strip()

In [35]:
print(df["Crop"].unique())

<StringArray>
[             'Arecanut',             'Arhar/Tur',                'Banana',
          'Black pepper',             'Cashewnut',               'Coconut',
         'Cowpea(Lobia)',          'Dry chillies',                'Ginger',
             'Groundnut',                 'Maize',     'Moong(Green Gram)',
        'Oilseeds total',   'Other Kharif pulses',        'other oilseeds',
     'Rapeseed &Mustard',                  'Rice',               'Sesamum',
             'Sugarcane',             'Sunflower',          'Sweet potato',
               'Tapioca',              'Turmeric',                  'Urad',
                 'Bajra',           'Castor seed',             'Coriander',
          'Cotton(lint)',                'Garlic',                  'Gram',
             'Guar seed',            'Horse-gram',                 'Jowar',
               'Linseed',                'Masoor',                 'Mesta',
            'Niger seed',                 'Onion',    'Other  Rabi pulses',
                'Potato',                  'Ragi',             'Safflower',
              'Sannhamp',         'Small millets',              'Soyabean',
               'Tobacco',                 'Wheat', 'Peas & beans (Pulses)',
                  'Jute',                'Barley',               'Khesari',
                  'Moth',         'Other Cereals',              'Cardamom',
   'Other Summer Pulses',                    <NA>]
Length: 56, dtype: string

In [36]:
state_mapping = {
    "THE DADRA AND NAGAR HAVELI": "Dadra and Nagar Haveli",
    "Laddak": "Ladakh",
    "CHANDIGARH": "Chandigarh"
}

df["State"] = df["State"].replace(state_mapping)

In [37]:
print(sorted(df["State"].dropna().unique()))
print("Number of states:", df["State"].nunique())

['Andaman and Nicobar Island', 'Andhra Pradesh', 'Arunachal Pradesh', 'Assam', 'Bihar', 'Chandigarh', 'Chhattisgarh', 'Dadra and Nagar Haveli', 'Daman and Diu', 'Delhi', 'Goa', 'Gujarat', 'Haryana', 'Himachal Pradesh', 'Jammu and Kashmir', 'Jharkhand', 'Karnataka', 'Kerala', 'Ladakh', 'Madhya Pradesh', 'Maharashtra', 'Manipur', 'Meghalaya', 'Mizoram', 'Nagaland', 'Odisha', 'Puducherry', 'Punjab', 'Rajasthan', 'Sikkim', 'Tamil Nadu', 'Telangana', 'Tripura', 'Uttar Pradesh', 'Uttarakhand', 'West Bengal']
Number of states: 36

In [38]:
print("Missing Crop before:", df["Crop"].isna().sum())

Missing Crop before: 9

In [39]:
df = df.dropna(subset=["Crop"]).copy()

In [40]:
print("Missing Crop after:", df["Crop"].isna().sum())

Missing Crop after: 0

In [41]:
print("Missing Production:", df["Production"].isna().sum())

Missing Production: 4944

In [42]:
df = df.dropna(subset=["Production"]).copy()

In [43]:
print(df.isnull().sum())

State         0
District      0
Crop          0
Crop_Year     0
Season        0
Area          0
Production    0
Yield         0
dtype: int64

In [44]:
zero_production = df[df["Production"] == 0]

zero_production[
    ["State", "District", "Crop",
     "Crop_Year", "Season",
     "Area", "Production", "Yield"]
].head(20)

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
59,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2015,Rabi,0.50,0.0,0.60
60,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2016,Rabi,6.50,0.0,0.05
63,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2013,Rabi,0.50,0.0,0.40
64,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2014,Rabi,1.00,0.0,0.40
65,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2015,Rabi,0.50,0.0,0.40
124,Andaman and Nicobar Island,NICOBARS,Black pepper,2005,Whole Year,41.00,0.0,0.00
133,Andaman and Nicobar Island,NICOBARS,Black pepper,2017,Rabi,12.40,0.0,0.03
134,Andaman and Nicobar Island,NICOBARS,Black pepper,2018,Rabi,10.41,0.0,0.00
189,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Cashewnut,2017,Rabi,0.80,0.0,0.55
329,Andaman and Nicobar Island,NICOBARS,Ginger,2017,Rabi,0.61,0.0,0.02
429,Andaman and Nicobar Island,SOUTH ANDAMANS,Moong(Green Gram),2017,Rabi,0.50,0.0,0.60
443,Andaman and Nicobar Island,NICOBARS,other oilseeds,2003,Whole Year,4.20,0.0,0.07
444,Andaman and Nicobar Island,NICOBARS,other oilseeds,2004,Whole Year,1.00,0.0,0.11
447,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,other oilseeds,2017,Rabi,0.16,0.0,1.25
461,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2016,Rabi,3.50,0.0,0.11
462,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2017,Rabi,0.11,0.0,2.36
464,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2011,Rabi,1.30,0.0,0.23
465,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2014,Rabi,0.20,0.0,1.50
479,Andaman and Nicobar Island,NICOBARS,Rice,2012,Autumn,0.35,0.0,1.14
524,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2017,Rabi,0.23,0.0,1.17

In [45]:
print("Zero production rows:", len(zero_production))

Zero production rows: 1465

In [46]:
inconsistent_zero = df[
    (df["Production"] == 0) &
    (df["Yield"] > 0)
]

print(
    "Production = 0 but Yield > 0:",
    len(inconsistent_zero)
)

inconsistent_zero.head(20)

Production = 0 but Yield > 0: 434

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
59,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2015,Rabi,0.50,0.0,0.60
60,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2016,Rabi,6.50,0.0,0.05
63,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2013,Rabi,0.50,0.0,0.40
64,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2014,Rabi,1.00,0.0,0.40
65,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2015,Rabi,0.50,0.0,0.40
133,Andaman and Nicobar Island,NICOBARS,Black pepper,2017,Rabi,12.40,0.0,0.03
189,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Cashewnut,2017,Rabi,0.80,0.0,0.55
329,Andaman and Nicobar Island,NICOBARS,Ginger,2017,Rabi,0.61,0.0,0.02
429,Andaman and Nicobar Island,SOUTH ANDAMANS,Moong(Green Gram),2017,Rabi,0.50,0.0,0.60
443,Andaman and Nicobar Island,NICOBARS,other oilseeds,2003,Whole Year,4.20,0.0,0.07
444,Andaman and Nicobar Island,NICOBARS,other oilseeds,2004,Whole Year,1.00,0.0,0.11
447,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,other oilseeds,2017,Rabi,0.16,0.0,1.25
461,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2016,Rabi,3.50,0.0,0.11
462,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2017,Rabi,0.11,0.0,2.36
464,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2011,Rabi,1.30,0.0,0.23
465,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2014,Rabi,0.20,0.0,1.50
479,Andaman and Nicobar Island,NICOBARS,Rice,2012,Autumn,0.35,0.0,1.14
524,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2017,Rabi,0.23,0.0,1.17
525,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2018,Rabi,1.20,0.0,0.25
526,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2019,Rabi,0.50,0.0,0.60

In [47]:
print("Area <= 0:", (df["Area"] <= 0).sum())

Area <= 0: 0

In [48]:
df[df["Crop_Year"] == 2020].head(20)

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
326054,Uttarakhand,ALMORA,Arhar/Tur,2020,Kharif,216.0,140.0,0.65
326086,Uttarakhand,CHAMOLI,Arhar/Tur,2020,Kharif,227.0,178.0,0.78
326103,Uttarakhand,CHAMPAWAT,Arhar/Tur,2020,Kharif,2.0,1.0,0.50
326124,Uttarakhand,DEHRADUN,Arhar/Tur,2020,Kharif,387.0,516.0,1.33
326155,Uttarakhand,NAINITAL,Arhar/Tur,2020,Kharif,5.0,3.0,0.60
326176,Uttarakhand,PAURI GARHWAL,Arhar/Tur,2020,Kharif,158.0,124.0,0.78
326186,Uttarakhand,PITHORAGARH,Arhar/Tur,2020,Kharif,2.0,1.0,0.50
326207,Uttarakhand,RUDRA PRAYAG,Arhar/Tur,2020,Kharif,158.0,124.0,0.78
326228,Uttarakhand,TEHRI GARHWAL,Arhar/Tur,2020,Kharif,1741.0,2273.0,1.31
326266,Uttarakhand,UTTAR KASHI,Arhar/Tur,2020,Kharif,431.0,632.0,1.47
326303,Uttarakhand,ALMORA,Barley,2020,Rabi,3540.0,2645.0,0.75
326324,Uttarakhand,BAGESHWAR,Barley,2020,Rabi,851.0,1028.0,1.21
326345,Uttarakhand,CHAMOLI,Barley,2020,Rabi,1839.0,2732.0,1.49
326366,Uttarakhand,CHAMPAWAT,Barley,2020,Rabi,699.0,845.0,1.21
326387,Uttarakhand,DEHRADUN,Barley,2020,Rabi,690.0,1322.0,1.92
326408,Uttarakhand,HARIDWAR,Barley,2020,Rabi,5.0,8.0,1.60
326429,Uttarakhand,NAINITAL,Barley,2020,Rabi,708.0,908.0,1.28
326450,Uttarakhand,PAURI GARHWAL,Barley,2020,Rabi,3930.0,5011.0,1.28
326471,Uttarakhand,PITHORAGARH,Barley,2020,Rabi,3358.0,5483.0,1.63
326492,Uttarakhand,RUDRA PRAYAG,Barley,2020,Rabi,1540.0,1839.0,1.19

In [49]:
df[df["Crop_Year"] == 2020]["State"].value_counts()

State
Uttarakhand    319
Name: count, dtype: Int64

In [50]:
df[df["Crop_Year"] == 2020]["Crop"].value_counts().head(30)

Crop
Garlic                   23
Potato                   23
Maize                    17
Rice                     16
Urad                     16
Barley                   13
Rapeseed &Mustard        13
Peas & beans (Pulses)    13
Wheat                    13
Masoor                   13
Onion                    13
Soyabean                 12
Sesamum                  12
Other Cereals            12
Other Kharif pulses      12
Turmeric                 12
Small millets            11
Horse-gram               11
Ragi                     11
Gram                     11
Arhar/Tur                10
other oilseeds            8
Groundnut                 6
Sugarcane                 5
Moong(Green Gram)         5
Other  Rabi pulses        3
Sunflower                 3
Moth                      1
Tobacco                   1
Name: count, dtype: Int64

In [51]:
os.makedirs("../data/processed", exist_ok=True)

df.to_csv(
    "../data/processed/agriculture_clean.csv",
    index=False
)

print("Clean dataset saved!")
print("Shape:", df.shape)

Clean dataset saved!
Shape: (340383, 8)

In [52]:
df["Production"] == 0

0         False
1         False
2         False
3         False
4         False
          ...
345331    False
345332    False
345333    False
345334    False
345335    False
Name: Production, Length: 340383, dtype: bool

In [57]:
Production == 0 and Yield > 0

NameError: name 'Production' is not defined

In [54]:
df[df["Crop_Year"] == 2020]["State"].value_counts()

State
Uttarakhand    319
Name: count, dtype: Int64

In [55]:
df[df["Crop_Year"] == 2020]["Crop"].value_counts()

Crop
Garlic                   23
Potato                   23
Maize                    17
Rice                     16
Urad                     16
Barley                   13
Rapeseed &Mustard        13
Peas & beans (Pulses)    13
Wheat                    13
Masoor                   13
Onion                    13
Soyabean                 12
Sesamum                  12
Other Cereals            12
Other Kharif pulses      12
Turmeric                 12
Small millets            11
Horse-gram               11
Ragi                     11
Gram                     11
Arhar/Tur                10
other oilseeds            8
Groundnut                 6
Sugarcane                 5
Moong(Green Gram)         5
Other  Rabi pulses        3
Sunflower                 3
Moth                      1
Tobacco                   1
Name: count, dtype: Int64

In [56]:
crop_yield_stats.head(20)

                    count         mean    median   min       max
Crop
Coconut              2891  8943.243196  8109.890  0.00  43958.33
Cashewnut            1519     7.002916     0.400  0.00   9801.00
Onion               10621    13.245736    11.000  0.00   4070.00
Maize               20335     2.675144     1.950  0.00   1494.00
Sannhamp             2738     1.516644     0.500  0.00   1022.00
Tobacco              3858     2.702519     1.540  0.00    964.80
Sugarcane           10826    56.188318    55.400  0.00    500.49
Potato              10729    13.182370    10.760  0.00    311.02
Cotton(lint)         6318     2.163686     1.640  0.00    300.00
Sesamum             12744     0.509976     0.360  0.00    275.00
Arhar/Tur           10764     0.884049     0.790  0.00    270.00
Banana               4042    29.756524    23.450  0.00    258.07
Other  Rabi pulses   4728     0.751066     0.610  0.00    251.00
Rice                21573     2.102165     2.040  0.00    223.73
Jute                 1837     9.775411     9.540  0.02    180.29
Sweet potato         5656     9.421494     8.765  0.00     99.33
Bajra                8091     2.652741     1.140  0.00     97.32
Tapioca              2264    18.938542    12.860  0.00     73.39
Niger seed           2835     0.404557     0.300  0.00     71.00
Sunflower            7104     0.966047     0.870  0.00     70.00

In [58]:
print("Number of states:", df["State"].nunique())

print("\nState values:")
for state in sorted(df["State"].dropna().unique()):
    print(repr(state))

Number of states: 36

State values:
'Andaman and Nicobar Island'
'Andhra Pradesh'
'Arunachal Pradesh'
'Assam'
'Bihar'
'Chandigarh'
'Chhattisgarh'
'Dadra and Nagar Haveli'
'Daman and Diu'
'Delhi'
'Goa'
'Gujarat'
'Haryana'
'Himachal Pradesh'
'Jammu and Kashmir'
'Jharkhand'
'Karnataka'
'Kerala'
'Ladakh'
'Madhya Pradesh'
'Maharashtra'
'Manipur'
'Meghalaya'
'Mizoram'
'Nagaland'
'Odisha'
'Puducherry'
'Punjab'
'Rajasthan'
'Sikkim'
'Tamil Nadu'
'Telangana'
'Tripura'
'Uttar Pradesh'
'Uttarakhand'
'West Bengal'

In [59]:
inconsistent_zero = df[
    (df["Production"] == 0) &
    (df["Yield"] > 0)
]

print("Inconsistent records:", len(inconsistent_zero))

inconsistent_zero[
    [
        "State",
        "District",
        "Crop",
        "Crop_Year",
        "Season",
        "Area",
        "Production",
        "Yield"
    ]
].head(30)

Inconsistent records: 434

,State,District,Crop,Crop_Year,Season,Area,Production,Yield
59,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2015,Rabi,0.50,0.0,0.60
60,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Arhar/Tur,2016,Rabi,6.50,0.0,0.05
63,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2013,Rabi,0.50,0.0,0.40
64,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2014,Rabi,1.00,0.0,0.40
65,Andaman and Nicobar Island,SOUTH ANDAMANS,Arhar/Tur,2015,Rabi,0.50,0.0,0.40
133,Andaman and Nicobar Island,NICOBARS,Black pepper,2017,Rabi,12.40,0.0,0.03
189,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Cashewnut,2017,Rabi,0.80,0.0,0.55
329,Andaman and Nicobar Island,NICOBARS,Ginger,2017,Rabi,0.61,0.0,0.02
429,Andaman and Nicobar Island,SOUTH ANDAMANS,Moong(Green Gram),2017,Rabi,0.50,0.0,0.60
443,Andaman and Nicobar Island,NICOBARS,other oilseeds,2003,Whole Year,4.20,0.0,0.07
444,Andaman and Nicobar Island,NICOBARS,other oilseeds,2004,Whole Year,1.00,0.0,0.11
447,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,other oilseeds,2017,Rabi,0.16,0.0,1.25
461,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2016,Rabi,3.50,0.0,0.11
462,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Rapeseed &Mustard,2017,Rabi,0.11,0.0,2.36
464,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2011,Rabi,1.30,0.0,0.23
465,Andaman and Nicobar Island,SOUTH ANDAMANS,Rapeseed &Mustard,2014,Rabi,0.20,0.0,1.50
479,Andaman and Nicobar Island,NICOBARS,Rice,2012,Autumn,0.35,0.0,1.14
524,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2017,Rabi,0.23,0.0,1.17
525,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2018,Rabi,1.20,0.0,0.25
526,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sesamum,2019,Rabi,0.50,0.0,0.60
579,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sunflower,2015,Rabi,0.50,0.0,0.40
580,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,Sunflower,2016,Rabi,0.50,0.0,0.80
723,Andaman and Nicobar Island,SOUTH ANDAMANS,Urad,2019,Rabi,1.00,0.0,0.02
51535,Bihar,PURBI CHAMPARAN,Moong(Green Gram),2000,Kharif,1.00,0.0,0.10
80315,Goa,NORTH GOA,Ragi,2014,Kharif,0.10,0.0,0.75
88263,Gujarat,ARAVALLI,Moth,2019,Kharif,1.00,0.0,0.46
103459,Himachal Pradesh,HAMIRPUR,Dry chillies,2014,Kharif,1.00,0.0,0.27
104095,Himachal Pradesh,MANDI,Groundnut,2000,Kharif,6.00,0.0,0.02
104110,Himachal Pradesh,SHIMLA,Groundnut,2000,Kharif,6.00,0.0,0.02
104361,Himachal Pradesh,BILASPUR,Jowar,2000,Kharif,4.00,0.0,0.03

In [60]:
inconsistent_zero["Crop"].value_counts()

Crop
Sesamum               102
Urad                   45
Moong(Green Gram)      45
Ragi                   41
Rapeseed &Mustard      21
Linseed                20
Horse-gram             17
Safflower              14
Small millets          13
Sunflower              11
Niger seed              9
Castor seed             8
Moth                    8
other oilseeds          7
Cardamom                7
Tobacco                 7
Groundnut               6
Other Cereals           6
Arhar/Tur               6
Bajra                   4
Wheat                   4
Coriander               4
Gram                    3
Maize                   3
Mesta                   3
Cotton(lint)            2
Ginger                  2
Other  Rabi pulses      2
Turmeric                2
Jowar                   2
Black pepper            2
Masoor                  1
Cashewnut               1
Cowpea(Lobia)           1
Rice                    1
Sugarcane               1
Barley                  1
Sannhamp                1
Dry chillies            1
Name: count, dtype: Int64

In [61]:
zero_production = df[df["Production"] == 0]

print("Zero production:", len(zero_production))

print("\nYield statistics:")
print(zero_production["Yield"].describe())

print("\nCrops:")
print(zero_production["Crop"].value_counts().head(20))

Zero production: 1465

Yield statistics:
count    1465.000000
mean        0.056287
std         0.148391
min         0.000000
25%         0.000000
50%         0.000000
75%         0.050000
max         2.360000
Name: Yield, dtype: float64

Crops:
Crop
Sesamum                  203
Moong(Green Gram)        138
Urad                      93
Maize                     68
Moth                      56
Rapeseed &Mustard         46
Ragi                      46
Groundnut                 45
Gram                      44
Sannhamp                  44
Small millets             44
Barley                    39
Linseed                   35
Other  Rabi pulses        34
Cotton(lint)              34
Peas & beans (Pulses)     32
Banana                    29
Horse-gram                29
Masoor                    29
other oilseeds            29
Name: count, dtype: Int64

In [62]:
crop_yield_stats = (
    df.groupby("Crop")["Yield"]
      .agg(
          count="count",
          mean="mean",
          median="median",
          min="min",
          max="max"
      )
      .sort_values("max", ascending=False)
)

crop_yield_stats.head(20)

                    count         mean    median   min       max
Crop
Coconut              2891  8943.243196  8109.890  0.00  43958.33
Cashewnut            1519     7.002916     0.400  0.00   9801.00
Onion               10621    13.245736    11.000  0.00   4070.00
Maize               20335     2.675144     1.950  0.00   1494.00
Sannhamp             2738     1.516644     0.500  0.00   1022.00
Tobacco              3858     2.702519     1.540  0.00    964.80
Sugarcane           10826    56.188318    55.400  0.00    500.49
Potato              10729    13.182370    10.760  0.00    311.02
Cotton(lint)         6318     2.163686     1.640  0.00    300.00
Sesamum             12744     0.509976     0.360  0.00    275.00
Arhar/Tur           10764     0.884049     0.790  0.00    270.00
Banana               4042    29.756524    23.450  0.00    258.07
Other  Rabi pulses   4728     0.751066     0.610  0.00    251.00
Rice                21573     2.102165     2.040  0.00    223.73
Jute                 1837     9.775411     9.540  0.02    180.29
Sweet potato         5656     9.421494     8.765  0.00     99.33
Bajra                8091     2.652741     1.140  0.00     97.32
Tapioca              2264    18.938542    12.860  0.00     73.39
Niger seed           2835     0.404557     0.300  0.00     71.00
Sunflower            7104     0.966047     0.870  0.00     70.00