In [1]:
import pandas as pd
import numpy as np
import os

In [2]:
df = pd.read_csv("../data/processed/ml_training_base.csv")

print("Rows:", len(df))
print("Columns:", df.shape[1])

Rows: 338483
Columns: 8

In [3]:
locations = (
    df[["State", "District"]]
    .drop_duplicates()
    .sort_values(["State", "District"])
    .reset_index(drop=True)
)

print("Unique State-District combinations:", len(locations))
locations.head(20)

Unique State-District combinations: 771

                         State                  District
0   Andaman and Nicobar Island                  NICOBARS
1   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN
2   Andaman and Nicobar Island            SOUTH ANDAMANS
3               Andhra Pradesh                  ADILABAD
4               Andhra Pradesh                 ANANTAPUR
5               Andhra Pradesh                  CHITTOOR
6               Andhra Pradesh             EAST GODAVARI
7               Andhra Pradesh                    GUNTUR
8               Andhra Pradesh                 HYDERABAD
9               Andhra Pradesh                    KADAPA
10              Andhra Pradesh                KARIMNAGAR
11              Andhra Pradesh                   KHAMMAM
12              Andhra Pradesh                   KRISHNA
13              Andhra Pradesh                   KURNOOL
14              Andhra Pradesh               MAHBUBNAGAR
15              Andhra Pradesh                     MEDAK
16              Andhra Pradesh                  NALGONDA
17              Andhra Pradesh                 NIZAMABAD
18              Andhra Pradesh                  PRAKASAM
19              Andhra Pradesh                RANGAREDDI

In [4]:
district_counts = (
    locations.groupby("State")["District"]
    .nunique()
    .sort_values(ascending=False)
)

district_counts

State
Uttar Pradesh                 88
Madhya Pradesh                67
Bihar                         56
Tamil Nadu                    37
Maharashtra                   36
Rajasthan                     33
Gujarat                       33
Assam                         33
Telangana                     32
Odisha                        30
Karnataka                     30
Chhattisgarh                  28
Arunachal Pradesh             25
Jharkhand                     24
Andhra Pradesh                23
West Bengal                   22
Haryana                       22
Punjab                        22
Jammu and Kashmir             22
Kerala                        14
Uttarakhand                   13
Himachal Pradesh              12
Nagaland                      11
Meghalaya                     11
Manipur                        9
Tripura                        8
Mizoram                        8
Puducherry                     4
Sikkim                         4
Andaman and Nicobar Island     3
Dadra and Nagar Haveli         3
Goa                            2
Ladakh                         2
Daman and Diu                  2
Chandigarh                     1
Delhi                          1
Name: District, dtype: int64

In [5]:
print("Total states:", locations["State"].nunique())
print("Total districts:", locations["District"].nunique())

Total states: 36
Total districts: 707

In [6]:
for state in sorted(locations["State"].unique()):
    print("\n" + "=" * 60)
    print(state)
    print("=" * 60)
    print(
        sorted(
            locations.loc[
                locations["State"] == state,
                "District"
            ].dropna().unique()
        )
    )

============================================================
Andaman and Nicobar Island
============================================================
['NICOBARS', 'NORTH AND MIDDLE ANDAMAN', 'SOUTH ANDAMANS']

============================================================
Andhra Pradesh
============================================================
['ADILABAD', 'ANANTAPUR', 'CHITTOOR', 'EAST GODAVARI', 'GUNTUR', 'HYDERABAD', 'KADAPA', 'KARIMNAGAR', 'KHAMMAM', 'KRISHNA', 'KURNOOL', 'MAHBUBNAGAR', 'MEDAK', 'NALGONDA', 'NIZAMABAD', 'PRAKASAM', 'RANGAREDDI', 'SPSR NELLORE', 'SRIKAKULAM', 'VISAKHAPATANAM', 'VIZIANAGARAM', 'WARANGAL', 'WEST GODAVARI']

============================================================
Arunachal Pradesh
============================================================
['ANJAW', 'CHANGLANG', 'DIBANG VALLEY', 'EAST KAMENG', 'EAST SIANG', 'KAMLE', 'KRA DAADI', 'KURUNG KUMEY', 'LEPARADA', 'LOHIT', 'LONGDING', 'LOWER DIBANG VALLEY', 'LOWER SIANG', 'LOWER SUBANSIRI', 'NAMSAI', 'PAKKE KESSANG', 'PAPUM PARE', 'SHI YOMI', 'SIANG', 'TAWANG', 'TIRAP', 'UPPER SIANG', 'UPPER SUBANSIRI', 'WEST KAMENG', 'WEST SIANG']

============================================================
Assam
============================================================
['BAKSA', 'BARPETA', 'BISWANATH', 'BONGAIGAON', 'CACHAR', 'CHARAIDEO', 'CHIRANG', 'DARRANG', 'DHEMAJI', 'DHUBRI', 'DIBRUGARH', 'DIMA HASAO', 'GOALPARA', 'GOLAGHAT', 'HAILAKANDI', 'HOJAI', 'JORHAT', 'KAMRUP', 'KAMRUP METRO', 'KARBI ANGLONG', 'KARIMGANJ', 'KOKRAJHAR', 'LAKHIMPUR', 'MAJULI', 'MARIGAON', 'NAGAON', 'NALBARI', 'SIVASAGAR', 'SONITPUR', 'SOUTH SALMARA MANCACHAR', 'TINSUKIA', 'UDALGURI', 'WEST KARBI ANGLONG']

============================================================
Bihar
============================================================
['ARARIA', 'ARWAL', 'AURANGABAD', 'BANKA', 'BEGUSARAI', 'BHAGALPUR', 'BHOJPUR', 'BOKARO', 'BUXAR', 'CHATRA', 'DARBHANGA', 'DEOGHAR', 'DHANBAD', 'DUMKA', 'EAST SINGHBUM', 'GARHWA', 'GAYA', 'GIRIDIH', 'GODDA', 'GOPALGANJ', 'GUMLA', 'HAZARIBAGH', 'JAMUI', 'JEHANABAD', 'KAIMUR (BHABUA)', 'KATIHAR', 'KHAGARIA', 'KISHANGANJ', 'KODERMA', 'LAKHISARAI', 'LOHARDAGA', 'MADHEPURA', 'MADHUBANI', 'MUNGER', 'MUZAFFARPUR', 'NALANDA', 'NAWADA', 'PAKUR', 'PALAMU', 'PASHCHIM CHAMPARAN', 'PATNA', 'PURBI CHAMPARAN', 'PURNIA', 'RANCHI', 'ROHTAS', 'SAHARSA', 'SAHEBGANJ', 'SAMASTIPUR', 'SARAN', 'SHEIKHPURA', 'SHEOHAR', 'SITAMARHI', 'SIWAN', 'SUPAUL', 'VAISHALI', 'WEST SINGHBHUM']

============================================================
Chandigarh
============================================================
['CHANDIGARH']

============================================================
Chhattisgarh
============================================================
['BALOD', 'BALODA BAZAR', 'BALRAMPUR', 'BASTAR', 'BEMETARA', 'BIJAPUR', 'BILASPUR', 'DANTEWADA', 'DHAMTARI', 'DURG', 'GARIYABAND', 'GAURELLA-PENDRA-MARWAHI', 'JANJGIR-CHAMPA', 'JASHPUR', 'KABIRDHAM', 'KANKER', 'KONDAGAON', 'KORBA', 'KOREA', 'MAHASAMUND', 'MUNGELI', 'NARAYANPUR', 'RAIGARH', 'RAIPUR', 'RAJNANDGAON', 'SUKMA', 'SURAJPUR', 'SURGUJA']

============================================================
Dadra and Nagar Haveli
============================================================
['DADRA AND NAGAR HAVELI', 'DAMAN', 'DIU']

============================================================
Daman and Diu
============================================================
['DAMAN', 'DIU']

============================================================
Delhi
============================================================
['DELHI_TOTAL']

============================================================
Goa
============================================================
['NORTH GOA', 'SOUTH GOA']

============================================================
Gujarat
============================================================
['AHMADABAD', 'AMRELI', 'ANAND', 'ARAVALLI', 'BANAS KANTHA', 'BHARUCH', 'BHAVNAGAR', 'BOTAD', 'CHHOTAUDEPUR', 'DANG', 'DEVBHUMI DWARKA', 'DOHAD', 'GANDHINAGAR', 'GIR SOMNATH', 'JAMNAGAR', 'JUNAGADH', 'KACHCHH', 'KHEDA', 'MAHESANA', 'MAHISAGAR', 'MORBI', 'NARMADA', 'NAVSARI', 'PANCH MAHALS', 'PATAN', 'PORBANDAR', 'RAJKOT', 'SABAR KANTHA', 'SURAT', 'SURENDRANAGAR', 'TAPI', 'VADODARA', 'VALSAD']

============================================================
Haryana
============================================================
['AMBALA', 'BHIWANI', 'CHARKI DADRI', 'FARIDABAD', 'FATEHABAD', 'GURGAON', 'HISAR', 'JHAJJAR', 'JIND', 'KAITHAL', 'KARNAL', 'KURUKSHETRA', 'MAHENDRAGARH', 'MEWAT', 'PALWAL', 'PANCHKULA', 'PANIPAT', 'REWARI', 'ROHTAK', 'SIRSA', 'SONIPAT', 'YAMUNANAGAR']

============================================================
Himachal Pradesh
============================================================
['BILASPUR', 'CHAMBA', 'HAMIRPUR', 'KANGRA', 'KINNAUR', 'KULLU', 'LAHUL AND SPITI', 'MANDI', 'SHIMLA', 'SIRMAUR', 'SOLAN', 'UNA']

============================================================
Jammu and Kashmir
============================================================
['ANANTNAG', 'BADGAM', 'BANDIPORA', 'BARAMULLA', 'DODA', 'GANDERBAL', 'JAMMU', 'KARGIL', 'KATHUA', 'KISHTWAR', 'KULGAM', 'KUPWARA', 'LEH LADAKH', 'POONCH', 'PULWAMA', 'RAJAURI', 'RAMBAN', 'REASI', 'SAMBA', 'SHOPIAN', 'SRINAGAR', 'UDHAMPUR']

============================================================
Jharkhand
============================================================
['BOKARO', 'CHATRA', 'DEOGHAR', 'DHANBAD', 'DUMKA', 'EAST SINGHBUM', 'GARHWA', 'GIRIDIH', 'GODDA', 'GUMLA', 'HAZARIBAGH', 'JAMTARA', 'KHUNTI', 'KODERMA', 'LATEHAR', 'LOHARDAGA', 'PAKUR', 'PALAMU', 'RAMGARH', 'RANCHI', 'SAHEBGANJ', 'SARAIKELA KHARSAWAN', 'SIMDEGA', 'WEST SINGHBHUM']

============================================================
Karnataka
============================================================
['BAGALKOTE', 'BALLARI', 'BANGALORE RURAL', 'BELAGAVI', 'BENGALURU URBAN', 'BIDAR', 'CHAMARAJANAGARA', 'CHIKKABALLAPURA', 'CHIKKAMAGALURU', 'CHITRADURGA', 'DAKSHINA KANNADA', 'DAVANGERE', 'DHARWAD', 'GADAG', 'HASSAN', 'HAVERI', 'KALABURAGI', 'KODAGU', 'KOLAR', 'KOPPAL', 'MANDYA', 'MYSURU', 'RAICHUR', 'RAMANAGARA', 'SHIVAMOGGA', 'TUMAKURU', 'UDUPI', 'UTTARA KANNADA', 'VIJAYAPURA', 'YADAGIRI']

============================================================
Kerala
============================================================
['ALAPPUZHA', 'ERNAKULAM', 'IDUKKI', 'KANNUR', 'KASARAGOD', 'KOLLAM', 'KOTTAYAM', 'KOZHIKODE', 'MALAPPURAM', 'PALAKKAD', 'PATHANAMTHITTA', 'THIRUVANANTHAPURAM', 'THRISSUR', 'WAYANAD']

============================================================
Ladakh
============================================================
['KARGIL', 'LEH LADAKH']

============================================================
Madhya Pradesh
============================================================
['AGAR MALWA', 'ALIRAJPUR', 'ANUPPUR', 'ASHOKNAGAR', 'BALAGHAT', 'BARWANI', 'BASTAR', 'BETUL', 'BHIND', 'BHOPAL', 'BILASPUR', 'BURHANPUR', 'CHHATARPUR', 'CHHINDWARA', 'DAMOH', 'DANTEWADA', 'DATIA', 'DEWAS', 'DHAMTARI', 'DHAR', 'DINDORI', 'DURG', 'GUNA', 'GWALIOR', 'HARDA', 'HOSHANGABAD', 'INDORE', 'JABALPUR', 'JANJGIR-CHAMPA', 'JASHPUR', 'JHABUA', 'KABIRDHAM', 'KANKER', 'KATNI', 'KHANDWA', 'KHARGONE', 'KORBA', 'KOREA', 'MAHASAMUND', 'MANDLA', 'MANDSAUR', 'MORENA', 'NARSINGHPUR', 'NEEMUCH', 'NIWARI', 'PANNA', 'RAIPUR', 'RAISEN', 'RAJGARH', 'RAJNANDGAON', 'RATLAM', 'REWA', 'SAGAR', 'SATNA', 'SEHORE', 'SEONI', 'SHAHDOL', 'SHAJAPUR', 'SHEOPUR', 'SHIVPURI', 'SIDHI', 'SINGRAULI', 'SURGUJA', 'TIKAMGARH', 'UJJAIN', 'UMARIA', 'VIDISHA']

============================================================
Maharashtra
============================================================
['AHMEDNAGAR', 'AKOLA', 'AMRAVATI', 'AURANGABAD', 'BEED', 'BHANDARA', 'BULDHANA', 'CHANDRAPUR', 'DHULE', 'GADCHIROLI', 'GONDIA', 'HINGOLI', 'JALGAON', 'JALNA', 'KOLHAPUR', 'LATUR', 'MUMBAI', 'MUMBAI SUBURBAN', 'NAGPUR', 'NANDED', 'NANDURBAR', 'NASHIK', 'OSMANABAD', 'PALGHAR', 'PARBHANI', 'PUNE', 'RAIGAD', 'RATNAGIRI', 'SANGLI', 'SATARA', 'SINDHUDURG', 'SOLAPUR', 'THANE', 'WARDHA', 'WASHIM', 'YAVATMAL']

============================================================
Manipur
============================================================
['BISHNUPUR', 'CHANDEL', 'CHURACHANDPUR', 'IMPHAL EAST', 'IMPHAL WEST', 'SENAPATI', 'TAMENGLONG', 'THOUBAL', 'UKHRUL']

============================================================
Meghalaya
============================================================
['EAST GARO HILLS', 'EAST JAINTIA HILLS', 'EAST KHASI HILLS', 'NORTH GARO HILLS', 'RI BHOI', 'SOUTH GARO HILLS', 'SOUTH WEST GARO HILLS', 'SOUTH WEST KHASI HILLS', 'WEST GARO HILLS', 'WEST JAINTIA HILLS', 'WEST KHASI HILLS']

============================================================
Mizoram
============================================================
['AIZAWL', 'CHAMPHAI', 'KOLASIB', 'LAWNGTLAI', 'LUNGLEI', 'MAMIT', 'SAIHA', 'SERCHHIP']

============================================================
Nagaland
============================================================
['DIMAPUR', 'KIPHIRE', 'KOHIMA', 'LONGLENG', 'MOKOKCHUNG', 'MON', 'PEREN', 'PHEK', 'TUENSANG', 'WOKHA', 'ZUNHEBOTO']

============================================================
Odisha
============================================================
['ANUGUL', 'BALANGIR', 'BALESHWAR', 'BARGARH', 'BHADRAK', 'BOUDH', 'CUTTACK', 'DEOGARH', 'DHENKANAL', 'GAJAPATI', 'GANJAM', 'JAGATSINGHAPUR', 'JAJAPUR', 'JHARSUGUDA', 'KALAHANDI', 'KANDHAMAL', 'KENDRAPARA', 'KENDUJHAR', 'KHORDHA', 'KORAPUT', 'MALKANGIRI', 'MAYURBHANJ', 'NABARANGPUR', 'NAYAGARH', 'NUAPADA', 'PURI', 'RAYAGADA', 'SAMBALPUR', 'SONEPUR', 'SUNDARGARH']

============================================================
Puducherry
============================================================
['KARAIKAL', 'MAHE', 'PONDICHERRY', 'YANAM']

============================================================
Punjab
============================================================
['AMRITSAR', 'BARNALA', 'BATHINDA', 'FARIDKOT', 'FATEHGARH SAHIB', 'FAZILKA', 'FIROZEPUR', 'GURDASPUR', 'HOSHIARPUR', 'JALANDHAR', 'KAPURTHALA', 'LUDHIANA', 'MANSA', 'MOGA', 'MUKTSAR', 'PATHANKOT', 'PATIALA', 'RUPNAGAR', 'S NAGAR', 'SANGRUR', 'SHAHID BHAGAT SINGH NAGAR', 'TARN TARAN']

============================================================
Rajasthan
============================================================
['AJMER', 'ALWAR', 'BANSWARA', 'BARAN', 'BARMER', 'BHARATPUR', 'BHILWARA', 'BIKANER', 'BUNDI', 'CHITTORGARH', 'CHURU', 'DAUSA', 'DHOLPUR', 'DUNGARPUR', 'GANGANAGAR', 'HANUMANGARH', 'JAIPUR', 'JAISALMER', 'JALORE', 'JHALAWAR', 'JHUNJHUNU', 'JODHPUR', 'KARAULI', 'KOTA', 'NAGAUR', 'PALI', 'PRATAPGARH', 'RAJSAMAND', 'SAWAI MADHOPUR', 'SIKAR', 'SIROHI', 'TONK', 'UDAIPUR']

============================================================
Sikkim
============================================================
['EAST DISTRICT', 'NORTH DISTRICT', 'SOUTH DISTRICT', 'WEST DISTRICT']

============================================================
Tamil Nadu
============================================================
['ARIYALUR', 'CHENGALPATTU', 'CHENNAI', 'COIMBATORE', 'CUDDALORE', 'DHARMAPURI', 'DINDIGUL', 'ERODE', 'KALLAKURICHI', 'KANCHIPURAM', 'KANNIYAKUMARI', 'KARUR', 'KRISHNAGIRI', 'MADURAI', 'NAGAPATTINAM', 'NAMAKKAL', 'PERAMBALUR', 'PUDUKKOTTAI', 'RAMANATHAPURAM', 'RANIPET', 'SALEM', 'SIVAGANGA', 'TENKASI', 'THANJAVUR', 'THE NILGIRIS', 'THENI', 'THIRUVALLUR', 'THIRUVARUR', 'TIRUCHIRAPPALLI', 'TIRUNELVELI', 'TIRUPATHUR', 'TIRUPPUR', 'TIRUVANNAMALAI', 'TUTICORIN', 'VELLORE', 'VILLUPURAM', 'VIRUDHUNAGAR']

============================================================
Telangana
============================================================
['ADILABAD', 'BHADRADRI', 'HANUMAKONDA', 'JAGITIAL', 'JANGOAN', 'JAYASHANKAR', 'JOGULAMBA', 'KAMAREDDY', 'KARIMNAGAR', 'KHAMMAM', 'KOMARAM BHEEM ASIFABAD', 'MAHABUBABAD', 'MAHBUBNAGAR', 'MANCHERIAL', 'MEDAK', 'MEDCHAL MALKAJGIRI', 'MULUGU', 'NAGARKURNOOL', 'NALGONDA', 'NARAYANAPET', 'NIRMAL', 'NIZAMABAD', 'PEDDAPALLI', 'RAJANNA', 'RANGAREDDI', 'SANGAREDDY', 'SIDDIPET', 'SURYAPET', 'VIKARABAD', 'WANAPARTHY', 'WARANGAL', 'YADADRI']

============================================================
Tripura
============================================================
['DHALAI', 'GOMATI', 'KHOWAI', 'NORTH TRIPURA', 'SEPAHIJALA', 'SOUTH TRIPURA', 'UNAKOTI', 'WEST TRIPURA']

============================================================
Uttar Pradesh
============================================================
['AGRA', 'ALIGARH', 'ALLAHABAD', 'ALMORA', 'AMBEDKAR NAGAR', 'AMETHI', 'AMROHA', 'AURAIYA', 'AZAMGARH', 'BAGESHWAR', 'BAGHPAT', 'BAHRAICH', 'BALLIA', 'BALRAMPUR', 'BANDA', 'BARABANKI', 'BAREILLY', 'BASTI', 'BIJNOR', 'BUDAUN', 'BULANDSHAHR', 'CHAMOLI', 'CHAMPAWAT', 'CHANDAULI', 'CHITRAKOOT', 'DEHRADUN', 'DEORIA', 'ETAH', 'ETAWAH', 'FAIZABAD', 'FARRUKHABAD', 'FATEHPUR', 'FIROZABAD', 'GAUTAM BUDDHA NAGAR', 'GHAZIABAD', 'GHAZIPUR', 'GONDA', 'GORAKHPUR', 'HAMIRPUR', 'HAPUR', 'HARDOI', 'HARIDWAR', 'HATHRAS', 'JALAUN', 'JAUNPUR', 'JHANSI', 'KANNAUJ', 'KANPUR DEHAT', 'KANPUR NAGAR', 'KASGANJ', 'KAUSHAMBI', 'KHERI', 'KUSHI NAGAR', 'LALITPUR', 'LUCKNOW', 'MAHARAJGANJ', 'MAHOBA', 'MAINPURI', 'MATHURA', 'MAU', 'MEERUT', 'MIRZAPUR', 'MORADABAD', 'MUZAFFARNAGAR', 'NAINITAL', 'PAURI GARHWAL', 'PILIBHIT', 'PITHORAGARH', 'PRATAPGARH', 'RAE BARELI', 'RAMPUR', 'RUDRA PRAYAG', 'SAHARANPUR', 'SAMBHAL', 'SANT KABEER NAGAR', 'SANT RAVIDAS NAGAR', 'SHAHJAHANPUR', 'SHAMLI', 'SHRAVASTI', 'SIDDHARTH NAGAR', 'SITAPUR', 'SONBHADRA', 'SULTANPUR', 'TEHRI GARHWAL', 'UDAM SINGH NAGAR', 'UNNAO', 'UTTAR KASHI', 'VARANASI']

============================================================
Uttarakhand
============================================================
['ALMORA', 'BAGESHWAR', 'CHAMOLI', 'CHAMPAWAT', 'DEHRADUN', 'HARIDWAR', 'NAINITAL', 'PAURI GARHWAL', 'PITHORAGARH', 'RUDRA PRAYAG', 'TEHRI GARHWAL', 'UDAM SINGH NAGAR', 'UTTAR KASHI']

============================================================
West Bengal
============================================================
['ALIPURDUAR', 'BANKURA', 'BIRBHUM', 'COOCHBEHAR', 'DARJEELING', 'DINAJPUR DAKSHIN', 'DINAJPUR UTTAR', 'HOOGHLY', 'HOWRAH', 'JALPAIGURI', 'JHARGRAM', 'KALIMPONG', 'MALDAH', 'MEDINIPUR EAST', 'MEDINIPUR WEST', 'MURSHIDABAD', 'NADIA', 'PARAGANAS NORTH', 'PARAGANAS SOUTH', 'PASCHIM BARDHAMAN', 'PURBA BARDHAMAN', 'PURULIA']

In [7]:
district_data = (
    df.groupby(["State", "District"])
      .agg(
          records=("Yield", "size"),
          crops=("Crop", "nunique"),
          years=("Crop_Year", "nunique")
      )
      .reset_index()
)

district_data.head()

                        State                  District  records  crops  years
0  Andaman and Nicobar Island                  NICOBARS      242     17     20
1  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN      232     24     16
2  Andaman and Nicobar Island            SOUTH ANDAMANS      222     23     15
3              Andhra Pradesh                  ADILABAD      547     37     16
4              Andhra Pradesh                 ANANTAPUR      945     39     23

In [8]:
district_data["records"].describe()

count     771.000000
mean      439.018158
std       253.899524
min         1.000000
25%       223.000000
50%       484.000000
75%       629.500000
max      1194.000000
Name: records, dtype: float64

In [9]:
district_data["years"].describe()

count    771.000000
mean      18.346304
std        7.319298
min        1.000000
25%       16.000000
50%       23.000000
75%       23.000000
max       23.000000
Name: years, dtype: float64

In [10]:
district_data.sort_values("records").head(30)

                      State                 District  records  crops  years
573              Tamil Nadu                  CHENNAI        1      1      1
80                    Assam  SOUTH SALMARA MANCACHAR        1      1      1
170  Dadra and Nagar Haveli                    DAMAN        1      1      1
171  Dadra and Nagar Haveli                      DIU        1      1      1
419             Maharashtra                   MUMBAI        1      1      1
74                    Assam                   MAJULI        2      2      1
66                    Assam                    HOJAI        2      2      1
56                    Assam                CHARAIDEO        2      2      1
83                    Assam       WEST KARBI ANGLONG        2      2      1
53                    Assam                BISWANATH        2      2      1
420             Maharashtra          MUMBAI SUBURBAN        2      2      2
590              Tamil Nadu                  RANIPET        3      3      1
579              Tamil Nadu             KALLAKURICHI        4      4      1
572              Tamil Nadu             CHENGALPATTU        5      5      1
593              Tamil Nadu                  TENKASI        5      4      1
601              Tamil Nadu               TIRUPATHUR        7      7      1
380          Madhya Pradesh                   NIWARI        7      7      1
8            Andhra Pradesh                HYDERABAD        8      2      4
367          Madhya Pradesh                KABIRDHAM       12     12      1
719           Uttar Pradesh             RUDRA PRAYAG       16     10      2
43        Arunachal Pradesh                 SHI YOMI       17     16      1
670           Uttar Pradesh                CHAMPAWAT       17     11      2
657           Uttar Pradesh                BAGESHWAR       17     11      2
41        Arunachal Pradesh            PAKKE KESSANG       18     16      1
173           Daman and Diu                      DIU       21      1     21
172           Daman and Diu                    DAMAN       21      1     21
34        Arunachal Pradesh                 LEPARADA       22     20      1
354          Madhya Pradesh                 DHAMTARI       28     20      2
374          Madhya Pradesh               MAHASAMUND       28     20      2
351          Madhya Pradesh                DANTEWADA       29     22      2

In [11]:
district_data.sort_values("years").head(30)

                      State                 District  records  crops  years
43        Arunachal Pradesh                 SHI YOMI       17     16      1
41        Arunachal Pradesh            PAKKE KESSANG       18     16      1
66                    Assam                    HOJAI        2      2      1
380          Madhya Pradesh                   NIWARI        7      7      1
53                    Assam                BISWANATH        2      2      1
56                    Assam                CHARAIDEO        2      2      1
74                    Assam                   MAJULI        2      2      1
80                    Assam  SOUTH SALMARA MANCACHAR        1      1      1
601              Tamil Nadu               TIRUPATHUR        7      7      1
419             Maharashtra                   MUMBAI        1      1      1
152            Chhattisgarh  GAURELLA-PENDRA-MARWAHI       31     29      1
83                    Assam       WEST KARBI ANGLONG        2      2      1
367          Madhya Pradesh                KABIRDHAM       12     12      1
579              Tamil Nadu             KALLAKURICHI        4      4      1
171  Dadra and Nagar Haveli                      DIU        1      1      1
170  Dadra and Nagar Haveli                    DAMAN        1      1      1
593              Tamil Nadu                  TENKASI        5      4      1
590              Tamil Nadu                  RANIPET        3      3      1
572              Tamil Nadu             CHENGALPATTU        5      5      1
573              Tamil Nadu                  CHENNAI        1      1      1
34        Arunachal Pradesh                 LEPARADA       22     20      1
670           Uttar Pradesh                CHAMPAWAT       17     11      2
38        Arunachal Pradesh              LOWER SIANG       44     20      2
719           Uttar Pradesh             RUDRA PRAYAG       16     10      2
627               Telangana              NARAYANAPET       59     22      2
657           Uttar Pradesh                BAGESHWAR       17     11      2
624               Telangana                   MULUGU       44     18      2
420             Maharashtra          MUMBAI SUBURBAN        2      2      2
351          Madhya Pradesh                DANTEWADA       29     22      2
372          Madhya Pradesh                    KORBA       29     21      2

In [12]:
location_master = locations.copy()

location_master["Latitude"] = np.nan
location_master["Longitude"] = np.nan

location_master.head()

                        State                  District  Latitude  Longitude
0  Andaman and Nicobar Island                  NICOBARS       NaN        NaN
1  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN       NaN        NaN
2  Andaman and Nicobar Island            SOUTH ANDAMANS       NaN        NaN
3              Andhra Pradesh                  ADILABAD       NaN        NaN
4              Andhra Pradesh                 ANANTAPUR       NaN        NaN

In [13]:
os.makedirs("../data/processed", exist_ok=True)

location_master.to_csv(
    "../data/processed/location_master.csv",
    index=False
)

print("Location master created!")
print("Rows:", len(location_master))

Location master created!
Rows: 771