In [11]:
!python -m pip install geopy

Collecting geopy
  Using cached geopy-2.5.0-py3-none-any.whl.metadata (7.1 kB)
Collecting geographiclib<3,>=1.52 (from geopy)
  Using cached geographiclib-2.1-py3-none-any.whl.metadata (1.6 kB)
Using cached geopy-2.5.0-py3-none-any.whl (114 kB)
Using cached geographiclib-2.1-py3-none-any.whl (40 kB)
Installing collected packages: geographiclib, geopy

   -------------------- ------------------- 1/2 [geopy]
   -------------------- ------------------- 1/2 [geopy]
   ---------------------------------------- 2/2 [geopy]

Successfully installed geographiclib-2.1 geopy-2.5.0

In [20]:
import pandas as pd
import numpy as np
import os

In [21]:
locations = pd.read_csv(
    "../data/processed/location_master.csv"
)

print("APY location combinations:", len(locations))
locations.head()

APY location combinations: 771

                        State                  District  Latitude  Longitude
0  Andaman and Nicobar Island                  NICOBARS       NaN        NaN
1  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN       NaN        NaN
2  Andaman and Nicobar Island            SOUTH ANDAMANS       NaN        NaN
3              Andhra Pradesh                  ADILABAD       NaN        NaN
4              Andhra Pradesh                 ANANTAPUR       NaN        NaN

In [22]:
def normalize_name(value):
    if pd.isna(value):
        return None
    
    value = str(value).strip().upper()
    
    # Normalize common punctuation
    value = value.replace("&", "AND")
    value = value.replace("-", " ")
    
    # Remove repeated spaces
    value = " ".join(value.split())
    
    return value

In [23]:
locations["State_Normalized"] = (
    locations["State"].apply(normalize_name)
)

locations["District_Normalized"] = (
    locations["District"].apply(normalize_name)
)

In [24]:
locations["Latitude"] = np.nan
locations["Longitude"] = np.nan
locations["Mapping_Status"] = "UNVERIFIED"
locations["Mapping_Source"] = ""

In [25]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(
    user_agent="smart-crop-ai-college-project"
)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1
)

In [26]:
def geocode_verified(district, state):
    
    queries = [
        f"{district}, {state}, India",
        f"{district}, India"
    ]
    
    for query in queries:
        
        try:
            result = geocode(query)
            
            if result is None:
                continue
            
            address = result.address.upper()
            
            expected_state = normalize_name(state)
            
            # State must appear in returned address
            if expected_state in address:
                return {
                    "latitude": result.latitude,
                    "longitude": result.longitude,
                    "status": "VERIFIED",
                    "source": "Nominatim_state_match",
                    "matched_address": result.address
                }
            
        except Exception as e:
            print("Error:", e)
    
    return {
        "latitude": np.nan,
        "longitude": np.nan,
        "status": "REVIEW_REQUIRED",
        "source": "No_verified_match",
        "matched_address": ""
    }

In [27]:
test_cases = [
    ("ADILABAD", "Andhra Pradesh"),
    ("ANANTAPUR", "Andhra Pradesh"),
    ("NICOBARS", "Andaman and Nicobar Island"),
    ("NORTH AND MIDDLE ANDAMAN", "Andaman and Nicobar Island"),
    ("SOUTH ANDAMANS", "Andaman and Nicobar Island")
]

for district, state in test_cases:
    
    result = geocode_verified(
        district,
        state
    )
    
    print(
        state,
        "|",
        district,
        "→",
        result
    )

Andhra Pradesh | ADILABAD → {'latitude': nan, 'longitude': nan, 'status': 'REVIEW_REQUIRED', 'source': 'No_verified_match', 'matched_address': ''}
Andhra Pradesh | ANANTAPUR → {'latitude': 14.6783221, 'longitude': 77.6065039, 'status': 'VERIFIED', 'source': 'Nominatim_state_match', 'matched_address': 'Anantapur, Anantapuram, Andhra Pradesh, 515001, India'}
Andaman and Nicobar Island | NICOBARS → {'latitude': nan, 'longitude': nan, 'status': 'REVIEW_REQUIRED', 'source': 'No_verified_match', 'matched_address': ''}
Andaman and Nicobar Island | NORTH AND MIDDLE ANDAMAN → {'latitude': 12.6112387, 'longitude': 92.8316541, 'status': 'VERIFIED', 'source': 'Nominatim_state_match', 'matched_address': 'North and Middle Andaman, Andaman and Nicobar Islands, India'}
Andaman and Nicobar Island | SOUTH ANDAMANS → {'latitude': nan, 'longitude': nan, 'status': 'REVIEW_REQUIRED', 'source': 'No_verified_match', 'matched_address': ''}

In [28]:
results = []

for index, row in locations.iterrows():

    print(
        f"Processing {index + 1}/{len(locations)}: "
        f"{row['State']} | {row['District']}"
    )

    result = geocode_verified(
        row["District"],
        row["State"]
    )

    results.append({
        "State": row["State"],
        "District": row["District"],
        "Latitude": result["latitude"],
        "Longitude": result["longitude"],
        "Mapping_Status": result["status"],
        "Mapping_Source": result["source"],
        "Matched_Address": result["matched_address"]
    })

Processing 1/771: Andaman and Nicobar Island | NICOBARS
Processing 2/771: Andaman and Nicobar Island | NORTH AND MIDDLE ANDAMAN
Processing 3/771: Andaman and Nicobar Island | SOUTH ANDAMANS
Processing 4/771: Andhra Pradesh | ADILABAD
Processing 5/771: Andhra Pradesh | ANANTAPUR
Processing 6/771: Andhra Pradesh | CHITTOOR
Processing 7/771: Andhra Pradesh | EAST GODAVARI
Processing 8/771: Andhra Pradesh | GUNTUR
Processing 9/771: Andhra Pradesh | HYDERABAD
Processing 10/771: Andhra Pradesh | KADAPA
Processing 11/771: Andhra Pradesh | KARIMNAGAR
Processing 12/771: Andhra Pradesh | KHAMMAM
Processing 13/771: Andhra Pradesh | KRISHNA
Processing 14/771: Andhra Pradesh | KURNOOL
Processing 15/771: Andhra Pradesh | MAHBUBNAGAR
Processing 16/771: Andhra Pradesh | MEDAK
Processing 17/771: Andhra Pradesh | NALGONDA
Processing 18/771: Andhra Pradesh | NIZAMABAD
Processing 19/771: Andhra Pradesh | PRAKASAM
Processing 20/771: Andhra Pradesh | RANGAREDDI
Processing 21/771: Andhra Pradesh | SPSR NELLORE
Processing 22/771: Andhra Pradesh | SRIKAKULAM
Processing 23/771: Andhra Pradesh | VISAKHAPATANAM
Processing 24/771: Andhra Pradesh | VIZIANAGARAM
Processing 25/771: Andhra Pradesh | WARANGAL
Processing 26/771: Andhra Pradesh | WEST GODAVARI
Processing 27/771: Arunachal Pradesh | ANJAW
Processing 28/771: Arunachal Pradesh | CHANGLANG
Processing 29/771: Arunachal Pradesh | DIBANG VALLEY
Processing 30/771: Arunachal Pradesh | EAST KAMENG
Processing 31/771: Arunachal Pradesh | EAST SIANG
Processing 32/771: Arunachal Pradesh | KAMLE
Processing 33/771: Arunachal Pradesh | KRA DAADI
Processing 34/771: Arunachal Pradesh | KURUNG KUMEY
Processing 35/771: Arunachal Pradesh | LEPARADA
Processing 36/771: Arunachal Pradesh | LOHIT
Processing 37/771: Arunachal Pradesh | LONGDING
Processing 38/771: Arunachal Pradesh | LOWER DIBANG VALLEY
Processing 39/771: Arunachal Pradesh | LOWER SIANG
Processing 40/771: Arunachal Pradesh | LOWER SUBANSIRI
Processing 41/771: Arunachal Pradesh | NAMSAI
Processing 42/771: Arunachal Pradesh | PAKKE KESSANG
Processing 43/771: Arunachal Pradesh | PAPUM PARE
Processing 44/771: Arunachal Pradesh | SHI YOMI
Processing 45/771: Arunachal Pradesh | SIANG
Processing 46/771: Arunachal Pradesh | TAWANG
Processing 47/771: Arunachal Pradesh | TIRAP
Processing 48/771: Arunachal Pradesh | UPPER SIANG
Processing 49/771: Arunachal Pradesh | UPPER SUBANSIRI
Processing 50/771: Arunachal Pradesh | WEST KAMENG
Processing 51/771: Arunachal Pradesh | WEST SIANG
Processing 52/771: Assam | BAKSA
Processing 53/771: Assam | BARPETA
Processing 54/771: Assam | BISWANATH
Processing 55/771: Assam | BONGAIGAON
Processing 56/771: Assam | CACHAR
Processing 57/771: Assam | CHARAIDEO
Processing 58/771: Assam | CHIRANG
Processing 59/771: Assam | DARRANG
Processing 60/771: Assam | DHEMAJI
Processing 61/771: Assam | DHUBRI
Processing 62/771: Assam | DIBRUGARH
Processing 63/771: Assam | DIMA HASAO
Processing 64/771: Assam | GOALPARA
Processing 65/771: Assam | GOLAGHAT
Processing 66/771: Assam | HAILAKANDI
Processing 67/771: Assam | HOJAI
Processing 68/771: Assam | JORHAT
Processing 69/771: Assam | KAMRUP
Processing 70/771: Assam | KAMRUP METRO
Processing 71/771: Assam | KARBI ANGLONG
Processing 72/771: Assam | KARIMGANJ
Processing 73/771: Assam | KOKRAJHAR
Processing 74/771: Assam | LAKHIMPUR
Processing 75/771: Assam | MAJULI
Processing 76/771: Assam | MARIGAON
Processing 77/771: Assam | NAGAON
Processing 78/771: Assam | NALBARI
Processing 79/771: Assam | SIVASAGAR
Processing 80/771: Assam | SONITPUR
Processing 81/771: Assam | SOUTH SALMARA MANCACHAR
Processing 82/771: Assam | TINSUKIA
Processing 83/771: Assam | UDALGURI
Processing 84/771: Assam | WEST KARBI ANGLONG
Processing 85/771: Bihar | ARARIA
Processing 86/771: Bihar | ARWAL
Processing 87/771: Bihar | AURANGABAD
Processing 88/771: Bihar | BANKA
Processing 89/771: Bihar | BEGUSARAI
Processing 90/771: Bihar | BHAGALPUR
Processing 91/771: Bihar | BHOJPUR
Processing 92/771: Bihar | BOKARO
Processing 93/771: Bihar | BUXAR
Processing 94/771: Bihar | CHATRA
Processing 95/771: Bihar | DARBHANGA
Processing 96/771: Bihar | DEOGHAR
Processing 97/771: Bihar | DHANBAD
Processing 98/771: Bihar | DUMKA
Processing 99/771: Bihar | EAST SINGHBUM
Processing 100/771: Bihar | GARHWA
Processing 101/771: Bihar | GAYA
Processing 102/771: Bihar | GIRIDIH
Processing 103/771: Bihar | GODDA
Processing 104/771: Bihar | GOPALGANJ
Processing 105/771: Bihar | GUMLA
Processing 106/771: Bihar | HAZARIBAGH
Processing 107/771: Bihar | JAMUI
Processing 108/771: Bihar | JEHANABAD
Processing 109/771: Bihar | KAIMUR (BHABUA)
Processing 110/771: Bihar | KATIHAR
Processing 111/771: Bihar | KHAGARIA
Processing 112/771: Bihar | KISHANGANJ
Processing 113/771: Bihar | KODERMA
Processing 114/771: Bihar | LAKHISARAI
Processing 115/771: Bihar | LOHARDAGA
Processing 116/771: Bihar | MADHEPURA
Processing 117/771: Bihar | MADHUBANI
Processing 118/771: Bihar | MUNGER
Processing 119/771: Bihar | MUZAFFARPUR
Processing 120/771: Bihar | NALANDA
Processing 121/771: Bihar | NAWADA
Processing 122/771: Bihar | PAKUR
Processing 123/771: Bihar | PALAMU
Processing 124/771: Bihar | PASHCHIM CHAMPARAN
Processing 125/771: Bihar | PATNA
Processing 126/771: Bihar | PURBI CHAMPARAN
Processing 127/771: Bihar | PURNIA
Processing 128/771: Bihar | RANCHI
Processing 129/771: Bihar | ROHTAS
Processing 130/771: Bihar | SAHARSA
Processing 131/771: Bihar | SAHEBGANJ
Processing 132/771: Bihar | SAMASTIPUR
Processing 133/771: Bihar | SARAN
Processing 134/771: Bihar | SHEIKHPURA
Processing 135/771: Bihar | SHEOHAR
Processing 136/771: Bihar | SITAMARHI
Processing 137/771: Bihar | SIWAN
Processing 138/771: Bihar | SUPAUL
Processing 139/771: Bihar | VAISHALI
Processing 140/771: Bihar | WEST SINGHBHUM
Processing 141/771: Chandigarh | CHANDIGARH
Processing 142/771: Chhattisgarh | BALOD
Processing 143/771: Chhattisgarh | BALODA BAZAR
Processing 144/771: Chhattisgarh | BALRAMPUR
Processing 145/771: Chhattisgarh | BASTAR
Processing 146/771: Chhattisgarh | BEMETARA
Processing 147/771: Chhattisgarh | BIJAPUR
Processing 148/771: Chhattisgarh | BILASPUR
Processing 149/771: Chhattisgarh | DANTEWADA
Processing 150/771: Chhattisgarh | DHAMTARI
Processing 151/771: Chhattisgarh | DURG
Processing 152/771: Chhattisgarh | GARIYABAND
Processing 153/771: Chhattisgarh | GAURELLA-PENDRA-MARWAHI
Processing 154/771: Chhattisgarh | JANJGIR-CHAMPA
Processing 155/771: Chhattisgarh | JASHPUR
Processing 156/771: Chhattisgarh | KABIRDHAM
Processing 157/771: Chhattisgarh | KANKER
Processing 158/771: Chhattisgarh | KONDAGAON
Processing 159/771: Chhattisgarh | KORBA
Processing 160/771: Chhattisgarh | KOREA
Processing 161/771: Chhattisgarh | MAHASAMUND
Processing 162/771: Chhattisgarh | MUNGELI
Processing 163/771: Chhattisgarh | NARAYANPUR
Processing 164/771: Chhattisgarh | RAIGARH
Processing 165/771: Chhattisgarh | RAIPUR
Processing 166/771: Chhattisgarh | RAJNANDGAON
Processing 167/771: Chhattisgarh | SUKMA
Processing 168/771: Chhattisgarh | SURAJPUR
Processing 169/771: Chhattisgarh | SURGUJA
Processing 170/771: Dadra and Nagar Haveli | DADRA AND NAGAR HAVELI
Processing 171/771: Dadra and Nagar Haveli | DAMAN
Processing 172/771: Dadra and Nagar Haveli | DIU
Processing 173/771: Daman and Diu | DAMAN
Processing 174/771: Daman and Diu | DIU
Processing 175/771: Delhi | DELHI_TOTAL
Processing 176/771: Goa | NORTH GOA
Processing 177/771: Goa | SOUTH GOA
Processing 178/771: Gujarat | AHMADABAD
Processing 179/771: Gujarat | AMRELI
Processing 180/771: Gujarat | ANAND
Processing 181/771: Gujarat | ARAVALLI
Processing 182/771: Gujarat | BANAS KANTHA
Processing 183/771: Gujarat | BHARUCH
Processing 184/771: Gujarat | BHAVNAGAR
Processing 185/771: Gujarat | BOTAD
Processing 186/771: Gujarat | CHHOTAUDEPUR
Processing 187/771: Gujarat | DANG
Processing 188/771: Gujarat | DEVBHUMI DWARKA
Processing 189/771: Gujarat | DOHAD
Processing 190/771: Gujarat | GANDHINAGAR
Processing 191/771: Gujarat | GIR SOMNATH
Processing 192/771: Gujarat | JAMNAGAR
Processing 193/771: Gujarat | JUNAGADH
Processing 194/771: Gujarat | KACHCHH
Processing 195/771: Gujarat | KHEDA
Processing 196/771: Gujarat | MAHESANA
Processing 197/771: Gujarat | MAHISAGAR
Processing 198/771: Gujarat | MORBI
Processing 199/771: Gujarat | NARMADA
Processing 200/771: Gujarat | NAVSARI
Processing 201/771: Gujarat | PANCH MAHALS
Processing 202/771: Gujarat | PATAN
Processing 203/771: Gujarat | PORBANDAR
Processing 204/771: Gujarat | RAJKOT
Processing 205/771: Gujarat | SABAR KANTHA
Processing 206/771: Gujarat | SURAT
Processing 207/771: Gujarat | SURENDRANAGAR
Processing 208/771: Gujarat | TAPI
Processing 209/771: Gujarat | VADODARA
Processing 210/771: Gujarat | VALSAD
Processing 211/771: Haryana | AMBALA
Processing 212/771: Haryana | BHIWANI
Processing 213/771: Haryana | CHARKI DADRI
Processing 214/771: Haryana | FARIDABAD
Processing 215/771: Haryana | FATEHABAD
Processing 216/771: Haryana | GURGAON
Processing 217/771: Haryana | HISAR
Processing 218/771: Haryana | JHAJJAR
Processing 219/771: Haryana | JIND
Processing 220/771: Haryana | KAITHAL
Processing 221/771: Haryana | KARNAL
Processing 222/771: Haryana | KURUKSHETRA
Processing 223/771: Haryana | MAHENDRAGARH
Processing 224/771: Haryana | MEWAT
Processing 225/771: Haryana | PALWAL
Processing 226/771: Haryana | PANCHKULA
Processing 227/771: Haryana | PANIPAT
Processing 228/771: Haryana | REWARI
Processing 229/771: Haryana | ROHTAK
Processing 230/771: Haryana | SIRSA
Processing 231/771: Haryana | SONIPAT
Processing 232/771: Haryana | YAMUNANAGAR
Processing 233/771: Himachal Pradesh | BILASPUR
Processing 234/771: Himachal Pradesh | CHAMBA
Processing 235/771: Himachal Pradesh | HAMIRPUR
Processing 236/771: Himachal Pradesh | KANGRA
Processing 237/771: Himachal Pradesh | KINNAUR
Processing 238/771: Himachal Pradesh | KULLU
Processing 239/771: Himachal Pradesh | LAHUL AND SPITI
Processing 240/771: Himachal Pradesh | MANDI
Processing 241/771: Himachal Pradesh | SHIMLA
Processing 242/771: Himachal Pradesh | SIRMAUR
Processing 243/771: Himachal Pradesh | SOLAN
Processing 244/771: Himachal Pradesh | UNA
Processing 245/771: Jammu and Kashmir | ANANTNAG
Processing 246/771: Jammu and Kashmir | BADGAM
Processing 247/771: Jammu and Kashmir | BANDIPORA
Processing 248/771: Jammu and Kashmir | BARAMULLA
Processing 249/771: Jammu and Kashmir | DODA
Processing 250/771: Jammu and Kashmir | GANDERBAL
Processing 251/771: Jammu and Kashmir | JAMMU
Processing 252/771: Jammu and Kashmir | KARGIL
Processing 253/771: Jammu and Kashmir | KATHUA
Processing 254/771: Jammu and Kashmir | KISHTWAR
Processing 255/771: Jammu and Kashmir | KULGAM
Processing 256/771: Jammu and Kashmir | KUPWARA
Processing 257/771: Jammu and Kashmir | LEH LADAKH
Processing 258/771: Jammu and Kashmir | POONCH
Processing 259/771: Jammu and Kashmir | PULWAMA
Processing 260/771: Jammu and Kashmir | RAJAURI
Processing 261/771: Jammu and Kashmir | RAMBAN
Processing 262/771: Jammu and Kashmir | REASI
Processing 263/771: Jammu and Kashmir | SAMBA
Processing 264/771: Jammu and Kashmir | SHOPIAN
Processing 265/771: Jammu and Kashmir | SRINAGAR
Processing 266/771: Jammu and Kashmir | UDHAMPUR
Processing 267/771: Jharkhand | BOKARO
Processing 268/771: Jharkhand | CHATRA
Processing 269/771: Jharkhand | DEOGHAR
Processing 270/771: Jharkhand | DHANBAD
Processing 271/771: Jharkhand | DUMKA
Processing 272/771: Jharkhand | EAST SINGHBUM
Processing 273/771: Jharkhand | GARHWA
Processing 274/771: Jharkhand | GIRIDIH
Processing 275/771: Jharkhand | GODDA
Processing 276/771: Jharkhand | GUMLA
Processing 277/771: Jharkhand | HAZARIBAGH
Processing 278/771: Jharkhand | JAMTARA
Processing 279/771: Jharkhand | KHUNTI
Processing 280/771: Jharkhand | KODERMA
Processing 281/771: Jharkhand | LATEHAR
Processing 282/771: Jharkhand | LOHARDAGA
Processing 283/771: Jharkhand | PAKUR
Processing 284/771: Jharkhand | PALAMU
Processing 285/771: Jharkhand | RAMGARH
Processing 286/771: Jharkhand | RANCHI
Processing 287/771: Jharkhand | SAHEBGANJ
Processing 288/771: Jharkhand | SARAIKELA KHARSAWAN
Processing 289/771: Jharkhand | SIMDEGA
Processing 290/771: Jharkhand | WEST SINGHBHUM
Processing 291/771: Karnataka | BAGALKOTE
Processing 292/771: Karnataka | BALLARI
Processing 293/771: Karnataka | BANGALORE RURAL
Processing 294/771: Karnataka | BELAGAVI
Processing 295/771: Karnataka | BENGALURU URBAN
Processing 296/771: Karnataka | BIDAR
Processing 297/771: Karnataka | CHAMARAJANAGARA
Processing 298/771: Karnataka | CHIKKABALLAPURA
Processing 299/771: Karnataka | CHIKKAMAGALURU
Processing 300/771: Karnataka | CHITRADURGA
Processing 301/771: Karnataka | DAKSHINA KANNADA
Processing 302/771: Karnataka | DAVANGERE
Processing 303/771: Karnataka | DHARWAD
Processing 304/771: Karnataka | GADAG
Processing 305/771: Karnataka | HASSAN
Processing 306/771: Karnataka | HAVERI
Processing 307/771: Karnataka | KALABURAGI
Processing 308/771: Karnataka | KODAGU
Processing 309/771: Karnataka | KOLAR
Processing 310/771: Karnataka | KOPPAL
Processing 311/771: Karnataka | MANDYA
Processing 312/771: Karnataka | MYSURU
Processing 313/771: Karnataka | RAICHUR
Processing 314/771: Karnataka | RAMANAGARA
Processing 315/771: Karnataka | SHIVAMOGGA
Processing 316/771: Karnataka | TUMAKURU
Processing 317/771: Karnataka | UDUPI
Processing 318/771: Karnataka | UTTARA KANNADA
Processing 319/771: Karnataka | VIJAYAPURA
Processing 320/771: Karnataka | YADAGIRI
Processing 321/771: Kerala | ALAPPUZHA
Processing 322/771: Kerala | ERNAKULAM
Processing 323/771: Kerala | IDUKKI
Processing 324/771: Kerala | KANNUR
Processing 325/771: Kerala | KASARAGOD
Processing 326/771: Kerala | KOLLAM
Processing 327/771: Kerala | KOTTAYAM
Processing 328/771: Kerala | KOZHIKODE
Processing 329/771: Kerala | MALAPPURAM
Processing 330/771: Kerala | PALAKKAD
Processing 331/771: Kerala | PATHANAMTHITTA
Processing 332/771: Kerala | THIRUVANANTHAPURAM
Processing 333/771: Kerala | THRISSUR
Processing 334/771: Kerala | WAYANAD
Processing 335/771: Ladakh | KARGIL
Processing 336/771: Ladakh | LEH LADAKH
Processing 337/771: Madhya Pradesh | AGAR MALWA
Processing 338/771: Madhya Pradesh | ALIRAJPUR
Processing 339/771: Madhya Pradesh | ANUPPUR
Processing 340/771: Madhya Pradesh | ASHOKNAGAR
Processing 341/771: Madhya Pradesh | BALAGHAT
Processing 342/771: Madhya Pradesh | BARWANI
Processing 343/771: Madhya Pradesh | BASTAR
Processing 344/771: Madhya Pradesh | BETUL
Processing 345/771: Madhya Pradesh | BHIND
Processing 346/771: Madhya Pradesh | BHOPAL
Processing 347/771: Madhya Pradesh | BILASPUR
Processing 348/771: Madhya Pradesh | BURHANPUR
Processing 349/771: Madhya Pradesh | CHHATARPUR
Processing 350/771: Madhya Pradesh | CHHINDWARA
Processing 351/771: Madhya Pradesh | DAMOH
Processing 352/771: Madhya Pradesh | DANTEWADA
Processing 353/771: Madhya Pradesh | DATIA
Processing 354/771: Madhya Pradesh | DEWAS
Processing 355/771: Madhya Pradesh | DHAMTARI
Processing 356/771: Madhya Pradesh | DHAR
Processing 357/771: Madhya Pradesh | DINDORI
Processing 358/771: Madhya Pradesh | DURG
Processing 359/771: Madhya Pradesh | GUNA
Processing 360/771: Madhya Pradesh | GWALIOR
Processing 361/771: Madhya Pradesh | HARDA
Processing 362/771: Madhya Pradesh | HOSHANGABAD
Processing 363/771: Madhya Pradesh | INDORE
Processing 364/771: Madhya Pradesh | JABALPUR
Processing 365/771: Madhya Pradesh | JANJGIR-CHAMPA
Processing 366/771: Madhya Pradesh | JASHPUR
Processing 367/771: Madhya Pradesh | JHABUA
Processing 368/771: Madhya Pradesh | KABIRDHAM
Processing 369/771: Madhya Pradesh | KANKER
Processing 370/771: Madhya Pradesh | KATNI
Processing 371/771: Madhya Pradesh | KHANDWA
Processing 372/771: Madhya Pradesh | KHARGONE
Processing 373/771: Madhya Pradesh | KORBA
Processing 374/771: Madhya Pradesh | KOREA
Processing 375/771: Madhya Pradesh | MAHASAMUND
Processing 376/771: Madhya Pradesh | MANDLA
Processing 377/771: Madhya Pradesh | MANDSAUR
Processing 378/771: Madhya Pradesh | MORENA
Processing 379/771: Madhya Pradesh | NARSINGHPUR
Processing 380/771: Madhya Pradesh | NEEMUCH
Processing 381/771: Madhya Pradesh | NIWARI
Processing 382/771: Madhya Pradesh | PANNA
Processing 383/771: Madhya Pradesh | RAIPUR
Processing 384/771: Madhya Pradesh | RAISEN
Processing 385/771: Madhya Pradesh | RAJGARH
Processing 386/771: Madhya Pradesh | RAJNANDGAON
Processing 387/771: Madhya Pradesh | RATLAM
Processing 388/771: Madhya Pradesh | REWA
Processing 389/771: Madhya Pradesh | SAGAR
Processing 390/771: Madhya Pradesh | SATNA
Processing 391/771: Madhya Pradesh | SEHORE
Processing 392/771: Madhya Pradesh | SEONI
Processing 393/771: Madhya Pradesh | SHAHDOL
Processing 394/771: Madhya Pradesh | SHAJAPUR
Processing 395/771: Madhya Pradesh | SHEOPUR
Processing 396/771: Madhya Pradesh | SHIVPURI
Processing 397/771: Madhya Pradesh | SIDHI
Processing 398/771: Madhya Pradesh | SINGRAULI
Processing 399/771: Madhya Pradesh | SURGUJA
Processing 400/771: Madhya Pradesh | TIKAMGARH
Processing 401/771: Madhya Pradesh | UJJAIN
Processing 402/771: Madhya Pradesh | UMARIA
Processing 403/771: Madhya Pradesh | VIDISHA
Processing 404/771: Maharashtra | AHMEDNAGAR
Processing 405/771: Maharashtra | AKOLA
Processing 406/771: Maharashtra | AMRAVATI
Processing 407/771: Maharashtra | AURANGABAD
Processing 408/771: Maharashtra | BEED
Processing 409/771: Maharashtra | BHANDARA
Processing 410/771: Maharashtra | BULDHANA
Processing 411/771: Maharashtra | CHANDRAPUR
Processing 412/771: Maharashtra | DHULE
Processing 413/771: Maharashtra | GADCHIROLI
Processing 414/771: Maharashtra | GONDIA
Processing 415/771: Maharashtra | HINGOLI
Processing 416/771: Maharashtra | JALGAON
Processing 417/771: Maharashtra | JALNA
Processing 418/771: Maharashtra | KOLHAPUR
Processing 419/771: Maharashtra | LATUR
Processing 420/771: Maharashtra | MUMBAI
Processing 421/771: Maharashtra | MUMBAI SUBURBAN
Processing 422/771: Maharashtra | NAGPUR
Processing 423/771: Maharashtra | NANDED
Processing 424/771: Maharashtra | NANDURBAR
Processing 425/771: Maharashtra | NASHIK
Processing 426/771: Maharashtra | OSMANABAD
Processing 427/771: Maharashtra | PALGHAR
Processing 428/771: Maharashtra | PARBHANI
Processing 429/771: Maharashtra | PUNE
Processing 430/771: Maharashtra | RAIGAD
Processing 431/771: Maharashtra | RATNAGIRI
Processing 432/771: Maharashtra | SANGLI
Processing 433/771: Maharashtra | SATARA
Processing 434/771: Maharashtra | SINDHUDURG
Processing 435/771: Maharashtra | SOLAPUR
Processing 436/771: Maharashtra | THANE
Processing 437/771: Maharashtra | WARDHA
Processing 438/771: Maharashtra | WASHIM
Processing 439/771: Maharashtra | YAVATMAL
Processing 440/771: Manipur | BISHNUPUR
Processing 441/771: Manipur | CHANDEL
Processing 442/771: Manipur | CHURACHANDPUR
Processing 443/771: Manipur | IMPHAL EAST
Processing 444/771: Manipur | IMPHAL WEST
Processing 445/771: Manipur | SENAPATI
Processing 446/771: Manipur | TAMENGLONG
Processing 447/771: Manipur | THOUBAL
Processing 448/771: Manipur | UKHRUL
Processing 449/771: Meghalaya | EAST GARO HILLS
Processing 450/771: Meghalaya | EAST JAINTIA HILLS
Processing 451/771: Meghalaya | EAST KHASI HILLS
Processing 452/771: Meghalaya | NORTH GARO HILLS
Processing 453/771: Meghalaya | RI BHOI
Processing 454/771: Meghalaya | SOUTH GARO HILLS
Processing 455/771: Meghalaya | SOUTH WEST GARO HILLS
Processing 456/771: Meghalaya | SOUTH WEST KHASI HILLS
Processing 457/771: Meghalaya | WEST GARO HILLS
Processing 458/771: Meghalaya | WEST JAINTIA HILLS
Processing 459/771: Meghalaya | WEST KHASI HILLS
Processing 460/771: Mizoram | AIZAWL
Processing 461/771: Mizoram | CHAMPHAI
Processing 462/771: Mizoram | KOLASIB
Processing 463/771: Mizoram | LAWNGTLAI
Processing 464/771: Mizoram | LUNGLEI
Processing 465/771: Mizoram | MAMIT
Processing 466/771: Mizoram | SAIHA
Processing 467/771: Mizoram | SERCHHIP
Processing 468/771: Nagaland | DIMAPUR
Processing 469/771: Nagaland | KIPHIRE
Processing 470/771: Nagaland | KOHIMA
Processing 471/771: Nagaland | LONGLENG
Processing 472/771: Nagaland | MOKOKCHUNG
Processing 473/771: Nagaland | MON

In [33]:
location_results = pd.DataFrame(results)

print("Total locations:", len(location_results))

location_results.head()

Total locations: 771

,State,District,Latitude,Longitude,Mapping_Status,Mapping_Source,Matched_Address
0,Andaman and Nicobar Island,NICOBARS,NaN,NaN,REVIEW_REQUIRED,No_verified_match,
1,Andaman and Nicobar Island,NORTH AND MIDDLE ANDAMAN,12.611239,92.831654,VERIFIED,Nominatim_state_match,"North and Middle Andaman, Andaman and Nicobar ..."
2,Andaman and Nicobar Island,SOUTH ANDAMANS,NaN,NaN,REVIEW_REQUIRED,No_verified_match,
3,Andhra Pradesh,ADILABAD,NaN,NaN,REVIEW_REQUIRED,No_verified_match,
4,Andhra Pradesh,ANANTAPUR,14.678322,77.606504,VERIFIED,Nominatim_state_match,"Anantapur, Anantapuram, Andhra Pradesh, 515001..."

In [31]:
print(
    location_results["Mapping_Status"]
    .value_counts()
)

Mapping_Status
VERIFIED           709
REVIEW_REQUIRED     62
Name: count, dtype: int64

In [34]:
verified = (
    location_results["Mapping_Status"] == "VERIFIED"
).sum()

total = len(location_results)

success_rate = verified / total * 100

print(f"Verified: {verified}/{total}")
print(f"Success rate: {success_rate:.2f}%")

Verified: 709/771
Success rate: 91.96%

In [35]:
review_locations = location_results[
    location_results["Mapping_Status"] == "REVIEW_REQUIRED"
].copy()

print("Locations requiring review:", len(review_locations))

review_locations[
    ["State", "District"]
].head(50)

Locations requiring review: 62

                          State                   District
0    Andaman and Nicobar Island                   NICOBARS
2    Andaman and Nicobar Island             SOUTH ANDAMANS
3                Andhra Pradesh                   ADILABAD
10               Andhra Pradesh                 KARIMNAGAR
15               Andhra Pradesh                      MEDAK
16               Andhra Pradesh                   NALGONDA
19               Andhra Pradesh                 RANGAREDDI
22               Andhra Pradesh             VISAKHAPATANAM
24               Andhra Pradesh                   WARANGAL
34            Arunachal Pradesh                   LEPARADA
80                        Assam    SOUTH SALMARA MANCACHAR
91                        Bihar                     BOKARO
96                        Bihar                    DHANBAD
97                        Bihar                      DUMKA
98                        Bihar              EAST SINGHBUM
99                        Bihar                     GARHWA
101                       Bihar                    GIRIDIH
102                       Bihar                      GODDA
104                       Bihar                      GUMLA
105                       Bihar                 HAZARIBAGH
112                       Bihar                    KODERMA
114                       Bihar                  LOHARDAGA
121                       Bihar                      PAKUR
122                       Bihar                     PALAMU
139                       Bihar             WEST SINGHBHUM
174                       Delhi                DELHI_TOTAL
185                     Gujarat               CHHOTAUDEPUR
188                     Gujarat                      DOHAD
212                     Haryana               CHARKI DADRI
238            Himachal Pradesh            LAHUL AND SPITI
256           Jammu and Kashmir                 LEH LADAKH
271                   Jharkhand              EAST SINGHBUM
342              Madhya Pradesh                     BASTAR
351              Madhya Pradesh                  DANTEWADA
354              Madhya Pradesh                   DHAMTARI
357              Madhya Pradesh                       DURG
364              Madhya Pradesh             JANJGIR-CHAMPA
365              Madhya Pradesh                    JASHPUR
367              Madhya Pradesh                  KABIRDHAM
368              Madhya Pradesh                     KANKER
372              Madhya Pradesh                      KORBA
374              Madhya Pradesh                 MAHASAMUND
385              Madhya Pradesh                RAJNANDGAON
398              Madhya Pradesh                    SURGUJA
518                      Punjab                  FIROZEPUR
532                      Punjab  SHAHID BHAGAT SINGH NAGAR
632                   Telangana                 RANGAREDDI
651               Uttar Pradesh                     ALMORA
669               Uttar Pradesh                    CHAMOLI
670               Uttar Pradesh                  CHAMPAWAT

In [36]:
review_by_state = (
    review_locations
    .groupby("State")
    .size()
    .sort_values(ascending=False)
)

print(review_by_state)

State
Bihar                         14
Madhya Pradesh                12
Uttar Pradesh                 10
Andhra Pradesh                 7
Uttarakhand                    3
Andaman and Nicobar Island     2
Punjab                         2
West Bengal                    2
Gujarat                        2
Haryana                        1
Jammu and Kashmir              1
Jharkhand                      1
Delhi                          1
Telangana                      1
Assam                          1
Arunachal Pradesh              1
Himachal Pradesh               1
dtype: int64

In [37]:
os.makedirs("../data/processed", exist_ok=True)

In [38]:
location_results.to_csv(
    "../data/processed/location_reference_results.csv",
    index=False
)

review_locations.to_csv(
    "../data/processed/location_review.csv",
    index=False
)

print("Location reference files saved.")

Location reference files saved.

In [39]:
location_results["Mapping_Status"].value_counts()

Mapping_Status
VERIFIED           709
REVIEW_REQUIRED     62
Name: count, dtype: int64

In [40]:
review_by_state

State
Bihar                         14
Madhya Pradesh                12
Uttar Pradesh                 10
Andhra Pradesh                 7
Uttarakhand                    3
Andaman and Nicobar Island     2
Punjab                         2
West Bengal                    2
Gujarat                        2
Haryana                        1
Jammu and Kashmir              1
Jharkhand                      1
Delhi                          1
Telangana                      1
Assam                          1
Arunachal Pradesh              1
Himachal Pradesh               1
dtype: int64

In [41]:
review_locations = location_results[
    location_results["Mapping_Status"] == "REVIEW_REQUIRED"
].copy()

print("Locations requiring review:", len(review_locations))

review_locations[
    ["State", "District"]
].head(100)

Locations requiring review: 62

                          State          District
0    Andaman and Nicobar Island          NICOBARS
2    Andaman and Nicobar Island    SOUTH ANDAMANS
3                Andhra Pradesh          ADILABAD
10               Andhra Pradesh        KARIMNAGAR
15               Andhra Pradesh             MEDAK
..                          ...               ...
745                 Uttarakhand      RUDRA PRAYAG
747                 Uttarakhand  UDAM SINGH NAGAR
748                 Uttarakhand       UTTAR KASHI
766                 West Bengal   PARAGANAS NORTH
767                 West Bengal   PARAGANAS SOUTH

[62 rows x 2 columns]

In [42]:
review_by_state = (
    review_locations
    .groupby("State")
    .size()
    .sort_values(ascending=False)
)

print(review_by_state)

State
Bihar                         14
Madhya Pradesh                12
Uttar Pradesh                 10
Andhra Pradesh                 7
Uttarakhand                    3
Andaman and Nicobar Island     2
Punjab                         2
West Bengal                    2
Gujarat                        2
Haryana                        1
Jammu and Kashmir              1
Jharkhand                      1
Delhi                          1
Telangana                      1
Assam                          1
Arunachal Pradesh              1
Himachal Pradesh               1
dtype: int64

In [43]:
review_locations.to_csv(
    "../data/processed/location_review.csv",
    index=False
)

print("Review file saved.")

Review file saved.

In [44]:
verified_locations = location_results[
    location_results["Mapping_Status"] == "VERIFIED"
].copy()

verified_locations.to_csv(
    "../data/processed/location_verified.csv",
    index=False
)

print("Verified locations:", len(verified_locations))

Verified locations: 709

In [45]:
pd.set_option("display.max_rows", 100)

review_locations[
    ["State", "District", "Mapping_Status", "Mapping_Source"]
]

,State,District,Mapping_Status,Mapping_Source
0,Andaman and Nicobar Island,NICOBARS,REVIEW_REQUIRED,No_verified_match
2,Andaman and Nicobar Island,SOUTH ANDAMANS,REVIEW_REQUIRED,No_verified_match
3,Andhra Pradesh,ADILABAD,REVIEW_REQUIRED,No_verified_match
10,Andhra Pradesh,KARIMNAGAR,REVIEW_REQUIRED,No_verified_match
15,Andhra Pradesh,MEDAK,REVIEW_REQUIRED,No_verified_match
16,Andhra Pradesh,NALGONDA,REVIEW_REQUIRED,No_verified_match
19,Andhra Pradesh,RANGAREDDI,REVIEW_REQUIRED,No_verified_match
22,Andhra Pradesh,VISAKHAPATANAM,REVIEW_REQUIRED,No_verified_match
24,Andhra Pradesh,WARANGAL,REVIEW_REQUIRED,No_verified_match
34,Arunachal Pradesh,LEPARADA,REVIEW_REQUIRED,No_verified_match
80,Assam,SOUTH SALMARA MANCACHAR,REVIEW_REQUIRED,No_verified_match
91,Bihar,BOKARO,REVIEW_REQUIRED,No_verified_match
96,Bihar,DHANBAD,REVIEW_REQUIRED,No_verified_match
97,Bihar,DUMKA,REVIEW_REQUIRED,No_verified_match
98,Bihar,EAST SINGHBUM,REVIEW_REQUIRED,No_verified_match
99,Bihar,GARHWA,REVIEW_REQUIRED,No_verified_match
101,Bihar,GIRIDIH,REVIEW_REQUIRED,No_verified_match
102,Bihar,GODDA,REVIEW_REQUIRED,No_verified_match
104,Bihar,GUMLA,REVIEW_REQUIRED,No_verified_match
105,Bihar,HAZARIBAGH,REVIEW_REQUIRED,No_verified_match
112,Bihar,KODERMA,REVIEW_REQUIRED,No_verified_match
114,Bihar,LOHARDAGA,REVIEW_REQUIRED,No_verified_match
121,Bihar,PAKUR,REVIEW_REQUIRED,No_verified_match
122,Bihar,PALAMU,REVIEW_REQUIRED,No_verified_match
139,Bihar,WEST SINGHBHUM,REVIEW_REQUIRED,No_verified_match
174,Delhi,DELHI_TOTAL,REVIEW_REQUIRED,No_verified_match
185,Gujarat,CHHOTAUDEPUR,REVIEW_REQUIRED,No_verified_match
188,Gujarat,DOHAD,REVIEW_REQUIRED,No_verified_match
212,Haryana,CHARKI DADRI,REVIEW_REQUIRED,No_verified_match
238,Himachal Pradesh,LAHUL AND SPITI,REVIEW_REQUIRED,No_verified_match
256,Jammu and Kashmir,LEH LADAKH,REVIEW_REQUIRED,No_verified_match
271,Jharkhand,EAST SINGHBUM,REVIEW_REQUIRED,No_verified_match
342,Madhya Pradesh,BASTAR,REVIEW_REQUIRED,No_verified_match
351,Madhya Pradesh,DANTEWADA,REVIEW_REQUIRED,No_verified_match
354,Madhya Pradesh,DHAMTARI,REVIEW_REQUIRED,No_verified_match
357,Madhya Pradesh,DURG,REVIEW_REQUIRED,No_verified_match
364,Madhya Pradesh,JANJGIR-CHAMPA,REVIEW_REQUIRED,No_verified_match
365,Madhya Pradesh,JASHPUR,REVIEW_REQUIRED,No_verified_match
367,Madhya Pradesh,KABIRDHAM,REVIEW_REQUIRED,No_verified_match
368,Madhya Pradesh,KANKER,REVIEW_REQUIRED,No_verified_match
372,Madhya Pradesh,KORBA,REVIEW_REQUIRED,No_verified_match
374,Madhya Pradesh,MAHASAMUND,REVIEW_REQUIRED,No_verified_match
385,Madhya Pradesh,RAJNANDGAON,REVIEW_REQUIRED,No_verified_match
398,Madhya Pradesh,SURGUJA,REVIEW_REQUIRED,No_verified_match
518,Punjab,FIROZEPUR,REVIEW_REQUIRED,No_verified_match
532,Punjab,SHAHID BHAGAT SINGH NAGAR,REVIEW_REQUIRED,No_verified_match
632,Telangana,RANGAREDDI,REVIEW_REQUIRED,No_verified_match
651,Uttar Pradesh,ALMORA,REVIEW_REQUIRED,No_verified_match
669,Uttar Pradesh,CHAMOLI,REVIEW_REQUIRED,No_verified_match
670,Uttar Pradesh,CHAMPAWAT,REVIEW_REQUIRED,No_verified_match
700,Uttar Pradesh,KUSHI NAGAR,REVIEW_REQUIRED,No_verified_match
713,Uttar Pradesh,PAURI GARHWAL,REVIEW_REQUIRED,No_verified_match
715,Uttar Pradesh,PITHORAGARH,REVIEW_REQUIRED,No_verified_match
719,Uttar Pradesh,RUDRA PRAYAG,REVIEW_REQUIRED,No_verified_match
722,Uttar Pradesh,SANT KABEER NAGAR,REVIEW_REQUIRED,No_verified_match
731,Uttar Pradesh,TEHRI GARHWAL,REVIEW_REQUIRED,No_verified_match
732,Uttar Pradesh,UDAM SINGH NAGAR,REVIEW_REQUIRED,No_verified_match
745,Uttarakhand,RUDRA PRAYAG,REVIEW_REQUIRED,No_verified_match
747,Uttarakhand,UDAM SINGH NAGAR,REVIEW_REQUIRED,No_verified_match
748,Uttarakhand,UTTAR KASHI,REVIEW_REQUIRED,No_verified_match
766,West Bengal,PARAGANAS NORTH,REVIEW_REQUIRED,No_verified_match
767,West Bengal,PARAGANAS SOUTH,REVIEW_REQUIRED,No_verified_match

In [46]:
print(review_by_state)

State
Bihar                         14
Madhya Pradesh                12
Uttar Pradesh                 10
Andhra Pradesh                 7
Uttarakhand                    3
Andaman and Nicobar Island     2
Punjab                         2
West Bengal                    2
Gujarat                        2
Haryana                        1
Jammu and Kashmir              1
Jharkhand                      1
Delhi                          1
Telangana                      1
Assam                          1
Arunachal Pradesh              1
Himachal Pradesh               1
dtype: int64

In [47]:
pd.set_option("display.max_rows", 100)

review_locations[
    ["State", "District"]
].sort_values(
    ["State", "District"]
)

                          State                   District
0    Andaman and Nicobar Island                   NICOBARS
2    Andaman and Nicobar Island             SOUTH ANDAMANS
3                Andhra Pradesh                   ADILABAD
10               Andhra Pradesh                 KARIMNAGAR
15               Andhra Pradesh                      MEDAK
16               Andhra Pradesh                   NALGONDA
19               Andhra Pradesh                 RANGAREDDI
22               Andhra Pradesh             VISAKHAPATANAM
24               Andhra Pradesh                   WARANGAL
34            Arunachal Pradesh                   LEPARADA
80                        Assam    SOUTH SALMARA MANCACHAR
91                        Bihar                     BOKARO
96                        Bihar                    DHANBAD
97                        Bihar                      DUMKA
98                        Bihar              EAST SINGHBUM
99                        Bihar                     GARHWA
101                       Bihar                    GIRIDIH
102                       Bihar                      GODDA
104                       Bihar                      GUMLA
105                       Bihar                 HAZARIBAGH
112                       Bihar                    KODERMA
114                       Bihar                  LOHARDAGA
121                       Bihar                      PAKUR
122                       Bihar                     PALAMU
139                       Bihar             WEST SINGHBHUM
174                       Delhi                DELHI_TOTAL
185                     Gujarat               CHHOTAUDEPUR
188                     Gujarat                      DOHAD
212                     Haryana               CHARKI DADRI
238            Himachal Pradesh            LAHUL AND SPITI
256           Jammu and Kashmir                 LEH LADAKH
271                   Jharkhand              EAST SINGHBUM
342              Madhya Pradesh                     BASTAR
351              Madhya Pradesh                  DANTEWADA
354              Madhya Pradesh                   DHAMTARI
357              Madhya Pradesh                       DURG
364              Madhya Pradesh             JANJGIR-CHAMPA
365              Madhya Pradesh                    JASHPUR
367              Madhya Pradesh                  KABIRDHAM
368              Madhya Pradesh                     KANKER
372              Madhya Pradesh                      KORBA
374              Madhya Pradesh                 MAHASAMUND
385              Madhya Pradesh                RAJNANDGAON
398              Madhya Pradesh                    SURGUJA
518                      Punjab                  FIROZEPUR
532                      Punjab  SHAHID BHAGAT SINGH NAGAR
632                   Telangana                 RANGAREDDI
651               Uttar Pradesh                     ALMORA
669               Uttar Pradesh                    CHAMOLI
670               Uttar Pradesh                  CHAMPAWAT
700               Uttar Pradesh                KUSHI NAGAR
713               Uttar Pradesh              PAURI GARHWAL
715               Uttar Pradesh                PITHORAGARH
719               Uttar Pradesh               RUDRA PRAYAG
722               Uttar Pradesh          SANT KABEER NAGAR
731               Uttar Pradesh              TEHRI GARHWAL
732               Uttar Pradesh           UDAM SINGH NAGAR
745                 Uttarakhand               RUDRA PRAYAG
747                 Uttarakhand           UDAM SINGH NAGAR
748                 Uttarakhand                UTTAR KASHI
766                 West Bengal            PARAGANAS NORTH
767                 West Bengal            PARAGANAS SOUTH

In [48]:
review_locations[
    ["State", "District"]
].sort_values(
    ["State", "District"]
).to_csv(
    "../data/processed/location_review_detailed.csv",
    index=False
)

print("Detailed review list saved.")

Detailed review list saved.

In [49]:
review_locations[
    ["State", "District"]
].sort_values(
    ["State", "District"]
)

                          State                   District
0    Andaman and Nicobar Island                   NICOBARS
2    Andaman and Nicobar Island             SOUTH ANDAMANS
3                Andhra Pradesh                   ADILABAD
10               Andhra Pradesh                 KARIMNAGAR
15               Andhra Pradesh                      MEDAK
16               Andhra Pradesh                   NALGONDA
19               Andhra Pradesh                 RANGAREDDI
22               Andhra Pradesh             VISAKHAPATANAM
24               Andhra Pradesh                   WARANGAL
34            Arunachal Pradesh                   LEPARADA
80                        Assam    SOUTH SALMARA MANCACHAR
91                        Bihar                     BOKARO
96                        Bihar                    DHANBAD
97                        Bihar                      DUMKA
98                        Bihar              EAST SINGHBUM
99                        Bihar                     GARHWA
101                       Bihar                    GIRIDIH
102                       Bihar                      GODDA
104                       Bihar                      GUMLA
105                       Bihar                 HAZARIBAGH
112                       Bihar                    KODERMA
114                       Bihar                  LOHARDAGA
121                       Bihar                      PAKUR
122                       Bihar                     PALAMU
139                       Bihar             WEST SINGHBHUM
174                       Delhi                DELHI_TOTAL
185                     Gujarat               CHHOTAUDEPUR
188                     Gujarat                      DOHAD
212                     Haryana               CHARKI DADRI
238            Himachal Pradesh            LAHUL AND SPITI
256           Jammu and Kashmir                 LEH LADAKH
271                   Jharkhand              EAST SINGHBUM
342              Madhya Pradesh                     BASTAR
351              Madhya Pradesh                  DANTEWADA
354              Madhya Pradesh                   DHAMTARI
357              Madhya Pradesh                       DURG
364              Madhya Pradesh             JANJGIR-CHAMPA
365              Madhya Pradesh                    JASHPUR
367              Madhya Pradesh                  KABIRDHAM
368              Madhya Pradesh                     KANKER
372              Madhya Pradesh                      KORBA
374              Madhya Pradesh                 MAHASAMUND
385              Madhya Pradesh                RAJNANDGAON
398              Madhya Pradesh                    SURGUJA
518                      Punjab                  FIROZEPUR
532                      Punjab  SHAHID BHAGAT SINGH NAGAR
632                   Telangana                 RANGAREDDI
651               Uttar Pradesh                     ALMORA
669               Uttar Pradesh                    CHAMOLI
670               Uttar Pradesh                  CHAMPAWAT
700               Uttar Pradesh                KUSHI NAGAR
713               Uttar Pradesh              PAURI GARHWAL
715               Uttar Pradesh                PITHORAGARH
719               Uttar Pradesh               RUDRA PRAYAG
722               Uttar Pradesh          SANT KABEER NAGAR
731               Uttar Pradesh              TEHRI GARHWAL
732               Uttar Pradesh           UDAM SINGH NAGAR
745                 Uttarakhand               RUDRA PRAYAG
747                 Uttarakhand           UDAM SINGH NAGAR
748                 Uttarakhand                UTTAR KASHI
766                 West Bengal            PARAGANAS NORTH
767                 West Bengal            PARAGANAS SOUTH

In [50]:
print(review_by_state)

State
Bihar                         14
Madhya Pradesh                12
Uttar Pradesh                 10
Andhra Pradesh                 7
Uttarakhand                    3
Andaman and Nicobar Island     2
Punjab                         2
West Bengal                    2
Gujarat                        2
Haryana                        1
Jammu and Kashmir              1
Jharkhand                      1
Delhi                          1
Telangana                      1
Assam                          1
Arunachal Pradesh              1
Himachal Pradesh               1
dtype: int64

In [51]:
historical_state_mapping = {

    # Historical Andhra Pradesh → current Telangana
    ("Andhra Pradesh", "ADILABAD"): ("Telangana", "Adilabad"),
    ("Andhra Pradesh", "KARIMNAGAR"): ("Telangana", "Karimnagar"),
    ("Andhra Pradesh", "MEDAK"): ("Telangana", "Medak"),
    ("Andhra Pradesh", "NALGONDA"): ("Telangana", "Nalgonda"),
    ("Andhra Pradesh", "RANGAREDDI"): ("Telangana", "Rangareddy"),
    ("Andhra Pradesh", "WARANGAL"): ("Telangana", "Warangal"),

    # Historical Andhra Pradesh spelling/location
    ("Andhra Pradesh", "VISAKHAPATANAM"): ("Andhra Pradesh", "Visakhapatnam"),

    # Historical Bihar → current Jharkhand
    ("Bihar", "BOKARO"): ("Jharkhand", "Bokaro"),
    ("Bihar", "DHANBAD"): ("Jharkhand", "Dhanbad"),
    ("Bihar", "DUMKA"): ("Jharkhand", "Dumka"),
    ("Bihar", "EAST SINGHBUM"): ("Jharkhand", "East Singhbhum"),
    ("Bihar", "GARHWA"): ("Jharkhand", "Garhwa"),
    ("Bihar", "GIRIDIH"): ("Jharkhand", "Giridih"),
    ("Bihar", "GODDA"): ("Jharkhand", "Godda"),
    ("Bihar", "GUMLA"): ("Jharkhand", "Gumla"),
    ("Bihar", "HAZARIBAGH"): ("Jharkhand", "Hazaribagh"),
    ("Bihar", "KODERMA"): ("Jharkhand", "Koderma"),
    ("Bihar", "LOHARDAGA"): ("Jharkhand", "Lohardaga"),
    ("Bihar", "PAKUR"): ("Jharkhand", "Pakur"),
    ("Bihar", "PALAMU"): ("Jharkhand", "Palamu"),
    ("Bihar", "WEST SINGHBHUM"): ("Jharkhand", "West Singhbhum"),

    # Historical Madhya Pradesh → current Chhattisgarh
    ("Madhya Pradesh", "BASTAR"): ("Chhattisgarh", "Bastar"),
    ("Madhya Pradesh", "DANTEWADA"): ("Chhattisgarh", "Dantewada"),
    ("Madhya Pradesh", "DHAMTARI"): ("Chhattisgarh", "Dhamtari"),
    ("Madhya Pradesh", "DURG"): ("Chhattisgarh", "Durg"),
    ("Madhya Pradesh", "JANJGIR-CHAMPA"): ("Chhattisgarh", "Janjgir-Champa"),
    ("Madhya Pradesh", "JASHPUR"): ("Chhattisgarh", "Jashpur"),
    ("Madhya Pradesh", "KABIRDHAM"): ("Chhattisgarh", "Kabirdham"),
    ("Madhya Pradesh", "KANKER"): ("Chhattisgarh", "Kanker"),
    ("Madhya Pradesh", "KORBA"): ("Chhattisgarh", "Korba"),
    ("Madhya Pradesh", "MAHASAMUND"): ("Chhattisgarh", "Mahasamund"),
    ("Madhya Pradesh", "RAJNANDGAON"): ("Chhattisgarh", "Rajnandgaon"),
    ("Madhya Pradesh", "SURGUJA"): ("Chhattisgarh", "Surguja"),

    # Historical Uttar Pradesh → current Uttarakhand
    ("Uttar Pradesh", "ALMORA"): ("Uttarakhand", "Almora"),
    ("Uttar Pradesh", "CHAMOLI"): ("Uttarakhand", "Chamoli"),
    ("Uttar Pradesh", "CHAMPAWAT"): ("Uttarakhand", "Champawat"),
    ("Uttar Pradesh", "PAURI GARHWAL"): ("Uttarakhand", "Pauri Garhwal"),
    ("Uttar Pradesh", "PITHORAGARH"): ("Uttarakhand", "Pithoragarh"),
    ("Uttar Pradesh", "RUDRA PRAYAG"): ("Uttarakhand", "Rudraprayag"),
    ("Uttar Pradesh", "TEHRI GARHWAL"): ("Uttarakhand", "Tehri Garhwal"),
    ("Uttar Pradesh", "UDAM SINGH NAGAR"): ("Uttarakhand", "Udham Singh Nagar"),

    # Current-name spelling / administrative changes
    ("Andaman and Nicobar Island", "NICOBARS"): (
        "Andaman and Nicobar Islands",
        "Nicobar"
    ),

    ("Andaman and Nicobar Island", "SOUTH ANDAMANS"): (
        "Andaman and Nicobar Islands",
        "South Andaman"
    ),

    ("Arunachal Pradesh", "LEPARADA"): (
        "Arunachal Pradesh",
        "Lepa Rada"
    ),

    ("Assam", "SOUTH SALMARA MANCACHAR"): (
        "Assam",
        "South Salmara-Mankachar"
    ),

    ("Gujarat", "CHHOTAUDEPUR"): (
        "Gujarat",
        "Chhota Udaipur"
    ),

    ("Haryana", "CHARKI DADRI"): (
        "Haryana",
        "Charkhi Dadri"
    ),

    ("Himachal Pradesh", "LAHUL AND SPITI"): (
        "Himachal Pradesh",
        "Lahaul and Spiti"
    ),

    ("Jammu and Kashmir", "LEH LADAKH"): (
        "Ladakh",
        "Leh"
    ),

    ("Punjab", "FIROZEPUR"): (
        "Punjab",
        "Firozpur"
    ),

    ("Punjab", "SHAHID BHAGAT SINGH NAGAR"): (
        "Punjab",
        "Shaheed Bhagat Singh Nagar"
    ),

    ("West Bengal", "PARAGANAS NORTH"): (
        "West Bengal",
        "North 24 Parganas"
    ),

    ("West Bengal", "PARAGANAS SOUTH"): (
        "West Bengal",
        "South 24 Parganas"
    ),

    # UP districts that remain Uttar Pradesh
    ("Uttar Pradesh", "KUSHI NAGAR"): (
        "Uttar Pradesh",
        "Kushinagar"
    ),

    ("Uttar Pradesh", "SANT KABEER NAGAR"): (
        "Uttar Pradesh",
        "Sant Kabir Nagar"
    ),

    # Current Uttarakhand spellings
    ("Uttarakhand", "RUDRA PRAYAG"): (
        "Uttarakhand",
        "Rudraprayag"
    ),

    ("Uttarakhand", "UDAM SINGH NAGAR"): (
        "Uttarakhand",
        "Udham Singh Nagar"
    ),

    ("Uttarakhand", "UTTAR KASHI"): (
        "Uttarakhand",
        "Uttarkashi"
    ),

    # Telangana record
    ("Telangana", "RANGAREDDI"): (
        "Telangana",
        "Rangareddy"
    ),

    # Jharkhand record
    ("Jharkhand", "EAST SINGHBUM"): (
        "Jharkhand",
        "East Singhbhum"
    ),

    # Delhi
    ("Delhi", "DELHI_TOTAL"): (
        "Delhi",
        "Delhi"
    ),
}

In [52]:
def reconcile_location(state, district):

    key = (state, district)

    if key in historical_state_mapping:

        current_state, current_district = \
            historical_state_mapping[key]

        return pd.Series({
            "Current_State": current_state,
            "Current_District": current_district,
            "Reconciliation_Status": "MAPPED"
        })

    return pd.Series({
        "Current_State": state,
        "Current_District": district,
        "Reconciliation_Status": "UNCHANGED"
    })

In [53]:
reconciled = locations.apply(
    lambda row: reconcile_location(
        row["State"],
        row["District"]
    ),
    axis=1
)

locations = pd.concat(
    [locations, reconciled],
    axis=1
)

In [54]:
review_keys = set(
    zip(
        review_locations["State"],
        review_locations["District"]
    )
)

locations[
    locations.apply(
        lambda row:
        (row["State"], row["District"]) in review_keys,
        axis=1
    )
][
    [
        "State",
        "District",
        "Current_State",
        "Current_District",
        "Reconciliation_Status"
    ]
]

,State,District,Current_State,Current_District,Reconciliation_Status
0,Andaman and Nicobar Island,NICOBARS,Andaman and Nicobar Islands,Nicobar,MAPPED
2,Andaman and Nicobar Island,SOUTH ANDAMANS,Andaman and Nicobar Islands,South Andaman,MAPPED
3,Andhra Pradesh,ADILABAD,Telangana,Adilabad,MAPPED
10,Andhra Pradesh,KARIMNAGAR,Telangana,Karimnagar,MAPPED
15,Andhra Pradesh,MEDAK,Telangana,Medak,MAPPED
16,Andhra Pradesh,NALGONDA,Telangana,Nalgonda,MAPPED
19,Andhra Pradesh,RANGAREDDI,Telangana,Rangareddy,MAPPED
22,Andhra Pradesh,VISAKHAPATANAM,Andhra Pradesh,Visakhapatnam,MAPPED
24,Andhra Pradesh,WARANGAL,Telangana,Warangal,MAPPED
34,Arunachal Pradesh,LEPARADA,Arunachal Pradesh,Lepa Rada,MAPPED
80,Assam,SOUTH SALMARA MANCACHAR,Assam,South Salmara-Mankachar,MAPPED
91,Bihar,BOKARO,Jharkhand,Bokaro,MAPPED
96,Bihar,DHANBAD,Jharkhand,Dhanbad,MAPPED
97,Bihar,DUMKA,Jharkhand,Dumka,MAPPED
98,Bihar,EAST SINGHBUM,Jharkhand,East Singhbhum,MAPPED
99,Bihar,GARHWA,Jharkhand,Garhwa,MAPPED
101,Bihar,GIRIDIH,Jharkhand,Giridih,MAPPED
102,Bihar,GODDA,Jharkhand,Godda,MAPPED
104,Bihar,GUMLA,Jharkhand,Gumla,MAPPED
105,Bihar,HAZARIBAGH,Jharkhand,Hazaribagh,MAPPED
112,Bihar,KODERMA,Jharkhand,Koderma,MAPPED
114,Bihar,LOHARDAGA,Jharkhand,Lohardaga,MAPPED
121,Bihar,PAKUR,Jharkhand,Pakur,MAPPED
122,Bihar,PALAMU,Jharkhand,Palamu,MAPPED
139,Bihar,WEST SINGHBHUM,Jharkhand,West Singhbhum,MAPPED
174,Delhi,DELHI_TOTAL,Delhi,Delhi,MAPPED
185,Gujarat,CHHOTAUDEPUR,Gujarat,Chhota Udaipur,MAPPED
188,Gujarat,DOHAD,Gujarat,DOHAD,UNCHANGED
212,Haryana,CHARKI DADRI,Haryana,Charkhi Dadri,MAPPED
238,Himachal Pradesh,LAHUL AND SPITI,Himachal Pradesh,Lahaul and Spiti,MAPPED
256,Jammu and Kashmir,LEH LADAKH,Ladakh,Leh,MAPPED
271,Jharkhand,EAST SINGHBUM,Jharkhand,East Singhbhum,MAPPED
342,Madhya Pradesh,BASTAR,Chhattisgarh,Bastar,MAPPED
351,Madhya Pradesh,DANTEWADA,Chhattisgarh,Dantewada,MAPPED
354,Madhya Pradesh,DHAMTARI,Chhattisgarh,Dhamtari,MAPPED
357,Madhya Pradesh,DURG,Chhattisgarh,Durg,MAPPED
364,Madhya Pradesh,JANJGIR-CHAMPA,Chhattisgarh,Janjgir-Champa,MAPPED
365,Madhya Pradesh,JASHPUR,Chhattisgarh,Jashpur,MAPPED
367,Madhya Pradesh,KABIRDHAM,Chhattisgarh,Kabirdham,MAPPED
368,Madhya Pradesh,KANKER,Chhattisgarh,Kanker,MAPPED
372,Madhya Pradesh,KORBA,Chhattisgarh,Korba,MAPPED
374,Madhya Pradesh,MAHASAMUND,Chhattisgarh,Mahasamund,MAPPED
385,Madhya Pradesh,RAJNANDGAON,Chhattisgarh,Rajnandgaon,MAPPED
398,Madhya Pradesh,SURGUJA,Chhattisgarh,Surguja,MAPPED
518,Punjab,FIROZEPUR,Punjab,Firozpur,MAPPED
532,Punjab,SHAHID BHAGAT SINGH NAGAR,Punjab,Shaheed Bhagat Singh Nagar,MAPPED
632,Telangana,RANGAREDDI,Telangana,Rangareddy,MAPPED
651,Uttar Pradesh,ALMORA,Uttarakhand,Almora,MAPPED
669,Uttar Pradesh,CHAMOLI,Uttarakhand,Chamoli,MAPPED
670,Uttar Pradesh,CHAMPAWAT,Uttarakhand,Champawat,MAPPED
700,Uttar Pradesh,KUSHI NAGAR,Uttar Pradesh,Kushinagar,MAPPED
713,Uttar Pradesh,PAURI GARHWAL,Uttarakhand,Pauri Garhwal,MAPPED
715,Uttar Pradesh,PITHORAGARH,Uttarakhand,Pithoragarh,MAPPED
719,Uttar Pradesh,RUDRA PRAYAG,Uttarakhand,Rudraprayag,MAPPED
722,Uttar Pradesh,SANT KABEER NAGAR,Uttar Pradesh,Sant Kabir Nagar,MAPPED
731,Uttar Pradesh,TEHRI GARHWAL,Uttarakhand,Tehri Garhwal,MAPPED
732,Uttar Pradesh,UDAM SINGH NAGAR,Uttarakhand,Udham Singh Nagar,MAPPED
745,Uttarakhand,RUDRA PRAYAG,Uttarakhand,Rudraprayag,MAPPED
747,Uttarakhand,UDAM SINGH NAGAR,Uttarakhand,Udham Singh Nagar,MAPPED
748,Uttarakhand,UTTAR KASHI,Uttarakhand,Uttarkashi,MAPPED
766,West Bengal,PARAGANAS NORTH,West Bengal,North 24 Parganas,MAPPED
767,West Bengal,PARAGANAS SOUTH,West Bengal,South 24 Parganas,MAPPED

In [55]:
def geocode_reconciled(state, district):

    queries = [
        f"{district}, {state}, India",
        f"{district} district, {state}, India"
    ]

    for query in queries:

        try:
            result = geocode(query)

            if result:
                address = result.address.upper()

                return {
                    "Latitude": result.latitude,
                    "Longitude": result.longitude,
                    "Geocoded_Address": result.address,
                    "Geocode_Status": "FOUND"
                }

        except Exception as e:
            print("Error:", e)

    return {
        "Latitude": np.nan,
        "Longitude": np.nan,
        "Geocoded_Address": "",
        "Geocode_Status": "NOT_FOUND"
    }

In [56]:
review_mask = locations.apply(
    lambda row:
    (row["State"], row["District"]) in review_keys,
    axis=1
)

review_df = locations[review_mask].copy()

print("Locations to process:", len(review_df))

Locations to process: 62

In [57]:
geo_results = []

for _, row in review_df.iterrows():

    print(
        row["State"],
        "|",
        row["District"],
        "→",
        row["Current_State"],
        "|",
        row["Current_District"]
    )

    result = geocode_reconciled(
        row["Current_State"],
        row["Current_District"]
    )

    geo_results.append(result)

Andaman and Nicobar Island | NICOBARS → Andaman and Nicobar Islands | Nicobar
Andaman and Nicobar Island | SOUTH ANDAMANS → Andaman and Nicobar Islands | South Andaman
Andhra Pradesh | ADILABAD → Telangana | Adilabad
Andhra Pradesh | KARIMNAGAR → Telangana | Karimnagar
Andhra Pradesh | MEDAK → Telangana | Medak
Andhra Pradesh | NALGONDA → Telangana | Nalgonda
Andhra Pradesh | RANGAREDDI → Telangana | Rangareddy
Andhra Pradesh | VISAKHAPATANAM → Andhra Pradesh | Visakhapatnam
Andhra Pradesh | WARANGAL → Telangana | Warangal
Arunachal Pradesh | LEPARADA → Arunachal Pradesh | Lepa Rada
Assam | SOUTH SALMARA MANCACHAR → Assam | South Salmara-Mankachar
Bihar | BOKARO → Jharkhand | Bokaro
Bihar | DHANBAD → Jharkhand | Dhanbad
Bihar | DUMKA → Jharkhand | Dumka
Bihar | EAST SINGHBUM → Jharkhand | East Singhbhum
Bihar | GARHWA → Jharkhand | Garhwa
Bihar | GIRIDIH → Jharkhand | Giridih
Bihar | GODDA → Jharkhand | Godda
Bihar | GUMLA → Jharkhand | Gumla
Bihar | HAZARIBAGH → Jharkhand | Hazaribagh
Bihar | KODERMA → Jharkhand | Koderma
Bihar | LOHARDAGA → Jharkhand | Lohardaga
Bihar | PAKUR → Jharkhand | Pakur
Bihar | PALAMU → Jharkhand | Palamu
Bihar | WEST SINGHBHUM → Jharkhand | West Singhbhum
Delhi | DELHI_TOTAL → Delhi | Delhi
Gujarat | CHHOTAUDEPUR → Gujarat | Chhota Udaipur
Gujarat | DOHAD → Gujarat | DOHAD
Haryana | CHARKI DADRI → Haryana | Charkhi Dadri
Himachal Pradesh | LAHUL AND SPITI → Himachal Pradesh | Lahaul and Spiti
Jammu and Kashmir | LEH LADAKH → Ladakh | Leh
Jharkhand | EAST SINGHBUM → Jharkhand | East Singhbhum
Madhya Pradesh | BASTAR → Chhattisgarh | Bastar
Madhya Pradesh | DANTEWADA → Chhattisgarh | Dantewada
Madhya Pradesh | DHAMTARI → Chhattisgarh | Dhamtari
Madhya Pradesh | DURG → Chhattisgarh | Durg
Madhya Pradesh | JANJGIR-CHAMPA → Chhattisgarh | Janjgir-Champa
Madhya Pradesh | JASHPUR → Chhattisgarh | Jashpur
Madhya Pradesh | KABIRDHAM → Chhattisgarh | Kabirdham
Madhya Pradesh | KANKER → Chhattisgarh | Kanker
Madhya Pradesh | KORBA → Chhattisgarh | Korba
Madhya Pradesh | MAHASAMUND → Chhattisgarh | Mahasamund
Madhya Pradesh | RAJNANDGAON → Chhattisgarh | Rajnandgaon
Madhya Pradesh | SURGUJA → Chhattisgarh | Surguja
Punjab | FIROZEPUR → Punjab | Firozpur
Punjab | SHAHID BHAGAT SINGH NAGAR → Punjab | Shaheed Bhagat Singh Nagar
Telangana | RANGAREDDI → Telangana | Rangareddy
Uttar Pradesh | ALMORA → Uttarakhand | Almora
Uttar Pradesh | CHAMOLI → Uttarakhand | Chamoli
Uttar Pradesh | CHAMPAWAT → Uttarakhand | Champawat
Uttar Pradesh | KUSHI NAGAR → Uttar Pradesh | Kushinagar
Uttar Pradesh | PAURI GARHWAL → Uttarakhand | Pauri Garhwal
Uttar Pradesh | PITHORAGARH → Uttarakhand | Pithoragarh
Uttar Pradesh | RUDRA PRAYAG → Uttarakhand | Rudraprayag
Uttar Pradesh | SANT KABEER NAGAR → Uttar Pradesh | Sant Kabir Nagar
Uttar Pradesh | TEHRI GARHWAL → Uttarakhand | Tehri Garhwal
Uttar Pradesh | UDAM SINGH NAGAR → Uttarakhand | Udham Singh Nagar
Uttarakhand | RUDRA PRAYAG → Uttarakhand | Rudraprayag
Uttarakhand | UDAM SINGH NAGAR → Uttarakhand | Udham Singh Nagar
Uttarakhand | UTTAR KASHI → Uttarakhand | Uttarkashi
West Bengal | PARAGANAS NORTH → West Bengal | North 24 Parganas
West Bengal | PARAGANAS SOUTH → West Bengal | South 24 Parganas

In [58]:
geo_results_df = pd.DataFrame(geo_results)

review_df = review_df.reset_index(drop=True)

review_df = pd.concat(
    [review_df, geo_results_df],
    axis=1
)

In [59]:
print(
    review_df["Geocode_Status"].value_counts()
)

Geocode_Status
FOUND        61
NOT_FOUND     1
Name: count, dtype: int64

In [60]:
review_df[
    [
        "State",
        "District",
        "Current_State",
        "Current_District",
        "Latitude",
        "Longitude",
        "Geocode_Status"
    ]
]

,State,District,Current_State,Current_District,Latitude,Latitude,Longitude,Longitude,Geocode_Status
0,Andaman and Nicobar Island,NICOBARS,Andaman and Nicobar Islands,Nicobar,NaN,7.000017,NaN,93.811053,FOUND
1,Andaman and Nicobar Island,SOUTH ANDAMANS,Andaman and Nicobar Islands,South Andaman,NaN,10.705690,NaN,92.487468,FOUND
2,Andhra Pradesh,ADILABAD,Telangana,Adilabad,NaN,19.675945,NaN,78.533990,FOUND
3,Andhra Pradesh,KARIMNAGAR,Telangana,Karimnagar,NaN,18.434812,NaN,79.132804,FOUND
4,Andhra Pradesh,MEDAK,Telangana,Medak,NaN,17.937510,NaN,78.211745,FOUND
5,Andhra Pradesh,NALGONDA,Telangana,Nalgonda,NaN,17.050441,NaN,79.266924,FOUND
6,Andhra Pradesh,RANGAREDDI,Telangana,Rangareddy,NaN,16.934415,NaN,77.778834,FOUND
7,Andhra Pradesh,VISAKHAPATANAM,Andhra Pradesh,Visakhapatnam,NaN,17.693553,NaN,83.292130,FOUND
8,Andhra Pradesh,WARANGAL,Telangana,Warangal,NaN,17.982064,NaN,79.597095,FOUND
9,Arunachal Pradesh,LEPARADA,Arunachal Pradesh,Lepa Rada,NaN,27.921127,NaN,94.740936,FOUND
10,Assam,SOUTH SALMARA MANCACHAR,Assam,South Salmara-Mankachar,NaN,25.760447,NaN,89.892806,FOUND
11,Bihar,BOKARO,Jharkhand,Bokaro,NaN,23.699128,NaN,85.991069,FOUND
12,Bihar,DHANBAD,Jharkhand,Dhanbad,NaN,23.795281,NaN,86.430964,FOUND
13,Bihar,DUMKA,Jharkhand,Dumka,NaN,24.267794,NaN,87.248549,FOUND
14,Bihar,EAST SINGHBUM,Jharkhand,East Singhbhum,NaN,22.613184,NaN,86.381940,FOUND
15,Bihar,GARHWA,Jharkhand,Garhwa,NaN,24.053577,NaN,83.652682,FOUND
16,Bihar,GIRIDIH,Jharkhand,Giridih,NaN,24.331455,NaN,86.154812,FOUND
17,Bihar,GODDA,Jharkhand,Godda,NaN,24.864589,NaN,87.298484,FOUND
18,Bihar,GUMLA,Jharkhand,Gumla,NaN,23.160376,NaN,84.459957,FOUND
19,Bihar,HAZARIBAGH,Jharkhand,Hazaribagh,NaN,24.086696,NaN,85.491223,FOUND
20,Bihar,KODERMA,Jharkhand,Koderma,NaN,24.493124,NaN,85.556081,FOUND
21,Bihar,LOHARDAGA,Jharkhand,Lohardaga,NaN,23.477004,NaN,84.698668,FOUND
22,Bihar,PAKUR,Jharkhand,Pakur,NaN,24.532591,NaN,87.593232,FOUND
23,Bihar,PALAMU,Jharkhand,Palamu,NaN,24.221298,NaN,84.172556,FOUND
24,Bihar,WEST SINGHBHUM,Jharkhand,West Singhbhum,NaN,22.428286,NaN,85.531748,FOUND
25,Delhi,DELHI_TOTAL,Delhi,Delhi,NaN,28.666453,NaN,77.216978,FOUND
26,Gujarat,CHHOTAUDEPUR,Gujarat,Chhota Udaipur,NaN,22.222434,NaN,73.777875,FOUND
27,Gujarat,DOHAD,Gujarat,DOHAD,NaN,NaN,NaN,NaN,NOT_FOUND
28,Haryana,CHARKI DADRI,Haryana,Charkhi Dadri,NaN,28.600100,NaN,76.112371,FOUND
29,Himachal Pradesh,LAHUL AND SPITI,Himachal Pradesh,Lahaul and Spiti,NaN,32.501586,NaN,77.578989,FOUND
30,Jammu and Kashmir,LEH LADAKH,Ladakh,Leh,NaN,34.164203,NaN,77.584813,FOUND
31,Jharkhand,EAST SINGHBUM,Jharkhand,East Singhbhum,NaN,22.613184,NaN,86.381940,FOUND
32,Madhya Pradesh,BASTAR,Chhattisgarh,Bastar,NaN,19.119128,NaN,81.829187,FOUND
33,Madhya Pradesh,DANTEWADA,Chhattisgarh,Dantewada,NaN,18.864065,NaN,81.383395,FOUND
34,Madhya Pradesh,DHAMTARI,Chhattisgarh,Dhamtari,NaN,20.532626,NaN,81.715599,FOUND
35,Madhya Pradesh,DURG,Chhattisgarh,Durg,NaN,21.198296,NaN,81.400792,FOUND
36,Madhya Pradesh,JANJGIR-CHAMPA,Chhattisgarh,Janjgir-Champa,NaN,21.986403,NaN,82.553661,FOUND
37,Madhya Pradesh,JASHPUR,Chhattisgarh,Jashpur,NaN,22.770251,NaN,83.970801,FOUND
38,Madhya Pradesh,KABIRDHAM,Chhattisgarh,Kabirdham,NaN,22.115008,NaN,81.244694,FOUND
39,Madhya Pradesh,KANKER,Chhattisgarh,Kanker,NaN,20.269275,NaN,81.493211,FOUND
40,Madhya Pradesh,KORBA,Chhattisgarh,Korba,NaN,22.519822,NaN,82.635003,FOUND
41,Madhya Pradesh,MAHASAMUND,Chhattisgarh,Mahasamund,NaN,21.192285,NaN,82.489026,FOUND
42,Madhya Pradesh,RAJNANDGAON,Chhattisgarh,Rajnandgaon,NaN,21.068442,NaN,80.797078,FOUND
43,Madhya Pradesh,SURGUJA,Chhattisgarh,Surguja,NaN,22.947011,NaN,83.165687,FOUND
44,Punjab,FIROZEPUR,Punjab,Firozpur,NaN,30.875383,NaN,74.652544,FOUND
45,Punjab,SHAHID BHAGAT SINGH NAGAR,Punjab,Shaheed Bhagat Singh Nagar,NaN,31.126969,NaN,76.159899,FOUND
46,Telangana,RANGAREDDI,Telangana,Rangareddy,NaN,16.934415,NaN,77.778834,FOUND
47,Uttar Pradesh,ALMORA,Uttarakhand,Almora,NaN,29.702651,NaN,79.432632,FOUND
48,Uttar Pradesh,CHAMOLI,Uttarakhand,Chamoli,NaN,30.498596,NaN,79.619054,FOUND
49,Uttar Pradesh,CHAMPAWAT,Uttarakhand,Champawat,NaN,29.235032,NaN,80.102307,FOUND
50,Uttar Pradesh,KUSHI NAGAR,Uttar Pradesh,Kushinagar,NaN,26.743827,NaN,83.916232,FOUND
51,Uttar Pradesh,PAURI GARHWAL,Uttarakhand,Pauri Garhwal,NaN,29.847317,NaN,78.707048,FOUND
52,Uttar Pradesh,PITHORAGARH,Uttarakhand,Pithoragarh,NaN,29.585871,NaN,80.215167,FOUND
53,Uttar Pradesh,RUDRA PRAYAG,Uttarakhand,Rudraprayag,NaN,30.491584,NaN,79.036607,FOUND
54,Uttar Pradesh,SANT KABEER NAGAR,Uttar Pradesh,Sant Kabir Nagar,NaN,26.755082,NaN,83.039855,FOUND
55,Uttar Pradesh,TEHRI GARHWAL,Uttarakhand,Tehri Garhwal,NaN,30.465818,NaN,78.483735,FOUND
56,Uttar Pradesh,UDAM SINGH NAGAR,Uttarakhand,Udham Singh Nagar,NaN,29.047831,NaN,79.432616,FOUND
57,Uttarakhand,RUDRA PRAYAG,Uttarakhand,Rudraprayag,NaN,30.491584,NaN,79.036607,FOUND
58,Uttarakhand,UDAM SINGH NAGAR,Uttarakhand,Udham Singh Nagar,NaN,29.047831,NaN,79.432616,FOUND
59,Uttarakhand,UTTAR KASHI,Uttarakhand,Uttarkashi,NaN,30.963573,NaN,78.636252,FOUND
60,West Bengal,PARAGANAS NORTH,West Bengal,North 24 Parganas,NaN,22.692681,NaN,88.662580,FOUND
61,West Bengal,PARAGANAS SOUTH,West Bengal,South 24 Parganas,NaN,22.177673,NaN,88.530785,FOUND

In [63]:
print(review_df["Geocode_Status"].value_counts())

Geocode_Status
FOUND        61
NOT_FOUND     1
Name: count, dtype: int64

In [64]:
review_df[
    review_df["Geocode_Status"] == "NOT_FOUND"
][
    ["State", "District", "Current_State", "Current_District"]
]

      State District Current_State Current_District
27  Gujarat    DOHAD       Gujarat            DOHAD

In [66]:
dohad_result = geocode_reconciled(
    "Gujarat",
    "Dahod"
)

print(dohad_result)

{'Latitude': 22.9194099, 'Longitude': 74.1342725, 'Geocoded_Address': 'Dahod, Gujarat, India', 'Geocode_Status': 'FOUND'}

In [67]:
review_df.loc[
    review_df["District"] == "DOHAD",
    "Current_District"
] = "Dahod"

review_df.loc[
    review_df["District"] == "DOHAD",
    "Latitude"
] = dohad_result["Latitude"]

review_df.loc[
    review_df["District"] == "DOHAD",
    "Longitude"
] = dohad_result["Longitude"]

review_df.loc[
    review_df["District"] == "DOHAD",
    "Geocoded_Address"
] = dohad_result["Geocoded_Address"]

review_df.loc[
    review_df["District"] == "DOHAD",
    "Geocode_Status"
] = dohad_result["Geocode_Status"]

In [68]:
print(review_df["Geocode_Status"].value_counts())

Geocode_Status
FOUND    62
Name: count, dtype: int64

In [69]:
print(
    review_df[
        review_df["Geocode_Status"] != "FOUND"
    ]
)

Empty DataFrame
Columns: [State, District, Latitude, Longitude, State_Normalized, District_Normalized, Mapping_Status, Mapping_Source, Current_State, Current_District, Reconciliation_Status, Latitude, Longitude, Geocoded_Address, Geocode_Status]
Index: []

In [71]:
final_locations = pd.concat(
    [
        verified_locations,
        review_df
    ],
    ignore_index=True
)

print("Final location count:", len(final_locations))
print("Unique State-District pairs:",
      final_locations[["State", "District"]].drop_duplicates().shape[0])

print(
    final_locations["Geocode_Status"]
    .value_counts()
)

InvalidIndexError: Reindexing only valid with uniquely valued Index objects

In [72]:
final_locations.to_csv(
    "../data/processed/location_reference_final.csv",
    index=False
)

print("Final location reference saved!")

NameError: name 'final_locations' is not defined

In [73]:
print("verified_locations duplicate columns:")
print(verified_locations.columns[verified_locations.columns.duplicated()].tolist())

print("\nreview_df duplicate columns:")
print(review_df.columns[review_df.columns.duplicated()].tolist())

verified_locations duplicate columns:
[]

review_df duplicate columns:
['Latitude', 'Longitude']

In [74]:
verified_locations = verified_locations.loc[
    :, ~verified_locations.columns.duplicated()
].copy()

review_df = review_df.loc[
    :, ~review_df.columns.duplicated()
].copy()

In [75]:
print("Verified duplicate columns:",
      verified_locations.columns[
          verified_locations.columns.duplicated()
      ].tolist())

print("Review duplicate columns:",
      review_df.columns[
          review_df.columns.duplicated()
      ].tolist())

Verified duplicate columns: []
Review duplicate columns: []

In [76]:
common_columns = [
    "State",
    "District",
    "Current_State",
    "Current_District",
    "Latitude",
    "Longitude",
    "Geocoded_Address",
    "Geocode_Status"
]

In [77]:
verified_locations_final = verified_locations[
    [col for col in common_columns
     if col in verified_locations.columns]
].copy()

review_locations_final = review_df[
    [col for col in common_columns
     if col in review_df.columns]
].copy()

In [78]:
print(verified_locations_final.columns.tolist())
print(review_locations_final.columns.tolist())

['State', 'District', 'Latitude', 'Longitude']
['State', 'District', 'Current_State', 'Current_District', 'Latitude', 'Longitude', 'Geocoded_Address', 'Geocode_Status']

In [79]:
final_locations = pd.concat(
    [
        verified_locations_final,
        review_locations_final
    ],
    ignore_index=True
)

In [80]:
print("Final location count:", len(final_locations))

print(
    "Unique State-District pairs:",
    final_locations[
        ["State", "District"]
    ].drop_duplicates().shape[0]
)

Final location count: 771
Unique State-District pairs: 771

In [81]:
print("Missing Latitude:",
      final_locations["Latitude"].isna().sum())

print("Missing Longitude:",
      final_locations["Longitude"].isna().sum())

Missing Latitude: 61
Missing Longitude: 61

In [82]:
print(final_locations["Geocode_Status"].value_counts())

Geocode_Status
FOUND    62
Name: count, dtype: int64

In [83]:
duplicates = final_locations[
    final_locations.duplicated(
        subset=["State", "District"],
        keep=False
    )
]

print("Duplicate State-District pairs:",
      len(duplicates))

duplicates.head(20)

Duplicate State-District pairs: 0

Empty DataFrame
Columns: [State, District, Latitude, Longitude, Current_State, Current_District, Geocoded_Address, Geocode_Status]
Index: []

In [84]:
final_locations.to_csv(
    "../data/processed/location_reference_final.csv",
    index=False
)

print("✅ Final location reference saved!")
print("Rows:", len(final_locations))

✅ Final location reference saved!
Rows: 771