In [5]:
import pandas as pd
import numpy as np
import requests
import time
import os

In [6]:
agriculture = pd.read_csv(
    "../data/processed/ml_training_base.csv"
)

locations = pd.read_csv(
    "../data/processed/location_reference_final.csv"
)

print("Agriculture:", agriculture.shape)
print("Locations:", locations.shape)

Agriculture: (338483, 8)
Locations: (771, 8)

In [7]:
print(locations.columns.tolist())

['State', 'District', 'Latitude', 'Longitude', 'Current_State', 'Current_District', 'Geocoded_Address', 'Geocode_Status']

In [8]:
locations[
    ["State", "District", "Latitude", "Longitude"]
].head()

                        State                  District   Latitude  Longitude
0  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  12.611239  92.831654
1              Andhra Pradesh                 ANANTAPUR  14.678322  77.606504
2              Andhra Pradesh                  CHITTOOR  13.325036  79.648061
3              Andhra Pradesh             EAST GODAVARI  16.995664  81.715438
4              Andhra Pradesh                    GUNTUR  16.291519  80.454159

In [9]:
agriculture_weather_base = agriculture.merge(
    locations[
        ["State", "District", "Latitude", "Longitude"]
    ],
    on=["State", "District"],
    how="left"
)

In [10]:
print(agriculture_weather_base.shape)

(338483, 10)

In [11]:
print(
    agriculture_weather_base[
        ["Latitude", "Longitude"]
    ].isna().sum()
)

Latitude     0
Longitude    0
dtype: int64

In [12]:
print("Agriculture rows:", len(agriculture))
print("Location rows:", len(locations))

print("Missing coordinates after merge:")
print(
    agriculture_weather_base[
        ["Latitude", "Longitude"]
    ].isna().sum()
)

Agriculture rows: 338483
Location rows: 771
Missing coordinates after merge:
Latitude     0
Longitude    0
dtype: int64

In [13]:
missing_locations = (
    agriculture_weather_base[
        agriculture_weather_base["Latitude"].isna()
    ][
        ["State", "District"]
    ]
    .drop_duplicates()
    .sort_values(["State", "District"])
)

print("Unmatched State-District combinations:",
      len(missing_locations))

missing_locations.head(100)

Unmatched State-District combinations: 0

Empty DataFrame
Columns: [State, District]
Index: []

In [14]:
agri_locations = (
    agriculture[
        ["State", "District"]
    ]
    .drop_duplicates()
)

print(
    "Agriculture unique State-District:",
    len(agri_locations)
)

Agriculture unique State-District: 771

In [15]:
location_keys = (
    locations[
        ["State", "District"]
    ]
    .drop_duplicates()
)

print(
    "Reference unique State-District:",
    len(location_keys)
)

Reference unique State-District: 771

In [16]:
unmatched = agri_locations.merge(
    location_keys,
    on=["State", "District"],
    how="left",
    indicator=True
)

unmatched = unmatched[
    unmatched["_merge"] == "left_only"
]

print("Unmatched locations:", len(unmatched))

unmatched.head(100)

Unmatched locations: 0

Empty DataFrame
Columns: [State, District, _merge]
Index: []

In [17]:
print("Unmatched locations:", len(unmatched))

Unmatched locations: 0

In [18]:
unmatched.head(100)

Empty DataFrame
Columns: [State, District, _merge]
Index: []

In [19]:
print(
    "Duplicate location pairs:",
    locations.duplicated(
        subset=["State", "District"]
    ).sum()
)

Duplicate location pairs: 0

In [20]:
duplicates = locations[
    locations.duplicated(
        subset=["State", "District"],
        keep=False
    )
].sort_values(["State", "District"])

print(duplicates.head(30))

Empty DataFrame
Columns: [State, District, Latitude, Longitude, Current_State, Current_District, Geocoded_Address, Geocode_Status]
Index: []

In [21]:
print("Location rows:", len(locations))
print(
    "Unique State-District:",
    locations[
        ["State", "District"]
    ].drop_duplicates().shape[0]
)

Location rows: 771
Unique State-District: 771

In [22]:
locations = locations.drop_duplicates(
    subset=["State", "District"],
    keep="first"
).copy()

print("Location rows after deduplication:", len(locations))

Location rows after deduplication: 771

In [23]:
agriculture_weather_base = agriculture.merge(
    locations[
        ["State", "District", "Latitude", "Longitude"]
    ],
    on=["State", "District"],
    how="left"
)

In [24]:
print(
    agriculture_weather_base[
        ["Latitude", "Longitude"]
    ].isna().sum()
)

Latitude     0
Longitude    0
dtype: int64

In [25]:
print("Location rows:", len(locations))

print(
    "Unique State-District:",
    locations[["State", "District"]].drop_duplicates().shape[0]
)

print(
    "Duplicate pairs:",
    locations.duplicated(
        subset=["State", "District"]
    ).sum()
)

Location rows: 771
Unique State-District: 771
Duplicate pairs: 0

In [26]:
print("Missing Latitude in location file:",
      locations["Latitude"].isna().sum())

print("Missing Longitude in location file:",
      locations["Longitude"].isna().sum())

Missing Latitude in location file: 0
Missing Longitude in location file: 0

In [27]:
missing_coords = locations[
    locations["Latitude"].isna() |
    locations["Longitude"].isna()
].copy()

print("Locations without coordinates:",
      len(missing_coords))

missing_coords[
    ["State", "District", "Current_State",
     "Current_District", "Latitude", "Longitude"]
]

Locations without coordinates: 0

Empty DataFrame
Columns: [State, District, Current_State, Current_District, Latitude, Longitude]
Index: []

In [28]:
print("Missing Latitude:",
      locations["Latitude"].isna().sum())

print("Missing Longitude:",
      locations["Longitude"].isna().sum())

print(missing_coords[
    ["State", "District", "Current_State",
     "Current_District"]
].to_string(index=False))

Missing Latitude: 0
Missing Longitude: 0
Empty DataFrame
Columns: [State, District, Current_State, Current_District]
Index: []

In [29]:
missing_coords = final_locations[
    final_locations["Latitude"].isna() |
    final_locations["Longitude"].isna()
].copy()

print("Missing coordinate locations:", len(missing_coords))

missing_coords[
    ["State", "District", "Current_State", "Current_District"]
].head(100)

NameError: name 'final_locations' is not defined

In [30]:
import pandas as pd
import numpy as np

final_locations = pd.read_csv(
    "../data/processed/location_reference_final.csv"
)

print("Rows:", len(final_locations))
print("Columns:", final_locations.shape[1])

Rows: 771
Columns: 8

In [31]:
missing_coords = final_locations[
    final_locations["Latitude"].isna() |
    final_locations["Longitude"].isna()
].copy()

print("Missing coordinate locations:", len(missing_coords))

Missing coordinate locations: 0

In [32]:
missing_coords[
    ["State", "District", "Current_State", "Current_District"]
].head(100)

Empty DataFrame
Columns: [State, District, Current_State, Current_District]
Index: []

In [33]:
from geopy.geocoders import Nominatim
from geopy.extra.rate_limiter import RateLimiter

geolocator = Nominatim(
    user_agent="smart-crop-ai-college-project"
)

geocode = RateLimiter(
    geolocator.geocode,
    min_delay_seconds=1
)

In [34]:
def geocode_final_location(state, district):

    queries = [
        f"{district}, {state}, India",
        f"{district} district, {state}, India"
    ]

    for query in queries:

        try:
            result = geocode(query)

            if result:
                return {
                    "Latitude": result.latitude,
                    "Longitude": result.longitude,
                    "Geocoded_Address": result.address,
                    "Status": "FOUND"
                }

        except Exception as e:
            print("Error:", e)

    return {
        "Latitude": np.nan,
        "Longitude": np.nan,
        "Geocoded_Address": "",
        "Status": "NOT_FOUND"
    }

In [35]:
for index, row in missing_coords.iterrows():

    print(
        f"{row['State']} | {row['District']} "
        f"→ {row['Current_State']} | {row['Current_District']}"
    )

    result = geocode_final_location(
        row["Current_State"],
        row["Current_District"]
    )

    final_locations.loc[index, "Latitude"] = result["Latitude"]
    final_locations.loc[index, "Longitude"] = result["Longitude"]
    final_locations.loc[index, "Geocoded_Address"] = result["Geocoded_Address"]

    print(
        result["Status"],
        result["Latitude"],
        result["Longitude"]
    )

In [36]:
print(
    "Missing Latitude:",
    final_locations["Latitude"].isna().sum()
)

print(
    "Missing Longitude:",
    final_locations["Longitude"].isna().sum()
)

Missing Latitude: 0
Missing Longitude: 0

In [37]:
final_locations.to_csv(
    "../data/processed/location_reference_final.csv",
    index=False
)

print("✅ Final location reference updated!")
print("Rows:", len(final_locations))

✅ Final location reference updated!
Rows: 771

In [38]:
import pandas as pd
import numpy as np
import requests
import time
import os

In [39]:
agriculture = pd.read_csv(
    "../data/processed/ml_training_base.csv"
)

locations = pd.read_csv(
    "../data/processed/location_reference_final.csv"
)

print("Agriculture:", agriculture.shape)
print("Locations:", locations.shape)

Agriculture: (338483, 8)
Locations: (771, 8)

In [40]:
agriculture_weather_base = agriculture.merge(
    locations[
        [
            "State",
            "District",
            "Latitude",
            "Longitude"
        ]
    ],
    on=["State", "District"],
    how="left"
)

In [41]:
print(
    agriculture_weather_base[
        ["Latitude", "Longitude"]
    ].isna().sum()
)

Latitude     0
Longitude    0
dtype: int64

In [42]:
print("Agriculture rows:", len(agriculture))
print("After location merge:", len(agriculture_weather_base))

Agriculture rows: 338483
After location merge: 338483

In [43]:
print(
    agriculture_weather_base["Crop_Year"]
    .min()
)

print(
    agriculture_weather_base["Crop_Year"]
    .max()
)

1997
2019

In [44]:
print(
    agriculture_weather_base["Season"]
    .value_counts()
)

Season
Kharif        135248
Rabi           99317
Whole Year     66957
Summer         21885
Winter          8192
Autumn          6884
Name: count, dtype: int64

In [45]:
test_location = locations.iloc[0]

print(test_location[
    ["State", "District", "Latitude", "Longitude"]
])

State        Andaman and Nicobar Island
District       NORTH AND MIDDLE ANDAMAN
Latitude                      12.611239
Longitude                     92.831654
Name: 0, dtype: object

In [46]:
lat = test_location["Latitude"]
lon = test_location["Longitude"]

url = "https://archive-api.open-meteo.com/v1/archive"

params = {
    "latitude": lat,
    "longitude": lon,
    "start_date": "2019-01-01",
    "end_date": "2019-12-31",
    "daily": ",".join([
        "temperature_2m_mean",
        "temperature_2m_max",
        "temperature_2m_min",
        "precipitation_sum"
    ]),
    "timezone": "auto",
    "models": "era5"
}

response = requests.get(
    url,
    params=params,
    timeout=60
)

print("HTTP status:", response.status_code)

HTTP status: 429

In [47]:
weather_json = response.json()

print(weather_json.keys())

dict_keys(['reason', 'error'])

In [48]:
print(weather_json["daily"].keys())

KeyError: 'daily'

In [49]:
weather_test = pd.DataFrame(
    weather_json["daily"]
)

weather_test.head()

KeyError: 'daily'

In [50]:
weather_test.describe()

NameError: name 'weather_test' is not defined

In [51]:
def fetch_weather(lat, lon, year):

    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": f"{year}-01-01",
        "end_date": f"{year}-12-31",
        "daily": ",".join([
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum"
        ]),
        "timezone": "auto",
        "models": "era5"
    }

    for attempt in range(3):

        try:
            response = requests.get(
                url,
                params=params,
                timeout=60
            )

            if response.status_code == 200:
                data = response.json()

                weather = pd.DataFrame(
                    data["daily"]
                )

                weather["latitude"] = lat
                weather["longitude"] = lon
                weather["year"] = year

                return weather

            print(
                f"Request failed: {response.status_code}"
            )

        except Exception as e:
            print(
                f"Attempt {attempt + 1} failed:",
                e
            )

            time.sleep(5)

    return None

In [52]:
test = locations.iloc[0]

test_weather = fetch_weather(
    test["Latitude"],
    test["Longitude"],
    2019
)

print(test_weather.shape)
test_weather.head()

Request failed: 429
Request failed: 429
Request failed: 429

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
test_weather["date"] = pd.to_datetime(
    test_weather["time"]
)

test_weather = test_weather.drop(
    columns=["time"]
)

test_weather.head()

,temperature_2m_mean,temperature_2m_max,temperature_2m_min,precipitation_sum,latitude,longitude,year,date
0,25.1,27.5,22.9,0.5,12.611239,92.831654,2019,2019-01-01
1,25.1,27.2,23.5,0.3,12.611239,92.831654,2019,2019-01-02
2,25.9,28.4,24.1,0.0,12.611239,92.831654,2019,2019-01-03
3,25.4,27.8,23.9,0.0,12.611239,92.831654,2019,2019-01-04
4,25.9,27.9,23.9,0.0,12.611239,92.831654,2019,2019-01-05

In [ ]:
years = range(1997, 2020)

location_years = []

for _, row in locations.iterrows():

    for year in years:

        location_years.append({
            "State": row["State"],
            "District": row["District"],
            "Latitude": row["Latitude"],
            "Longitude": row["Longitude"],
            "Year": year
        })

location_years = pd.DataFrame(
    location_years
)

print(location_years.shape)

(17733, 5)

In [ ]:
print(test_weather.shape)

(365, 8)

In [ ]:
print(location_years.shape)

(17733, 5)

In [ ]:
import os

WEATHER_DIR = "../data/weather"

os.makedirs(WEATHER_DIR, exist_ok=True)

print("Weather folder ready:", WEATHER_DIR)

Weather folder ready: ../data/weather

In [ ]:
def download_weather_year(lat, lon, year, output_file):

    # Don't download again if already completed
    if os.path.exists(output_file):
        return "EXISTS"

    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": f"{year}-01-01",
        "end_date": f"{year}-12-31",
        "daily": ",".join([
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum"
        ]),
        "timezone": "auto",
        "models": "era5"
    }

    for attempt in range(3):

        try:

            response = requests.get(
                url,
                params=params,
                timeout=60
            )

            if response.status_code == 200:

                data = response.json()

                weather = pd.DataFrame(
                    data["daily"]
                )

                weather["Latitude"] = lat
                weather["Longitude"] = lon
                weather["Year"] = year

                weather.to_csv(
                    output_file,
                    index=False
                )

                return "SUCCESS"

            print(
                f"HTTP {response.status_code} "
                f"for {year}"
            )

        except Exception as e:

            print(
                f"Attempt {attempt + 1} failed "
                f"for {year}: {e}"
            )

            time.sleep(5)

    return "FAILED"

In [53]:
test_row = location_years.iloc[0]

test_file = os.path.join(
    WEATHER_DIR,
    "test_weather.csv"
)

status = download_weather_year(
    test_row["Latitude"],
    test_row["Longitude"],
    int(test_row["Year"]),
    test_file
)

print("Status:", status)
print("File exists:", os.path.exists(test_file))

NameError: name 'location_years' is not defined

In [54]:
if os.path.exists(test_file):
    os.remove(test_file)

print("Test file removed.")

NameError: name 'test_file' is not defined

In [55]:
test_batch = location_years.head(20).copy()

print(
    test_batch[
        ["State", "District", "Year"]
    ]
)

NameError: name 'location_years' is not defined

In [56]:
batch_results = []

for i, row in test_batch.iterrows():

    output_file = os.path.join(
        WEATHER_DIR,
        f"test_{i}.csv"
    )

    status = download_weather_year(
        row["Latitude"],
        row["Longitude"],
        int(row["Year"]),
        output_file
    )

    batch_results.append({
        "State": row["State"],
        "District": row["District"],
        "Year": int(row["Year"]),
        "Status": status
    })

    print(
        i + 1,
        "/",
        len(test_batch),
        status
    )

    time.sleep(0.5)

NameError: name 'test_batch' is not defined

In [57]:
batch_results_df = pd.DataFrame(
    batch_results
)

print(
    batch_results_df["Status"].value_counts()
)

KeyError: 'Status'

In [58]:
for file in os.listdir(WEATHER_DIR):

    if file.startswith("test_"):

        os.remove(
            os.path.join(
                WEATHER_DIR,
                file
            )
        )

print("Test weather files removed.")

NameError: name 'WEATHER_DIR' is not defined

In [59]:
batch_results_df["Status"].value_counts()

KeyError: 'Status'

In [60]:
import os
import time
import pandas as pd
import requests

WEATHER_DIR = "../data/weather"
os.makedirs(WEATHER_DIR, exist_ok=True)

CHECKPOINT_FILE = os.path.join(
    WEATHER_DIR,
    "weather_checkpoint.csv"
)

FAILED_FILE = os.path.join(
    WEATHER_DIR,
    "weather_failed.csv"
)

In [61]:
if os.path.exists(CHECKPOINT_FILE):
    completed = pd.read_csv(CHECKPOINT_FILE)
else:
    completed = pd.DataFrame(
        columns=[
            "State",
            "District",
            "Year",
            "Latitude",
            "Longitude",
            "Status"
        ]
    )

print("Already completed:", len(completed))

Already completed: 463

In [62]:
def fetch_weather_year(lat, lon, year):

    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": f"{year}-01-01",
        "end_date": f"{year}-12-31",
        "daily": ",".join([
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum"
        ]),
        "timezone": "auto",
        "models": "era5"
    }

    for attempt in range(3):

        try:

            response = requests.get(
                url,
                params=params,
                timeout=60
            )

            if response.status_code == 200:

                data = response.json()

                weather = pd.DataFrame(
                    data["daily"]
                )

                weather["Latitude"] = lat
                weather["Longitude"] = lon
                weather["Year"] = year

                return weather

            print(
                f"HTTP {response.status_code}"
            )

        except Exception as e:

            print(
                f"Attempt {attempt + 1}: {e}"
            )

            time.sleep(5)

    return None

In [63]:
failed_records = []

total = len(location_years)

for i, row in location_years.head(100).iterrows():

    state = row["State"]
    district = row["District"]
    year = int(row["Year"])

    # Check whether already completed
    already_done = completed[
        (completed["State"] == state) &
        (completed["District"] == district) &
        (completed["Year"] == year)
    ]

    if len(already_done) > 0:
        continue

    print(
        f"[{i + 1}/{total}] "
        f"{state} | {district} | {year}"
    )

    weather = fetch_weather_year(
        row["Latitude"],
        row["Longitude"],
        year
    )

    if weather is not None:

        # Save individual weather file
        filename = (
            f"{i}_{year}.csv"
        )

        filepath = os.path.join(
            WEATHER_DIR,
            filename
        )

        weather.to_csv(
            filepath,
            index=False
        )

        completed = pd.concat(
            [
                completed,
                pd.DataFrame([{
                    "State": state,
                    "District": district,
                    "Year": year,
                    "Latitude": row["Latitude"],
                    "Longitude": row["Longitude"],
                    "Status": "SUCCESS"
                }])
            ],
            ignore_index=True
        )

        completed.to_csv(
            CHECKPOINT_FILE,
            index=False
        )

    else:

        failed_records.append({
            "State": state,
            "District": district,
            "Year": year
        })

        pd.DataFrame(
            failed_records
        ).to_csv(
            FAILED_FILE,
            index=False
        )

    # Small delay
    time.sleep(0.5)

print("Download process finished.")

NameError: name 'location_years' is not defined

In [64]:
print(
    completed["Status"].value_counts()
)

Status
SUCCESS    463
Name: count, dtype: int64

In [65]:
print(
    "Completed:",
    len(completed)
)

Completed: 463

In [66]:
print(completed.tail())
print(completed["Status"].value_counts())
print("Completed:", len(completed))

                 State       District  Year   Latitude  Longitude   Status
458  Arunachal Pradesh  DIBANG VALLEY  2018  28.829104  95.955410  SUCCESS
459  Arunachal Pradesh  DIBANG VALLEY  2019  28.829104  95.955410  SUCCESS
460  Arunachal Pradesh    EAST KAMENG  1997  27.557781  93.075301  SUCCESS
461  Arunachal Pradesh    EAST KAMENG  1998  27.557781  93.075301  SUCCESS
462  Arunachal Pradesh    EAST KAMENG  1999  27.557781  93.075301  SUCCESS
Status
SUCCESS    463
Name: count, dtype: int64
Completed: 463

In [67]:
hyderabad_mask = (
    (final_locations["State"] == "Andhra Pradesh") &
    (final_locations["District"] == "HYDERABAD")
)

final_locations.loc[
    hyderabad_mask,
    [
        "State",
        "District",
        "Current_State",
        "Current_District",
        "Latitude",
        "Longitude"
    ]
]

,State,District,Current_State,Current_District,Latitude,Longitude
5,Andhra Pradesh,HYDERABAD,Telangana,Hyderabad,17.6,78.7833

In [68]:
final_locations.loc[
    hyderabad_mask,
    "Latitude"
] = 17.6000

final_locations.loc[
    hyderabad_mask,
    "Longitude"
] = 78.7833

final_locations.loc[
    hyderabad_mask,
    "Current_State"
] = "Telangana"

final_locations.loc[
    hyderabad_mask,
    "Current_District"
] = "Hyderabad"

final_locations.loc[
    hyderabad_mask,
    "Geocoded_Address"
] = "Hyderabad District, Telangana, India"

In [69]:
final_locations.to_csv(
    "../data/processed/location_reference_final.csv",
    index=False
)

print("Location reference updated.")

Location reference updated.

In [70]:
print(
    final_locations[
        ["Latitude", "Longitude"]
    ].describe()
)

         Latitude   Longitude
count  771.000000  771.000000
mean    23.275181   81.320172
std      5.622589    6.270646
min      7.000017   68.968207
25%     20.269275   76.648035
50%     24.262815   79.519810
75%     26.859081   85.467439
max     34.514070   96.840721

In [71]:
suspicious = final_locations[
    (final_locations["Latitude"] < 6) |
    (final_locations["Latitude"] > 37) |
    (final_locations["Longitude"] < 68) |
    (final_locations["Longitude"] > 98)
]

print("Out-of-India-range locations:", len(suspicious))

Out-of-India-range locations: 0

In [72]:
print(
    "Latitude missing:",
    final_locations["Latitude"].isna().sum()
)

print(
    "Longitude missing:",
    final_locations["Longitude"].isna().sum()
)

Latitude missing: 0
Longitude missing: 0

In [73]:
print("Out-of-India-range locations:", len(suspicious))

Out-of-India-range locations: 0

In [74]:
print(
    final_locations[
        ["Latitude", "Longitude"]
    ].describe()
)

         Latitude   Longitude
count  771.000000  771.000000
mean    23.275181   81.320172
std      5.622589    6.270646
min      7.000017   68.968207
25%     20.269275   76.648035
50%     24.262815   79.519810
75%     26.859081   85.467439
max     34.514070   96.840721

In [75]:
final_locations.to_csv(
    "../data/processed/location_reference_final.csv",
    index=False
)

In [76]:
final_locations[
    (final_locations["State"] == "Andhra Pradesh") &
    (final_locations["District"] == "HYDERABAD")
][
    ["State", "District", "Latitude", "Longitude"]
]

            State   District  Latitude  Longitude
5  Andhra Pradesh  HYDERABAD      17.6    78.7833

In [77]:
for i, row in location_years.iterrows():

    state = row["State"]
    district = row["District"]
    year = int(row["Year"])

    already_done = completed[
        (completed["State"] == state) &
        (completed["District"] == district) &
        (completed["Year"] == year)
    ]

    if len(already_done) > 0:
        continue

    weather = fetch_weather_year(
        row["Latitude"],
        row["Longitude"],
        year
    )

    if weather is not None:

        filename = f"{i}_{year}.csv"

        filepath = os.path.join(
            WEATHER_DIR,
            filename
        )

        weather.to_csv(
            filepath,
            index=False
        )

        completed = pd.concat(
            [
                completed,
                pd.DataFrame([{
                    "State": state,
                    "District": district,
                    "Year": year,
                    "Latitude": row["Latitude"],
                    "Longitude": row["Longitude"],
                    "Status": "SUCCESS"
                }])
            ],
            ignore_index=True
        )

        completed.to_csv(
            CHECKPOINT_FILE,
            index=False
        )

    else:

        failed_records.append({
            "State": state,
            "District": district,
            "Year": year
        })

        pd.DataFrame(
            failed_records
        ).to_csv(
            FAILED_FILE,
            index=False
        )

    if (i + 1) % 100 == 0:
        print(
            f"Progress: {i + 1}/{len(location_years)}"
        )

    time.sleep(0.5)

NameError: name 'location_years' is not defined

In [78]:
print("Old downloader stopped.")

Old downloader stopped.

In [79]:
import pandas as pd
import numpy as np
import requests
import time
import os

In [80]:
locations = pd.read_csv(
    "../data/processed/location_reference_final.csv"
)

print("Locations:", len(locations))

Locations: 771

In [81]:
weather_locations = locations[
    [
        "State",
        "District",
        "Latitude",
        "Longitude"
    ]
].drop_duplicates(
    subset=["State", "District"]
).reset_index(drop=True)

weather_locations["Location_ID"] = (
    weather_locations.index + 1
)

print(
    "Unique locations:",
    len(weather_locations)
)

Unique locations: 771

In [82]:
BATCH_SIZE = 10

location_batches = [
    weather_locations.iloc[i:i+BATCH_SIZE].copy()
    for i in range(
        0,
        len(weather_locations),
        BATCH_SIZE
    )
]

print("Number of batches:", len(location_batches))

Number of batches: 78

In [83]:
def fetch_weather_batch(batch):

    latitudes = ",".join(
        batch["Latitude"].astype(str)
    )

    longitudes = ",".join(
        batch["Longitude"].astype(str)
    )

    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": latitudes,
        "longitude": longitudes,

        "start_date": "1997-01-01",
        "end_date": "2019-12-31",

        "daily": ",".join([
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum"
        ]),

        "timezone": "auto",
        "models": "era5"
    }

    for attempt in range(3):

        try:

            response = requests.get(
                url,
                params=params,
                timeout=300
            )

            print(
                "HTTP status:",
                response.status_code
            )

            if response.status_code == 200:
                return response.json()

            if response.status_code == 429:
                print(
                    "Rate limited. Waiting 30 seconds..."
                )
                time.sleep(30)

            else:
                print(
                    response.text[:500]
                )

        except Exception as e:

            print(
                "Error:",
                e
            )

            time.sleep(10)

    return None

In [84]:
test_batch = location_batches[0]

print(
    test_batch[
        [
            "Location_ID",
            "State",
            "District"
        ]
    ]
)

   Location_ID                       State                  District
0            1  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN
1            2              Andhra Pradesh                 ANANTAPUR
2            3              Andhra Pradesh                  CHITTOOR
3            4              Andhra Pradesh             EAST GODAVARI
4            5              Andhra Pradesh                    GUNTUR
5            6              Andhra Pradesh                 HYDERABAD
6            7              Andhra Pradesh                    KADAPA
7            8              Andhra Pradesh                   KHAMMAM
8            9              Andhra Pradesh                   KRISHNA
9           10              Andhra Pradesh                   KURNOOL

In [85]:
test_response = fetch_weather_batch(
    test_batch
)

HTTP status: 429
Rate limited. Waiting 30 seconds...

KeyboardInterrupt:

In [86]:
import pandas as pd

climate = pd.read_csv(
    "../data/raw/india_climate_adm2.csv"
)

print("Shape:", climate.shape)
print("Columns:")
print(climate.columns.tolist())

Shape: (736, 14712)
Columns:

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22200\2389640964.py:3: DtypeWarning: Columns (0: asdf_id) have mixed types. Specify dtype option on import or set low_memory=False.
  climate = pd.read_csv(

In [87]:
climate.head()

,asdf_id,udel_precip_v501_sum.1900.max,udel_precip_v501_sum.1900.mean,udel_precip_v501_sum.1900.min,udel_precip_v501_sum.1900.sum,udel_precip_v501_sum.1901.max,udel_precip_v501_sum.1901.mean,udel_precip_v501_sum.1901.min,udel_precip_v501_sum.1901.sum,udel_precip_v501_sum.1902.max,...,Level,OBJECTID,Shape_Area,Shape_Length,gqid,id,shapeGroup,shapeID,shapeName,shapeType
0,0,1256.1,1055.673401,893.7,1746.197027,1232.1,965.243313,690.9,1589.226027,1229.6,...,ADM2,1.0,0.421664,3.925451,0.0,0.0,IND,IND-ADM2-76128533B24212364,Ashoknagar,ADM2
1,1,1410.0,1286.310088,1133.5,3856.902955,1699.7,1264.334160,979.7,3772.806962,1139.6,...,ADM2,2.0,0.748785,7.526803,1.0,1.0,IND,IND-ADM2-76128533B65758206,Raisen,ADM2
2,2,1704.6,1289.800499,1029.7,5397.429014,1735.3,1355.507972,905.3,5695.707017,1139.6,...,ADM2,3.0,1.033143,7.724320,2.0,2.0,IND,IND-ADM2-76128533B77651862,Chhindwara,ADM2
3,3,1704.6,1288.580439,910.3,4540.424012,1706.9,1094.007035,762.2,3853.350010,1102.8,...,ADM2,4.0,0.875211,6.736091,3.0,3.0,IND,IND-ADM2-76128533B14961718,Betul,ADM2
4,4,1704.6,1397.505873,1308.6,3223.308988,1735.3,1387.842665,953.5,3215.012991,1139.6,...,ADM2,5.0,0.586915,5.467521,4.0,4.0,IND,IND-ADM2-76128533B94465219,Hoshangabad,ADM2

In [88]:
climate.info()

<class 'pandas.DataFrame'>
RangeIndex: 736 entries, 0 to 735
Columns: 14712 entries, asdf_id to shapeType
dtypes: float64(14706), object(1), str(5)
memory usage: 82.6+ MB

In [89]:
import re

precip_years = sorted({
    int(re.search(r"\.(\d{4})\.", c).group(1))
    for c in climate.columns
    if c.startswith("udel_precip_v501_sum.")
    and re.search(r"\.(\d{4})\.", c)
})

temp_years = sorted({
    int(re.search(r"\.(\d{4})\.", c).group(1))
    for c in climate.columns
    if c.startswith("udel_air_temp_v501_mean.")
    and re.search(r"\.(\d{4})\.", c)
})

print("Precipitation years:")
print(precip_years)

print("\nTemperature years:")
print(temp_years)

Precipitation years:
[1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

Temperature years:
[1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

In [90]:
print(
    climate["shapeNames"].head(20).tolist()
)

KeyError: 'shapeNames'

In [91]:
print(climate.columns[-20:].tolist())

['ltdr_avhrr_ndvi_v5_yearly.2011.max', 'ltdr_avhrr_ndvi_v5_yearly.2011.mean', 'ltdr_avhrr_ndvi_v5_yearly.2011.min', 'ltdr_avhrr_ndvi_v5_yearly.2011.count', 'srtm_elevation_500m.none.mean', 'srtm_elevation_500m.none.max', 'srtm_elevation_500m.none.min', 'srtm_slope_500m.none.mean', 'srtm_slope_500m.none.max', 'srtm_slope_500m.none.min', 'Level', 'OBJECTID', 'Shape_Area', 'Shape_Length', 'gqid', 'id', 'shapeGroup', 'shapeID', 'shapeName', 'shapeType']

In [92]:
for col in climate.columns:
    if "shape" in str(col).lower() or "name" in str(col).lower():
        print(repr(col))

'Shape_Area'
'Shape_Length'
'shapeGroup'
'shapeID'
'shapeName'
'shapeType'

In [93]:
print("Shape:", climate.shape)
print("Number of columns:", len(climate.columns))

Shape: (736, 14712)
Number of columns: 14712

In [94]:
for col in climate.columns:
    if "shape" in str(col).lower() or "name" in str(col).lower():
        print(repr(col))

'Shape_Area'
'Shape_Length'
'shapeGroup'
'shapeID'
'shapeName'
'shapeType'

In [95]:
print(climate["shapeName"].head(20).tolist())

['Ashoknagar', 'Raisen', 'Chhindwara', 'Betul', 'Hoshangabad', 'Sehore', 'Jabalpur', 'Narsimhapur', 'Panna', 'Ujjain', 'Rewa', 'Dindori', 'Balaghat', 'Barwani', 'Satna', 'Chhatarpur', 'Indore', 'Ratlam', 'Harda', 'Sagar']

In [96]:
print("Unique climate districts:", climate["shapeName"].nunique())

Unique climate districts: 728

In [97]:
import re

precip_years = sorted({
    int(re.search(r"\.(\d{4})\.", c).group(1))
    for c in climate.columns
    if c.startswith("udel_precip_v501_sum.")
    and re.search(r"\.(\d{4})\.", c)
})

temp_years = sorted({
    int(re.search(r"\.(\d{4})\.", c).group(1))
    for c in climate.columns
    if c.startswith("udel_air_temp_v501_mean.")
    and re.search(r"\.(\d{4})\.", c)
})

print("Precipitation years:", precip_years)
print("Temperature years:", temp_years)

Precipitation years: [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Temperature years: [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]

In [98]:
temp_columns = [
    c for c in climate.columns
    if c.startswith("udel_air_temp_v501_mean.")
]

print("Number of temperature columns:", len(temp_columns))
print(temp_columns[:20])

Number of temperature columns: 354
['udel_air_temp_v501_mean.1900.max', 'udel_air_temp_v501_mean.1900.mean', 'udel_air_temp_v501_mean.1900.min', 'udel_air_temp_v501_mean.1901.max', 'udel_air_temp_v501_mean.1901.mean', 'udel_air_temp_v501_mean.1901.min', 'udel_air_temp_v501_mean.1902.max', 'udel_air_temp_v501_mean.1902.mean', 'udel_air_temp_v501_mean.1902.min', 'udel_air_temp_v501_mean.1903.max', 'udel_air_temp_v501_mean.1903.mean', 'udel_air_temp_v501_mean.1903.min', 'udel_air_temp_v501_mean.1904.max', 'udel_air_temp_v501_mean.1904.mean', 'udel_air_temp_v501_mean.1904.min', 'udel_air_temp_v501_mean.1905.max', 'udel_air_temp_v501_mean.1905.mean', 'udel_air_temp_v501_mean.1905.min', 'udel_air_temp_v501_mean.1906.max', 'udel_air_temp_v501_mean.1906.mean']

In [99]:
rain_columns = [
    c for c in climate.columns
    if c.startswith("udel_precip_v501_sum.")
]

print("Number of rainfall columns:", len(rain_columns))
print(rain_columns[:20])

Number of rainfall columns: 472
['udel_precip_v501_sum.1900.max', 'udel_precip_v501_sum.1900.mean', 'udel_precip_v501_sum.1900.min', 'udel_precip_v501_sum.1900.sum', 'udel_precip_v501_sum.1901.max', 'udel_precip_v501_sum.1901.mean', 'udel_precip_v501_sum.1901.min', 'udel_precip_v501_sum.1901.sum', 'udel_precip_v501_sum.1902.max', 'udel_precip_v501_sum.1902.mean', 'udel_precip_v501_sum.1902.min', 'udel_precip_v501_sum.1902.sum', 'udel_precip_v501_sum.1903.max', 'udel_precip_v501_sum.1903.mean', 'udel_precip_v501_sum.1903.min', 'udel_precip_v501_sum.1903.sum', 'udel_precip_v501_sum.1904.max', 'udel_precip_v501_sum.1904.mean', 'udel_precip_v501_sum.1904.min', 'udel_precip_v501_sum.1904.sum']

In [100]:
print("=== PRECIPITATION ===")
print("Years:", precip_years)
print("Number of years:", len(precip_years))

print("\n=== TEMPERATURE ===")
print("Years:", temp_years)
print("Number of years:", len(temp_years))

print("\n=== TEMPERATURE COLUMNS ===")
print("Count:", len(temp_columns))
print(temp_columns[:10])

print("\n=== RAINFALL COLUMNS ===")
print("Count:", len(rain_columns))
print(rain_columns[:10])

=== PRECIPITATION ===
Years: [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Number of years: 118

=== TEMPERATURE ===
Years: [1900, 1901, 1902, 1903, 1904, 1905, 1906, 1907, 1908, 1909, 1910, 1911, 1912, 1913, 1914, 1915, 1916, 1917, 1918, 1919, 1920, 1921, 1922, 1923, 1924, 1925, 1926, 1927, 1928, 1929, 1930, 1931, 1932, 1933, 1934, 1935, 1936, 1937, 1938, 1939, 1940, 1941, 1942, 1943, 1944, 1945, 1946, 1947, 1948, 1949, 1950, 1951, 1952, 1953, 1954, 1955, 1956, 1957, 1958, 1959, 1960, 1961, 1962, 1963, 1964, 1965, 1966, 1967, 1968, 1969, 1970, 1971, 1972, 1973, 1974, 1975, 1976, 1977, 1978, 1979, 1980, 1981, 1982, 1983, 1984, 1985, 1986, 1987, 1988, 1989, 1990, 1991, 1992, 1993, 1994, 1995, 1996, 1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Number of years: 118

=== TEMPERATURE COLUMNS ===
Count: 354
['udel_air_temp_v501_mean.1900.max', 'udel_air_temp_v501_mean.1900.mean', 'udel_air_temp_v501_mean.1900.min', 'udel_air_temp_v501_mean.1901.max', 'udel_air_temp_v501_mean.1901.mean', 'udel_air_temp_v501_mean.1901.min', 'udel_air_temp_v501_mean.1902.max', 'udel_air_temp_v501_mean.1902.mean', 'udel_air_temp_v501_mean.1902.min', 'udel_air_temp_v501_mean.1903.max']

=== RAINFALL COLUMNS ===
Count: 472
['udel_precip_v501_sum.1900.max', 'udel_precip_v501_sum.1900.mean', 'udel_precip_v501_sum.1900.min', 'udel_precip_v501_sum.1900.sum', 'udel_precip_v501_sum.1901.max', 'udel_precip_v501_sum.1901.mean', 'udel_precip_v501_sum.1901.min', 'udel_precip_v501_sum.1901.sum', 'udel_precip_v501_sum.1902.max', 'udel_precip_v501_sum.1902.mean']

In [101]:
years = list(range(1997, 2018))

print("Years:", years)
print("Number of years:", len(years))

Years: [1997, 1998, 1999, 2000, 2001, 2002, 2003, 2004, 2005, 2006, 2007, 2008, 2009, 2010, 2011, 2012, 2013, 2014, 2015, 2016, 2017]
Number of years: 21

In [102]:
selected_columns = ["shapeName"]

for year in years:

    rainfall_col = f"udel_precip_v501_sum.{year}.mean"
    temperature_col = f"udel_air_temp_v501_mean.{year}.mean"

    if rainfall_col in climate.columns:
        selected_columns.append(rainfall_col)

    if temperature_col in climate.columns:
        selected_columns.append(temperature_col)

print("Selected columns:", len(selected_columns))
print(selected_columns[:10])

Selected columns: 43
['shapeName', 'udel_precip_v501_sum.1997.mean', 'udel_air_temp_v501_mean.1997.mean', 'udel_precip_v501_sum.1998.mean', 'udel_air_temp_v501_mean.1998.mean', 'udel_precip_v501_sum.1999.mean', 'udel_air_temp_v501_mean.1999.mean', 'udel_precip_v501_sum.2000.mean', 'udel_air_temp_v501_mean.2000.mean', 'udel_precip_v501_sum.2001.mean']

In [103]:
climate_selected = climate[
    selected_columns
].copy()

print("Shape:", climate_selected.shape)

Shape: (736, 43)

In [104]:
climate_long = []

for year in years:

    rainfall_col = f"udel_precip_v501_sum.{year}.mean"
    temperature_col = f"udel_air_temp_v501_mean.{year}.mean"

    temp_df = pd.DataFrame({
        "District": climate["shapeName"],
        "Year": year,
        "Rainfall": climate[rainfall_col],
        "Temperature": climate[temperature_col]
    })

    climate_long.append(temp_df)

climate_long = pd.concat(
    climate_long,
    ignore_index=True
)

In [105]:
print(climate_long.shape)

(15456, 4)

In [106]:
climate_long.head(20)

       District  Year     Rainfall  Temperature
0    Ashoknagar  1997  1154.893187    24.769161
1        Raisen  1997  1290.198661    25.106505
2    Chhindwara  1997  1264.709764    23.979165
3         Betul  1997  1087.367823    24.184304
4   Hoshangabad  1997  1330.598633    24.850245
5        Sehore  1997  1234.098640    25.263430
6      Jabalpur  1997  1380.214735    24.471699
7   Narsimhapur  1997  1283.165172    24.797110
8         Panna  1997  1042.653667    24.812649
9        Ujjain  1997  1013.165130    25.360090
10         Rewa  1997   932.956096    25.040579
11      Dindori  1997  1402.317504    22.828786
12     Balaghat  1997  1464.493287    24.964197
13      Barwani  1997   761.736297    26.352082
14        Satna  1997   920.482014    24.987283
15   Chhatarpur  1997  1014.284830    25.148266
16       Indore  1997  1014.293701    25.432639
17       Ratlam  1997   976.624100    25.523076
18        Harda  1997  1166.714412    26.003164
19        Sagar  1997  1148.390521    25.281539

In [107]:
climate_long.info()

<class 'pandas.DataFrame'>
RangeIndex: 15456 entries, 0 to 15455
Data columns (total 4 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   District     15435 non-null  str
 1   Year         15456 non-null  int64
 2   Rainfall     15351 non-null  float64
 3   Temperature  15351 non-null  float64
dtypes: float64(2), int64(1), str(1)
memory usage: 483.1 KB

In [108]:
print(
    climate_long.isna().sum()
)

District        21
Year             0
Rainfall       105
Temperature    105
dtype: int64

In [109]:
print(
    climate_long[
        ["Rainfall", "Temperature"]
    ].describe()
)

           Rainfall   Temperature
count  15351.000000  15351.000000
mean    1366.490550     24.384443
std      870.870792      4.544038
min       37.049886     -4.277918
25%      819.303489     24.274656
50%     1137.190936     25.608837
75%     1627.959889     26.670027
max    10972.057165     29.785217

In [110]:
climate_long.to_csv(
    "../data/processed/climate_1997_2017.csv",
    index=False
)

print("✅ Climate dataset saved!")

✅ Climate dataset saved!

In [111]:
print(climate_long.shape)
print(climate_long.isna().sum())
print(climate_long.head())

(15456, 4)
District        21
Year             0
Rainfall       105
Temperature    105
dtype: int64
      District  Year     Rainfall  Temperature
0   Ashoknagar  1997  1154.893187    24.769161
1       Raisen  1997  1290.198661    25.106505
2   Chhindwara  1997  1264.709764    23.979165
3        Betul  1997  1087.367823    24.184304
4  Hoshangabad  1997  1330.598633    24.850245

In [112]:
missing_climate = climate_long[
    climate_long["Rainfall"].isna() |
    climate_long["Temperature"].isna()
].copy()

print("Missing rows:", len(missing_climate))

print(
    missing_climate[
        ["District", "Year", "Rainfall", "Temperature"]
    ].to_string(index=False)
)

Missing rows: 105
       District  Year  Rainfall  Temperature
       Nicobars  1997       NaN          NaN
    Lakshadweep  1997       NaN          NaN
         Mumbai  1997       NaN          NaN
Mumbai Suburban  1997       NaN          NaN
            NaN  1997       NaN          NaN
       Nicobars  1998       NaN          NaN
    Lakshadweep  1998       NaN          NaN
         Mumbai  1998       NaN          NaN
Mumbai Suburban  1998       NaN          NaN
            NaN  1998       NaN          NaN
       Nicobars  1999       NaN          NaN
    Lakshadweep  1999       NaN          NaN
         Mumbai  1999       NaN          NaN
Mumbai Suburban  1999       NaN          NaN
            NaN  1999       NaN          NaN
       Nicobars  2000       NaN          NaN
    Lakshadweep  2000       NaN          NaN
         Mumbai  2000       NaN          NaN
Mumbai Suburban  2000       NaN          NaN
            NaN  2000       NaN          NaN
       Nicobars  2001       NaN          NaN
    Lakshadweep  2001       NaN          NaN
         Mumbai  2001       NaN          NaN
Mumbai Suburban  2001       NaN          NaN
            NaN  2001       NaN          NaN
       Nicobars  2002       NaN          NaN
    Lakshadweep  2002       NaN          NaN
         Mumbai  2002       NaN          NaN
Mumbai Suburban  2002       NaN          NaN
            NaN  2002       NaN          NaN
       Nicobars  2003       NaN          NaN
    Lakshadweep  2003       NaN          NaN
         Mumbai  2003       NaN          NaN
Mumbai Suburban  2003       NaN          NaN
            NaN  2003       NaN          NaN
       Nicobars  2004       NaN          NaN
    Lakshadweep  2004       NaN          NaN
         Mumbai  2004       NaN          NaN
Mumbai Suburban  2004       NaN          NaN
            NaN  2004       NaN          NaN
       Nicobars  2005       NaN          NaN
    Lakshadweep  2005       NaN          NaN
         Mumbai  2005       NaN          NaN
Mumbai Suburban  2005       NaN          NaN
            NaN  2005       NaN          NaN
       Nicobars  2006       NaN          NaN
    Lakshadweep  2006       NaN          NaN
         Mumbai  2006       NaN          NaN
Mumbai Suburban  2006       NaN          NaN
            NaN  2006       NaN          NaN
       Nicobars  2007       NaN          NaN
    Lakshadweep  2007       NaN          NaN
         Mumbai  2007       NaN          NaN
Mumbai Suburban  2007       NaN          NaN
            NaN  2007       NaN          NaN
       Nicobars  2008       NaN          NaN
    Lakshadweep  2008       NaN          NaN
         Mumbai  2008       NaN          NaN
Mumbai Suburban  2008       NaN          NaN
            NaN  2008       NaN          NaN
       Nicobars  2009       NaN          NaN
    Lakshadweep  2009       NaN          NaN
         Mumbai  2009       NaN          NaN
Mumbai Suburban  2009       NaN          NaN
            NaN  2009       NaN          NaN
       Nicobars  2010       NaN          NaN
    Lakshadweep  2010       NaN          NaN
         Mumbai  2010       NaN          NaN
Mumbai Suburban  2010       NaN          NaN
            NaN  2010       NaN          NaN
       Nicobars  2011       NaN          NaN
    Lakshadweep  2011       NaN          NaN
         Mumbai  2011       NaN          NaN
Mumbai Suburban  2011       NaN          NaN
            NaN  2011       NaN          NaN
       Nicobars  2012       NaN          NaN
    Lakshadweep  2012       NaN          NaN
         Mumbai  2012       NaN          NaN
Mumbai Suburban  2012       NaN          NaN
            NaN  2012       NaN          NaN
       Nicobars  2013       NaN          NaN
    Lakshadweep  2013       NaN          NaN
         Mumbai  2013       NaN          NaN
Mumbai Suburban  2013       NaN          NaN
            NaN  2013       NaN          NaN
       Nicobars  2014       NaN          NaN
    Lakshadweep  2014       NaN          NaN
         Mumbai  2014       NaN          NaN
Mumbai Suburban  2014       NaN          NaN
            NaN  2014       NaN          NaN
       Nicobars  2015       NaN          NaN
    Lakshadweep  2015       NaN          NaN
         Mumbai  2015       NaN          NaN
Mumbai Suburban  2015       NaN          NaN
            NaN  2015       NaN          NaN
       Nicobars  2016       NaN          NaN
    Lakshadweep  2016       NaN          NaN
         Mumbai  2016       NaN          NaN
Mumbai Suburban  2016       NaN          NaN
            NaN  2016       NaN          NaN
       Nicobars  2017       NaN          NaN
    Lakshadweep  2017       NaN          NaN
         Mumbai  2017       NaN          NaN
Mumbai Suburban  2017       NaN          NaN
            NaN  2017       NaN          NaN

In [113]:

missing_districts = (
    missing_climate["District"]
    .value_counts()
)

print(missing_districts)

District
Nicobars           21
Lakshadweep        21
Mumbai             21
Mumbai Suburban    21
Name: count, dtype: int64

In [114]:
print(
    "Total climate districts:",
    climate_long["District"].nunique()
)

print(
    "Districts with missing climate:",
    missing_climate["District"].nunique()
)

Total climate districts: 728
Districts with missing climate: 4

In [115]:
print(
    missing_districts.index.tolist()
)

['Nicobars', 'Lakshadweep', 'Mumbai', 'Mumbai Suburban']

In [116]:
print(missing_districts)
print(missing_districts.index.tolist())

District
Nicobars           21
Lakshadweep        21
Mumbai             21
Mumbai Suburban    21
Name: count, dtype: int64
['Nicobars', 'Lakshadweep', 'Mumbai', 'Mumbai Suburban']

In [117]:
print("Total missing rows:", len(missing_climate))

print("\nMissing by district:")
print(missing_climate["District"].value_counts())

print("\nNumber of districts:")
print(missing_climate["District"].nunique())

Total missing rows: 105

Missing by district:
District
Nicobars           21
Lakshadweep        21
Mumbai             21
Mumbai Suburban    21
Name: count, dtype: int64

Number of districts:
4

In [118]:
print(
    missing_climate["District"].isna().sum()
)

21

In [119]:
print(
    missing_climate[
        missing_climate["District"].isna()
    ][
        ["District", "Year", "Rainfall", "Temperature"]
    ]
)

      District  Year  Rainfall  Temperature
735        NaN  1997       NaN          NaN
1471       NaN  1998       NaN          NaN
2207       NaN  1999       NaN          NaN
2943       NaN  2000       NaN          NaN
3679       NaN  2001       NaN          NaN
4415       NaN  2002       NaN          NaN
5151       NaN  2003       NaN          NaN
5887       NaN  2004       NaN          NaN
6623       NaN  2005       NaN          NaN
7359       NaN  2006       NaN          NaN
8095       NaN  2007       NaN          NaN
8831       NaN  2008       NaN          NaN
9567       NaN  2009       NaN          NaN
10303      NaN  2010       NaN          NaN
11039      NaN  2011       NaN          NaN
11775      NaN  2012       NaN          NaN
12511      NaN  2013       NaN          NaN
13247      NaN  2014       NaN          NaN
13983      NaN  2015       NaN          NaN
14719      NaN  2016       NaN          NaN
15455      NaN  2017       NaN          NaN

In [120]:
print(
    climate[
        climate["shapeName"].isna()
    ][
        ["shapeName"]
    ]
)

    shapeName
735       NaN

In [121]:
print(
    "Missing shapeName:",
    climate["shapeName"].isna().sum()
)

Missing shapeName: 1

In [122]:
print("Missing District in climate_long:",
      climate_long["District"].isna().sum())

print("Missing shapeName in climate:",
      climate["shapeName"].isna().sum())

Missing District in climate_long: 21
Missing shapeName in climate: 1

In [123]:
climate = climate[
    climate["shapeName"].notna()
].copy()

print("Climate districts:", climate["shapeName"].nunique())

Climate districts: 728

In [124]:
special_districts = [
    "NICOBARS",
    "LAKSHADWEEP",
    "MUMBAI",
    "MUMBAI SUBURBAN"
]

for district in special_districts:

    matches = agriculture[
        agriculture["District"]
        .astype(str)
        .str.upper()
        .str.strip()
        == district
    ]

    print(
        district,
        "→",
        len(matches),
        "agricultural records"
    )

NICOBARS → 242 agricultural records
LAKSHADWEEP → 0 agricultural records
MUMBAI → 1 agricultural records
MUMBAI SUBURBAN → 2 agricultural records

In [125]:
special_districts = [
    "NICOBARS",
    "LAKSHADWEEP",
    "MUMBAI",
    "MUMBAI SUBURBAN"
]

for district in special_districts:

    matches = agriculture[
        agriculture["District"]
        .astype(str)
        .str.upper()
        .str.strip()
        == district
    ]

    print(
        f"{district}: {len(matches)} agriculture records"
    )

NICOBARS: 242 agriculture records
LAKSHADWEEP: 0 agriculture records
MUMBAI: 1 agriculture records
MUMBAI SUBURBAN: 2 agriculture records

In [126]:
special_districts = [
    "NICOBARS",
    "MUMBAI",
    "MUMBAI SUBURBAN"
]

special_locations = final_locations[
    final_locations["District"]
    .astype(str)
    .str.upper()
    .str.strip()
    .isin(special_districts)
].copy()

print(
    special_locations[
        [
            "State",
            "District",
            "Current_State",
            "Current_District",
            "Latitude",
            "Longitude"
        ]
    ].to_string(index=False)
)

                     State        District               Current_State Current_District  Latitude  Longitude
               Maharashtra          MUMBAI                         NaN              NaN 19.054999  72.869203
               Maharashtra MUMBAI SUBURBAN                         NaN              NaN 19.130984  72.889462
Andaman and Nicobar Island        NICOBARS Andaman and Nicobar Islands          Nicobar  7.000017  93.811053

In [127]:
special_weather = []

for _, row in special_locations.iterrows():

    for year in range(1997, 2018):

        print(
            f"{row['District']} | {year}"
        )

        weather = fetch_weather_year(
            row["Latitude"],
            row["Longitude"],
            year
        )

        if weather is not None:

            weather["District"] = row["District"]
            weather["State"] = row["State"]
            weather["Year"] = year

            special_weather.append(
                weather
            )

        time.sleep(0.5)

MUMBAI | 1997
HTTP 429
HTTP 429
HTTP 429
MUMBAI | 1998
HTTP 429
HTTP 429
HTTP 429
MUMBAI | 1999
HTTP 429
HTTP 429
HTTP 429
MUMBAI | 2000
HTTP 429
HTTP 429

KeyboardInterrupt:

In [128]:
import requests
import pandas as pd
import time

def fetch_weather_year(lat, lon, year):

    url = "https://archive-api.open-meteo.com/v1/archive"

    params = {
        "latitude": lat,
        "longitude": lon,
        "start_date": f"{year}-01-01",
        "end_date": f"{year}-12-31",
        "daily": ",".join([
            "temperature_2m_mean",
            "temperature_2m_max",
            "temperature_2m_min",
            "precipitation_sum"
        ]),
        "timezone": "auto",
        "models": "era5"
    }

    for attempt in range(3):

        try:
            response = requests.get(
                url,
                params=params,
                timeout=60
            )

            if response.status_code == 200:

                data = response.json()

                weather = pd.DataFrame(
                    data["daily"]
                )

                return weather

            print(
                f"HTTP {response.status_code}"
            )

        except Exception as e:

            print(
                f"Attempt {attempt + 1} failed: {e}"
            )

            time.sleep(5)

    return None

In [129]:
test_row = special_locations.iloc[0]

test_weather = fetch_weather_year(
    test_row["Latitude"],
    test_row["Longitude"],
    2019
)

print(test_weather.shape)
print(test_weather.head())

HTTP 429
HTTP 429
HTTP 429

AttributeError: 'NoneType' object has no attribute 'shape'

In [ ]:
special_weather = []

for _, row in special_locations.iterrows():

    for year in range(1997, 2018):

        print(
            f"{row['District']} | {year}"
        )

        weather = fetch_weather_year(
            row["Latitude"],
            row["Longitude"],
            year
        )

        if weather is not None:

            weather["District"] = row["District"]
            weather["State"] = row["State"]
            weather["Year"] = year

            special_weather.append(weather)

        time.sleep(0.5)

print(
    "Successful location-years:",
    len(special_weather)
)

MUMBAI | 1997
MUMBAI | 1998
MUMBAI | 1999
MUMBAI | 2000
MUMBAI | 2001
MUMBAI | 2002
MUMBAI | 2003
MUMBAI | 2004
MUMBAI | 2005
MUMBAI | 2006
MUMBAI | 2007
MUMBAI | 2008
MUMBAI | 2009
MUMBAI | 2010
MUMBAI | 2011
MUMBAI | 2012
MUMBAI | 2013
MUMBAI | 2014
MUMBAI | 2015
MUMBAI | 2016
MUMBAI | 2017
MUMBAI SUBURBAN | 1997
MUMBAI SUBURBAN | 1998
MUMBAI SUBURBAN | 1999
MUMBAI SUBURBAN | 2000
MUMBAI SUBURBAN | 2001
MUMBAI SUBURBAN | 2002
MUMBAI SUBURBAN | 2003
MUMBAI SUBURBAN | 2004
MUMBAI SUBURBAN | 2005
MUMBAI SUBURBAN | 2006
MUMBAI SUBURBAN | 2007
MUMBAI SUBURBAN | 2008
MUMBAI SUBURBAN | 2009
MUMBAI SUBURBAN | 2010
MUMBAI SUBURBAN | 2011
MUMBAI SUBURBAN | 2012
MUMBAI SUBURBAN | 2013
MUMBAI SUBURBAN | 2014
MUMBAI SUBURBAN | 2015
MUMBAI SUBURBAN | 2016
MUMBAI SUBURBAN | 2017
NICOBARS | 1997
NICOBARS | 1998
NICOBARS | 1999
NICOBARS | 2000
NICOBARS | 2001
NICOBARS | 2002
NICOBARS | 2003
NICOBARS | 2004
NICOBARS | 2005
NICOBARS | 2006
NICOBARS | 2007
NICOBARS | 2008
NICOBARS | 2009
NICOBARS | 2010
NICOBARS | 2011
NICOBARS | 2012
NICOBARS | 2013
NICOBARS | 2014
NICOBARS | 2015
NICOBARS | 2016
NICOBARS | 2017
Successful location-years: 63

In [ ]:
special_weather_daily = pd.concat(
    special_weather,
    ignore_index=True
)

print("Daily rows:", len(special_weather_daily))
print(
    special_weather_daily[
        ["State", "District", "Year"]
    ].drop_duplicates().shape
)

ValueError: No objects to concatenate

In [130]:
special_weather_daily["time"] = pd.to_datetime(
    special_weather_daily["time"]
)

NameError: name 'special_weather_daily' is not defined

In [131]:
special_climate = (
    special_weather_daily
    .groupby(
        ["State", "District", "Year"],
        as_index=False
    )
    .agg(
        Rainfall=(
            "precipitation_sum",
            "sum"
        ),
        Temperature=(
            "temperature_2m_mean",
            "mean"
        )
    )
)

NameError: name 'special_weather_daily' is not defined

In [132]:
print(special_climate.shape)
print(special_climate.head())

NameError: name 'special_climate' is not defined

In [133]:
special_climate.to_csv(
    "../data/processed/special_climate_1997_2017.csv",
    index=False
)

print("✅ Special climate saved")

NameError: name 'special_climate' is not defined

In [134]:
print(
    final_locations[
        [
            "State",
            "District",
            "Current_State",
            "Current_District"
        ]
    ].head(20)
)

                         State                  District Current_State  \
0   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN           NaN
1               Andhra Pradesh                 ANANTAPUR           NaN
2               Andhra Pradesh                  CHITTOOR           NaN
3               Andhra Pradesh             EAST GODAVARI           NaN
4               Andhra Pradesh                    GUNTUR           NaN
5               Andhra Pradesh                 HYDERABAD     Telangana
6               Andhra Pradesh                    KADAPA           NaN
7               Andhra Pradesh                   KHAMMAM           NaN
8               Andhra Pradesh                   KRISHNA           NaN
9               Andhra Pradesh                   KURNOOL           NaN
10              Andhra Pradesh               MAHBUBNAGAR           NaN
11              Andhra Pradesh                 NIZAMABAD           NaN
12              Andhra Pradesh                  PRAKASAM           NaN
13              Andhra Pradesh              SPSR NELLORE           NaN
14              Andhra Pradesh                SRIKAKULAM           NaN
15              Andhra Pradesh              VIZIANAGARAM           NaN
16              Andhra Pradesh             WEST GODAVARI           NaN
17           Arunachal Pradesh                     ANJAW           NaN
18           Arunachal Pradesh                 CHANGLANG           NaN
19           Arunachal Pradesh             DIBANG VALLEY           NaN

   Current_District
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
5         Hyderabad
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN

In [135]:
print(
    final_locations.columns.tolist()
)

['State', 'District', 'Latitude', 'Longitude', 'Current_State', 'Current_District', 'Geocoded_Address', 'Geocode_Status']

In [136]:
print(
    final_locations[
        [
            "State",
            "District",
            "Current_State",
            "Current_District"
        ]
    ].head(20)
)

print(
    final_locations.columns.tolist()
)

                         State                  District Current_State  \
0   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN           NaN
1               Andhra Pradesh                 ANANTAPUR           NaN
2               Andhra Pradesh                  CHITTOOR           NaN
3               Andhra Pradesh             EAST GODAVARI           NaN
4               Andhra Pradesh                    GUNTUR           NaN
5               Andhra Pradesh                 HYDERABAD     Telangana
6               Andhra Pradesh                    KADAPA           NaN
7               Andhra Pradesh                   KHAMMAM           NaN
8               Andhra Pradesh                   KRISHNA           NaN
9               Andhra Pradesh                   KURNOOL           NaN
10              Andhra Pradesh               MAHBUBNAGAR           NaN
11              Andhra Pradesh                 NIZAMABAD           NaN
12              Andhra Pradesh                  PRAKASAM           NaN
13              Andhra Pradesh              SPSR NELLORE           NaN
14              Andhra Pradesh                SRIKAKULAM           NaN
15              Andhra Pradesh              VIZIANAGARAM           NaN
16              Andhra Pradesh             WEST GODAVARI           NaN
17           Arunachal Pradesh                     ANJAW           NaN
18           Arunachal Pradesh                 CHANGLANG           NaN
19           Arunachal Pradesh             DIBANG VALLEY           NaN

   Current_District
0               NaN
1               NaN
2               NaN
3               NaN
4               NaN
5         Hyderabad
6               NaN
7               NaN
8               NaN
9               NaN
10              NaN
11              NaN
12              NaN
13              NaN
14              NaN
15              NaN
16              NaN
17              NaN
18              NaN
19              NaN
['State', 'District', 'Latitude', 'Longitude', 'Current_State', 'Current_District', 'Geocoded_Address', 'Geocode_Status']

In [137]:
# Unique agricultural State-District combinations
agri_locations = (
    agriculture[
        ["State", "District"]
    ]
    .drop_duplicates()
    .copy()
)

# Normalize names
agri_locations["District_clean"] = (
    agri_locations["District"]
    .astype(str)
    .str.upper()
    .str.strip()
)

climate_districts = (
    climate["shapeName"]
    .dropna()
    .astype(str)
    .str.upper()
    .str.strip()
    .drop_duplicates()
)

exact_matches = climate_districts[
    climate_districts.isin(
        agri_locations["District_clean"]
    )
]

print("Climate districts:", len(climate_districts))
print("Exact district-name matches:", len(exact_matches))
print(
    "Unmatched climate districts:",
    len(climate_districts) - len(exact_matches)
)

Climate districts: 728
Exact district-name matches: 589
Unmatched climate districts: 139

In [138]:
district_state_counts = (
    agri_locations
    .groupby("District_clean")["State"]
    .nunique()
    .sort_values(ascending=False)
)

ambiguous_districts = (
    district_state_counts[
        district_state_counts > 1
    ]
)

print(
    "District names appearing in multiple states:",
    len(ambiguous_districts)
)

print(ambiguous_districts)

District names appearing in multiple states: 63
District_clean
BILASPUR          3
UTTAR KASHI       2
ALMORA            2
TEHRI GARHWAL     2
SURGUJA           2
                 ..
CHAMPAWAT         2
BOKARO            2
WARANGAL          2
WEST SINGHBHUM    2
ADILABAD          2
Name: State, Length: 63, dtype: int64

In [139]:
for district in ambiguous_districts.index:

    print("\n", district)

    print(
        agri_locations[
            agri_locations["District_clean"] == district
        ][
            ["State", "District"]
        ].to_string(index=False)
    )

 BILASPUR
           State District
    Chhattisgarh BILASPUR
Himachal Pradesh BILASPUR
  Madhya Pradesh BILASPUR

 UTTAR KASHI
        State    District
Uttar Pradesh UTTAR KASHI
  Uttarakhand UTTAR KASHI

 ALMORA
        State District
Uttar Pradesh   ALMORA
  Uttarakhand   ALMORA

 TEHRI GARHWAL
        State      District
Uttar Pradesh TEHRI GARHWAL
  Uttarakhand TEHRI GARHWAL

 SURGUJA
         State District
  Chhattisgarh  SURGUJA
Madhya Pradesh  SURGUJA

 SAHEBGANJ
    State  District
    Bihar SAHEBGANJ
Jharkhand SAHEBGANJ

 UDAM SINGH NAGAR
        State         District
Uttar Pradesh UDAM SINGH NAGAR
  Uttarakhand UDAM SINGH NAGAR

 RANGAREDDI
         State   District
Andhra Pradesh RANGAREDDI
     Telangana RANGAREDDI

 RANCHI
    State District
    Bihar   RANCHI
Jharkhand   RANCHI

 RAJNANDGAON
         State    District
  Chhattisgarh RAJNANDGAON
Madhya Pradesh RAJNANDGAON

 RAIPUR
         State District
  Chhattisgarh   RAIPUR
Madhya Pradesh   RAIPUR

 PRATAPGARH
        State   District
    Rajasthan PRATAPGARH
Uttar Pradesh PRATAPGARH

 PITHORAGARH
        State    District
Uttar Pradesh PITHORAGARH
  Uttarakhand PITHORAGARH

 PAURI GARHWAL
        State      District
Uttar Pradesh PAURI GARHWAL
  Uttarakhand PAURI GARHWAL

 RUDRA PRAYAG
        State     District
Uttar Pradesh RUDRA PRAYAG
  Uttarakhand RUDRA PRAYAG

 PAKUR
    State District
    Bihar    PAKUR
Jharkhand    PAKUR

 NIZAMABAD
         State  District
Andhra Pradesh NIZAMABAD
     Telangana NIZAMABAD

 BAGESHWAR
        State  District
Uttar Pradesh BAGESHWAR
  Uttarakhand BAGESHWAR

 AURANGABAD
      State   District
      Bihar AURANGABAD
Maharashtra AURANGABAD

 NALGONDA
         State District
Andhra Pradesh NALGONDA
     Telangana NALGONDA

 NAINITAL
        State District
Uttar Pradesh NAINITAL
  Uttarakhand NAINITAL

 MEDAK
         State District
Andhra Pradesh    MEDAK
     Telangana    MEDAK

 MAHBUBNAGAR
         State    District
Andhra Pradesh MAHBUBNAGAR
     Telangana MAHBUBNAGAR

 MAHASAMUND
         State   District
  Chhattisgarh MAHASAMUND
Madhya Pradesh MAHASAMUND

 LOHARDAGA
    State  District
    Bihar LOHARDAGA
Jharkhand LOHARDAGA

 LEH LADAKH
            State   District
Jammu and Kashmir LEH LADAKH
           Ladakh LEH LADAKH

 KOREA
         State District
  Chhattisgarh    KOREA
Madhya Pradesh    KOREA

 KORBA
         State District
  Chhattisgarh    KORBA
Madhya Pradesh    KORBA

 KODERMA
    State District
    Bihar  KODERMA
Jharkhand  KODERMA

 KHAMMAM
         State District
Andhra Pradesh  KHAMMAM
     Telangana  KHAMMAM

 PALAMU
    State District
    Bihar   PALAMU
Jharkhand   PALAMU

 KARIMNAGAR
         State   District
Andhra Pradesh KARIMNAGAR
     Telangana KARIMNAGAR

 KARGIL
            State District
Jammu and Kashmir   KARGIL
           Ladakh   KARGIL

 BALRAMPUR
        State  District
 Chhattisgarh BALRAMPUR
Uttar Pradesh BALRAMPUR

 KANKER
         State District
  Chhattisgarh   KANKER
Madhya Pradesh   KANKER

 JASHPUR
         State District
  Chhattisgarh  JASHPUR
Madhya Pradesh  JASHPUR

 JANJGIR-CHAMPA
         State       District
  Chhattisgarh JANJGIR-CHAMPA
Madhya Pradesh JANJGIR-CHAMPA

 HAZARIBAGH
    State   District
    Bihar HAZARIBAGH
Jharkhand HAZARIBAGH

 KABIRDHAM
         State  District
  Chhattisgarh KABIRDHAM
Madhya Pradesh KABIRDHAM

 HAMIRPUR
           State District
Himachal Pradesh HAMIRPUR
   Uttar Pradesh HAMIRPUR

 GUMLA
    State District
    Bihar    GUMLA
Jharkhand    GUMLA

 GODDA
    State District
    Bihar    GODDA
Jharkhand    GODDA

 GIRIDIH
    State District
    Bihar  GIRIDIH
Jharkhand  GIRIDIH

 GARHWA
    State District
    Bihar   GARHWA
Jharkhand   GARHWA

 EAST SINGHBUM
    State      District
    Bihar EAST SINGHBUM
Jharkhand EAST SINGHBUM

 DURG
         State District
  Chhattisgarh     DURG
Madhya Pradesh     DURG

 HARIDWAR
        State District
Uttar Pradesh HARIDWAR
  Uttarakhand HARIDWAR

 DUMKA
    State District
    Bihar    DUMKA
Jharkhand    DUMKA

 DIU
                 State District
         Daman and Diu      DIU
Dadra and Nagar Haveli      DIU

 DHAMTARI
         State District
  Chhattisgarh DHAMTARI
Madhya Pradesh DHAMTARI

 DHANBAD
    State District
    Bihar  DHANBAD
Jharkhand  DHANBAD

 DEHRADUN
        State District
Uttar Pradesh DEHRADUN
  Uttarakhand DEHRADUN

 BASTAR
         State District
  Chhattisgarh   BASTAR
Madhya Pradesh   BASTAR

 DANTEWADA
         State  District
  Chhattisgarh DANTEWADA
Madhya Pradesh DANTEWADA

 DEOGHAR
    State District
    Bihar  DEOGHAR
Jharkhand  DEOGHAR

 DAMAN
                 State District
         Daman and Diu    DAMAN
Dadra and Nagar Haveli    DAMAN

 CHATRA
    State District
    Bihar   CHATRA
Jharkhand   CHATRA

 CHAMOLI
        State District
Uttar Pradesh  CHAMOLI
  Uttarakhand  CHAMOLI

 CHAMPAWAT
        State  District
Uttar Pradesh CHAMPAWAT
  Uttarakhand CHAMPAWAT

 BOKARO
    State District
    Bihar   BOKARO
Jharkhand   BOKARO

 WARANGAL
         State District
Andhra Pradesh WARANGAL
     Telangana WARANGAL

 WEST SINGHBHUM
    State       District
    Bihar WEST SINGHBHUM
Jharkhand WEST SINGHBHUM

 ADILABAD
         State District
Andhra Pradesh ADILABAD
     Telangana ADILABAD

In [140]:
unmatched_climate = climate_districts[
    ~climate_districts.isin(exact_matches)
].copy()

print("Unmatched:", len(unmatched_climate))

print(
    unmatched_climate.tolist()
)

Unmatched: 139
['NARSIMHAPUR', 'KHARGONE (WEST NIMAR)', 'KHANDWA (EAST NIMAR)', 'LAHUL & SPITI', 'DATA NOT AVAILABLE', 'BARAMULA', 'SHUPIYAN', 'RAJOURI', 'LEH(LADAKH)', 'PUNCH', 'BANDIPORE', 'CHHOTA UDAIPUR', 'BATOD', 'ARAVALI', 'THE DANGS', 'DADRA & NAGAR HAVELI', 'VISAKHAPATNAM', 'SRI POTTI SRIRAMULU NELLORE', 'KADAPA(YSR)', 'SARAIKELA-KHARSAWAN', 'PASHCHIMI SINGHBHUM', 'PURBI SINGHBHUM', 'KODARMA', 'SAHIBGANJ', 'PURBA CHAMPARAN', 'NORTH  & MIDDLE ANDAMAN', 'SOUTH ANDAMAN', 'MORIGAON', 'KARBI ANGLONG EAST', 'KAMRUP METROPOLITAN', 'PUDUCHERRY', 'KANGPOKPI', 'SIPAHIJULA', 'UNOKOTI', 'RIBHOI', 'BEMETRA', 'GARIABAND', 'KABEERDHAM', 'UTTAR BASTAR KANKER', 'DAKSHIN BASTAR DANTEWADA', 'KORIYA', 'UTTARKASHI', 'GARHWAL', 'HARDWAR', 'RUDRAPRAYAG', 'UDHAM SINGH NAGAR', 'LAKSHADWEEP', 'DAKSHIN DINAJPUR', 'KOLKATA', 'SOUTH TWENTY FOUR PARGANAS', 'DARJILING', 'UTTAR DINAJPUR', 'PURBA MEDINIPUR', 'HAORA', 'NORTH TWENTY FOUR PARGANAS', 'BARDDHAMAN', 'PURULIYA', 'KOCH BIHAR', 'PASCHIM MEDINIPUR', 'HUGLI', 'FIROZPUR', 'SAHIBZADA AJIT SINGH NAGAR', 'MYSORE', 'YADGIR', 'CHIKMAGALUR', 'DAVANAGERE', 'CHAMARAJANAGAR', 'GULBARGA', 'BAGALKOT', 'SHIMOGA', 'BELLARY', 'TUMKUR', 'BELGAUM', 'BANGALORE', 'AHMADNAGAR', 'GONDIYA', 'BULDANA', 'BID', 'SUBARNAPUR', 'DEBAGARH', 'NABARANGAPUR', 'BAUDH', 'JHUNJHUNUN', 'CHITTAURGARH', 'JALOR', 'KANSHIRAM NAGAR', 'SAMLI', 'SHRAWASTI', 'MAHAMAYA NAGAR', 'JYOTIBA PHULE NAGAR', 'SANT RAVIDAS NAGAR (BHADOHI)', 'SIDDHARTHNAGAR', 'SANT KABIR NAGAR', 'BARA BANKI', 'MAHRAJGANJ', 'KUSHINAGAR', 'VILUPPURAM', 'KANCHEEPURAM', 'THOOTHUKKUDI', 'DHAULPUR', 'JANGAON', 'HYDRABAD', 'RANGAREDDY', 'KOMARAM BHEEM', 'JAGTIAL', 'RAJANNA SIRCILLA', 'WARANGAL (R)', 'WARANGAL (U)', 'YADADRI BHONGIRI', 'MEDCHAL', 'MAHABUBNAGAR', 'KARBI ANGLONG WEST', 'SOUTH SALMARA-MANKACHAR', 'AGAR', 'PHERZAWL', 'NONEY', 'TENGNOUPAL', 'KAMJONG', 'KAKCHING', 'JIRIBAM', 'NORTH WEST', 'NEW DELHI', 'EAST', 'SOUTH WEST', 'WEST', 'SOUTH', 'NORTH', 'NORTH EAST', 'SOUTH EAST', 'CENTRAL', 'SHAHDARA', 'PASCHIM BARDDHAMAN', 'NARAYANPET', 'HNAHTHIAL', 'SAITUAL', 'KHAWZAWL', 'CHENGALPUTTU', 'MAYILADUTHURAI', 'GAURELLA PENDRA MARWAHI']

In [141]:
pd.DataFrame({
    "Climate_District": unmatched_climate
}).to_csv(
    "../data/processed/unmatched_climate_districts.csv",
    index=False
)

print("Saved unmatched district list.")

Saved unmatched district list.

In [142]:
!{__import__('sys').executable} -m pip install rapidfuzz

Requirement already satisfied: rapidfuzz in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (3.14.5)

In [143]:
from rapidfuzz import process, fuzz

In [144]:
agri_district_names = (
    agri_locations["District_clean"]
    .dropna()
    .unique()
    .tolist()
)

In [145]:
for district in unmatched_climate:

    matches = process.extract(
        district,
        agri_district_names,
        scorer=fuzz.token_sort_ratio,
        limit=3
    )

    print(
        f"\n{district}"
    )

    for match in matches:
        print(
            f"   {match[0]} → {match[1]}"
        )

NARSIMHAPUR
   NARSINGHPUR → 81.81818181818181
   JASHPUR → 66.66666666666667
   NARAYANPUR → 66.66666666666667

KHARGONE (WEST NIMAR)
   KHARGONE → 55.172413793103445
   EAST KAMENG → 50.0
   EAST GARO HILLS → 50.0

KHANDWA (EAST NIMAR)
   EAST GODAVARI → 54.54545454545454
   MEDINIPUR EAST → 52.94117647058824
   EAST JAINTIA HILLS → 52.63157894736843

LAHUL & SPITI
   LAHUL AND SPITI → 85.71428571428572
   LALITPUR → 47.61904761904761
   PAURI GARHWAL → 46.15384615384615

DATA NOT AVAILABLE
   SANT KABEER NAGAR → 51.42857142857142
   WEST JAINTIA HILLS → 50.0
   NORTH GARO HILLS → 47.05882352941176

BARAMULA
   BARAMULLA → 94.11764705882352
   BARNALA → 80.0
   BALRAMPUR → 70.58823529411764

SHUPIYAN
   SHOPIAN → 80.0
   SIANG → 61.53846153846154
   SIWAN → 61.53846153846154

RAJOURI
   RAJAURI → 85.71428571428572
   SURAJPUR → 66.66666666666667
   ALIRAJPUR → 62.5

LEH(LADAKH)
   LEH LADAKH → 57.14285714285714
   BHADRAK → 55.55555555555556
   LEPARADA → 52.63157894736843

PUNCH
   POONCH → 72.72727272727273
   PUNE → 66.66666666666667
   PANCHKULA → 57.14285714285714

BANDIPORE
   BANDIPORA → 88.88888888888889
   INDORE → 66.66666666666667
   RANIPET → 62.5

CHHOTA UDAIPUR
   CHHOTAUDEPUR → 84.61538461538461
   CHHATARPUR → 66.66666666666667
   CHANDRAPUR → 66.66666666666667

BATOD
   BALOD → 80.0
   BATHINDA → 61.53846153846154
   BOTAD → 60.0

ARAVALI
   ARAVALLI → 93.33333333333333
   AMRAVATI → 80.0
   KARAULI → 71.42857142857143

THE DANGS
   THE NILGIRIS → 66.66666666666667
   DANG → 61.53846153846154
   SOUTH ANDAMANS → 60.86956521739131

DADRA & NAGAR HAVELI
   DADRA AND NAGAR HAVELI → 90.47619047619048
   GANDHINAGAR → 58.06451612903225
   GAUTAM BUDDHA NAGAR → 56.41025641025641

VISAKHAPATNAM
   VISAKHAPATANAM → 96.2962962962963
   NAGAPATTINAM → 64.0
   VIZIANAGARAM → 56.00000000000001

SRI POTTI SRIRAMULU NELLORE
   SPSR NELLORE → 56.41025641025641
   BANGALORE RURAL → 47.61904761904761
   NORTH TRIPURA → 44.99999999999999

KADAPA(YSR)
   KADAPA → 70.58823529411764
   KENDRAPARA → 57.14285714285714
   KANDHAMAL → 50.0

SARAIKELA-KHARSAWAN
   SAHARSA → 53.84615384615385
   VISAKHAPATANAM → 48.484848484848484
   SRIKAKULAM → 48.275862068965516

PASHCHIMI SINGHBHUM
   EAST SINGHBUM → 68.75
   WEST SINGHBHUM → 54.54545454545454
   UDAM SINGH NAGAR → 51.42857142857142

PURBI SINGHBHUM
   EAST SINGHBUM → 64.28571428571428
   WEST SINGHBHUM → 62.06896551724138
   UDAM SINGH NAGAR → 58.06451612903225

KODARMA
   KODERMA → 85.71428571428572
   KORBA → 66.66666666666667
   KOREA → 66.66666666666667

SAHIBGANJ
   SAHEBGANJ → 88.88888888888889
   KARIMGANJ → 66.66666666666667
   KISHANGANJ → 63.1578947368421

PURBA CHAMPARAN
   PURBI CHAMPARAN → 93.33333333333333
   PURBA BARDHAMAN → 73.33333333333334
   PASHCHIM CHAMPARAN → 72.72727272727273

NORTH  & MIDDLE ANDAMAN
   NORTH AND MIDDLE ANDAMAN → 91.30434782608697
   SOUTH ANDAMANS → 61.111111111111114
   SIDDHARTH NAGAR → 54.054054054054056

SOUTH ANDAMAN
   SOUTH ANDAMANS → 96.2962962962963
   PARAGANAS SOUTH → 71.42857142857143
   SOUTH GOA → 63.63636363636363

MORIGAON
   MARIGAON → 87.5
   BONGAIGAON → 66.66666666666667
   GURGAON → 66.66666666666667

KARBI ANGLONG EAST
   KARBI ANGLONG → 83.87096774193549
   WEST KARBI ANGLONG → 72.22222222222221
   EAST GODAVARI → 51.61290322580645

KAMRUP METROPOLITAN
   KAMRUP METRO → 77.41935483870968
   KAMRUP → 48.0
   AMRELI → 48.0

PUDUCHERRY
   PONDICHERRY → 76.19047619047619
   ALIPURDUAR → 50.0
   KURUKSHETRA → 47.61904761904761

KANGPOKPI
   KATNI → 57.14285714285714
   PAKKE KESSANG → 54.54545454545454
   KARBI ANGLONG → 54.54545454545454

SIPAHIJULA
   SEPAHIJALA → 80.0
   PANCHKULA → 63.1578947368421
   SUPAUL → 62.5

UNOKOTI
   UNAKOTI → 85.71428571428572
   KHUNTI → 61.53846153846154
   KURNOOL → 57.14285714285714

RIBHOI
   RI BHOI → 61.53846153846154
   PARBHANI → 57.14285714285714
   PILIBHIT → 57.14285714285714

BEMETRA
   BEMETARA → 93.33333333333333
   BARMER → 61.53846153846154
   BARPETA → 57.14285714285714

GARIABAND
   GARIYABAND → 94.73684210526316
   FARIDABAD → 77.77777777777779
   GHAZIABAD → 77.77777777777779

KABEERDHAM
   KABIRDHAM → 84.21052631578947
   KANDHAMAL → 63.1578947368421
   WARDHA → 62.5

UTTAR BASTAR KANKER
   TARN TARAN → 62.06896551724138
   BANAS KANTHA → 58.06451612903225
   UTTARA KANNADA → 54.54545454545454

DAKSHIN BASTAR DANTEWADA
   DAKSHINA KANNADA → 65.0
   DINAJPUR DAKSHIN → 55.00000000000001
   DANTEWADA → 54.54545454545454

KORIYA
   KORBA → 72.72727272727273
   KOREA → 72.72727272727273
   KOHIMA → 66.66666666666667

UTTARKASHI
   CUTTACK → 58.82352941176471
   TENKASI → 58.82352941176471
   VARANASI → 55.55555555555556

GARHWAL
   GARHWA → 92.3076923076923
   ARWAL → 83.33333333333334
   PAURI GARHWAL → 70.0

HARDWAR
   HARIDWAR → 93.33333333333333
   HARDA → 83.33333333333334
   DHARWAD → 71.42857142857143

RUDRAPRAYAG
   KENDRAPARA → 57.14285714285714
   DARRANG → 55.55555555555556
   NUAPADA → 55.55555555555556

UDHAM SINGH NAGAR
   UDAM SINGH NAGAR → 96.96969696969697
   SIDDHARTH NAGAR → 68.75
   NARSINGHPUR → 64.28571428571428

LAKSHADWEEP
   KHANDWA → 55.55555555555556
   PALAKKAD → 52.63157894736843
   BAKSA → 50.0

DAKSHIN DINAJPUR
   DINAJPUR DAKSHIN → 100.0
   DAKSHINA KANNADA → 62.5
   KINNAUR → 60.86956521739131

KOLKATA
   KOTA → 72.72727272727273
   KOLAR → 66.66666666666667
   AKOLA → 66.66666666666667

SOUTH TWENTY FOUR PARGANAS
   PARAGANAS SOUTH → 68.29268292682926
   SOUTH WEST GARO HILLS → 55.319148936170215
   SOUTH WEST KHASI HILLS → 54.16666666666667

DARJILING
   DARJEELING → 84.21052631578947
   DARRANG → 62.5
   DANG → 61.53846153846154

UTTAR DINAJPUR
   DINAJPUR UTTAR → 100.0
   ALIPURDUAR → 58.33333333333333
   UTTARA KANNADA → 57.14285714285714

PURBA MEDINIPUR
   MEDINIPUR WEST → 68.96551724137932
   DINAJPUR UTTAR → 62.06896551724138
   MEDINIPUR EAST → 62.06896551724138

HAORA
   HARDA → 80.0
   CHATRA → 72.72727272727273
   ALMORA → 72.72727272727273

NORTH TWENTY FOUR PARGANAS
   PARAGANAS NORTH → 68.29268292682926
   PARAGANAS SOUTH → 48.78048780487805
   NORTH TRIPURA → 46.15384615384615

BARDDHAMAN
   PURBA BARDHAMAN → 72.0
   DAMAN → 66.66666666666667
   BARAN → 66.66666666666667

PURULIYA
   PURULIA → 93.33333333333333
   PURNIA → 71.42857142857143
   PURI → 66.66666666666667

KOCH BIHAR
   BHARUCH → 70.58823529411764
   BHADRAK → 58.82352941176471
   BAHRAICH → 55.55555555555556

PASCHIM MEDINIPUR
   MEDINIPUR WEST → 70.96774193548387
   PASHCHIM CHAMPARAN → 62.857142857142854
   PASCHIM BARDHAMAN → 58.82352941176471

HUGLI
   MUNGELI → 66.66666666666667
   HINGOLI → 66.66666666666667
   LUNGLEI → 66.66666666666667

FIROZPUR
   FIROZEPUR → 94.11764705882352
   MIRZAPUR → 75.0
   HAMIRPUR → 62.5

SAHIBZADA AJIT SINGH NAGAR
   SHAHID BHAGAT SINGH NAGAR → 78.43137254901961
   SANT RAVIDAS NAGAR → 59.09090909090908
   FATEHGARH SAHIB → 53.65853658536586

MYSORE
   MYSURU → 66.66666666666667
   MORENA → 66.66666666666667
   SEHORE → 66.66666666666667

YADGIR
   YADAGIRI → 85.71428571428572
   YADADRI → 61.53846153846154
   AGRA → 60.0

CHIKMAGALUR
   CHIKKAMAGALURU → 88.0
   BHAGALPUR → 70.0
   CHIKKABALLAPURA → 69.23076923076923

DAVANAGERE
   DAVANGERE → 94.73684210526316
   BHAVNAGAR → 63.1578947368421
   RAMANAGARA → 60.0

CHAMARAJANAGAR
   CHAMARAJANAGARA → 96.55172413793103
   RAMANAGARA → 66.66666666666667
   AMBEDKAR NAGAR → 64.28571428571428

GULBARGA
   GURGAON → 66.66666666666667
   BARGARH → 66.66666666666667
   GOALPARA → 62.5

BAGALKOT
   BAGALKOTE → 94.11764705882352
   BAGHPAT → 66.66666666666667
   BALAGHAT → 62.5

SHIMOGA
   SHIVAMOGGA → 82.35294117647058
   SHIMLA → 76.92307692307692
   MOGA → 72.72727272727273

BELLARY
   BALLARI → 71.42857142857143
   BAREILLY → 66.66666666666667
   BALLIA → 61.53846153846154

TUMKUR
   TUMAKURU → 85.71428571428572
   UDHAMPUR → 57.14285714285714
   TIRUPPUR → 57.14285714285714

BELGAUM
   BELAGAVI → 66.66666666666667
   BADGAM → 61.53846153846154
   KULGAM → 61.53846153846154

BANGALORE
   BAGALKOTE → 77.77777777777779
   BANGALORE RURAL → 75.0
   BHAGALPUR → 66.66666666666667

AHMADNAGAR
   AHMEDNAGAR → 90.0
   RAMANAGARA → 80.0
   JAMNAGAR → 77.77777777777779

GONDIYA
   GONDIA → 92.3076923076923
   GONDA → 83.33333333333334
   NALGONDA → 66.66666666666667

BULDANA
   BULDHANA → 93.33333333333333
   BUDAUN → 76.92307692307692
   BANKA → 66.66666666666667

BID
   BIDAR → 75.0
   BHIND → 75.0
   JIND → 57.14285714285714

SUBARNAPUR
   SURAJPUR → 77.77777777777779
   BALRAMPUR → 73.6842105263158
   BHARATPUR → 73.6842105263158

DEBAGARH
   BARGARH → 80.0
   DEOGARH → 80.0
   DIBRUGARH → 70.58823529411764

NABARANGAPUR
   NABARANGPUR → 95.65217391304348
   NARAYANPUR → 72.72727272727273
   SAHARANPUR → 72.72727272727273

BAUDH
   BOUDH → 80.0
   BHARUCH → 66.66666666666667
   BULDHANA → 61.53846153846154

JHUNJHUNUN
   JHUNJHUNU → 94.73684210526316
   JAUNPUR → 47.05882352941176
   SHAHJAHANPUR → 45.45454545454546

CHITTAURGARH
   CHITTORGARH → 86.95652173913044
   CHITRADURGA → 78.26086956521739
   CHANDIGARH → 63.63636363636363

JALOR
   JALORE → 90.9090909090909
   ALMORA → 72.72727272727273
   GWALIOR → 66.66666666666667

KANSHIRAM NAGAR
   KUSHI NAGAR → 76.92307692307692
   KANPUR NAGAR → 74.07407407407408
   KARIMNAGAR → 72.0

SAMLI
   SHAMLI → 90.9090909090909
   AMRELI → 72.72727272727273
   SANGLI → 72.72727272727273

SHRAWASTI
   SHRAVASTI → 88.88888888888889
   SAMASTIPUR → 63.1578947368421
   AMRAVATI → 58.82352941176471

MAHAMAYA NAGAR
   CHAMARAJANAGARA → 68.96551724137932
   RAMANAGARA → 66.66666666666667
   AHMEDNAGAR → 66.66666666666667

JYOTIBA PHULE NAGAR
   BANGALORE RURAL → 52.94117647058824
   JAMNAGAR → 51.85185185185186
   DIBANG VALLEY → 50.0

SANT RAVIDAS NAGAR (BHADOHI)
   SANT RAVIDAS NAGAR → 78.26086956521739
   SHAHID BHAGAT SINGH NAGAR → 60.37735849056604
   SANT KABEER NAGAR → 53.333333333333336

SIDDHARTHNAGAR
   SRINAGAR → 63.63636363636363
   SIDDHARTH NAGAR → 62.06896551724138
   VIRUDHUNAGAR → 61.53846153846154

SANT KABIR NAGAR
   SANT KABEER NAGAR → 90.9090909090909
   KANPUR NAGAR → 64.28571428571428
   KARIMNAGAR → 61.53846153846154

BARA BANKI
   BANKURA → 70.58823529411764
   BANKA → 66.66666666666667
   BHANDARA → 66.66666666666667

MAHRAJGANJ
   MAHARAJGANJ → 95.23809523809523
   MARIGAON → 66.66666666666667
   MAHENDRAGARH → 63.63636363636363

KUSHINAGAR
   KUSHI NAGAR → 95.23809523809523
   SRINAGAR → 77.77777777777779
   KARIMNAGAR → 70.0

VILUPPURAM
   VILLUPURAM → 90.0
   MALAPPURAM → 70.0
   TIRUPPUR → 66.66666666666667

KANCHEEPURAM
   KANCHIPURAM → 86.95652173913044
   MADHEPURA → 66.66666666666667
   MANCHERIAL → 63.63636363636363

THOOTHUKKUDI
   IDUKKI → 44.44444444444444
   THOUBAL → 42.10526315789473
   HOOGHLY → 42.10526315789473

DHAULPUR
   DHOLPUR → 80.0
   HAPUR → 76.92307692307692
   UDHAMPUR → 75.0

JANGAON
   JALGAON → 85.71428571428572
   JANGOAN → 85.71428571428572
   RAJNANDGAON → 77.77777777777779

HYDRABAD
   HYDERABAD → 94.11764705882352
   AHMADABAD → 70.58823529411764
   DHANBAD → 66.66666666666667

RANGAREDDY
   RANGAREDDI → 90.0
   SANGAREDDY → 90.0
   KAMAREDDY → 73.6842105263158

KOMARAM BHEEM
   KOMARAM BHEEM ASIFABAD → 74.28571428571429
   BEMETARA → 57.14285714285714
   KHAMMAM → 50.0

JAGTIAL
   JAGITIAL → 93.33333333333333
   PATIALA → 71.42857142857143
   DATIA → 66.66666666666667

RAJANNA SIRCILLA
   RAJANNA → 60.86956521739131
   SARAIKELA KHARSAWAN → 57.14285714285714
   RATNAGIRI → 56.00000000000001

WARANGAL (R)
   WARANGAL → 80.0
   DARBHANGA → 57.14285714285714
   KARNAL → 55.55555555555556

WARANGAL (U)
   WARANGAL → 80.0
   DARBHANGA → 57.14285714285714
   KARNAL → 55.55555555555556

YADADRI BHONGIRI
   CHARKI DADRI → 64.28571428571428
   BHADRADRI → 64.0
   RI BHOI → 60.86956521739131

MEDCHAL
   MEDAK → 66.66666666666667
   DHALAI → 61.53846153846154
   MANCHERIAL → 58.82352941176471

MAHABUBNAGAR
   MAHBUBNAGAR → 95.65217391304348
   MAHABUBABAD → 78.26086956521739
   BHAVNAGAR → 66.66666666666667

KARBI ANGLONG WEST
   WEST KARBI ANGLONG → 100.0
   KARBI ANGLONG → 83.87096774193549
   WEST GODAVARI → 64.51612903225806

SOUTH SALMARA-MANKACHAR
   PARAGANAS SOUTH → 63.1578947368421
   SOUTH SALMARA MANCACHAR → 60.86956521739131
   SOUTH ANDAMANS → 59.45945945945945

AGAR
   SAGAR → 88.88888888888889
   NAGAUR → 80.0
   AGRA → 75.0

PHERZAWL
   PALWAL → 57.14285714285714
   AIZAWL → 57.14285714285714
   PERAMBALUR → 55.55555555555556

NONEY
   NAGAON → 54.54545454545454
   INDORE → 54.54545454545454
   NANDED → 54.54545454545454

TENGNOUPAL
   THOUBAL → 58.82352941176471
   GOPALGANJ → 52.63157894736843
   DHENKANAL → 52.63157894736843

KAMJONG
   KALIMPONG → 75.0
   KANGRA → 61.53846153846154
   MON → 60.0

KAKCHING
   CHIRANG → 66.66666666666667
   MOKOKCHUNG → 66.66666666666667
   KALLAKURICHI → 60.0

JIRIBAM
   BIRBHUM → 57.14285714285714
   JAGITIAL → 53.333333333333336
   JHARGRAM → 53.333333333333336

NORTH WEST
   WEST GODAVARI → 60.86956521739131
   WEST DISTRICT → 60.86956521739131
   NORTH TRIPURA → 60.86956521739131

NEW DELHI
   RAE BARELI → 52.63157894736843
   DARJEELING → 52.63157894736843
   DELHI_TOTAL → 50.0

EAST
   MEWAT → 66.66666666666667
   REASI → 66.66666666666667
   DEWAS → 66.66666666666667

SOUTH WEST
   SOUTH WEST GARO HILLS → 64.51612903225806
   SOUTH WEST KHASI HILLS → 62.5
   WEST DISTRICT → 60.86956521739131

WEST
   WEST SIANG → 57.14285714285714
   WEST KAMENG → 53.333333333333336
   IMPHAL WEST → 53.333333333333336

SOUTH
   SOUTH GOA → 71.42857142857143
   SURAT → 60.0
   BOUDH → 60.0

NORTH
   NORTH GOA → 71.42857142857143
   NORTH TRIPURA → 55.55555555555556
   JORHAT → 54.54545454545454

NORTH EAST
   NORTH GOA → 73.6842105263158
   NORTH DISTRICT → 66.66666666666667
   NORTH GARO HILLS → 61.53846153846154

SOUTH EAST
   SOUTH GOA → 73.6842105263158
   SOUTH ANDAMANS → 66.66666666666667
   SOUTH DISTRICT → 66.66666666666667

CENTRAL
   CHATRA → 61.53846153846154
   NIRMAL → 61.53846153846154
   MANCHERIAL → 58.82352941176471

SHAHDARA
   SAHARSA → 80.0
   BHANDARA → 75.0
   SATARA → 71.42857142857143

PASCHIM BARDDHAMAN
   PASCHIM BARDHAMAN → 97.14285714285714
   PURBA BARDHAMAN → 72.72727272727273
   PASHCHIM CHAMPARAN → 72.22222222222221

NARAYANPET
   NARAYANAPET → 95.23809523809523
   NARAYANPUR → 80.0
   RANIPET → 70.58823529411764

HNAHTHIAL
   KAITHAL → 62.5
   PATIALA → 62.5
   HATHRAS → 62.5

SAITUAL
   KAITHAL → 71.42857142857143
   SATNA → 66.66666666666667
   SAIHA → 66.66666666666667

KHAWZAWL
   AIZAWL → 71.42857142857143
   KHANDWA → 66.66666666666667
   ARWAL → 61.53846153846154

CHENGALPUTTU
   CHENGALPATTU → 91.66666666666666
   BHAGALPUR → 57.14285714285714
   CHANDRAPUR → 54.54545454545454

MAYILADUTHURAI
   MADURAI → 66.66666666666667
   MATHURA → 66.66666666666667
   MADHEPURA → 60.86956521739131

GAURELLA PENDRA MARWAHI
   GAURELLA-PENDRA-MARWAHI → 65.21739130434783
   RAMANATHAPURAM → 48.64864864864865
   AGAR MALWA → 48.484848484848484

In [146]:
district_state_map = (
    agri_locations
    .groupby("District_clean")["State"]
    .agg(
        lambda x: sorted(set(x))
    )
    .to_dict()
)

In [147]:
unique_state_districts = {
    district: states[0]
    for district, states in district_state_map.items()
    if len(states) == 1
}

print(
    "District names with exactly one state:",
    len(unique_state_districts)
)

District names with exactly one state: 644

In [148]:
safe_exact = []

for district in exact_matches:

    if district in unique_state_districts:
        safe_exact.append(district)

print(
    "Safe exact district matches:",
    len(safe_exact)
)

Safe exact district matches: 543

In [149]:
ambiguous_exact = [
    d for d in exact_matches
    if d not in unique_state_districts
]

print(
    "Ambiguous exact matches:",
    len(ambiguous_exact)
)

print(ambiguous_exact[:100])

Ambiguous exact matches: 46
['BILASPUR', 'HAMIRPUR', 'KARGIL', 'DAMAN', 'DIU', 'HAZARIBAGH', 'CHATRA', 'GIRIDIH', 'LOHARDAGA', 'GODDA', 'PALAMU', 'DHANBAD', 'DUMKA', 'BOKARO', 'DEOGHAR', 'GUMLA', 'GARHWA', 'RANCHI', 'PAKUR', 'AURANGABAD', 'BASTAR', 'SURGUJA', 'BALRAMPUR', 'DURG', 'RAIPUR', 'DHAMTARI', 'KORBA', 'JASHPUR', 'MAHASAMUND', 'JANJGIR-CHAMPA', 'RAJNANDGAON', 'NAINITAL', 'DEHRADUN', 'ALMORA', 'CHAMPAWAT', 'TEHRI GARHWAL', 'BAGESHWAR', 'PITHORAGARH', 'CHAMOLI', 'PRATAPGARH', 'KARIMNAGAR', 'NIZAMABAD', 'MEDAK', 'NALGONDA', 'ADILABAD', 'KHAMMAM']

In [150]:
print("Safe exact:", len(safe_exact))
print("Ambiguous exact:", len(ambiguous_exact))
print(ambiguous_exact)

Safe exact: 543
Ambiguous exact: 46
['BILASPUR', 'HAMIRPUR', 'KARGIL', 'DAMAN', 'DIU', 'HAZARIBAGH', 'CHATRA', 'GIRIDIH', 'LOHARDAGA', 'GODDA', 'PALAMU', 'DHANBAD', 'DUMKA', 'BOKARO', 'DEOGHAR', 'GUMLA', 'GARHWA', 'RANCHI', 'PAKUR', 'AURANGABAD', 'BASTAR', 'SURGUJA', 'BALRAMPUR', 'DURG', 'RAIPUR', 'DHAMTARI', 'KORBA', 'JASHPUR', 'MAHASAMUND', 'JANJGIR-CHAMPA', 'RAJNANDGAON', 'NAINITAL', 'DEHRADUN', 'ALMORA', 'CHAMPAWAT', 'TEHRI GARHWAL', 'BAGESHWAR', 'PITHORAGARH', 'CHAMOLI', 'PRATAPGARH', 'KARIMNAGAR', 'NIZAMABAD', 'MEDAK', 'NALGONDA', 'ADILABAD', 'KHAMMAM']

In [151]:
climate_duplicates = (
    climate[
        climate["shapeName"].notna()
    ]
    .groupby("shapeName")
    .size()
    .sort_values(ascending=False)
)

print(
    climate_duplicates[
        climate_duplicates > 1
    ]
)

shapeName
Balrampur     2
Bijapur       2
Bilaspur      2
Aurangabad    2
Hamirpur      2
Pratapgarh    2
Raigarh       2
dtype: int64

In [152]:
climate_duplicates = (
    climate[
        climate["shapeName"].notna()
    ]
    .groupby("shapeName")
    .size()
    .sort_values(ascending=False)
)

duplicate_names = climate_duplicates[
    climate_duplicates > 1
].index.tolist()

print("Duplicate district names:")
print(climate_duplicates[climate_duplicates > 1])

Duplicate district names:
shapeName
Balrampur     2
Bijapur       2
Bilaspur      2
Aurangabad    2
Hamirpur      2
Pratapgarh    2
Raigarh       2
dtype: int64

In [153]:
for name in duplicate_names:

    print("\n====================")
    print(name)

    print(
        climate[
            climate["shapeName"] == name
        ][
            [
                "shapeName",
                "OBJECTID",
                "Shape_Area",
                "Shape_Length",
                "gqid",
                "shapeGroup",
                "shapeID",
                "shapeType"
            ]
        ].to_string(index=False)
    )

====================
Balrampur
shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
Balrampur     328.0    0.679424      7.294607 327.0        IND IND-ADM2-76128533B57252406      ADM2
Balrampur     579.0    0.295416      3.554175 578.0        IND IND-ADM2-76128533B94789404      ADM2

====================
Bijapur
shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
  Bijapur     333.0    0.783393      5.710165 332.0        IND IND-ADM2-76128533B64387799      ADM2
  Bijapur     428.0    0.882015      6.078660 427.0        IND IND-ADM2-76128533B86667053      ADM2

====================
Bilaspur
shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
 Bilaspur      58.0    0.110762      2.136653  57.0        IND  IND-ADM2-76128533B5474665      ADM2
 Bilaspur     321.0    0.372067      4.095616 320.0        IND IND-ADM2-76128533B27946096      ADM2

====================
Aurangabad
 shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
Aurangabad     166.0    0.310594      3.458405 165.0        IND IND-ADM2-76128533B30673598      ADM2
Aurangabad     471.0    0.884434      6.600379 470.0        IND IND-ADM2-76128533B64014086      ADM2

====================
Hamirpur
shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
 Hamirpur      62.0    0.106863      1.693800  61.0        IND IND-ADM2-76128533B69740248      ADM2
 Hamirpur     606.0    0.371676      4.581953 605.0        IND IND-ADM2-76128533B72971940      ADM2

====================
Pratapgarh
 shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
Pratapgarh     524.0    0.381591      3.963163 523.0        IND IND-ADM2-76128533B32371044      ADM2
Pratapgarh     605.0    0.334242      4.598835 604.0        IND IND-ADM2-76128533B52663243      ADM2

====================
Raigarh
shapeName  OBJECTID  Shape_Area  Shape_Length  gqid shapeGroup                    shapeID shapeType
  Raigarh     340.0    0.614081      5.991374 339.0        IND IND-ADM2-76128533B42793518      ADM2
  Raigarh     475.0    0.596007      6.378621 474.0        IND IND-ADM2-76128533B61308422      ADM2

In [154]:
ambiguous_mapping = []

for district in ambiguous_exact:

    states = (
        agri_locations[
            agri_locations["District_clean"] == district
        ]["State"]
        .unique()
        .tolist()
    )

    ambiguous_mapping.append({
        "Climate_District": district,
        "Possible_States": " | ".join(sorted(states))
    })

ambiguous_mapping = pd.DataFrame(
    ambiguous_mapping
)

print(
    ambiguous_mapping.to_string(index=False)
)

Climate_District                                  Possible_States
        BILASPUR Chhattisgarh | Himachal Pradesh | Madhya Pradesh
        HAMIRPUR                 Himachal Pradesh | Uttar Pradesh
          KARGIL                       Jammu and Kashmir | Ladakh
           DAMAN           Dadra and Nagar Haveli | Daman and Diu
             DIU           Dadra and Nagar Haveli | Daman and Diu
      HAZARIBAGH                                Bihar | Jharkhand
          CHATRA                                Bihar | Jharkhand
         GIRIDIH                                Bihar | Jharkhand
       LOHARDAGA                                Bihar | Jharkhand
           GODDA                                Bihar | Jharkhand
          PALAMU                                Bihar | Jharkhand
         DHANBAD                                Bihar | Jharkhand
           DUMKA                                Bihar | Jharkhand
          BOKARO                                Bihar | Jharkhand
         DEOGHAR                                Bihar | Jharkhand
           GUMLA                                Bihar | Jharkhand
          GARHWA                                Bihar | Jharkhand
          RANCHI                                Bihar | Jharkhand
           PAKUR                                Bihar | Jharkhand
      AURANGABAD                              Bihar | Maharashtra
          BASTAR                    Chhattisgarh | Madhya Pradesh
         SURGUJA                    Chhattisgarh | Madhya Pradesh
       BALRAMPUR                     Chhattisgarh | Uttar Pradesh
            DURG                    Chhattisgarh | Madhya Pradesh
          RAIPUR                    Chhattisgarh | Madhya Pradesh
        DHAMTARI                    Chhattisgarh | Madhya Pradesh
           KORBA                    Chhattisgarh | Madhya Pradesh
         JASHPUR                    Chhattisgarh | Madhya Pradesh
      MAHASAMUND                    Chhattisgarh | Madhya Pradesh
  JANJGIR-CHAMPA                    Chhattisgarh | Madhya Pradesh
     RAJNANDGAON                    Chhattisgarh | Madhya Pradesh
        NAINITAL                      Uttar Pradesh | Uttarakhand
        DEHRADUN                      Uttar Pradesh | Uttarakhand
          ALMORA                      Uttar Pradesh | Uttarakhand
       CHAMPAWAT                      Uttar Pradesh | Uttarakhand
   TEHRI GARHWAL                      Uttar Pradesh | Uttarakhand
       BAGESHWAR                      Uttar Pradesh | Uttarakhand
     PITHORAGARH                      Uttar Pradesh | Uttarakhand
         CHAMOLI                      Uttar Pradesh | Uttarakhand
      PRATAPGARH                        Rajasthan | Uttar Pradesh
      KARIMNAGAR                       Andhra Pradesh | Telangana
       NIZAMABAD                       Andhra Pradesh | Telangana
           MEDAK                       Andhra Pradesh | Telangana
        NALGONDA                       Andhra Pradesh | Telangana
        ADILABAD                       Andhra Pradesh | Telangana
         KHAMMAM                       Andhra Pradesh | Telangana

In [155]:
duplicate_climate = (
    climate[
        climate["shapeName"].notna()
    ]
    .groupby("shapeName")
    .filter(lambda x: len(x) > 1)
    [
        [
            "shapeName",
            "OBJECTID",
            "Shape_Area",
            "Shape_Length",
            "shapeID"
        ]
    ]
    .sort_values(["shapeName", "OBJECTID"])
)

print(duplicate_climate.to_string(index=False))

 shapeName  OBJECTID  Shape_Area  Shape_Length                    shapeID
Aurangabad     166.0    0.310594      3.458405 IND-ADM2-76128533B30673598
Aurangabad     471.0    0.884434      6.600379 IND-ADM2-76128533B64014086
 Balrampur     328.0    0.679424      7.294607 IND-ADM2-76128533B57252406
 Balrampur     579.0    0.295416      3.554175 IND-ADM2-76128533B94789404
   Bijapur     333.0    0.783393      5.710165 IND-ADM2-76128533B64387799
   Bijapur     428.0    0.882015      6.078660 IND-ADM2-76128533B86667053
  Bilaspur      58.0    0.110762      2.136653  IND-ADM2-76128533B5474665
  Bilaspur     321.0    0.372067      4.095616 IND-ADM2-76128533B27946096
  Hamirpur      62.0    0.106863      1.693800 IND-ADM2-76128533B69740248
  Hamirpur     606.0    0.371676      4.581953 IND-ADM2-76128533B72971940
Pratapgarh     524.0    0.381591      3.963163 IND-ADM2-76128533B32371044
Pratapgarh     605.0    0.334242      4.598835 IND-ADM2-76128533B52663243
   Raigarh     340.0    0.614081      5.991374 IND-ADM2-76128533B42793518
   Raigarh     475.0    0.596007      6.378621 IND-ADM2-76128533B61308422

In [156]:
import requests
import pandas as pd

url = "https://www.geoboundaries.org/api/current/gbOpen/IND/ADM2/"

response = requests.get(url, timeout=60)

print("HTTP status:", response.status_code)

gb = response.json()

print(gb.keys())

HTTP status: 200
dict_keys(['boundaryID', 'boundaryName', 'boundaryISO', 'boundaryYearRepresented', 'boundaryType', 'boundaryCanonical', 'boundarySource', 'boundaryLicense', 'licenseDetail', 'licenseSource', 'boundarySourceURL', 'sourceDataUpdateDate', 'buildDate', 'Continent', 'UNSDG-region', 'UNSDG-subregion', 'worldBankIncomeGroup', 'admUnitCount', 'meanVertices', 'minVertices', 'maxVertices', 'meanPerimeterLengthKM', 'minPerimeterLengthKM', 'maxPerimeterLengthKM', 'meanAreaSqKM', 'minAreaSqKM', 'maxAreaSqKM', 'staticDownloadLink', 'gjDownloadURL', 'tjDownloadURL', 'imagePreview', 'simplifiedGeometryGeoJSON'])

In [157]:
print("GeoJSON URL:")
print(gb["gjDownloadURL"])

GeoJSON URL:
https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IND/ADM2/geoBoundaries-IND-ADM2.geojson

In [158]:
geojson_url = gb["gjDownloadURL"]

r = requests.get(
    geojson_url,
    timeout=120
)

print("HTTP status:", r.status_code)

with open(
    "../data/raw/india_adm2.geojson",
    "wb"
) as f:
    f.write(r.content)

print("✅ ADM2 GeoJSON saved")

HTTP status: 200
✅ ADM2 GeoJSON saved

In [159]:
import geopandas as gpd

adm2 = gpd.read_file(
    "../data/raw/india_adm2.geojson"
)

print(adm2.shape)
print(adm2.columns.tolist())
print(adm2.head())

(735, 6)
['shapeName', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry']
     shapeName shapeISO                  shapeID shapeGroup shapeType  \
0   Ashoknagar           76128533B75548370501185        IND      ADM2
1       Raisen           76128533B57893545331548        IND      ADM2
2   Chhindwara           76128533B70646408240587        IND      ADM2
3        Betul           76128533B82559220423608        IND      ADM2
4  Hoshangabad           76128533B45314020251888        IND      ADM2

                                            geometry
0  POLYGON ((78.17491 24.84254, 78.17466 24.84194...
1  POLYGON ((77.38167 23.07004, 77.38094 23.0698,...
2  POLYGON ((79.23988 22.79135, 79.24 22.79172, 7...
3  POLYGON ((78.27229 22.39973, 78.27169 22.39897...
4  POLYGON ((78.03027 22.79953, 78.02986 22.79969...

In [160]:
import json

with open(
    "../data/raw/india_adm2.geojson",
    "r",
    encoding="utf-8"
) as f:
    adm2 = json.load(f)

print(adm2.keys())

dict_keys(['type', 'crs', 'features'])

In [161]:
print(
    "Number of features:",
    len(adm2["features"])
)

Number of features: 735

In [162]:
print(
    adm2["features"][0]["properties"]
)

{'shapeName': 'Ashoknagar', 'shapeISO': '', 'shapeID': '76128533B75548370501185', 'shapeGroup': 'IND', 'shapeType': 'ADM2'}

In [163]:
import requests

url = "https://www.geoboundaries.org/api/current/gbOpen/IND/ADM2/"

response = requests.get(url, timeout=60)

print("HTTP status:", response.status_code)

gb = response.json()

print(gb["gjDownloadURL"])

HTTP status: 200
https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IND/ADM2/geoBoundaries-IND-ADM2.geojson

In [164]:
geojson_url = gb["gjDownloadURL"]

r = requests.get(
    geojson_url,
    timeout=120
)

print("HTTP status:", r.status_code)

with open(
    "../data/raw/india_adm2.geojson",
    "wb"
) as f:
    f.write(r.content)

print("✅ ADM2 GeoJSON saved")

HTTP status: 200
✅ ADM2 GeoJSON saved

In [165]:
import json

with open(
    "../data/raw/india_adm2.geojson",
    "r",
    encoding="utf-8"
) as f:
    adm2 = json.load(f)

print("Top-level keys:")
print(adm2.keys())

print("\nNumber of features:")
print(len(adm2["features"]))

print("\nFirst feature properties:")
print(adm2["features"][0]["properties"])

Top-level keys:
dict_keys(['type', 'crs', 'features'])

Number of features:
735

First feature properties:
{'shapeName': 'Ashoknagar', 'shapeISO': '', 'shapeID': '76128533B75548370501185', 'shapeGroup': 'IND', 'shapeType': 'ADM2'}

In [176]:
climate_shape_ids = set(
    climate["shapeID"].dropna().astype(str)
)

geo_shape_ids = set()

for feature in adm2["features"]:
    props = feature.get("properties", {})
    
    for key, value in props.items():
        if value is not None:
            geo_shape_ids.add(str(value))

print(
    "Climate shape IDs:",
    len(climate_shape_ids)
)

print(
    "Matching IDs found in GeoJSON:",
    len(climate_shape_ids.intersection(geo_shape_ids))
)

Climate shape IDs: 735
Matching IDs found in GeoJSON: 0

In [177]:
climate_ids = (
    climate["shapeID"]
    .dropna()
    .astype(str)
    .str.replace(
        "IND-ADM2-",
        "",
        regex=False
    )
)

geo_ids = set()

for feature in adm2["features"]:
    props = feature.get("properties", {})

    if props.get("shapeID") is not None:
        geo_ids.add(
            str(props["shapeID"])
        )

print("Climate IDs:", len(climate_ids))
print("GeoJSON IDs:", len(geo_ids))

print(
    "Matching IDs:",
    len(set(climate_ids) & geo_ids)
)

Climate IDs: 735
GeoJSON IDs: 735
Matching IDs: 0

In [178]:
print("Climate:")
print(
    climate["shapeID"]
    .dropna()
    .head(10)
    .tolist()
)

print("\nGeoJSON:")
print([
    feature["properties"]["shapeID"]
    for feature in adm2["features"][:10]
])

Climate:
['IND-ADM2-76128533B24212364', 'IND-ADM2-76128533B65758206', 'IND-ADM2-76128533B77651862', 'IND-ADM2-76128533B14961718', 'IND-ADM2-76128533B94465219', 'IND-ADM2-76128533B31086418', 'IND-ADM2-76128533B49275069', 'IND-ADM2-76128533B87358694', 'IND-ADM2-76128533B55384561', 'IND-ADM2-76128533B34527011']

GeoJSON:
['76128533B75548370501185', '76128533B57893545331548', '76128533B70646408240587', '76128533B82559220423608', '76128533B45314020251888', '76128533B39959897010345', '76128533B27615708126939', '76128533B20683890392439', '76128533B81607600692021', '76128533B89286042589317']

In [179]:
safe_mapping = []

for district in safe_exact:

    state = unique_state_districts[district]

    safe_mapping.append({
        "Climate_District": district,
        "State": state,
        "Match_Method": "Exact + Unique State",
        "Confidence": "HIGH"
    })

safe_mapping = pd.DataFrame(safe_mapping)

print(safe_mapping.shape)
print(safe_mapping.head())

(543, 4)
  Climate_District           State          Match_Method Confidence
0       ASHOKNAGAR  Madhya Pradesh  Exact + Unique State       HIGH
1           RAISEN  Madhya Pradesh  Exact + Unique State       HIGH
2       CHHINDWARA  Madhya Pradesh  Exact + Unique State       HIGH
3            BETUL  Madhya Pradesh  Exact + Unique State       HIGH
4      HOSHANGABAD  Madhya Pradesh  Exact + Unique State       HIGH

In [180]:
current_mapping = final_locations[
    final_locations["Current_State"].notna() &
    final_locations["Current_District"].notna()
].copy()

print(
    "Historical/current mappings:",
    len(current_mapping)
)

print(
    current_mapping[
        [
            "State",
            "District",
            "Current_State",
            "Current_District"
        ]
    ].to_string(index=False)
)

Historical/current mappings: 63
                     State                  District               Current_State           Current_District
            Andhra Pradesh                 HYDERABAD                   Telangana                  Hyderabad
Andaman and Nicobar Island                  NICOBARS Andaman and Nicobar Islands                    Nicobar
Andaman and Nicobar Island            SOUTH ANDAMANS Andaman and Nicobar Islands              South Andaman
            Andhra Pradesh                  ADILABAD                   Telangana                   Adilabad
            Andhra Pradesh                KARIMNAGAR                   Telangana                 Karimnagar
            Andhra Pradesh                     MEDAK                   Telangana                      Medak
            Andhra Pradesh                  NALGONDA                   Telangana                   Nalgonda
            Andhra Pradesh                RANGAREDDI                   Telangana                 Rangareddy
            Andhra Pradesh            VISAKHAPATANAM              Andhra Pradesh              Visakhapatnam
            Andhra Pradesh                  WARANGAL                   Telangana                   Warangal
         Arunachal Pradesh                  LEPARADA           Arunachal Pradesh                  Lepa Rada
                     Assam   SOUTH SALMARA MANCACHAR                       Assam    South Salmara-Mankachar
                     Bihar                    BOKARO                   Jharkhand                     Bokaro
                     Bihar                   DHANBAD                   Jharkhand                    Dhanbad
                     Bihar                     DUMKA                   Jharkhand                      Dumka
                     Bihar             EAST SINGHBUM                   Jharkhand             East Singhbhum
                     Bihar                    GARHWA                   Jharkhand                     Garhwa
                     Bihar                   GIRIDIH                   Jharkhand                    Giridih
                     Bihar                     GODDA                   Jharkhand                      Godda
                     Bihar                     GUMLA                   Jharkhand                      Gumla
                     Bihar                HAZARIBAGH                   Jharkhand                 Hazaribagh
                     Bihar                   KODERMA                   Jharkhand                    Koderma
                     Bihar                 LOHARDAGA                   Jharkhand                  Lohardaga
                     Bihar                     PAKUR                   Jharkhand                      Pakur
                     Bihar                    PALAMU                   Jharkhand                     Palamu
                     Bihar            WEST SINGHBHUM                   Jharkhand             West Singhbhum
                     Delhi               DELHI_TOTAL                       Delhi                      Delhi
                   Gujarat              CHHOTAUDEPUR                     Gujarat             Chhota Udaipur
                   Gujarat                     DOHAD                     Gujarat                      Dahod
                   Haryana              CHARKI DADRI                     Haryana              Charkhi Dadri
          Himachal Pradesh           LAHUL AND SPITI            Himachal Pradesh           Lahaul and Spiti
         Jammu and Kashmir                LEH LADAKH                      Ladakh                        Leh
                 Jharkhand             EAST SINGHBUM                   Jharkhand             East Singhbhum
            Madhya Pradesh                    BASTAR                Chhattisgarh                     Bastar
            Madhya Pradesh                 DANTEWADA                Chhattisgarh                  Dantewada
            Madhya Pradesh                  DHAMTARI                Chhattisgarh                   Dhamtari
            Madhya Pradesh                      DURG                Chhattisgarh                       Durg
            Madhya Pradesh            JANJGIR-CHAMPA                Chhattisgarh             Janjgir-Champa
            Madhya Pradesh                   JASHPUR                Chhattisgarh                    Jashpur
            Madhya Pradesh                 KABIRDHAM                Chhattisgarh                  Kabirdham
            Madhya Pradesh                    KANKER                Chhattisgarh                     Kanker
            Madhya Pradesh                     KORBA                Chhattisgarh                      Korba
            Madhya Pradesh                MAHASAMUND                Chhattisgarh                 Mahasamund
            Madhya Pradesh               RAJNANDGAON                Chhattisgarh                Rajnandgaon
            Madhya Pradesh                   SURGUJA                Chhattisgarh                    Surguja
                    Punjab                 FIROZEPUR                      Punjab                   Firozpur
                    Punjab SHAHID BHAGAT SINGH NAGAR                      Punjab Shaheed Bhagat Singh Nagar
                 Telangana                RANGAREDDI                   Telangana                 Rangareddy
             Uttar Pradesh                    ALMORA                 Uttarakhand                     Almora
             Uttar Pradesh                   CHAMOLI                 Uttarakhand                    Chamoli
             Uttar Pradesh                 CHAMPAWAT                 Uttarakhand                  Champawat
             Uttar Pradesh               KUSHI NAGAR               Uttar Pradesh                 Kushinagar
             Uttar Pradesh             PAURI GARHWAL                 Uttarakhand              Pauri Garhwal
             Uttar Pradesh               PITHORAGARH                 Uttarakhand                Pithoragarh
             Uttar Pradesh              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
             Uttar Pradesh         SANT KABEER NAGAR               Uttar Pradesh           Sant Kabir Nagar
             Uttar Pradesh             TEHRI GARHWAL                 Uttarakhand              Tehri Garhwal
             Uttar Pradesh          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
               Uttarakhand          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand               UTTAR KASHI                 Uttarakhand                 Uttarkashi
               West Bengal           PARAGANAS NORTH                 West Bengal          North 24 Parganas
               West Bengal           PARAGANAS SOUTH                 West Bengal          South 24 Parganas

In [181]:
print(
    ambiguous_mapping.to_string(index=False)
)

Climate_District                                  Possible_States
        BILASPUR Chhattisgarh | Himachal Pradesh | Madhya Pradesh
        HAMIRPUR                 Himachal Pradesh | Uttar Pradesh
          KARGIL                       Jammu and Kashmir | Ladakh
           DAMAN           Dadra and Nagar Haveli | Daman and Diu
             DIU           Dadra and Nagar Haveli | Daman and Diu
      HAZARIBAGH                                Bihar | Jharkhand
          CHATRA                                Bihar | Jharkhand
         GIRIDIH                                Bihar | Jharkhand
       LOHARDAGA                                Bihar | Jharkhand
           GODDA                                Bihar | Jharkhand
          PALAMU                                Bihar | Jharkhand
         DHANBAD                                Bihar | Jharkhand
           DUMKA                                Bihar | Jharkhand
          BOKARO                                Bihar | Jharkhand
         DEOGHAR                                Bihar | Jharkhand
           GUMLA                                Bihar | Jharkhand
          GARHWA                                Bihar | Jharkhand
          RANCHI                                Bihar | Jharkhand
           PAKUR                                Bihar | Jharkhand
      AURANGABAD                              Bihar | Maharashtra
          BASTAR                    Chhattisgarh | Madhya Pradesh
         SURGUJA                    Chhattisgarh | Madhya Pradesh
       BALRAMPUR                     Chhattisgarh | Uttar Pradesh
            DURG                    Chhattisgarh | Madhya Pradesh
          RAIPUR                    Chhattisgarh | Madhya Pradesh
        DHAMTARI                    Chhattisgarh | Madhya Pradesh
           KORBA                    Chhattisgarh | Madhya Pradesh
         JASHPUR                    Chhattisgarh | Madhya Pradesh
      MAHASAMUND                    Chhattisgarh | Madhya Pradesh
  JANJGIR-CHAMPA                    Chhattisgarh | Madhya Pradesh
     RAJNANDGAON                    Chhattisgarh | Madhya Pradesh
        NAINITAL                      Uttar Pradesh | Uttarakhand
        DEHRADUN                      Uttar Pradesh | Uttarakhand
          ALMORA                      Uttar Pradesh | Uttarakhand
       CHAMPAWAT                      Uttar Pradesh | Uttarakhand
   TEHRI GARHWAL                      Uttar Pradesh | Uttarakhand
       BAGESHWAR                      Uttar Pradesh | Uttarakhand
     PITHORAGARH                      Uttar Pradesh | Uttarakhand
         CHAMOLI                      Uttar Pradesh | Uttarakhand
      PRATAPGARH                        Rajasthan | Uttar Pradesh
      KARIMNAGAR                       Andhra Pradesh | Telangana
       NIZAMABAD                       Andhra Pradesh | Telangana
           MEDAK                       Andhra Pradesh | Telangana
        NALGONDA                       Andhra Pradesh | Telangana
        ADILABAD                       Andhra Pradesh | Telangana
         KHAMMAM                       Andhra Pradesh | Telangana

In [182]:
ambiguous_mapping.to_csv(
    "../data/processed/ambiguous_climate_districts.csv",
    index=False
)

print("Saved:", len(ambiguous_mapping))

Saved: 46

In [183]:
current_mapping = final_locations[
    final_locations["Current_State"].notna() &
    final_locations["Current_District"].notna()
].copy()

print("Mappings available:", len(current_mapping))

print(
    current_mapping[
        ["State", "District", "Current_State", "Current_District"]
    ].to_string(index=False)
)

Mappings available: 63
                     State                  District               Current_State           Current_District
            Andhra Pradesh                 HYDERABAD                   Telangana                  Hyderabad
Andaman and Nicobar Island                  NICOBARS Andaman and Nicobar Islands                    Nicobar
Andaman and Nicobar Island            SOUTH ANDAMANS Andaman and Nicobar Islands              South Andaman
            Andhra Pradesh                  ADILABAD                   Telangana                   Adilabad
            Andhra Pradesh                KARIMNAGAR                   Telangana                 Karimnagar
            Andhra Pradesh                     MEDAK                   Telangana                      Medak
            Andhra Pradesh                  NALGONDA                   Telangana                   Nalgonda
            Andhra Pradesh                RANGAREDDI                   Telangana                 Rangareddy
            Andhra Pradesh            VISAKHAPATANAM              Andhra Pradesh              Visakhapatnam
            Andhra Pradesh                  WARANGAL                   Telangana                   Warangal
         Arunachal Pradesh                  LEPARADA           Arunachal Pradesh                  Lepa Rada
                     Assam   SOUTH SALMARA MANCACHAR                       Assam    South Salmara-Mankachar
                     Bihar                    BOKARO                   Jharkhand                     Bokaro
                     Bihar                   DHANBAD                   Jharkhand                    Dhanbad
                     Bihar                     DUMKA                   Jharkhand                      Dumka
                     Bihar             EAST SINGHBUM                   Jharkhand             East Singhbhum
                     Bihar                    GARHWA                   Jharkhand                     Garhwa
                     Bihar                   GIRIDIH                   Jharkhand                    Giridih
                     Bihar                     GODDA                   Jharkhand                      Godda
                     Bihar                     GUMLA                   Jharkhand                      Gumla
                     Bihar                HAZARIBAGH                   Jharkhand                 Hazaribagh
                     Bihar                   KODERMA                   Jharkhand                    Koderma
                     Bihar                 LOHARDAGA                   Jharkhand                  Lohardaga
                     Bihar                     PAKUR                   Jharkhand                      Pakur
                     Bihar                    PALAMU                   Jharkhand                     Palamu
                     Bihar            WEST SINGHBHUM                   Jharkhand             West Singhbhum
                     Delhi               DELHI_TOTAL                       Delhi                      Delhi
                   Gujarat              CHHOTAUDEPUR                     Gujarat             Chhota Udaipur
                   Gujarat                     DOHAD                     Gujarat                      Dahod
                   Haryana              CHARKI DADRI                     Haryana              Charkhi Dadri
          Himachal Pradesh           LAHUL AND SPITI            Himachal Pradesh           Lahaul and Spiti
         Jammu and Kashmir                LEH LADAKH                      Ladakh                        Leh
                 Jharkhand             EAST SINGHBUM                   Jharkhand             East Singhbhum
            Madhya Pradesh                    BASTAR                Chhattisgarh                     Bastar
            Madhya Pradesh                 DANTEWADA                Chhattisgarh                  Dantewada
            Madhya Pradesh                  DHAMTARI                Chhattisgarh                   Dhamtari
            Madhya Pradesh                      DURG                Chhattisgarh                       Durg
            Madhya Pradesh            JANJGIR-CHAMPA                Chhattisgarh             Janjgir-Champa
            Madhya Pradesh                   JASHPUR                Chhattisgarh                    Jashpur
            Madhya Pradesh                 KABIRDHAM                Chhattisgarh                  Kabirdham
            Madhya Pradesh                    KANKER                Chhattisgarh                     Kanker
            Madhya Pradesh                     KORBA                Chhattisgarh                      Korba
            Madhya Pradesh                MAHASAMUND                Chhattisgarh                 Mahasamund
            Madhya Pradesh               RAJNANDGAON                Chhattisgarh                Rajnandgaon
            Madhya Pradesh                   SURGUJA                Chhattisgarh                    Surguja
                    Punjab                 FIROZEPUR                      Punjab                   Firozpur
                    Punjab SHAHID BHAGAT SINGH NAGAR                      Punjab Shaheed Bhagat Singh Nagar
                 Telangana                RANGAREDDI                   Telangana                 Rangareddy
             Uttar Pradesh                    ALMORA                 Uttarakhand                     Almora
             Uttar Pradesh                   CHAMOLI                 Uttarakhand                    Chamoli
             Uttar Pradesh                 CHAMPAWAT                 Uttarakhand                  Champawat
             Uttar Pradesh               KUSHI NAGAR               Uttar Pradesh                 Kushinagar
             Uttar Pradesh             PAURI GARHWAL                 Uttarakhand              Pauri Garhwal
             Uttar Pradesh               PITHORAGARH                 Uttarakhand                Pithoragarh
             Uttar Pradesh              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
             Uttar Pradesh         SANT KABEER NAGAR               Uttar Pradesh           Sant Kabir Nagar
             Uttar Pradesh             TEHRI GARHWAL                 Uttarakhand              Tehri Garhwal
             Uttar Pradesh          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
               Uttarakhand          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand               UTTAR KASHI                 Uttarakhand                 Uttarkashi
               West Bengal           PARAGANAS NORTH                 West Bengal          North 24 Parganas
               West Bengal           PARAGANAS SOUTH                 West Bengal          South 24 Parganas

In [184]:
historical_mapping = current_mapping[
    [
        "State",
        "District",
        "Current_State",
        "Current_District"
    ]
].copy()

historical_mapping = historical_mapping.drop_duplicates()

historical_mapping["District_clean"] = (
    historical_mapping["District"]
    .astype(str)
    .str.upper()
    .str.strip()
)

historical_mapping["Current_District_clean"] = (
    historical_mapping["Current_District"]
    .astype(str)
    .str.upper()
    .str.strip()
)

print("Mapping rows:", len(historical_mapping))

print(
    historical_mapping[
        [
            "State",
            "District",
            "Current_State",
            "Current_District"
        ]
    ].to_string(index=False)
)

Mapping rows: 63
                     State                  District               Current_State           Current_District
            Andhra Pradesh                 HYDERABAD                   Telangana                  Hyderabad
Andaman and Nicobar Island                  NICOBARS Andaman and Nicobar Islands                    Nicobar
Andaman and Nicobar Island            SOUTH ANDAMANS Andaman and Nicobar Islands              South Andaman
            Andhra Pradesh                  ADILABAD                   Telangana                   Adilabad
            Andhra Pradesh                KARIMNAGAR                   Telangana                 Karimnagar
            Andhra Pradesh                     MEDAK                   Telangana                      Medak
            Andhra Pradesh                  NALGONDA                   Telangana                   Nalgonda
            Andhra Pradesh                RANGAREDDI                   Telangana                 Rangareddy
            Andhra Pradesh            VISAKHAPATANAM              Andhra Pradesh              Visakhapatnam
            Andhra Pradesh                  WARANGAL                   Telangana                   Warangal
         Arunachal Pradesh                  LEPARADA           Arunachal Pradesh                  Lepa Rada
                     Assam   SOUTH SALMARA MANCACHAR                       Assam    South Salmara-Mankachar
                     Bihar                    BOKARO                   Jharkhand                     Bokaro
                     Bihar                   DHANBAD                   Jharkhand                    Dhanbad
                     Bihar                     DUMKA                   Jharkhand                      Dumka
                     Bihar             EAST SINGHBUM                   Jharkhand             East Singhbhum
                     Bihar                    GARHWA                   Jharkhand                     Garhwa
                     Bihar                   GIRIDIH                   Jharkhand                    Giridih
                     Bihar                     GODDA                   Jharkhand                      Godda
                     Bihar                     GUMLA                   Jharkhand                      Gumla
                     Bihar                HAZARIBAGH                   Jharkhand                 Hazaribagh
                     Bihar                   KODERMA                   Jharkhand                    Koderma
                     Bihar                 LOHARDAGA                   Jharkhand                  Lohardaga
                     Bihar                     PAKUR                   Jharkhand                      Pakur
                     Bihar                    PALAMU                   Jharkhand                     Palamu
                     Bihar            WEST SINGHBHUM                   Jharkhand             West Singhbhum
                     Delhi               DELHI_TOTAL                       Delhi                      Delhi
                   Gujarat              CHHOTAUDEPUR                     Gujarat             Chhota Udaipur
                   Gujarat                     DOHAD                     Gujarat                      Dahod
                   Haryana              CHARKI DADRI                     Haryana              Charkhi Dadri
          Himachal Pradesh           LAHUL AND SPITI            Himachal Pradesh           Lahaul and Spiti
         Jammu and Kashmir                LEH LADAKH                      Ladakh                        Leh
                 Jharkhand             EAST SINGHBUM                   Jharkhand             East Singhbhum
            Madhya Pradesh                    BASTAR                Chhattisgarh                     Bastar
            Madhya Pradesh                 DANTEWADA                Chhattisgarh                  Dantewada
            Madhya Pradesh                  DHAMTARI                Chhattisgarh                   Dhamtari
            Madhya Pradesh                      DURG                Chhattisgarh                       Durg
            Madhya Pradesh            JANJGIR-CHAMPA                Chhattisgarh             Janjgir-Champa
            Madhya Pradesh                   JASHPUR                Chhattisgarh                    Jashpur
            Madhya Pradesh                 KABIRDHAM                Chhattisgarh                  Kabirdham
            Madhya Pradesh                    KANKER                Chhattisgarh                     Kanker
            Madhya Pradesh                     KORBA                Chhattisgarh                      Korba
            Madhya Pradesh                MAHASAMUND                Chhattisgarh                 Mahasamund
            Madhya Pradesh               RAJNANDGAON                Chhattisgarh                Rajnandgaon
            Madhya Pradesh                   SURGUJA                Chhattisgarh                    Surguja
                    Punjab                 FIROZEPUR                      Punjab                   Firozpur
                    Punjab SHAHID BHAGAT SINGH NAGAR                      Punjab Shaheed Bhagat Singh Nagar
                 Telangana                RANGAREDDI                   Telangana                 Rangareddy
             Uttar Pradesh                    ALMORA                 Uttarakhand                     Almora
             Uttar Pradesh                   CHAMOLI                 Uttarakhand                    Chamoli
             Uttar Pradesh                 CHAMPAWAT                 Uttarakhand                  Champawat
             Uttar Pradesh               KUSHI NAGAR               Uttar Pradesh                 Kushinagar
             Uttar Pradesh             PAURI GARHWAL                 Uttarakhand              Pauri Garhwal
             Uttar Pradesh               PITHORAGARH                 Uttarakhand                Pithoragarh
             Uttar Pradesh              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
             Uttar Pradesh         SANT KABEER NAGAR               Uttar Pradesh           Sant Kabir Nagar
             Uttar Pradesh             TEHRI GARHWAL                 Uttarakhand              Tehri Garhwal
             Uttar Pradesh          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand              RUDRA PRAYAG                 Uttarakhand                Rudraprayag
               Uttarakhand          UDAM SINGH NAGAR                 Uttarakhand          Udham Singh Nagar
               Uttarakhand               UTTAR KASHI                 Uttarakhand                 Uttarkashi
               West Bengal           PARAGANAS NORTH                 West Bengal          North 24 Parganas
               West Bengal           PARAGANAS SOUTH                 West Bengal          South 24 Parganas

In [185]:
climate_name_map = climate[
    climate["shapeName"].notna()
][
    ["shapeName", "shapeID"]
].copy()

climate_name_map["Climate_District_clean"] = (
    climate_name_map["shapeName"]
    .astype(str)
    .str.upper()
    .str.strip()
)

print(
    "Climate districts:",
    len(climate_name_map)
)

Climate districts: 735

In [186]:
historical_climate_matches = historical_mapping.merge(
    climate_name_map,
    left_on="Current_District_clean",
    right_on="Climate_District_clean",
    how="inner"
)

print(
    "Historical/current → climate matches:",
    len(historical_climate_matches)
)

Historical/current → climate matches: 43

In [187]:
print(
    historical_climate_matches[
        [
            "State",
            "District",
            "Current_State",
            "Current_District",
            "shapeName"
        ]
    ].to_string(index=False)
)

                     State                District               Current_State        Current_District               shapeName
Andaman and Nicobar Island          SOUTH ANDAMANS Andaman and Nicobar Islands           South Andaman           South Andaman
            Andhra Pradesh                ADILABAD                   Telangana                Adilabad                Adilabad
            Andhra Pradesh              KARIMNAGAR                   Telangana              Karimnagar              Karimnagar
            Andhra Pradesh                   MEDAK                   Telangana                   Medak                   Medak
            Andhra Pradesh                NALGONDA                   Telangana                Nalgonda                Nalgonda
            Andhra Pradesh              RANGAREDDI                   Telangana              Rangareddy              Rangareddy
            Andhra Pradesh          VISAKHAPATANAM              Andhra Pradesh           Visakhapatnam           Visakhapatnam
                     Assam SOUTH SALMARA MANCACHAR                       Assam South Salmara-Mankachar South Salmara-Mankachar
                     Bihar                  BOKARO                   Jharkhand                  Bokaro                  Bokaro
                     Bihar                 DHANBAD                   Jharkhand                 Dhanbad                 Dhanbad
                     Bihar                   DUMKA                   Jharkhand                   Dumka                   Dumka
                     Bihar                  GARHWA                   Jharkhand                  Garhwa                  Garhwa
                     Bihar                 GIRIDIH                   Jharkhand                 Giridih                 Giridih
                     Bihar                   GODDA                   Jharkhand                   Godda                   Godda
                     Bihar                   GUMLA                   Jharkhand                   Gumla                   Gumla
                     Bihar              HAZARIBAGH                   Jharkhand              Hazaribagh              Hazaribagh
                     Bihar               LOHARDAGA                   Jharkhand               Lohardaga               Lohardaga
                     Bihar                   PAKUR                   Jharkhand                   Pakur                   Pakur
                     Bihar                  PALAMU                   Jharkhand                  Palamu                  Palamu
                   Gujarat            CHHOTAUDEPUR                     Gujarat          Chhota Udaipur          Chhota Udaipur
            Madhya Pradesh                  BASTAR                Chhattisgarh                  Bastar                  Bastar
            Madhya Pradesh                DHAMTARI                Chhattisgarh                Dhamtari                Dhamtari
            Madhya Pradesh                    DURG                Chhattisgarh                    Durg                    Durg
            Madhya Pradesh          JANJGIR-CHAMPA                Chhattisgarh          Janjgir-Champa          Janjgir-Champa
            Madhya Pradesh                 JASHPUR                Chhattisgarh                 Jashpur                 Jashpur
            Madhya Pradesh                   KORBA                Chhattisgarh                   Korba                   Korba
            Madhya Pradesh              MAHASAMUND                Chhattisgarh              Mahasamund              Mahasamund
            Madhya Pradesh             RAJNANDGAON                Chhattisgarh             Rajnandgaon             Rajnandgaon
            Madhya Pradesh                 SURGUJA                Chhattisgarh                 Surguja                 Surguja
                    Punjab               FIROZEPUR                      Punjab                Firozpur                Firozpur
                 Telangana              RANGAREDDI                   Telangana              Rangareddy              Rangareddy
             Uttar Pradesh                  ALMORA                 Uttarakhand                  Almora                  Almora
             Uttar Pradesh                 CHAMOLI                 Uttarakhand                 Chamoli                 Chamoli
             Uttar Pradesh               CHAMPAWAT                 Uttarakhand               Champawat               Champawat
             Uttar Pradesh             KUSHI NAGAR               Uttar Pradesh              Kushinagar              Kushinagar
             Uttar Pradesh             PITHORAGARH                 Uttarakhand             Pithoragarh             Pithoragarh
             Uttar Pradesh            RUDRA PRAYAG                 Uttarakhand             Rudraprayag             Rudraprayag
             Uttar Pradesh       SANT KABEER NAGAR               Uttar Pradesh        Sant Kabir Nagar        Sant Kabir Nagar
             Uttar Pradesh           TEHRI GARHWAL                 Uttarakhand           Tehri Garhwal           Tehri Garhwal
             Uttar Pradesh        UDAM SINGH NAGAR                 Uttarakhand       Udham Singh Nagar       Udham Singh Nagar
               Uttarakhand            RUDRA PRAYAG                 Uttarakhand             Rudraprayag             Rudraprayag
               Uttarakhand        UDAM SINGH NAGAR                 Uttarakhand       Udham Singh Nagar       Udham Singh Nagar
               Uttarakhand             UTTAR KASHI                 Uttarakhand              Uttarkashi              Uttarkashi

In [188]:
ambiguous_with_history = ambiguous_mapping.merge(
    historical_climate_matches[
        ["District", "Current_District"]
    ].drop_duplicates(),
    left_on="Climate_District",
    right_on="Current_District",
    how="inner"
)

print(
    "Ambiguous climate districts resolved through historical mapping:",
    len(ambiguous_with_history)
)

Ambiguous climate districts resolved through historical mapping: 0

In [189]:
print("Historical/current → climate matches:", len(historical_climate_matches))
print("Ambiguous resolved:", len(ambiguous_with_history))

Historical/current → climate matches: 43
Ambiguous resolved: 0

In [190]:
historical_climate_matches = historical_mapping.merge(
    climate_name_map,
    left_on="Current_District_clean",
    right_on="Climate_District_clean",
    how="inner"
)

print(
    "Historical/current → climate matches:",
    len(historical_climate_matches)
)

Historical/current → climate matches: 43

In [191]:
ambiguous_mapping["Climate_District_clean"] = (
    ambiguous_mapping["Climate_District"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [192]:
ambiguous_resolved = ambiguous_mapping.merge(
    historical_climate_matches[
        [
            "District",
            "Current_District",
            "Current_District_clean"
        ]
    ].drop_duplicates(),
    left_on="Climate_District_clean",
    right_on="Current_District_clean",
    how="inner"
)

print(
    "Ambiguous districts resolved:",
    ambiguous_resolved["Climate_District"].nunique()
)

print(
    ambiguous_resolved[
        [
            "Climate_District",
            "District",
            "Current_District"
        ]
    ].to_string(index=False)
    
)

Ambiguous districts resolved: 29
Climate_District       District Current_District
      HAZARIBAGH     HAZARIBAGH       Hazaribagh
         GIRIDIH        GIRIDIH          Giridih
       LOHARDAGA      LOHARDAGA        Lohardaga
           GODDA          GODDA            Godda
          PALAMU         PALAMU           Palamu
         DHANBAD        DHANBAD          Dhanbad
           DUMKA          DUMKA            Dumka
          BOKARO         BOKARO           Bokaro
           GUMLA          GUMLA            Gumla
          GARHWA         GARHWA           Garhwa
           PAKUR          PAKUR            Pakur
          BASTAR         BASTAR           Bastar
         SURGUJA        SURGUJA          Surguja
            DURG           DURG             Durg
        DHAMTARI       DHAMTARI         Dhamtari
           KORBA          KORBA            Korba
         JASHPUR        JASHPUR          Jashpur
      MAHASAMUND     MAHASAMUND       Mahasamund
  JANJGIR-CHAMPA JANJGIR-CHAMPA   Janjgir-Champa
     RAJNANDGAON    RAJNANDGAON      Rajnandgaon
          ALMORA         ALMORA           Almora
       CHAMPAWAT      CHAMPAWAT        Champawat
   TEHRI GARHWAL  TEHRI GARHWAL    Tehri Garhwal
     PITHORAGARH    PITHORAGARH      Pithoragarh
         CHAMOLI        CHAMOLI          Chamoli
      KARIMNAGAR     KARIMNAGAR       Karimnagar
           MEDAK          MEDAK            Medak
        NALGONDA       NALGONDA         Nalgonda
        ADILABAD       ADILABAD         Adilabad

In [193]:
resolved_names = set(
    ambiguous_resolved["Climate_District_clean"]
)

still_ambiguous = ambiguous_mapping[
    ~ambiguous_mapping["Climate_District_clean"].isin(
        resolved_names
    )
].copy()

print(
    "Still ambiguous:",
    len(still_ambiguous)
)

print(
    still_ambiguous[
        ["Climate_District", "Possible_States"]
    ].to_string(index=False)
)

Still ambiguous: 17
Climate_District                                  Possible_States
        BILASPUR Chhattisgarh | Himachal Pradesh | Madhya Pradesh
        HAMIRPUR                 Himachal Pradesh | Uttar Pradesh
          KARGIL                       Jammu and Kashmir | Ladakh
           DAMAN           Dadra and Nagar Haveli | Daman and Diu
             DIU           Dadra and Nagar Haveli | Daman and Diu
          CHATRA                                Bihar | Jharkhand
         DEOGHAR                                Bihar | Jharkhand
          RANCHI                                Bihar | Jharkhand
      AURANGABAD                              Bihar | Maharashtra
       BALRAMPUR                     Chhattisgarh | Uttar Pradesh
          RAIPUR                    Chhattisgarh | Madhya Pradesh
        NAINITAL                      Uttar Pradesh | Uttarakhand
        DEHRADUN                      Uttar Pradesh | Uttarakhand
       BAGESHWAR                      Uttar Pradesh | Uttarakhand
      PRATAPGARH                        Rajasthan | Uttar Pradesh
       NIZAMABAD                       Andhra Pradesh | Telangana
         KHAMMAM                       Andhra Pradesh | Telangana

In [194]:
historical_climate_matches.to_csv(
    "../data/processed/historical_climate_matches.csv",
    index=False
)

ambiguous_resolved.to_csv(
    "../data/processed/ambiguous_climate_resolved.csv",
    index=False
)

still_ambiguous.to_csv(
    "../data/processed/still_ambiguous_climate.csv",
    index=False
)

print("✅ Mapping progress saved")

✅ Mapping progress saved

In [195]:
print("Historical matches:", len(historical_climate_matches))
print("Ambiguous resolved:", ambiguous_resolved["Climate_District"].nunique())
print("Still ambiguous:", len(still_ambiguous))

Historical matches: 43
Ambiguous resolved: 29
Still ambiguous: 17

In [196]:
print(
    still_ambiguous[
        ["Climate_District", "Possible_States"]
    ].to_string(index=False)
)

Climate_District                                  Possible_States
        BILASPUR Chhattisgarh | Himachal Pradesh | Madhya Pradesh
        HAMIRPUR                 Himachal Pradesh | Uttar Pradesh
          KARGIL                       Jammu and Kashmir | Ladakh
           DAMAN           Dadra and Nagar Haveli | Daman and Diu
             DIU           Dadra and Nagar Haveli | Daman and Diu
          CHATRA                                Bihar | Jharkhand
         DEOGHAR                                Bihar | Jharkhand
          RANCHI                                Bihar | Jharkhand
      AURANGABAD                              Bihar | Maharashtra
       BALRAMPUR                     Chhattisgarh | Uttar Pradesh
          RAIPUR                    Chhattisgarh | Madhya Pradesh
        NAINITAL                      Uttar Pradesh | Uttarakhand
        DEHRADUN                      Uttar Pradesh | Uttarakhand
       BAGESHWAR                      Uttar Pradesh | Uttarakhand
      PRATAPGARH                        Rajasthan | Uttar Pradesh
       NIZAMABAD                       Andhra Pradesh | Telangana
         KHAMMAM                       Andhra Pradesh | Telangana

In [197]:
print(
    still_ambiguous["Climate_District"].tolist()
)

['BILASPUR', 'HAMIRPUR', 'KARGIL', 'DAMAN', 'DIU', 'CHATRA', 'DEOGHAR', 'RANCHI', 'AURANGABAD', 'BALRAMPUR', 'RAIPUR', 'NAINITAL', 'DEHRADUN', 'BAGESHWAR', 'PRATAPGARH', 'NIZAMABAD', 'KHAMMAM']

In [198]:
!{__import__('sys').executable} -m pip install geopandas

Requirement already satisfied: geopandas in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (1.1.4)
Requirement already satisfied: numpy>=1.24 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (2.5.2)
Requirement already satisfied: pyogrio>=0.7.2 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (0.13.0)
Requirement already satisfied: packaging in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (26.3)
Requirement already satisfied: pandas>=2.0.0 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (3.0.5)
Requirement already satisfied: pyproj>=3.5.0 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (3.7.2)
Requirement already satisfied: shapely>=2.0.0 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from geopandas) (2.1.2)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from pandas>=2.0.0->geopandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from pandas>=2.0.0->geopandas) (2026.3)
Requirement already satisfied: certifi in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from pyogrio>=0.7.2->geopandas) (2026.7.22)
Requirement already satisfied: six>=1.5 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from python-dateutil>=2.8.2->pandas>=2.0.0->geopandas) (1.17.0)

In [199]:
import geopandas as gpd

print("GeoPandas:", gpd.__version__)

GeoPandas: 1.1.4

In [200]:
adm2 = gpd.read_file(
    "../data/raw/india_adm2.geojson"
)

print("ADM2 shape:", adm2.shape)
print(adm2.columns.tolist())

ADM2 shape: (735, 6)
['shapeName', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry']

In [201]:
import requests

url = "https://www.geoboundaries.org/api/current/gbOpen/IND/ADM1/"

response = requests.get(
    url,
    timeout=60
)

print("HTTP status:", response.status_code)

adm1_info = response.json()

print(adm1_info["gjDownloadURL"])

HTTP status: 200
https://github.com/wmgeolab/geoBoundaries/raw/9469f09/releaseData/gbOpen/IND/ADM1/geoBoundaries-IND-ADM1.geojson

In [202]:
adm1_url = adm1_info["gjDownloadURL"]

r = requests.get(
    adm1_url,
    timeout=120
)

with open(
    "../data/raw/india_adm1.geojson",
    "wb"
) as f:
    f.write(r.content)

print("✅ ADM1 downloaded")

✅ ADM1 downloaded

In [203]:
adm1 = gpd.read_file(
    "../data/raw/india_adm1.geojson"
)

print("ADM1 shape:", adm1.shape)
print(adm1.columns.tolist())

ADM1 shape: (36, 6)
['shapeName', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry']

In [205]:
climate_geo = climate[
    climate["shapeName"].notna()
].copy()

climate_geo["name_clean"] = (
    climate_geo["shapeName"]
    .astype(str)
    .str.upper()
    .str.strip()
)

adm2["name_clean"] = (
    adm2["shapeName"]
    .astype(str)
    .str.upper()
    .str.strip()
)

In [206]:
print(
    climate_geo[
        [
            "shapeName",
            "Shape_Area",
            "Shape_Length"
        ]
    ].head()
)

print(
    adm2[
        [
            "shapeName"
        ]
    ].head()
)

     shapeName  Shape_Area  Shape_Length
0   Ashoknagar    0.421664      3.925451
1       Raisen    0.748785      7.526803
2   Chhindwara    1.033143      7.724320
3        Betul    0.875211      6.736091
4  Hoshangabad    0.586915      5.467521
     shapeName
0   Ashoknagar
1       Raisen
2   Chhindwara
3        Betul
4  Hoshangabad

In [207]:
adm2_points = adm2.copy()

adm2_points["geometry"] = (
    adm2_points.geometry.centroid
)

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22200\1410426075.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'centroid' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  adm2_points.geometry.centroid

In [208]:
adm2_with_state = gpd.sjoin(
    adm2_points,
    adm1,
    how="left",
    predicate="within"
)

In [209]:
print(
    adm2_with_state[
        [
            "shapeName_left",
            "shapeName_right"
        ]
    ].head(20)
)

   shapeName_left shapeName_right
0      Ashoknagar  Madhya Pradesh
1          Raisen  Madhya Pradesh
2      Chhindwara  Madhya Pradesh
3           Betul  Madhya Pradesh
4     Hoshangabad  Madhya Pradesh
5          Sehore  Madhya Pradesh
6        Jabalpur  Madhya Pradesh
7     Narsimhapur  Madhya Pradesh
8           Panna  Madhya Pradesh
9          Ujjain  Madhya Pradesh
10           Rewa  Madhya Pradesh
11        Dindori  Madhya Pradesh
12       Balaghat  Madhya Pradesh
13        Barwani  Madhya Pradesh
14          Satna  Madhya Pradesh
15     Chhatarpur  Madhya Pradesh
16         Indore  Madhya Pradesh
17         Ratlam  Madhya Pradesh
18          Harda  Madhya Pradesh
19          Sagar  Madhya Pradesh

In [210]:
print(adm2_with_state.columns.tolist())

['shapeName_left', 'shapeISO_left', 'shapeID_left', 'shapeGroup_left', 'shapeType_left', 'geometry', 'name_clean', 'index_right', 'shapeName_right', 'shapeISO_right', 'shapeID_right', 'shapeGroup_right', 'shapeType_right']

In [211]:
print("GeoPandas:", gpd.__version__)
print("ADM2:", adm2.shape)
print("ADM1:", adm1.shape)
print(adm1.columns.tolist())

GeoPandas: 1.1.4
ADM2: (735, 7)
ADM1: (36, 6)
['shapeName', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry']

In [212]:
print("ADM1 CRS:", adm1.crs)
print("ADM2 CRS:", adm2.crs)

ADM1 CRS: EPSG:4326
ADM2 CRS: EPSG:4326

In [213]:
adm2 = adm2.to_crs(adm1.crs)

In [214]:
adm2_points = adm2.copy()

adm2_points["geometry"] = (
    adm2.geometry.representative_point()
)

adm2_with_state = gpd.sjoin(
    adm2_points,
    adm1[["shapeName", "geometry"]],
    how="left",
    predicate="within",
    lsuffix="_district",
    rsuffix="_state"
)

print(adm2_with_state.shape)
print(adm2_with_state.columns.tolist())

(735, 9)
['shapeName__district', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry', 'name_clean', 'index__state', 'shapeName__state']

In [215]:
print(
    adm2_with_state[
        [
            "shapeName_district",
            "shapeName_state"
        ]
    ].head(20).to_string(index=False)
)

KeyError: "None of [Index(['shapeName_district', 'shapeName_state'], dtype='str')] are in the [columns]"

In [216]:
print(adm2_with_state.columns.tolist())

['shapeName__district', 'shapeISO', 'shapeID', 'shapeGroup', 'shapeType', 'geometry', 'name_clean', 'index__state', 'shapeName__state']

In [217]:
print(
    adm2_with_state.head(3).to_string()
)

  shapeName__district shapeISO                  shapeID shapeGroup shapeType                   geometry  name_clean  index__state shapeName__state
0          Ashoknagar           76128533B75548370501185        IND      ADM2  POINT (77.87515 24.61438)  ASHOKNAGAR          27.0   Madhya Pradesh
1              Raisen           76128533B57893545331548        IND      ADM2  POINT (78.17483 23.26514)      RAISEN          27.0   Madhya Pradesh
2          Chhindwara           76128533B70646408240587        IND      ADM2  POINT (78.81087 22.13888)  CHHINDWARA          27.0   Madhya Pradesh

In [218]:
print(
    [col for col in adm2_with_state.columns
     if "shapeName" in col]
)

['shapeName__district', 'shapeName__state']

In [219]:
climate_geo_reference = adm2_with_state[
    [
        "shapeName__district",
        "shapeID",
        "shapeName__state"
    ]
].copy()

climate_geo_reference.columns = [
    "Climate_District",
    "Climate_ShapeID",
    "Climate_State"
]

climate_geo_reference["Climate_District_clean"] = (
    climate_geo_reference["Climate_District"]
    .astype(str)
    .str.upper()
    .str.strip()
)

print(
    climate_geo_reference.head(10).to_string(index=False)
)

Climate_District         Climate_ShapeID  Climate_State Climate_District_clean
      Ashoknagar 76128533B75548370501185 Madhya Pradesh             ASHOKNAGAR
          Raisen 76128533B57893545331548 Madhya Pradesh                 RAISEN
      Chhindwara 76128533B70646408240587 Madhya Pradesh             CHHINDWARA
           Betul 76128533B82559220423608 Madhya Pradesh                  BETUL
     Hoshangabad 76128533B45314020251888 Madhya Pradesh            HOSHANGABAD
          Sehore 76128533B39959897010345 Madhya Pradesh                 SEHORE
        Jabalpur 76128533B27615708126939 Madhya Pradesh               JABALPUR
     Narsimhapur 76128533B20683890392439 Madhya Pradesh            NARSIMHAPUR
           Panna 76128533B81607600692021 Madhya Pradesh                  PANNA
          Ujjain 76128533B89286042589317 Madhya Pradesh                 UJJAIN

In [220]:
missing_state = climate_geo_reference[
    climate_geo_reference["Climate_State"].isna()
]

print(
    "Climate districts without state:",
    len(missing_state)
)

Climate districts without state: 1

In [221]:
remaining_17_geo = climate_geo_reference[
    climate_geo_reference["Climate_District_clean"].isin(
        still_ambiguous["Climate_District_clean"]
    )
].copy()

print(
    remaining_17_geo[
        [
            "Climate_District",
            "Climate_State"
        ]
    ].to_string(index=False)
)

Climate_District                            Climate_State
        Bilaspur                         Himāchal Pradesh
        Hamirpur                         Himāchal Pradesh
          Kargil                                   Ladākh
           Daman Dādra and Nagar Haveli and Damān and Diu
             Diu Dādra and Nagar Haveli and Damān and Diu
          Chatra                                Jhārkhand
         Deoghar                                Jhārkhand
          Ranchi                                Jhārkhand
      Aurangabad                                    Bihār
        Bilaspur                             Chhattīsgarh
       Balrampur                             Chhattīsgarh
          Raipur                             Chhattīsgarh
        Nainital                              Uttarākhand
        Dehradun                              Uttarākhand
       Bageshwar                              Uttarākhand
      Aurangabad                              Mahārāshtra
      Pratapgarh                                Rājasthān
       Balrampur                            Uttar Pradesh
      Pratapgarh                            Uttar Pradesh
        Hamirpur                            Uttar Pradesh
       Nizamabad                                Telangāna
         Khammam                                Telangāna

In [222]:
print(
    "Total climate geographic records:",
    len(climate_geo_reference)
)

print(
    "Unique climate district names:",
    climate_geo_reference[
        "Climate_District_clean"
    ].nunique()
)

print(
    "Unique climate State-District pairs:",
    climate_geo_reference[
        ["Climate_State", "Climate_District_clean"]
    ].drop_duplicates().shape[0]
)

Total climate geographic records: 735
Unique climate district names: 728
Unique climate State-District pairs: 735

In [223]:
print(
    remaining_17_geo[
        ["Climate_District", "Climate_State"]
    ].to_string(index=False)
    
)

Climate_District                            Climate_State
        Bilaspur                         Himāchal Pradesh
        Hamirpur                         Himāchal Pradesh
          Kargil                                   Ladākh
           Daman Dādra and Nagar Haveli and Damān and Diu
             Diu Dādra and Nagar Haveli and Damān and Diu
          Chatra                                Jhārkhand
         Deoghar                                Jhārkhand
          Ranchi                                Jhārkhand
      Aurangabad                                    Bihār
        Bilaspur                             Chhattīsgarh
       Balrampur                             Chhattīsgarh
          Raipur                             Chhattīsgarh
        Nainital                              Uttarākhand
        Dehradun                              Uttarākhand
       Bageshwar                              Uttarākhand
      Aurangabad                              Mahārāshtra
      Pratapgarh                                Rājasthān
       Balrampur                            Uttar Pradesh
      Pratapgarh                            Uttar Pradesh
        Hamirpur                            Uttar Pradesh
       Nizamabad                                Telangāna
         Khammam                                Telangāna

In [224]:
import unicodedata

def normalize_text(value):
    if pd.isna(value):
        return None

    value = str(value)

    value = unicodedata.normalize(
        "NFKD",
        value
    )

    value = "".join(
        c for c in value
        if not unicodedata.combining(c)
    )

    return (
        value
        .upper()
        .strip()
    )

In [225]:
climate_geo_reference["Climate_State_clean"] = (
    climate_geo_reference["Climate_State"]
    .apply(normalize_text)
)

climate_geo_reference["Climate_District_clean"] = (
    climate_geo_reference["Climate_District"]
    .apply(normalize_text)
)

In [226]:
print(
    sorted(
        climate_geo_reference[
            "Climate_State_clean"
        ].dropna().unique()
    )
)

['ANDAMAN AND NICOBAR ISLANDS', 'ANDHRA PRADESH', 'ARUNACHAL PRADESH', 'ASSAM', 'BIHAR', 'CHANDIGARH', 'CHHATTISGARH', 'DADRA AND NAGAR HAVELI AND DAMAN AND DIU', 'DELHI', 'GOA', 'GUJARAT', 'HARYANA', 'HIMACHAL PRADESH', 'JAMMU AND KASHMIR', 'JHARKHAND', 'KARNATAKA', 'KERALA', 'LADAKH', 'MADHYA PRADESH', 'MAHARASHTRA', 'MANIPUR', 'MEGHALAYA', 'MIZORAM', 'NAGALAND', 'ODISHA', 'PUDUCHERRY', 'PUNJAB', 'RAJASTHAN', 'SIKKIM', 'TAMIL NADU', 'TELANGANA', 'TRIPURA', 'UTTAR PRADESH', 'UTTARAKHAND', 'WEST BENGAL']

In [227]:
climate_with_state = climate.merge(
    climate_geo_reference[
        [
            "Climate_District",
            "Climate_ShapeID",
            "Climate_State_clean"
        ]
    ],
    left_on="shapeID",
    right_on="Climate_ShapeID",
    how="left"
)

In [228]:
print(
    climate_with_state[
        [
            "shapeName",
            "Climate_State_clean"
        ]
    ].head(20)
)

      shapeName Climate_State_clean
0    Ashoknagar                 NaN
1        Raisen                 NaN
2    Chhindwara                 NaN
3         Betul                 NaN
4   Hoshangabad                 NaN
5        Sehore                 NaN
6      Jabalpur                 NaN
7   Narsimhapur                 NaN
8         Panna                 NaN
9        Ujjain                 NaN
10         Rewa                 NaN
11      Dindori                 NaN
12     Balaghat                 NaN
13      Barwani                 NaN
14        Satna                 NaN
15   Chhatarpur                 NaN
16       Indore                 NaN
17       Ratlam                 NaN
18        Harda                 NaN
19        Sagar                 NaN

In [229]:
print(
    "Missing climate states:",
    climate_with_state[
        "Climate_State_clean"
    ].isna().sum()
)

Missing climate states: 735

In [230]:
print(
    "Climate geo reference rows:",
    len(climate_geo_reference)
)

print(
    "Unique State-District:",
    climate_geo_reference[
        ["Climate_State_clean", "Climate_District_clean"]
    ].drop_duplicates().shape[0]
)

Climate geo reference rows: 735
Unique State-District: 735

In [231]:
print(
    climate_geo_reference[
        climate_geo_reference[
            "Climate_District_clean"
        ].isin([
            "BILASPUR",
            "HAMIRPUR",
            "AURANGABAD",
            "BALRAMPUR",
            "PRATAPGARH"
        ])
    ][
        [
            "Climate_District",
            "Climate_State_clean"
        ]
    ].to_string(index=False)
)

Climate_District Climate_State_clean
        Bilaspur    HIMACHAL PRADESH
        Hamirpur    HIMACHAL PRADESH
      Aurangabad               BIHAR
        Bilaspur        CHHATTISGARH
       Balrampur        CHHATTISGARH
      Aurangabad         MAHARASHTRA
      Pratapgarh           RAJASTHAN
       Balrampur       UTTAR PRADESH
      Pratapgarh       UTTAR PRADESH
        Hamirpur       UTTAR PRADESH

In [232]:
# Count how many geographic records exist for each district name
name_counts = (
    climate_geo_reference
    .groupby("Climate_District_clean")
    .size()
)

unique_climate_names = name_counts[
    name_counts == 1
].index

print(
    "Unique climate district names:",
    len(unique_climate_names)
)

Unique climate district names: 721

In [233]:
unique_geo_mapping = (
    climate_geo_reference[
        climate_geo_reference["Climate_District_clean"]
        .isin(unique_climate_names)
    ][
        [
            "Climate_District_clean",
            "Climate_State_clean"
        ]
    ]
    .drop_duplicates()
)

print(
    "Unique geographic mappings:",
    len(unique_geo_mapping)
)

print(
    unique_geo_mapping.head(20).to_string(index=False)
)

Unique geographic mappings: 721
Climate_District_clean Climate_State_clean
            ASHOKNAGAR      MADHYA PRADESH
                RAISEN      MADHYA PRADESH
            CHHINDWARA      MADHYA PRADESH
                 BETUL      MADHYA PRADESH
           HOSHANGABAD      MADHYA PRADESH
                SEHORE      MADHYA PRADESH
              JABALPUR      MADHYA PRADESH
           NARSIMHAPUR      MADHYA PRADESH
                 PANNA      MADHYA PRADESH
                UJJAIN      MADHYA PRADESH
                  REWA      MADHYA PRADESH
               DINDORI      MADHYA PRADESH
              BALAGHAT      MADHYA PRADESH
               BARWANI      MADHYA PRADESH
                 SATNA      MADHYA PRADESH
            CHHATARPUR      MADHYA PRADESH
                INDORE      MADHYA PRADESH
                RATLAM      MADHYA PRADESH
                 HARDA      MADHYA PRADESH
                 SAGAR      MADHYA PRADESH

In [234]:
climate_with_state = climate.copy()

climate_with_state["Climate_District_clean"] = (
    climate_with_state["shapeName"]
    .astype(str)
    .apply(normalize_text)
)

climate_with_state = climate_with_state.merge(
    unique_geo_mapping,
    on="Climate_District_clean",
    how="left"
)

print(
    "Climate records:",
    len(climate_with_state)
)

print(
    "States assigned:",
    climate_with_state["Climate_State_clean"].notna().sum()
)

print(
    "States still missing:",
    climate_with_state["Climate_State_clean"].isna().sum()
)

Climate records: 735
States assigned: 720
States still missing: 15

In [235]:
remaining_climate_names = (
    climate_with_state[
        climate_with_state["Climate_State_clean"].isna()
    ]["Climate_District_clean"]
    .unique()
)

print(
    "Remaining district names:",
    len(remaining_climate_names)
)

print(
    remaining_climate_names.tolist()
)

Remaining district names: 8
['BILASPUR', 'HAMIRPUR', 'AURANGABAD', 'BALRAMPUR', 'BIJAPUR', 'RAIGARH', 'LAKSHADWEEP', 'PRATAPGARH']

In [236]:
adm2_area = adm2.copy()

adm2_area["Geo_Area"] = (
    adm2_area.geometry.area
)

adm2_area["Climate_District_clean"] = (
    adm2_area["shapeName"]
    .astype(str)
    .apply(normalize_text)
)

print(
    adm2_area[
        [
            "shapeName",
            "Climate_District_clean",
            "Geo_Area"
        ]
    ].head()
)

     shapeName Climate_District_clean  Geo_Area
0   Ashoknagar             ASHOKNAGAR  0.421664
1       Raisen                 RAISEN  0.748785
2   Chhindwara             CHHINDWARA  1.033143
3        Betul                  BETUL  0.875211
4  Hoshangabad            HOSHANGABAD  0.586915

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22200\4167474384.py:4: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  adm2_area.geometry.area

In [237]:
adm2_projected = adm2.to_crs(
    adm2.estimate_utm_crs()
)

adm2_projected["Geo_Area"] = (
    adm2_projected.geometry.area
)

In [238]:
# Climate data
climate_with_state = climate.copy()

climate_with_state["Climate_District_clean"] = (
    climate_with_state["shapeName"]
    .astype(str)
    .apply(normalize_text)
)

# Geographic reference
geo_mapping = climate_geo_reference[
    [
        "Climate_District_clean",
        "Climate_State_clean"
    ]
].drop_duplicates()

# Count how many states each climate district name has
geo_name_counts = (
    geo_mapping
    .groupby("Climate_District_clean")
    ["Climate_State_clean"]
    .nunique()
)

# Names that have exactly one state
unique_geo_names = geo_name_counts[
    geo_name_counts == 1
].index

unique_geo_mapping = geo_mapping[
    geo_mapping["Climate_District_clean"]
    .isin(unique_geo_names)
].copy()

print(
    "Unique geographic district names:",
    len(unique_geo_mapping)
)

Unique geographic district names: 720

In [239]:
climate_unique = climate_with_state.merge(
    unique_geo_mapping,
    on="Climate_District_clean",
    how="left"
)

print(
    "Total climate records:",
    len(climate_unique)
)

print(
    "State assigned:",
    climate_unique["Climate_State_clean"].notna().sum()
)

print(
    "State missing:",
    climate_unique["Climate_State_clean"].isna().sum()
)

Total climate records: 735
State assigned: 720
State missing: 15

In [240]:
remaining_climate = climate_unique[
    climate_unique["Climate_State_clean"].isna()
].copy()

print(
    "Remaining climate records:",
    len(remaining_climate)
)

print(
    remaining_climate[
        ["shapeName", "shapeID", "Shape_Area", "Shape_Length"]
    ].to_string(index=False)
)

Remaining climate records: 15
  shapeName                    shapeID  Shape_Area  Shape_Length
   Bilaspur  IND-ADM2-76128533B5474665    0.110762      2.136653
   Hamirpur IND-ADM2-76128533B69740248    0.106863      1.693800
 Aurangabad IND-ADM2-76128533B30673598    0.310594      3.458405
   Bilaspur IND-ADM2-76128533B27946096    0.372067      4.095616
  Balrampur IND-ADM2-76128533B57252406    0.679424      7.294607
    Bijapur IND-ADM2-76128533B64387799    0.783393      5.710165
    Raigarh IND-ADM2-76128533B42793518    0.614081      5.991374
Lakshadweep  IND-ADM2-76128533B3096104    0.017468      2.503271
    Bijapur IND-ADM2-76128533B86667053    0.882015      6.078660
 Aurangabad IND-ADM2-76128533B64014086    0.884434      6.600379
    Raigarh IND-ADM2-76128533B61308422    0.596007      6.378621
 Pratapgarh IND-ADM2-76128533B32371044    0.381591      3.963163
  Balrampur IND-ADM2-76128533B94789404    0.295416      3.554175
 Pratapgarh IND-ADM2-76128533B52663243    0.334242      4.598835
   Hamirpur IND-ADM2-76128533B72971940    0.371676      4.581953

In [241]:
adm2_projected = adm2.to_crs(
    adm2.estimate_utm_crs()
)

In [242]:
print(adm2_with_state[
    adm2_with_state["shapeName__district"].isin([
        "Bilaspur",
        "Hamirpur",
        "Aurangabad",
        "Balrampur",
        "Bijapur",
        "Raigarh",
        "Pratapgarh"
    ])
][[
    "shapeName__district",
    "shapeName__state"
]].to_string(index=False))

shapeName__district shapeName__state
           Bilaspur Himāchal Pradesh
           Hamirpur Himāchal Pradesh
         Aurangabad            Bihār
           Bilaspur     Chhattīsgarh
          Balrampur     Chhattīsgarh
            Bijapur     Chhattīsgarh
            Raigarh     Chhattīsgarh
            Bijapur        Karnātaka
         Aurangabad      Mahārāshtra
            Raigarh      Mahārāshtra
         Pratapgarh        Rājasthān
          Balrampur    Uttar Pradesh
         Pratapgarh    Uttar Pradesh
           Hamirpur    Uttar Pradesh

In [243]:
# ============================================
# RESOLVE THE 15 REMAINING CLIMATE RECORDS
# ============================================

# Calculate area directly in the same CRS
# as the downloaded ADM2 GeoJSON.
# We are using it only as a matching fingerprint,
# not as a real-world area measurement.

adm2_area = adm2.copy()

adm2_area["Geo_Area"] = (
    adm2_area.geometry.area
)

adm2_area["Climate_District_clean"] = (
    adm2_area["shapeName"]
    .astype(str)
    .apply(normalize_text)
)

# State from our spatial join
geo_state = adm2_with_state[
    [
        "shapeName__district",
        "shapeName__state"
    ]
].copy()

geo_state["Climate_District_clean"] = (
    geo_state["shapeName__district"]
    .astype(str)
    .apply(normalize_text)
)

geo_state["Climate_State_clean"] = (
    geo_state["shapeName__state"]
    .astype(str)
    .apply(normalize_text)
)

# Add state to ADM2 area table
adm2_area = adm2_area.merge(
    geo_state[
        [
            "Climate_District_clean",
            "Climate_State_clean"
        ]
    ].drop_duplicates(),
    on="Climate_District_clean",
    how="left"
)

# --------------------------------------------
# Get the 15 climate records still missing state
# --------------------------------------------

remaining_climate = climate_unique[
    climate_unique["Climate_State_clean"].isna()
].copy()

remaining_climate["Shape_Area"] = pd.to_numeric(
    remaining_climate["Shape_Area"],
    errors="coerce"
)

# --------------------------------------------
# Match by district name + closest polygon area
# --------------------------------------------

resolved_remaining = []

for _, row in remaining_climate.iterrows():

    candidates = adm2_area[
        adm2_area["Climate_District_clean"]
        == row["Climate_District_clean"]
    ].copy()

    if candidates.empty:
        print(
            "NO CANDIDATE:",
            row["shapeName"]
        )
        continue

    candidates["area_difference"] = (
        abs(
            candidates["Geo_Area"]
            - row["Shape_Area"]
        )
    )

    best = candidates.loc[
        candidates["area_difference"].idxmin()
    ]

    resolved_remaining.append({
        "shapeID": row["shapeID"],
        "shapeName": row["shapeName"],
        "Climate_State_clean": best[
            "Climate_State_clean"
        ],
        "area_difference": best[
            "area_difference"
        ]
    })

resolved_remaining = pd.DataFrame(
    resolved_remaining
)

print(
    resolved_remaining.to_string(index=False)
)

print(
    "\nResolved:",
    len(resolved_remaining)
)

print(
    "Maximum area difference:",
    resolved_remaining[
        "area_difference"
    ].max()
)

                   shapeID   shapeName Climate_State_clean  area_difference
 IND-ADM2-76128533B5474665    Bilaspur    HIMACHAL PRADESH     1.500004e-10
IND-ADM2-76128533B69740248    Hamirpur    HIMACHAL PRADESH     4.975000e-07
IND-ADM2-76128533B30673598  Aurangabad               BIHAR     1.326500e-07
IND-ADM2-76128533B27946096    Bilaspur    HIMACHAL PRADESH     4.683911e-07
IND-ADM2-76128533B57252406   Balrampur        CHHATTISGARH     2.813000e-07
IND-ADM2-76128533B64387799     Bijapur        CHHATTISGARH     1.003507e-07
IND-ADM2-76128533B42793518     Raigarh        CHHATTISGARH     3.414000e-07
 IND-ADM2-76128533B3096104 Lakshadweep                 NaN     2.877500e-07
IND-ADM2-76128533B86667053     Bijapur        CHHATTISGARH     3.413000e-07
IND-ADM2-76128533B64014086  Aurangabad               BIHAR     1.445000e-08
IND-ADM2-76128533B61308422     Raigarh        CHHATTISGARH     3.498500e-07
IND-ADM2-76128533B32371044  Pratapgarh           RAJASTHAN     2.534000e-07
IND-ADM2-76128533B94789404   Balrampur        CHHATTISGARH     1.218000e-07
IND-ADM2-76128533B52663243  Pratapgarh           RAJASTHAN     1.742500e-07
IND-ADM2-76128533B72971940    Hamirpur    HIMACHAL PRADESH     2.104000e-07

Resolved: 15
Maximum area difference: 4.974999999879381e-07

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22200\178881524.py:13: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  adm2_area.geometry.area

In [244]:
print(
    resolved_remaining[
        [
            "shapeName",
            "Climate_State_clean",
            "area_difference"
        ]
    ].to_string(index=False)
)

  shapeName Climate_State_clean  area_difference
   Bilaspur    HIMACHAL PRADESH     1.500004e-10
   Hamirpur    HIMACHAL PRADESH     4.975000e-07
 Aurangabad               BIHAR     1.326500e-07
   Bilaspur    HIMACHAL PRADESH     4.683911e-07
  Balrampur        CHHATTISGARH     2.813000e-07
    Bijapur        CHHATTISGARH     1.003507e-07
    Raigarh        CHHATTISGARH     3.414000e-07
Lakshadweep                 NaN     2.877500e-07
    Bijapur        CHHATTISGARH     3.413000e-07
 Aurangabad               BIHAR     1.445000e-08
    Raigarh        CHHATTISGARH     3.498500e-07
 Pratapgarh           RAJASTHAN     2.534000e-07
  Balrampur        CHHATTISGARH     1.218000e-07
 Pratapgarh           RAJASTHAN     1.742500e-07
   Hamirpur    HIMACHAL PRADESH     2.104000e-07

In [245]:
# ============================================
# CORRECT POLYGON-LEVEL STATE + AREA REFERENCE
# ============================================

# Start from the original ADM2 polygons
polygon_ref = adm2.copy()

# Add the state found by the spatial join.
# IMPORTANT: use the row index, NOT district name.
polygon_ref["Climate_State_clean"] = (
    adm2_with_state["shapeName__state"]
    .apply(normalize_text)
)

polygon_ref["Climate_District_clean"] = (
    polygon_ref["shapeName"]
    .apply(normalize_text)
)

# Area in the same CRS used by the climate dataset
polygon_ref["Geo_Area"] = (
    polygon_ref.geometry.area
)

print(
    polygon_ref[
        [
            "shapeName",
            "Climate_State_clean",
            "Geo_Area"
        ]
    ].head(10).to_string(index=False)
)

  shapeName Climate_State_clean  Geo_Area
 Ashoknagar      MADHYA PRADESH  0.421664
     Raisen      MADHYA PRADESH  0.748785
 Chhindwara      MADHYA PRADESH  1.033143
      Betul      MADHYA PRADESH  0.875211
Hoshangabad      MADHYA PRADESH  0.586915
     Sehore      MADHYA PRADESH  0.577388
   Jabalpur      MADHYA PRADESH  0.449053
Narsimhapur      MADHYA PRADESH  0.451603
      Panna      MADHYA PRADESH  0.626586
     Ujjain      MADHYA PRADESH  0.542898

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_22200\1489632749.py:22: UserWarning: Geometry is in a geographic CRS. Results from 'area' are likely incorrect. Use 'GeoSeries.to_crs()' to re-project geometries to a projected CRS before this operation.

  polygon_ref.geometry.area

In [246]:
remaining_climate = climate_unique[
    climate_unique["Climate_State_clean"].isna()
].copy()

remaining_climate["Shape_Area"] = pd.to_numeric(
    remaining_climate["Shape_Area"],
    errors="coerce"
)

resolved_remaining = []

for _, row in remaining_climate.iterrows():

    candidates = polygon_ref[
        polygon_ref["Climate_District_clean"]
        == row["Climate_District_clean"]
    ].copy()

    if candidates.empty:
        print("NO CANDIDATE:", row["shapeName"])
        continue

    candidates["area_difference"] = (
        abs(
            candidates["Geo_Area"]
            - row["Shape_Area"]
        )
    )

    best = candidates.loc[
        candidates["area_difference"].idxmin()
    ]

    resolved_remaining.append({
        "shapeID": row["shapeID"],
        "shapeName": row["shapeName"],
        "Climate_State_clean": best["Climate_State_clean"],
        "area_difference": best["area_difference"]
    })

resolved_remaining = pd.DataFrame(
    resolved_remaining
)

print(
    resolved_remaining[
        [
            "shapeName",
            "Climate_State_clean",
            "area_difference"
        ]
    ].to_string(index=False)
)

  shapeName Climate_State_clean  area_difference
   Bilaspur    HIMACHAL PRADESH     1.500004e-10
   Hamirpur    HIMACHAL PRADESH     4.975000e-07
 Aurangabad               BIHAR     1.326500e-07
   Bilaspur        CHHATTISGARH     4.683911e-07
  Balrampur        CHHATTISGARH     2.813000e-07
    Bijapur        CHHATTISGARH     1.003507e-07
    Raigarh        CHHATTISGARH     3.414000e-07
Lakshadweep                 NaN     2.877500e-07
    Bijapur           KARNATAKA     3.413000e-07
 Aurangabad         MAHARASHTRA     1.445000e-08
    Raigarh         MAHARASHTRA     3.498500e-07
 Pratapgarh           RAJASTHAN     2.534000e-07
  Balrampur       UTTAR PRADESH     1.218000e-07
 Pratapgarh       UTTAR PRADESH     1.742500e-07
   Hamirpur       UTTAR PRADESH     2.104000e-07

In [247]:
print(
    "\nResolved records:",
    len(resolved_remaining)
)

print(
    "\nMaximum area difference:",
    resolved_remaining["area_difference"].max()
)

Resolved records: 15

Maximum area difference: 4.974999999879381e-07

In [248]:
# ============================================
# BUILD FINAL CLIMATE STATE-DISTRICT DATA
# ============================================

# Add the resolved states to the 720 already-matched records
resolved_lookup = resolved_remaining[
    [
        "shapeID",
        "Climate_State_clean"
    ]
].copy()

climate_final = climate_unique.merge(
    resolved_lookup,
    on="shapeID",
    how="left",
    suffixes=("", "_resolved")
)

# Fill missing states using the polygon-level resolution
climate_final["Climate_State_clean"] = (
    climate_final["Climate_State_clean"]
    .fillna(
        climate_final["Climate_State_clean_resolved"]
    )
)

# Remove temporary column
climate_final = climate_final.drop(
    columns=["Climate_State_clean_resolved"]
)

print("Total climate records:", len(climate_final))

print(
    "Missing states:",
    climate_final["Climate_State_clean"].isna().sum()
)

Total climate records: 735
Missing states: 1

In [249]:
climate_final = climate_final[
    climate_final["Climate_District_clean"]
    != "LAKSHADWEEP"
].copy()

print(
    "Final climate records:",
    len(climate_final)
)

print(
    "Missing states:",
    climate_final["Climate_State_clean"].isna().sum()
)

Final climate records: 734
Missing states: 0

In [250]:
print(agriculture.columns.tolist())

['State', 'District', 'Crop', 'Crop_Year', 'Season', 'Area', 'Production', 'Yield']

In [251]:
print(agriculture.shape)

print(
    agriculture[
        ["State", "District", "Year"]
    ].head()
)

(338483, 8)

KeyError: "['Year'] not in index"

In [252]:
print("Agriculture shape:", agriculture.shape)

print("\nAgriculture columns:")
print(agriculture.columns.tolist())

Agriculture shape: (338483, 8)

Agriculture columns:
['State', 'District', 'Crop', 'Crop_Year', 'Season', 'Area', 'Production', 'Yield']

In [253]:
print("\nFirst 5 rows:")
print(agriculture.head().to_string())

First 5 rows:
                        State  District      Crop  Crop_Year  Season    Area  Production  Yield
0  Andaman and Nicobar Island  NICOBARS  Arecanut       2007  Kharif  2439.6      3415.0   1.40
1  Andaman and Nicobar Island  NICOBARS  Arecanut       2007    Rabi  1626.4      2277.0   1.40
2  Andaman and Nicobar Island  NICOBARS  Arecanut       2008  Autumn  4147.0      3060.0   0.74
3  Andaman and Nicobar Island  NICOBARS  Arecanut       2008  Summer  4147.0      2660.0   0.64
4  Andaman and Nicobar Island  NICOBARS  Arecanut       2009  Autumn  4153.0      3120.0   0.75

In [254]:
# ============================================
# PREPARE AGRICULTURE DATA FOR CLIMATE MERGE
# ============================================

agri_merge = agriculture.copy()
climate_merge = climate_final.copy()

# Normalize State and District
agri_merge["State_clean"] = (
    agri_merge["State"]
    .astype(str)
    .apply(normalize_text)
)

agri_merge["District_clean"] = (
    agri_merge["District"]
    .astype(str)
    .apply(normalize_text)
)

agri_merge["Year"] = pd.to_numeric(
    agri_merge["Crop_Year"],
    errors="coerce"
).astype("Int64")

climate_merge["State_clean"] = (
    climate_merge["Climate_State_clean"]
    .astype(str)
    .apply(normalize_text)
)

climate_merge["District_clean"] = (
    climate_merge["Climate_District_clean"]
    .astype(str)
    .apply(normalize_text)
)

climate_merge["Year"] = pd.to_numeric(
    climate_merge["Year"],
    errors="coerce"
).astype("Int64")

print("Agriculture:", agri_merge.shape)
print("Climate:", climate_merge.shape)

KeyError: 'Year'

In [255]:
print("climate_long shape:", climate_long.shape)
print("climate_long columns:", climate_long.columns.tolist())
print(climate_long.head())

climate_long shape: (15456, 4)
climate_long columns: ['District', 'Year', 'Rainfall', 'Temperature']
      District  Year     Rainfall  Temperature
0   Ashoknagar  1997  1154.893187    24.769161
1       Raisen  1997  1290.198661    25.106505
2   Chhindwara  1997  1264.709764    23.979165
3        Betul  1997  1087.367823    24.184304
4  Hoshangabad  1997  1330.598633    24.850245

In [256]:
agri_merge = agriculture.copy()

agri_merge["State_clean"] = (
    agri_merge["State"]
    .astype(str)
    .apply(normalize_text)
)

agri_merge["District_clean"] = (
    agri_merge["District"]
    .astype(str)
    .apply(normalize_text)
)

agri_merge["Year"] = pd.to_numeric(
    agri_merge["Crop_Year"],
    errors="coerce"
).astype("Int64")

In [257]:
climate_merge = climate_long.copy()

climate_merge["District_clean"] = (
    climate_merge["District"]
    .astype(str)
    .apply(normalize_text)
)

climate_merge["Year"] = pd.to_numeric(
    climate_merge["Year"],
    errors="coerce"
).astype("Int64")

In [258]:
print("Agriculture:", agri_merge.shape)
print(
    agri_merge[
        ["State", "District", "Crop_Year", "Year"]
    ].head()
)

print("\nClimate:", climate_merge.shape)
print(
    climate_merge[
        ["District", "Year", "Rainfall", "Temperature"]
    ].head()
)

Agriculture: (338483, 11)
                        State  District  Crop_Year  Year
0  Andaman and Nicobar Island  NICOBARS       2007  2007
1  Andaman and Nicobar Island  NICOBARS       2007  2007
2  Andaman and Nicobar Island  NICOBARS       2008  2008
3  Andaman and Nicobar Island  NICOBARS       2008  2008
4  Andaman and Nicobar Island  NICOBARS       2009  2009

Climate: (15456, 5)
      District  Year     Rainfall  Temperature
0   Ashoknagar  1997  1154.893187    24.769161
1       Raisen  1997  1290.198661    25.106505
2   Chhindwara  1997  1264.709764    23.979165
3        Betul  1997  1087.367823    24.184304
4  Hoshangabad  1997  1330.598633    24.850245

In [259]:
print(
    climate_final[
        [
            "shapeName",
            "Climate_State_clean"
        ]
    ].head(20)
)

print(
    climate_final[
        "Climate_State_clean"
    ].isna().sum()
)

      shapeName Climate_State_clean
0    Ashoknagar      MADHYA PRADESH
1        Raisen      MADHYA PRADESH
2    Chhindwara      MADHYA PRADESH
3         Betul      MADHYA PRADESH
4   Hoshangabad      MADHYA PRADESH
5        Sehore      MADHYA PRADESH
6      Jabalpur      MADHYA PRADESH
7   Narsimhapur      MADHYA PRADESH
8         Panna      MADHYA PRADESH
9        Ujjain      MADHYA PRADESH
10         Rewa      MADHYA PRADESH
11      Dindori      MADHYA PRADESH
12     Balaghat      MADHYA PRADESH
13      Barwani      MADHYA PRADESH
14        Satna      MADHYA PRADESH
15   Chhatarpur      MADHYA PRADESH
16       Indore      MADHYA PRADESH
17       Ratlam      MADHYA PRADESH
18        Harda      MADHYA PRADESH
19        Sagar      MADHYA PRADESH
0

In [260]:
rainfall_columns = [
    c for c in climate_final.columns
    if "udel_precip_v501_sum." in str(c)
]

temperature_columns = [
    c for c in climate_final.columns
    if "udel_air_temp_v501_mean." in str(c)
]

print("Rainfall columns:", len(rainfall_columns))
print("Temperature columns:", len(temperature_columns))

print(rainfall_columns[:5])
print(temperature_columns[:5])

Rainfall columns: 472
Temperature columns: 354
['udel_precip_v501_sum.1900.max', 'udel_precip_v501_sum.1900.mean', 'udel_precip_v501_sum.1900.min', 'udel_precip_v501_sum.1900.sum', 'udel_precip_v501_sum.1901.max']
['udel_air_temp_v501_mean.1900.max', 'udel_air_temp_v501_mean.1900.mean', 'udel_air_temp_v501_mean.1900.min', 'udel_air_temp_v501_mean.1901.max', 'udel_air_temp_v501_mean.1901.mean']

In [261]:
import re

climate_rows = []

for _, row in climate_final.iterrows():

    district = row["shapeName"]
    state = row["Climate_State_clean"]

    for year in range(1997, 2018):

        rainfall_col = (
            f"udel_precip_v501_sum.{year}.mean"
        )

        temperature_col = (
            f"udel_air_temp_v501_mean.{year}.mean"
        )

        climate_rows.append({
            "State": state,
            "District": district,
            "Year": year,
            "Rainfall": row.get(rainfall_col),
            "Temperature": row.get(temperature_col)
        })

climate_final_long = pd.DataFrame(
    climate_rows
)

print(
    "Climate final shape:",
    climate_final_long.shape
)

print(
    climate_final_long.head()
)

Climate final shape: (15414, 5)
            State    District  Year     Rainfall  Temperature
0  MADHYA PRADESH  Ashoknagar  1997  1154.893187    24.769161
1  MADHYA PRADESH  Ashoknagar  1998   853.358013    26.046996
2  MADHYA PRADESH  Ashoknagar  1999  1231.380341    25.782112
3  MADHYA PRADESH  Ashoknagar  2000   774.924777    25.984592
4  MADHYA PRADESH  Ashoknagar  2001   861.789333    25.907567

In [262]:
climate_final_long["State_clean"] = (
    climate_final_long["State"]
    .astype(str)
    .apply(normalize_text)
)

climate_final_long["District_clean"] = (
    climate_final_long["District"]
    .astype(str)
    .apply(normalize_text)
)

climate_final_long["Year"] = pd.to_numeric(
    climate_final_long["Year"],
    errors="coerce"
).astype("Int64")

In [263]:
agri_merge[
    ["State_clean", "District_clean", "Year"]
].head()

                  State_clean District_clean  Year
0  ANDAMAN AND NICOBAR ISLAND       NICOBARS  2007
1  ANDAMAN AND NICOBAR ISLAND       NICOBARS  2007
2  ANDAMAN AND NICOBAR ISLAND       NICOBARS  2008
3  ANDAMAN AND NICOBAR ISLAND       NICOBARS  2008
4  ANDAMAN AND NICOBAR ISLAND       NICOBARS  2009

In [264]:
final_dataset = agri_merge.merge(
    climate_final_long[
        [
            "State_clean",
            "District_clean",
            "Year",
            "Rainfall",
            "Temperature"
        ]
    ],
    on=[
        "State_clean",
        "District_clean",
        "Year"
    ],
    how="left"
)

print(
    "Final dataset shape:",
    final_dataset.shape
)

Final dataset shape: (338483, 13)

In [265]:
print(
    "\nAgriculture rows:",
    len(agri_merge)
)

print(
    "Final rows:",
    len(final_dataset)
)

print(
    "Rainfall missing:",
    final_dataset["Rainfall"].isna().sum()
)

print(
    "Temperature missing:",
    final_dataset["Temperature"].isna().sum()
)

print(
    "Climate matched:",
    final_dataset[
        final_dataset["Rainfall"].notna() &
        final_dataset["Temperature"].notna()
    ].shape[0]
)

Agriculture rows: 338483
Final rows: 338483
Rainfall missing: 93487
Temperature missing: 93487
Climate matched: 244996

In [266]:
missing_climate = final_dataset[
    final_dataset["Rainfall"].isna()
].copy()

print("Missing climate rows:", len(missing_climate))

print("\nMissing by year:")
print(
    missing_climate["Year"]
    .value_counts()
    .sort_index()
)

Missing climate rows: 93487

Missing by year:
Year
1997     2117
1998     2798
1999     2742
2000     2549
2001     2479
2002     2598
2003     2607
2004     2561
2005     2593
2006     2684
2007     2535
2008     2672
2009     2676
2010     2771
2011     2945
2012     2724
2013     2746
2014     2757
2015     2852
2016     3013
2017     3092
2018    18007
2019    18969
Name: count, dtype: Int64

In [267]:
print("\nMissing by state:")
print(
    missing_climate["State"]
    .value_counts()
    .head(30)
)

Missing by state:
State
Karnataka                     14606
Uttar Pradesh                 10113
Andhra Pradesh                 8422
West Bengal                    8297
Madhya Pradesh                 5388
Chhattisgarh                   4573
Tamil Nadu                     4065
Rajasthan                      3953
Maharashtra                    3906
Odisha                         3516
Bihar                          3515
Assam                          3485
Telangana                      2766
Uttarakhand                    2718
Gujarat                        2195
Jharkhand                      1786
Jammu and Kashmir              1312
Meghalaya                       971
Arunachal Pradesh               915
Haryana                         856
Puducherry                      788
Tripura                         785
Nagaland                        754
Punjab                          723
Andaman and Nicobar Island      696
Himachal Pradesh                673
Kerala                          439
Dadra and Nagar Haveli          348
Mizoram                         245
Delhi                           203
Name: count, dtype: int64

In [268]:
print("\nMissing by State-District:")
print(
    missing_climate[
        ["State", "District"]
    ]
    .value_counts()
    .head(50)
)

Missing by State-District:
State           District
Karnataka       BELAGAVI             1194
                TUMAKURU             1163
                DAVANGERE            1140
                BALLARI              1139
                CHAMARAJANAGARA      1077
                MYSURU               1050
                SHIVAMOGGA           1048
                KALABURAGI           1034
                CHIKKAMAGALURU       1022
Andhra Pradesh  KADAPA                991
                VISAKHAPATANAM        978
Karnataka       BAGALKOTE             946
                VIJAYAPURA            897
                BENGALURU URBAN       869
West Bengal     PURULIA               823
Andhra Pradesh  SPSR NELLORE          822
West Bengal     MEDINIPUR WEST        795
                PURBA BARDHAMAN       757
                DINAJPUR UTTAR        752
                COOCHBEHAR            744
                DARJEELING            736
Assam           MARIGAON              727
                KARBI ANGLONG         724
Chhattisgarh    KANKER                713
Rajasthan       CHITTORGARH           713
Madhya Pradesh  KHANDWA               693
Uttar Pradesh   BARABANKI             676
Maharashtra     AHMEDNAGAR            674
Tamil Nadu      VILLUPURAM            663
Uttar Pradesh   KUSHI NAGAR           660
Bihar           PURBI CHAMPARAN       649
Maharashtra     BEED                  647
West Bengal     PARAGANAS NORTH       642
Chhattisgarh    KOREA                 632
Madhya Pradesh  KHARGONE              630
Chhattisgarh    KABIRDHAM             626
Madhya Pradesh  NARSINGHPUR           625
Uttar Pradesh   MAHARAJGANJ           611
Puducherry      PONDICHERRY           608
Chhattisgarh    DANTEWADA             606
Uttar Pradesh   HATHRAS               605
Rajasthan       DHOLPUR               601
Tamil Nadu      TUTICORIN             600
Andhra Pradesh  MEDAK                 597
Uttar Pradesh   SANT KABEER NAGAR     592
                SHRAVASTI             581
Andhra Pradesh  RANGAREDDI            578
Maharashtra     BULDHANA              576
Rajasthan       JALORE                575
Andhra Pradesh  MAHBUBNAGAR           559
Name: count, dtype: int64

In [269]:
missing_2018_2019 = final_dataset[
    final_dataset["Year"].isin([2018, 2019]) &
    final_dataset["Rainfall"].isna()
]

print(
    "2018–2019 missing:",
    len(missing_2018_2019)
)

print(
    missing_2018_2019[
        ["State", "District", "Year"]
    ].head(20)
)

2018–2019 missing: 36976
                          State                  District  Year
20   Andaman and Nicobar Island                  NICOBARS  2018
21   Andaman and Nicobar Island                  NICOBARS  2019
33   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2018
34   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2019
48   Andaman and Nicobar Island            SOUTH ANDAMANS  2018
49   Andaman and Nicobar Island            SOUTH ANDAMANS  2019
80   Andaman and Nicobar Island                  NICOBARS  2018
81   Andaman and Nicobar Island                  NICOBARS  2019
92   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2018
93   Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2019
107  Andaman and Nicobar Island            SOUTH ANDAMANS  2018
108  Andaman and Nicobar Island            SOUTH ANDAMANS  2019
126  Andaman and Nicobar Island                  NICOBARS  2019
136  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2018
137  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2019
151  Andaman and Nicobar Island            SOUTH ANDAMANS  2018
152  Andaman and Nicobar Island            SOUTH ANDAMANS  2019
168  Andaman and Nicobar Island                  NICOBARS  2018
169  Andaman and Nicobar Island                  NICOBARS  2019
180  Andaman and Nicobar Island  NORTH AND MIDDLE ANDAMAN  2018

In [270]:
missing_historical = final_dataset[
    final_dataset["Year"].between(1997, 2017) &
    final_dataset["Rainfall"].isna()
].copy()

print(
    "1997–2017 missing:",
    len(missing_historical)
)

1997–2017 missing: 56511

In [271]:
missing_pairs = (
    missing_historical[
        ["State", "District"]
    ]
    .drop_duplicates()
)

print(
    "Missing State-District pairs:",
    len(missing_pairs)
)

print(
    missing_pairs.head(100).to_string(index=False)
)

Missing State-District pairs: 176
                     State                 District
Andaman and Nicobar Island                 NICOBARS
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN
Andaman and Nicobar Island           SOUTH ANDAMANS
            Andhra Pradesh                 ADILABAD
            Andhra Pradesh                   KADAPA
            Andhra Pradesh               KARIMNAGAR
            Andhra Pradesh                  KHAMMAM
            Andhra Pradesh              MAHBUBNAGAR
            Andhra Pradesh                    MEDAK
            Andhra Pradesh                 NALGONDA
            Andhra Pradesh                NIZAMABAD
            Andhra Pradesh               RANGAREDDI
            Andhra Pradesh             SPSR NELLORE
            Andhra Pradesh           VISAKHAPATANAM
            Andhra Pradesh                 WARANGAL
            Andhra Pradesh                HYDERABAD
                     Assam             KAMRUP METRO
                     Assam            KARBI ANGLONG
                     Assam                 MARIGAON
                     Bihar                   BOKARO
                     Bihar                   CHATRA
                     Bihar                  DEOGHAR
                     Bihar                  DHANBAD
                     Bihar                    DUMKA
                     Bihar            EAST SINGHBUM
                     Bihar                   GARHWA
                     Bihar                  GIRIDIH
                     Bihar                    GODDA
                     Bihar                    GUMLA
                     Bihar               HAZARIBAGH
                     Bihar                  KODERMA
                     Bihar                LOHARDAGA
                     Bihar                    PAKUR
                     Bihar                   PALAMU
                     Bihar          PURBI CHAMPARAN
                     Bihar                   RANCHI
                     Bihar                SAHEBGANJ
                     Bihar           WEST SINGHBHUM
              Chhattisgarh                 BEMETARA
              Chhattisgarh                DANTEWADA
              Chhattisgarh               GARIYABAND
              Chhattisgarh                KABIRDHAM
              Chhattisgarh                   KANKER
              Chhattisgarh                    KOREA
    Dadra and Nagar Haveli   DADRA AND NAGAR HAVELI
             Daman and Diu                      DIU
             Daman and Diu                    DAMAN
                     Delhi              DELHI_TOTAL
                   Gujarat                 ARAVALLI
                   Gujarat                    BOTAD
                   Gujarat             CHHOTAUDEPUR
                   Gujarat                     DANG
                   Haryana             CHARKI DADRI
          Himachal Pradesh          LAHUL AND SPITI
         Jammu and Kashmir                BANDIPORA
         Jammu and Kashmir                  RAJAURI
         Jammu and Kashmir                BARAMULLA
         Jammu and Kashmir               LEH LADAKH
         Jammu and Kashmir                   POONCH
         Jammu and Kashmir                  SHOPIAN
         Jammu and Kashmir                   KARGIL
                 Jharkhand            EAST SINGHBUM
                 Jharkhand                  KODERMA
                 Jharkhand                SAHEBGANJ
                 Jharkhand      SARAIKELA KHARSAWAN
                 Jharkhand           WEST SINGHBHUM
                 Karnataka                BAGALKOTE
                 Karnataka                  BALLARI
                 Karnataka                 BELAGAVI
                 Karnataka          BENGALURU URBAN
                 Karnataka          CHAMARAJANAGARA
                 Karnataka           CHIKKAMAGALURU
                 Karnataka                DAVANGERE
                 Karnataka                   MYSURU
                 Karnataka               SHIVAMOGGA
                 Karnataka                 TUMAKURU
                 Karnataka               KALABURAGI
                 Karnataka               VIJAYAPURA
                 Karnataka                 YADAGIRI
                    Ladakh               LEH LADAKH
            Madhya Pradesh               AGAR MALWA
            Madhya Pradesh                   BASTAR
            Madhya Pradesh                 BILASPUR
            Madhya Pradesh                DANTEWADA
            Madhya Pradesh                 DHAMTARI
            Madhya Pradesh                     DURG
            Madhya Pradesh           JANJGIR-CHAMPA
            Madhya Pradesh                  JASHPUR
            Madhya Pradesh                KABIRDHAM
            Madhya Pradesh                   KANKER
            Madhya Pradesh                  KHANDWA
            Madhya Pradesh                 KHARGONE
            Madhya Pradesh                    KORBA
            Madhya Pradesh                    KOREA
            Madhya Pradesh               MAHASAMUND
            Madhya Pradesh              NARSINGHPUR
            Madhya Pradesh                   RAIPUR
            Madhya Pradesh              RAJNANDGAON
            Madhya Pradesh                  SURGUJA
               Maharashtra               AHMEDNAGAR

In [272]:
print(
    "Missing historical rows:",
    len(missing_historical)
)

print(
    "Unique missing State-District:",
    missing_historical[
        ["State", "District"]
    ].drop_duplicates().shape[0]
)

Missing historical rows: 56511
Unique missing State-District: 176

In [273]:
print(
    missing_historical[
        ["State", "District"]
    ]
    .drop_duplicates()
    .to_string(index=False)
)

                     State                 District
Andaman and Nicobar Island                 NICOBARS
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN
Andaman and Nicobar Island           SOUTH ANDAMANS
            Andhra Pradesh                 ADILABAD
            Andhra Pradesh                   KADAPA
            Andhra Pradesh               KARIMNAGAR
            Andhra Pradesh                  KHAMMAM
            Andhra Pradesh              MAHBUBNAGAR
            Andhra Pradesh                    MEDAK
            Andhra Pradesh                 NALGONDA
            Andhra Pradesh                NIZAMABAD
            Andhra Pradesh               RANGAREDDI
            Andhra Pradesh             SPSR NELLORE
            Andhra Pradesh           VISAKHAPATANAM
            Andhra Pradesh                 WARANGAL
            Andhra Pradesh                HYDERABAD
                     Assam             KAMRUP METRO
                     Assam            KARBI ANGLONG
                     Assam                 MARIGAON
                     Bihar                   BOKARO
                     Bihar                   CHATRA
                     Bihar                  DEOGHAR
                     Bihar                  DHANBAD
                     Bihar                    DUMKA
                     Bihar            EAST SINGHBUM
                     Bihar                   GARHWA
                     Bihar                  GIRIDIH
                     Bihar                    GODDA
                     Bihar                    GUMLA
                     Bihar               HAZARIBAGH
                     Bihar                  KODERMA
                     Bihar                LOHARDAGA
                     Bihar                    PAKUR
                     Bihar                   PALAMU
                     Bihar          PURBI CHAMPARAN
                     Bihar                   RANCHI
                     Bihar                SAHEBGANJ
                     Bihar           WEST SINGHBHUM
              Chhattisgarh                 BEMETARA
              Chhattisgarh                DANTEWADA
              Chhattisgarh               GARIYABAND
              Chhattisgarh                KABIRDHAM
              Chhattisgarh                   KANKER
              Chhattisgarh                    KOREA
    Dadra and Nagar Haveli   DADRA AND NAGAR HAVELI
             Daman and Diu                      DIU
             Daman and Diu                    DAMAN
                     Delhi              DELHI_TOTAL
                   Gujarat                 ARAVALLI
                   Gujarat                    BOTAD
                   Gujarat             CHHOTAUDEPUR
                   Gujarat                     DANG
                   Haryana             CHARKI DADRI
          Himachal Pradesh          LAHUL AND SPITI
         Jammu and Kashmir                BANDIPORA
         Jammu and Kashmir                  RAJAURI
         Jammu and Kashmir                BARAMULLA
         Jammu and Kashmir               LEH LADAKH
         Jammu and Kashmir                   POONCH
         Jammu and Kashmir                  SHOPIAN
         Jammu and Kashmir                   KARGIL
                 Jharkhand            EAST SINGHBUM
                 Jharkhand                  KODERMA
                 Jharkhand                SAHEBGANJ
                 Jharkhand      SARAIKELA KHARSAWAN
                 Jharkhand           WEST SINGHBHUM
                 Karnataka                BAGALKOTE
                 Karnataka                  BALLARI
                 Karnataka                 BELAGAVI
                 Karnataka          BENGALURU URBAN
                 Karnataka          CHAMARAJANAGARA
                 Karnataka           CHIKKAMAGALURU
                 Karnataka                DAVANGERE
                 Karnataka                   MYSURU
                 Karnataka               SHIVAMOGGA
                 Karnataka                 TUMAKURU
                 Karnataka               KALABURAGI
                 Karnataka               VIJAYAPURA
                 Karnataka                 YADAGIRI
                    Ladakh               LEH LADAKH
            Madhya Pradesh               AGAR MALWA
            Madhya Pradesh                   BASTAR
            Madhya Pradesh                 BILASPUR
            Madhya Pradesh                DANTEWADA
            Madhya Pradesh                 DHAMTARI
            Madhya Pradesh                     DURG
            Madhya Pradesh           JANJGIR-CHAMPA
            Madhya Pradesh                  JASHPUR
            Madhya Pradesh                KABIRDHAM
            Madhya Pradesh                   KANKER
            Madhya Pradesh                  KHANDWA
            Madhya Pradesh                 KHARGONE
            Madhya Pradesh                    KORBA
            Madhya Pradesh                    KOREA
            Madhya Pradesh               MAHASAMUND
            Madhya Pradesh              NARSINGHPUR
            Madhya Pradesh                   RAIPUR
            Madhya Pradesh              RAJNANDGAON
            Madhya Pradesh                  SURGUJA
               Maharashtra               AHMEDNAGAR
               Maharashtra                     BEED
               Maharashtra                 BULDHANA
               Maharashtra                   GONDIA
               Maharashtra                   RAIGAD
               Maharashtra                   MUMBAI
               Maharashtra          MUMBAI SUBURBAN
                 Meghalaya                  RI BHOI
                    Odisha                    BOUDH
                    Odisha                  DEOGARH
                    Odisha              NABARANGPUR
                    Odisha                  SONEPUR
                Puducherry              PONDICHERRY
                Puducherry                    YANAM
                    Punjab                FIROZEPUR
                    Punjab                  S NAGAR
                 Rajasthan              CHITTORGARH
                 Rajasthan                  DHOLPUR
                 Rajasthan                   JALORE
                 Rajasthan                JHUNJHUNU
                Tamil Nadu               VILLUPURAM
                Tamil Nadu              KANCHIPURAM
                Tamil Nadu                TUTICORIN
                 Telangana              HANUMAKONDA
                 Telangana                 JAGITIAL
                 Telangana                  JANGOAN
                 Telangana   KOMARAM BHEEM ASIFABAD
                 Telangana              MAHBUBNAGAR
                 Telangana       MEDCHAL MALKAJGIRI
                 Telangana                  RAJANNA
                 Telangana               RANGAREDDI
                 Telangana                 WARANGAL
                 Telangana                  YADADRI
                   Tripura               SEPAHIJALA
                   Tripura                  UNAKOTI
             Uttar Pradesh                   ALMORA
             Uttar Pradesh                   AMROHA
             Uttar Pradesh                BARABANKI
             Uttar Pradesh                  CHAMOLI
             Uttar Pradesh                 DEHRADUN
             Uttar Pradesh                 HARIDWAR
             Uttar Pradesh                  HATHRAS
             Uttar Pradesh                  KASGANJ
             Uttar Pradesh              KUSHI NAGAR
             Uttar Pradesh              MAHARAJGANJ
             Uttar Pradesh                 NAINITAL
             Uttar Pradesh            PAURI GARHWAL
             Uttar Pradesh              PITHORAGARH
             Uttar Pradesh        SANT KABEER NAGAR
             Uttar Pradesh       SANT RAVIDAS NAGAR
             Uttar Pradesh                   SHAMLI
             Uttar Pradesh                SHRAVASTI
             Uttar Pradesh          SIDDHARTH NAGAR
             Uttar Pradesh            TEHRI GARHWAL
             Uttar Pradesh         UDAM SINGH NAGAR
             Uttar Pradesh              UTTAR KASHI
             Uttar Pradesh                BAGESHWAR
             Uttar Pradesh                CHAMPAWAT
             Uttar Pradesh             RUDRA PRAYAG
               Uttarakhand                 HARIDWAR
               Uttarakhand            PAURI GARHWAL
               Uttarakhand             RUDRA PRAYAG
               Uttarakhand         UDAM SINGH NAGAR
               Uttarakhand              UTTAR KASHI
               West Bengal          PARAGANAS NORTH
               West Bengal          PARAGANAS SOUTH
               West Bengal               COOCHBEHAR
               West Bengal               DARJEELING
               West Bengal         DINAJPUR DAKSHIN
               West Bengal           DINAJPUR UTTAR
               West Bengal                  HOOGHLY
               West Bengal                   HOWRAH
               West Bengal           MEDINIPUR EAST
               West Bengal           MEDINIPUR WEST
               West Bengal          PURBA BARDHAMAN
               West Bengal                  PURULIA
               West Bengal        PASCHIM BARDHAMAN

In [274]:
missing_pairs = (
    missing_historical[
        ["State", "District"]
    ]
    .drop_duplicates()
    .sort_values(["State", "District"])
    .reset_index(drop=True)
)

print("Unique missing State-District pairs:", len(missing_pairs))

missing_pairs.to_csv(
    "../data/processed/missing_climate_pairs.csv",
    index=False
)

print("✅ Saved missing pairs")

Unique missing State-District pairs: 176
✅ Saved missing pairs

In [275]:
print(missing_pairs.groupby("State").size())

State
Andaman and Nicobar Island     3
Andhra Pradesh                13
Assam                          3
Bihar                         19
Chhattisgarh                   6
Dadra and Nagar Haveli         1
Daman and Diu                  2
Delhi                          1
Gujarat                        4
Haryana                        1
Himachal Pradesh               1
Jammu and Kashmir              7
Jharkhand                      5
Karnataka                     13
Ladakh                         1
Madhya Pradesh                19
Maharashtra                    7
Meghalaya                      1
Odisha                         4
Puducherry                     2
Punjab                         2
Rajasthan                      4
Tamil Nadu                     3
Telangana                     10
Tripura                        2
Uttar Pradesh                 24
Uttarakhand                    5
West Bengal                   13
dtype: int64

In [276]:
climate_names = set(
    climate_final_long["District_clean"].dropna()
)

missing_district_names = set(
    missing_historical["District_clean"].dropna()
)

print(
    "Missing agriculture district names:",
    len(missing_district_names)
)

print(
    "Names already present in climate:",
    len(
        missing_district_names &
        climate_names
    )
)

print(
    "Names NOT present in climate:",
    len(
        missing_district_names -
        climate_names
    )
)

Missing agriculture district names: 159
Names already present in climate: 46
Names NOT present in climate: 113

In [277]:
existing_name_matches = sorted(
    missing_district_names &
    climate_names
)

print(
    "Names already present in climate:",
    len(existing_name_matches)
)

print(existing_name_matches)

Names already present in climate: 46
['ADILABAD', 'ALMORA', 'BAGESHWAR', 'BASTAR', 'BILASPUR', 'BOKARO', 'CHAMOLI', 'CHAMPAWAT', 'CHATRA', 'DAMAN', 'DEHRADUN', 'DEOGHAR', 'DHAMTARI', 'DHANBAD', 'DIU', 'DUMKA', 'DURG', 'GARHWA', 'GIRIDIH', 'GODDA', 'GUMLA', 'HAZARIBAGH', 'JANJGIR-CHAMPA', 'JASHPUR', 'KARGIL', 'KARIMNAGAR', 'KHAMMAM', 'KORBA', 'LOHARDAGA', 'MAHASAMUND', 'MEDAK', 'MUMBAI', 'MUMBAI SUBURBAN', 'NAINITAL', 'NALGONDA', 'NICOBARS', 'NIZAMABAD', 'PAKUR', 'PALAMU', 'PITHORAGARH', 'RAIPUR', 'RAJNANDGAON', 'RANCHI', 'SURGUJA', 'TEHRI GARHWAL', 'YANAM']

In [278]:
for name in existing_name_matches:

    agri_states = sorted(
        missing_historical[
            missing_historical["District_clean"] == name
        ]["State_clean"]
        .dropna()
        .unique()
    )

    climate_states = sorted(
        climate_final_long[
            climate_final_long["District_clean"] == name
        ]["State_clean"]
        .dropna()
        .unique()
    )

    print(
        f"{name:25} "
        f"Agriculture={agri_states} "
        f"Climate={climate_states}"
    )

ADILABAD                  Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
ALMORA                    Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
BAGESHWAR                 Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
BASTAR                    Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
BILASPUR                  Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH', 'HIMACHAL PRADESH']
BOKARO                    Agriculture=['BIHAR'] Climate=['JHARKHAND']
CHAMOLI                   Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
CHAMPAWAT                 Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
CHATRA                    Agriculture=['BIHAR'] Climate=['JHARKHAND']
DAMAN                     Agriculture=['DAMAN AND DIU'] Climate=['DADRA AND NAGAR HAVELI AND DAMAN AND DIU']
DEHRADUN                  Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
DEOGHAR                   Agriculture=['BIHAR'] Climate=['JHARKHAND']
DHAMTARI                  Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
DHANBAD                   Agriculture=['BIHAR'] Climate=['JHARKHAND']
DIU                       Agriculture=['DAMAN AND DIU'] Climate=['DADRA AND NAGAR HAVELI AND DAMAN AND DIU']
DUMKA                     Agriculture=['BIHAR'] Climate=['JHARKHAND']
DURG                      Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
GARHWA                    Agriculture=['BIHAR'] Climate=['JHARKHAND']
GIRIDIH                   Agriculture=['BIHAR'] Climate=['JHARKHAND']
GODDA                     Agriculture=['BIHAR'] Climate=['JHARKHAND']
GUMLA                     Agriculture=['BIHAR'] Climate=['JHARKHAND']
HAZARIBAGH                Agriculture=['BIHAR'] Climate=['JHARKHAND']
JANJGIR-CHAMPA            Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
JASHPUR                   Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
KARGIL                    Agriculture=['JAMMU AND KASHMIR'] Climate=['LADAKH']
KARIMNAGAR                Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
KHAMMAM                   Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
KORBA                     Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
LOHARDAGA                 Agriculture=['BIHAR'] Climate=['JHARKHAND']
MAHASAMUND                Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
MEDAK                     Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
MUMBAI                    Agriculture=['MAHARASHTRA'] Climate=['MAHARASHTRA']
MUMBAI SUBURBAN           Agriculture=['MAHARASHTRA'] Climate=['MAHARASHTRA']
NAINITAL                  Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
NALGONDA                  Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
NICOBARS                  Agriculture=['ANDAMAN AND NICOBAR ISLAND'] Climate=['ANDAMAN AND NICOBAR ISLANDS']
NIZAMABAD                 Agriculture=['ANDHRA PRADESH'] Climate=['TELANGANA']
PAKUR                     Agriculture=['BIHAR'] Climate=['JHARKHAND']
PALAMU                    Agriculture=['BIHAR'] Climate=['JHARKHAND']
PITHORAGARH               Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
RAIPUR                    Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
RAJNANDGAON               Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
RANCHI                    Agriculture=['BIHAR'] Climate=['JHARKHAND']
SURGUJA                   Agriculture=['MADHYA PRADESH'] Climate=['CHHATTISGARH']
TEHRI GARHWAL             Agriculture=['UTTAR PRADESH'] Climate=['UTTARAKHAND']
YANAM                     Agriculture=['PUDUCHERRY'] Climate=['ANDHRA PRADESH']

In [279]:
# ============================================
# RECOVER HISTORICAL DISTRICTS USING
# CURRENT STATE/DISTRICT MAPPING
# ============================================

# Historical agriculture -> current geography
alias_map = final_locations[
    final_locations["Current_State"].notna() &
    final_locations["Current_District"].notna()
][
    [
        "State",
        "District",
        "Current_State",
        "Current_District"
    ]
].drop_duplicates().copy()

# Normalize everything
for col in [
    "State",
    "District",
    "Current_State",
    "Current_District"
]:
    alias_map[col + "_clean"] = (
        alias_map[col]
        .astype(str)
        .apply(normalize_text)
    )

# Climate state-district combinations
climate_pairs = climate_final_long[
    [
        "State_clean",
        "District_clean"
    ]
].drop_duplicates()

# Match historical agriculture geography
# to current climate geography
alias_climate = alias_map.merge(
    climate_pairs,
    left_on=[
        "Current_State_clean",
        "Current_District_clean"
    ],
    right_on=[
        "State_clean",
        "District_clean"
    ],
    how="inner"
)

print(
    "Historical → climate aliases:",
    len(alias_climate)
)

print(
    alias_climate[
        [
            "State",
            "District",
            "Current_State",
            "Current_District"
        ]
    ].drop_duplicates().to_string(index=False)
)

Historical → climate aliases: 43
                     State                District               Current_State        Current_District
Andaman and Nicobar Island          SOUTH ANDAMANS Andaman and Nicobar Islands           South Andaman
            Andhra Pradesh                ADILABAD                   Telangana                Adilabad
            Andhra Pradesh              KARIMNAGAR                   Telangana              Karimnagar
            Andhra Pradesh                   MEDAK                   Telangana                   Medak
            Andhra Pradesh                NALGONDA                   Telangana                Nalgonda
            Andhra Pradesh              RANGAREDDI                   Telangana              Rangareddy
            Andhra Pradesh          VISAKHAPATANAM              Andhra Pradesh           Visakhapatnam
                     Assam SOUTH SALMARA MANCACHAR                       Assam South Salmara-Mankachar
                     Bihar                  BOKARO                   Jharkhand                  Bokaro
                     Bihar                 DHANBAD                   Jharkhand                 Dhanbad
                     Bihar                   DUMKA                   Jharkhand                   Dumka
                     Bihar                  GARHWA                   Jharkhand                  Garhwa
                     Bihar                 GIRIDIH                   Jharkhand                 Giridih
                     Bihar                   GODDA                   Jharkhand                   Godda
                     Bihar                   GUMLA                   Jharkhand                   Gumla
                     Bihar              HAZARIBAGH                   Jharkhand              Hazaribagh
                     Bihar               LOHARDAGA                   Jharkhand               Lohardaga
                     Bihar                   PAKUR                   Jharkhand                   Pakur
                     Bihar                  PALAMU                   Jharkhand                  Palamu
                   Gujarat            CHHOTAUDEPUR                     Gujarat          Chhota Udaipur
            Madhya Pradesh                  BASTAR                Chhattisgarh                  Bastar
            Madhya Pradesh                DHAMTARI                Chhattisgarh                Dhamtari
            Madhya Pradesh                    DURG                Chhattisgarh                    Durg
            Madhya Pradesh          JANJGIR-CHAMPA                Chhattisgarh          Janjgir-Champa
            Madhya Pradesh                 JASHPUR                Chhattisgarh                 Jashpur
            Madhya Pradesh                   KORBA                Chhattisgarh                   Korba
            Madhya Pradesh              MAHASAMUND                Chhattisgarh              Mahasamund
            Madhya Pradesh             RAJNANDGAON                Chhattisgarh             Rajnandgaon
            Madhya Pradesh                 SURGUJA                Chhattisgarh                 Surguja
                    Punjab               FIROZEPUR                      Punjab                Firozpur
                 Telangana              RANGAREDDI                   Telangana              Rangareddy
             Uttar Pradesh                  ALMORA                 Uttarakhand                  Almora
             Uttar Pradesh                 CHAMOLI                 Uttarakhand                 Chamoli
             Uttar Pradesh               CHAMPAWAT                 Uttarakhand               Champawat
             Uttar Pradesh             KUSHI NAGAR               Uttar Pradesh              Kushinagar
             Uttar Pradesh             PITHORAGARH                 Uttarakhand             Pithoragarh
             Uttar Pradesh            RUDRA PRAYAG                 Uttarakhand             Rudraprayag
             Uttar Pradesh       SANT KABEER NAGAR               Uttar Pradesh        Sant Kabir Nagar
             Uttar Pradesh           TEHRI GARHWAL                 Uttarakhand           Tehri Garhwal
             Uttar Pradesh        UDAM SINGH NAGAR                 Uttarakhand       Udham Singh Nagar
               Uttarakhand            RUDRA PRAYAG                 Uttarakhand             Rudraprayag
               Uttarakhand        UDAM SINGH NAGAR                 Uttarakhand       Udham Singh Nagar
               Uttarakhand             UTTAR KASHI                 Uttarakhand              Uttarkashi

In [280]:
# Rebuild the climate pair table with explicit names
climate_pairs = (
    climate_final_long[
        ["State_clean", "District_clean"]
    ]
    .drop_duplicates()
    .rename(
        columns={
            "State_clean": "Climate_State_clean",
            "District_clean": "Climate_District_clean"
        }
    )
)

# Match historical agriculture geography
# to current climate geography
alias_climate = alias_map.merge(
    climate_pairs,
    left_on=[
        "Current_State_clean",
        "Current_District_clean"
    ],
    right_on=[
        "Climate_State_clean",
        "Climate_District_clean"
    ],
    how="inner"
)

print(
    "Historical → climate aliases:",
    len(alias_climate)
)

Historical → climate aliases: 43

In [281]:
missing_pairs = (
    missing_historical[
        ["State_clean", "District_clean"]
    ]
    .drop_duplicates()
)

recoverable_pairs = missing_pairs.merge(
    alias_climate[
        [
            "State_clean",
            "District_clean"
        ]
    ]
    .drop_duplicates(),
    on=[
        "State_clean",
        "District_clean"
    ],
    how="inner"
)

print(
    "Missing agriculture pairs:",
    len(missing_pairs)
)

print(
    "Recoverable through historical mapping:",
    len(recoverable_pairs)
)

Missing agriculture pairs: 176
Recoverable through historical mapping: 42

In [282]:
print(
    recoverable_pairs.to_string(index=False)
)

               State_clean    District_clean
ANDAMAN AND NICOBAR ISLAND    SOUTH ANDAMANS
            ANDHRA PRADESH          ADILABAD
            ANDHRA PRADESH        KARIMNAGAR
            ANDHRA PRADESH             MEDAK
            ANDHRA PRADESH          NALGONDA
            ANDHRA PRADESH        RANGAREDDI
            ANDHRA PRADESH    VISAKHAPATANAM
                     BIHAR            BOKARO
                     BIHAR           DHANBAD
                     BIHAR             DUMKA
                     BIHAR            GARHWA
                     BIHAR           GIRIDIH
                     BIHAR             GODDA
                     BIHAR             GUMLA
                     BIHAR        HAZARIBAGH
                     BIHAR         LOHARDAGA
                     BIHAR             PAKUR
                     BIHAR            PALAMU
                   GUJARAT      CHHOTAUDEPUR
            MADHYA PRADESH            BASTAR
            MADHYA PRADESH          DHAMTARI
            MADHYA PRADESH              DURG
            MADHYA PRADESH    JANJGIR-CHAMPA
            MADHYA PRADESH           JASHPUR
            MADHYA PRADESH             KORBA
            MADHYA PRADESH        MAHASAMUND
            MADHYA PRADESH       RAJNANDGAON
            MADHYA PRADESH           SURGUJA
                    PUNJAB         FIROZEPUR
                 TELANGANA        RANGAREDDI
             UTTAR PRADESH            ALMORA
             UTTAR PRADESH           CHAMOLI
             UTTAR PRADESH       KUSHI NAGAR
             UTTAR PRADESH       PITHORAGARH
             UTTAR PRADESH SANT KABEER NAGAR
             UTTAR PRADESH     TEHRI GARHWAL
             UTTAR PRADESH  UDAM SINGH NAGAR
             UTTAR PRADESH         CHAMPAWAT
             UTTAR PRADESH      RUDRA PRAYAG
               UTTARAKHAND      RUDRA PRAYAG
               UTTARAKHAND  UDAM SINGH NAGAR
               UTTARAKHAND       UTTAR KASHI

In [283]:
# ============================================
# 42 RECOVERABLE HISTORICAL DISTRICTS
# ============================================

alias_lookup = (
    alias_climate[
        [
            "State_clean",
            "District_clean",
            "Climate_State_clean",
            "Climate_District_clean"
        ]
    ]
    .drop_duplicates()
)

print("Alias mappings:", len(alias_lookup))

print(
    alias_lookup.to_string(index=False)
)

Alias mappings: 43
               State_clean          District_clean         Climate_State_clean  Climate_District_clean
ANDAMAN AND NICOBAR ISLAND          SOUTH ANDAMANS ANDAMAN AND NICOBAR ISLANDS           SOUTH ANDAMAN
            ANDHRA PRADESH                ADILABAD                   TELANGANA                ADILABAD
            ANDHRA PRADESH              KARIMNAGAR                   TELANGANA              KARIMNAGAR
            ANDHRA PRADESH                   MEDAK                   TELANGANA                   MEDAK
            ANDHRA PRADESH                NALGONDA                   TELANGANA                NALGONDA
            ANDHRA PRADESH              RANGAREDDI                   TELANGANA              RANGAREDDY
            ANDHRA PRADESH          VISAKHAPATANAM              ANDHRA PRADESH           VISAKHAPATNAM
                     ASSAM SOUTH SALMARA MANCACHAR                       ASSAM SOUTH SALMARA-MANKACHAR
                     BIHAR                  BOKARO                   JHARKHAND                  BOKARO
                     BIHAR                 DHANBAD                   JHARKHAND                 DHANBAD
                     BIHAR                   DUMKA                   JHARKHAND                   DUMKA
                     BIHAR                  GARHWA                   JHARKHAND                  GARHWA
                     BIHAR                 GIRIDIH                   JHARKHAND                 GIRIDIH
                     BIHAR                   GODDA                   JHARKHAND                   GODDA
                     BIHAR                   GUMLA                   JHARKHAND                   GUMLA
                     BIHAR              HAZARIBAGH                   JHARKHAND              HAZARIBAGH
                     BIHAR               LOHARDAGA                   JHARKHAND               LOHARDAGA
                     BIHAR                   PAKUR                   JHARKHAND                   PAKUR
                     BIHAR                  PALAMU                   JHARKHAND                  PALAMU
                   GUJARAT            CHHOTAUDEPUR                     GUJARAT          CHHOTA UDAIPUR
            MADHYA PRADESH                  BASTAR                CHHATTISGARH                  BASTAR
            MADHYA PRADESH                DHAMTARI                CHHATTISGARH                DHAMTARI
            MADHYA PRADESH                    DURG                CHHATTISGARH                    DURG
            MADHYA PRADESH          JANJGIR-CHAMPA                CHHATTISGARH          JANJGIR-CHAMPA
            MADHYA PRADESH                 JASHPUR                CHHATTISGARH                 JASHPUR
            MADHYA PRADESH                   KORBA                CHHATTISGARH                   KORBA
            MADHYA PRADESH              MAHASAMUND                CHHATTISGARH              MAHASAMUND
            MADHYA PRADESH             RAJNANDGAON                CHHATTISGARH             RAJNANDGAON
            MADHYA PRADESH                 SURGUJA                CHHATTISGARH                 SURGUJA
                    PUNJAB               FIROZEPUR                      PUNJAB                FIROZPUR
                 TELANGANA              RANGAREDDI                   TELANGANA              RANGAREDDY
             UTTAR PRADESH                  ALMORA                 UTTARAKHAND                  ALMORA
             UTTAR PRADESH                 CHAMOLI                 UTTARAKHAND                 CHAMOLI
             UTTAR PRADESH               CHAMPAWAT                 UTTARAKHAND               CHAMPAWAT
             UTTAR PRADESH             KUSHI NAGAR               UTTAR PRADESH              KUSHINAGAR
             UTTAR PRADESH             PITHORAGARH                 UTTARAKHAND             PITHORAGARH
             UTTAR PRADESH            RUDRA PRAYAG                 UTTARAKHAND             RUDRAPRAYAG
             UTTAR PRADESH       SANT KABEER NAGAR               UTTAR PRADESH        SANT KABIR NAGAR
             UTTAR PRADESH           TEHRI GARHWAL                 UTTARAKHAND           TEHRI GARHWAL
             UTTAR PRADESH        UDAM SINGH NAGAR                 UTTARAKHAND       UDHAM SINGH NAGAR
               UTTARAKHAND            RUDRA PRAYAG                 UTTARAKHAND             RUDRAPRAYAG
               UTTARAKHAND        UDAM SINGH NAGAR                 UTTARAKHAND       UDHAM SINGH NAGAR
               UTTARAKHAND             UTTAR KASHI                 UTTARAKHAND              UTTARKASHI

In [284]:
print(
    alias_lookup[
        ["State_clean", "District_clean"]
    ].duplicated().sum()
)

0

In [285]:
agri_with_alias = agri_merge.merge(
    alias_lookup,
    on=[
        "State_clean",
        "District_clean"
    ],
    how="left"
)

In [286]:
agri_with_alias["Merge_State"] = (
    agri_with_alias["Climate_State_clean"]
    .fillna(agri_with_alias["State_clean"])
)

agri_with_alias["Merge_District"] = (
    agri_with_alias["Climate_District_clean"]
    .fillna(agri_with_alias["District_clean"])
)

In [287]:
final_dataset_v2 = agri_with_alias.merge(
    climate_final_long[
        [
            "State_clean",
            "District_clean",
            "Year",
            "Rainfall",
            "Temperature"
        ]
    ],
    left_on=[
        "Merge_State",
        "Merge_District",
        "Year"
    ],
    right_on=[
        "State_clean",
        "District_clean",
        "Year"
    ],
    how="left",
    suffixes=("", "_climate")
)

print(
    "Final rows:",
    len(final_dataset_v2)
)

print(
    "Rainfall missing:",
    final_dataset_v2["Rainfall"].isna().sum()
)

print(
    "Temperature missing:",
    final_dataset_v2["Temperature"].isna().sum()
)

print(
    "Climate matched:",
    final_dataset_v2[
        final_dataset_v2["Rainfall"].notna() &
        final_dataset_v2["Temperature"].notna()
    ].shape[0]
)

Final rows: 338483
Rainfall missing: 85632
Temperature missing: 85632
Climate matched: 252851

In [288]:
missing_v2 = final_dataset_v2[
    final_dataset_v2["Rainfall"].isna()
].copy()

print("Total missing:", len(missing_v2))

print("\nMissing by year:")
print(
    missing_v2["Year"]
    .value_counts()
    .sort_index()
)

Total missing: 85632

Missing by year:
Year
1997     1478
1998     2077
1999     2196
2000     2192
2001     2111
2002     2202
2003     2226
2004     2184
2005     2224
2006     2296
2007     2268
2008     2330
2009     2319
2010     2402
2011     2561
2012     2449
2013     2500
2014     2478
2015     2581
2016     2754
2017     2828
2018    18007
2019    18969
Name: count, dtype: Int64

In [289]:
historical_missing_v2 = missing_v2[
    missing_v2["Year"].between(1997, 2017)
]

recent_missing_v2 = missing_v2[
    missing_v2["Year"].isin([2018, 2019])
]

print(
    "\n1997–2017 missing:",
    len(historical_missing_v2)
)

print(
    "2018–2019 missing:",
    len(recent_missing_v2)
)

1997–2017 missing: 48656
2018–2019 missing: 36976

In [290]:
print(
    "\nHistorical missing State-District pairs:",
    historical_missing_v2[
        ["State", "District"]
    ].drop_duplicates().shape[0]
)

Historical missing State-District pairs: 134

In [291]:
# ============================================
# ANALYZE THE REMAINING 134 DISTRICTS
# ============================================

remaining_pairs = (
    historical_missing_v2[
        ["State", "District"]
    ]
    .drop_duplicates()
    .sort_values(["State", "District"])
    .reset_index(drop=True)
)

print(
    "Remaining historical pairs:",
    len(remaining_pairs)
)

# Number of agriculture rows affected by each pair
pair_counts = (
    historical_missing_v2
    .groupby(["State", "District"])
    .size()
    .reset_index(name="Missing_Rows")
    .sort_values("Missing_Rows", ascending=False)
)

print(
    pair_counts.head(30).to_string(index=False)
)

Remaining historical pairs: 134
         State        District  Missing_Rows
     Karnataka        BELAGAVI          1079
     Karnataka        TUMAKURU          1054
     Karnataka       DAVANGERE          1029
     Karnataka         BALLARI          1022
     Karnataka CHAMARAJANAGARA           969
     Karnataka      SHIVAMOGGA           950
     Karnataka          MYSURU           944
     Karnataka      KALABURAGI           934
     Karnataka  CHIKKAMAGALURU           927
Andhra Pradesh          KADAPA           887
     Karnataka       BAGALKOTE           840
     Karnataka      VIJAYAPURA           794
     Karnataka BENGALURU URBAN           774
   West Bengal         PURULIA           754
   West Bengal  MEDINIPUR WEST           741
Andhra Pradesh    SPSR NELLORE           737
   West Bengal PURBA BARDHAMAN           700
   West Bengal  DINAJPUR UTTAR           699
   West Bengal      DARJEELING           683
   West Bengal      COOCHBEHAR           679
         Assam        MARIGAON           660
         Assam   KARBI ANGLONG           658
     Rajasthan     CHITTORGARH           653
  Chhattisgarh          KANKER           644
Madhya Pradesh         KHANDWA           630
   Maharashtra      AHMEDNAGAR           615
 Uttar Pradesh       BARABANKI           613
         Bihar PURBI CHAMPARAN           609
   Maharashtra            BEED           588
   West Bengal PARAGANAS NORTH           586

In [292]:
climate_names = set(
    climate_final_long["District_clean"]
    .dropna()
)

remaining_pairs["District_clean"] = (
    remaining_pairs["District"]
    .astype(str)
    .apply(normalize_text)
)

remaining_pairs["Name_In_Climate"] = (
    remaining_pairs["District_clean"]
    .isin(climate_names)
)

print(
    remaining_pairs[
        "Name_In_Climate"
    ].value_counts()
)

Name_In_Climate
False    117
True      17
Name: count, dtype: int64

In [293]:
ml_dataset = final_dataset_v2[
    final_dataset_v2["Rainfall"].notna() &
    final_dataset_v2["Temperature"].notna()
].copy()

print("ML dataset shape:", ml_dataset.shape)

print(
    ml_dataset[
        [
            "State",
            "District",
            "Crop",
            "Crop_Year",
            "Season",
            "Area",
            "Production",
            "Yield",
            "Rainfall",
            "Temperature"
        ]
    ].head()
)

ML dataset shape: (252851, 19)
                         State        District      Crop  Crop_Year  \
35  Andaman and Nicobar Island  SOUTH ANDAMANS  Arecanut       2002
36  Andaman and Nicobar Island  SOUTH ANDAMANS  Arecanut       2003
37  Andaman and Nicobar Island  SOUTH ANDAMANS  Arecanut       2004
38  Andaman and Nicobar Island  SOUTH ANDAMANS  Arecanut       2005
39  Andaman and Nicobar Island  SOUTH ANDAMANS  Arecanut       2006

        Season     Area  Production  Yield     Rainfall  Temperature
35  Whole Year  3105.00      5267.0   1.70  2535.595301    26.670068
36  Whole Year  3118.00      5182.0   1.66  2394.140488    26.726048
37  Whole Year  3160.67      3975.0   1.26  3068.546323    26.806391
38  Whole Year  3250.78      3058.0   0.94  3837.727716    26.861734
39  Whole Year  2000.00      2350.0   1.18  3021.143015    26.625411

In [294]:
print(
    ml_dataset[
        [
            "State",
            "District",
            "Crop",
            "Crop_Year",
            "Season",
            "Area",
            "Production",
            "Yield",
            "Rainfall",
            "Temperature"
        ]
    ].isna().sum()
)

State          0
District       0
Crop           0
Crop_Year      0
Season         0
Area           0
Production     0
Yield          0
Rainfall       0
Temperature    0
dtype: int64

In [295]:
print("Yield missing:", ml_dataset["Yield"].isna().sum())

print(
    ml_dataset["Yield"].describe()
)

Yield missing: 0
count    252851.000000
mean         68.353132
std         835.680528
min           0.010000
25%           0.570000
50%           1.020000
75%           2.430000
max       38800.000000
Name: Yield, dtype: float64

In [296]:

print(
    "Unique crops:",
    ml_dataset["Crop"].nunique()
)

print(
    ml_dataset["Crop"].value_counts().head(30)
)

Unique crops: 55
Crop
Rice                     16042
Maize                    15182
Moong(Green Gram)        10767
Urad                     10385
Sesamum                   9364
Groundnut                 9040
Wheat                     8692
Sugarcane                 8444
Rapeseed &Mustard         8436
Arhar/Tur                 8139
Potato                    8093
Onion                     7909
Gram                      7853
Jowar                     7106
Dry chillies              6554
Bajra                     6120
Peas & beans (Pulses)     5363
Small millets             5208
Sunflower                 5033
Masoor                    4801
Barley                    4747
Cotton(lint)              4654
Linseed                   4442
Sweet potato              4335
Turmeric                  4138
Other Kharif pulses       4133
Garlic                    3999
Ragi                      3963
Soyabean                  3791
Coriander                 3686
Name: count, dtype: int64

In [297]:
print(
    ml_dataset["Crop_Year"].min(),
    ml_dataset["Crop_Year"].max()
    
)

1997 2017

In [298]:
# ============================================
# EDA - BASIC DATA VALIDATION
# ============================================

print("Shape:", ml_dataset.shape)

print("\nColumns:")
print(ml_dataset.columns.tolist())

print("\nData types:")
print(ml_dataset.dtypes)

print("\nMissing values:")
print(ml_dataset.isna().sum())

print("\nDuplicate rows:")
print(ml_dataset.duplicated().sum())

print("\nUnique values:")
print("States:", ml_dataset["State"].nunique())
print("Districts:", ml_dataset["District"].nunique())
print("Crops:", ml_dataset["Crop"].nunique())
print("Seasons:", ml_dataset["Season"].nunique())
print("Years:", ml_dataset["Crop_Year"].nunique())

Shape: (252851, 19)

Columns:
['State', 'District', 'Crop', 'Crop_Year', 'Season', 'Area', 'Production', 'Yield', 'State_clean', 'District_clean', 'Year', 'Climate_State_clean', 'Climate_District_clean', 'Merge_State', 'Merge_District', 'State_clean_climate', 'District_clean_climate', 'Rainfall', 'Temperature']

Data types:
State                         str
District                      str
Crop                          str
Crop_Year                   int64
Season                        str
Area                      float64
Production                float64
Yield                     float64
State_clean                   str
District_clean                str
Year                        Int64
Climate_State_clean           str
Climate_District_clean        str
Merge_State                   str
Merge_District                str
State_clean_climate           str
District_clean_climate        str
Rainfall                  float64
Temperature               float64
dtype: object

Missing values:
State                          0
District                       0
Crop                           0
Crop_Year                      0
Season                         0
Area                           0
Production                     0
Yield                          0
State_clean                    0
District_clean                 0
Year                           0
Climate_State_clean       244996
Climate_District_clean    244996
Merge_State                    0
Merge_District                 0
State_clean_climate            0
District_clean_climate         0
Rainfall                       0
Temperature                    0
dtype: int64

Duplicate rows:
0

Unique values:
States: 33
Districts: 577
Crops: 55
Seasons: 6
Years: 21

In [299]:
print(
    ml_dataset[
        [
            "Area",
            "Production",
            "Yield",
            "Rainfall",
            "Temperature"
        ]
    ].describe()
)

               Area    Production          Yield       Rainfall    Temperature
count  2.528510e+05  2.528510e+05  252851.000000  252851.000000  252851.000000
mean   1.205476e+04  9.906186e+05      68.353132    1292.523736      24.995436
std    4.475100e+04  2.160165e+07     835.680528     765.767565       3.529735
min    8.000000e-02  1.000000e+00       0.010000      37.049886      -3.143808
25%    9.000000e+01  1.000000e+02       0.570000     818.161575      24.805856
50%    6.130000e+02  8.000000e+02       1.020000    1097.866745      25.742969
75%    4.556000e+03  7.400000e+03       2.430000    1520.125145      26.629394
max    8.580100e+06  1.597800e+09   38800.000000    9751.900021      29.657743

In [300]:
print("Area <= 0:", (ml_dataset["Area"] <= 0).sum())

Area <= 0: 0

In [301]:
print(
    "Production < 0:",
    (ml_dataset["Production"] < 0).sum()
)

Production < 0: 0

In [302]:
print("Yield <= 0:", (ml_dataset["Yield"] <= 0).sum())

Yield <= 0: 0

In [303]:
print(
    "Rainfall < 0:",
    (ml_dataset["Rainfall"] < 0).sum()
)

Rainfall < 0: 0

In [304]:
print(
    "Temperature outside -20 to 60:",
    (
        (ml_dataset["Temperature"] < -20) |
        (ml_dataset["Temperature"] > 60)
    ).sum()
)

Temperature outside -20 to 60: 0

In [305]:
ml_dataset["Calculated_Yield"] = (
    ml_dataset["Production"] /
    ml_dataset["Area"]
)

ml_dataset["Yield_Difference"] = (
    ml_dataset["Yield"] -
    ml_dataset["Calculated_Yield"]
)

print(
    ml_dataset["Yield_Difference"].describe()
)

count    252851.000000
mean         -0.000316
std           0.018256
min          -5.870000
25%          -0.002193
50%           0.000000
75%           0.002222
max           0.400000
Name: Yield_Difference, dtype: float64

In [306]:
print(
    ml_dataset[
        abs(ml_dataset["Yield_Difference"]) > 0.1
    ][
        [
            "Crop",
            "Area",
            "Production",
            "Yield",
            "Calculated_Yield",
            "Yield_Difference"
        ]
    ].head(20)
)

                         Crop  Area  Production  Yield  Calculated_Yield  \
363                 Groundnut   1.2         1.0   0.50          0.833333
424            Oilseeds total   1.6         1.0   0.75          0.625000
445         Rapeseed &Mustard   0.8         1.0   0.88          1.250000
446         Rapeseed &Mustard   1.0         1.0   0.76          1.000000
555                 Sunflower   1.0         1.0   0.50          1.000000
58915                Sannhamp   2.0         6.0   2.78          3.000000
59027                Sannhamp   1.0         6.0   5.55          6.000000
64066                  Masoor   1.0         2.0   1.50          2.000000
79467                    Ragi   2.0         3.0   1.34          1.500000
100411           Cotton(lint)   1.0         1.0   0.50          1.000000
100412           Cotton(lint)   4.0         2.0   0.39          0.500000
100430           Cotton(lint)   1.0         1.0   0.50          1.000000
100485           Dry chillies   2.0         1.0   0.27          0.500000
100783                 Ginger   2.0         5.0   2.29          2.500000
100818                 Ginger   1.0         2.0   2.29          2.000000
101105              Groundnut   2.0         2.0   0.75          1.000000
102015                   Moth   2.0         1.0   0.25          0.500000
102016                   Moth   1.0         1.0   0.50          1.000000
102393  Peas & beans (Pulses)   2.0         1.0   0.25          0.500000
104170                Tobacco   0.5         1.0   1.20          2.000000

        Yield_Difference
363            -0.333333
424             0.125000
445            -0.370000
446            -0.240000
555            -0.500000
58915          -0.220000
59027          -0.450000
64066          -0.500000
79467          -0.160000
100411         -0.500000
100412         -0.110000
100430         -0.500000
100485         -0.230000
100783         -0.210000
100818          0.290000
101105         -0.250000
102015         -0.250000
102016         -0.500000
102393         -0.250000
104170         -0.800000

In [307]:
print(
    ml_dataset["Crop"]
    .value_counts()
    .head(30)
)

Crop
Rice                     16042
Maize                    15182
Moong(Green Gram)        10767
Urad                     10385
Sesamum                   9364
Groundnut                 9040
Wheat                     8692
Sugarcane                 8444
Rapeseed &Mustard         8436
Arhar/Tur                 8139
Potato                    8093
Onion                     7909
Gram                      7853
Jowar                     7106
Dry chillies              6554
Bajra                     6120
Peas & beans (Pulses)     5363
Small millets             5208
Sunflower                 5033
Masoor                    4801
Barley                    4747
Cotton(lint)              4654
Linseed                   4442
Sweet potato              4335
Turmeric                  4138
Other Kharif pulses       4133
Garlic                    3999
Ragi                      3963
Soyabean                  3791
Coriander                 3686
Name: count, dtype: int64

In [308]:
print(
    "Smallest crop count:"
)

print(
    ml_dataset["Crop"]
    .value_counts()
    .tail(20)
)

Smallest crop count:
Crop
Tobacco                2935
Sannhamp               2111
Niger seed             1887
Coconut                1860
Tapioca                1756
Mesta                  1712
Guar seed              1631
Arecanut               1520
Jute                   1330
Khesari                1262
Safflower              1167
Cashewnut              1096
Moth                   1080
Black pepper            992
Other Cereals           914
Cowpea(Lobia)           856
other oilseeds          823
Oilseeds total          368
Cardamom                347
Other Summer Pulses      25
Name: count, dtype: int64

In [309]:
# ============================================
# CREATE FINAL ML DATASET
# ============================================

model_df = final_dataset_v2[
    [
        "State",
        "District",
        "Crop",
        "Crop_Year",
        "Season",
        "Area",
        "Rainfall",
        "Temperature",
        "Yield"
    ]
].copy()

print("Model dataset:", model_df.shape)

print("\nMissing values:")
print(model_df.isna().sum())

print("\nDuplicates:")
print(model_df.duplicated().sum())

Model dataset: (338483, 9)

Missing values:
State              0
District           0
Crop               0
Crop_Year          0
Season             0
Area               0
Rainfall       85632
Temperature    85632
Yield              0
dtype: int64

Duplicates:
0

In [310]:
model_df = model_df[
    (model_df["Area"] > 0) &
    (model_df["Rainfall"] >= 0) &
    (model_df["Yield"] > 0)
].copy()

print("After validation:", model_df.shape)

After validation: (252851, 9)

In [311]:
print(
    model_df.nlargest(
        20,
        "Yield"
    )[
        [
            "State",
            "District",
            "Crop",
            "Crop_Year",
            "Season",
            "Area",
            "Yield"
        ]
    ].to_string(index=False)
)

         State        District    Crop  Crop_Year     Season    Area    Yield
   West Bengal         BIRBHUM Coconut       2006 Whole Year   509.0 38800.00
    Tamil Nadu           ERODE Coconut       2008 Whole Year 10014.0 33133.61
         Assam        TINSUKIA Coconut       2015 Whole Year    75.0 30093.33
         Assam        TINSUKIA Coconut       2016 Whole Year    76.0 28789.47
         Assam          KAMRUP Coconut       2005 Whole Year  2026.0 28334.16
         Assam       LAKHIMPUR Coconut       2001 Whole Year   192.0 26270.83
    Tamil Nadu           THENI Coconut       2005 Whole Year 15342.0 25739.80
         Assam          JORHAT Coconut       2016 Whole Year   453.0 25430.46
    Tamil Nadu TIRUCHIRAPPALLI Coconut       2008 Whole Year  6703.0 24630.76
    Tamil Nadu       THANJAVUR Coconut       2011 Whole Year 33742.0 24414.68
         Assam        GOLAGHAT Coconut       2005 Whole Year   658.0 24410.33
Andhra Pradesh        PRAKASAM Coconut       2017 Whole Year    21.0 23809.52
    Tamil Nadu      THIRUVARUR Coconut       2007 Whole Year  5374.0 23502.05
    Tamil Nadu       CUDDALORE Coconut       2016 Whole Year  1640.0 23231.71
    Tamil Nadu   KANNIYAKUMARI Coconut       2014 Whole Year 24232.0 23213.11
    Tamil Nadu    NAGAPATTINAM Coconut       2009 Whole Year  4105.0 23020.71
    Tamil Nadu       THANJAVUR Coconut       2015 Whole Year 37210.0 22824.51
    Tamil Nadu TIRUCHIRAPPALLI Coconut       2009 Whole Year  6490.0 22804.31
         Assam        GOLAGHAT Coconut       2006 Whole Year   612.0 22148.69
         Assam        GOLAGHAT Coconut       2007 Whole Year   639.0 21954.62

In [312]:
print(
    model_df["Yield"].quantile(
        [0.90, 0.95, 0.99, 0.995, 0.999]
    )
)

0.900       10.4300
0.950       25.0000
0.990       96.4900
0.995     5939.2225
0.999    13868.7750
Name: Yield, dtype: float64

In [313]:
coconut = model_df[
    model_df["Crop"].str.strip().str.lower() == "coconut"
].copy()

print("Coconut rows:", len(coconut))

print(
    coconut["Yield"].describe(
        percentiles=[.50, .75, .90, .95, .99, .995, .999]
    )
)

Coconut rows: 1860
count     1860.000000
mean      8669.126231
std       4509.811680
min          2.500000
50%       7818.075000
75%      11281.802500
90%      14629.942000
95%      16700.728500
99%      22034.188700
99.5%    24413.396750
99.9%    30522.009480
max      38800.000000
Name: Yield, dtype: float64

In [314]:
print(
    coconut.nlargest(
        30,
        "Yield"
    )[
        [
            "State",
            "District",
            "Crop_Year",
            "Area",
            "Yield"
        ]
    ].to_string(index=False)
)

         State        District  Crop_Year    Area    Yield
   West Bengal         BIRBHUM       2006   509.0 38800.00
    Tamil Nadu           ERODE       2008 10014.0 33133.61
         Assam        TINSUKIA       2015    75.0 30093.33
         Assam        TINSUKIA       2016    76.0 28789.47
         Assam          KAMRUP       2005  2026.0 28334.16
         Assam       LAKHIMPUR       2001   192.0 26270.83
    Tamil Nadu           THENI       2005 15342.0 25739.80
         Assam          JORHAT       2016   453.0 25430.46
    Tamil Nadu TIRUCHIRAPPALLI       2008  6703.0 24630.76
    Tamil Nadu       THANJAVUR       2011 33742.0 24414.68
         Assam        GOLAGHAT       2005   658.0 24410.33
Andhra Pradesh        PRAKASAM       2017    21.0 23809.52
    Tamil Nadu      THIRUVARUR       2007  5374.0 23502.05
    Tamil Nadu       CUDDALORE       2016  1640.0 23231.71
    Tamil Nadu   KANNIYAKUMARI       2014 24232.0 23213.11
    Tamil Nadu    NAGAPATTINAM       2009  4105.0 23020.71
    Tamil Nadu       THANJAVUR       2015 37210.0 22824.51
    Tamil Nadu TIRUCHIRAPPALLI       2009  6490.0 22804.31
         Assam        GOLAGHAT       2006   612.0 22148.69
         Assam        GOLAGHAT       2007   639.0 21954.62
         Assam        TINSUKIA       2017    76.0 21842.11
    Tamil Nadu           THENI       2009 18173.0 21691.52
    Tamil Nadu      THIRUVARUR       2011  4916.0 21623.27
    Tamil Nadu      DHARMAPURI       2009  6926.0 21570.89
    Tamil Nadu        DINDIGUL       2008 25708.0 21545.82
    Tamil Nadu      DHARMAPURI       2006  9781.0 21429.30
    Tamil Nadu   KANNIYAKUMARI       2015 24182.0 21321.64
Andhra Pradesh      SRIKAKULAM       2012 14421.0 21285.00
     Telangana         KHAMMAM       2014   437.0 21105.00
     Telangana      RANGAREDDI       2014     2.0 21105.00

In [315]:
print(
    final_dataset_v2[
        (final_dataset_v2["Crop"].str.strip().str.lower() == "coconut") &
        (final_dataset_v2["Yield"] > 100)
    ][
        [
            "State",
            "District",
            "Crop_Year",
            "Area",
            "Production",
            "Yield"
        ]
    ].head(30).to_string(index=False)
)

                     State                 District  Crop_Year     Area  Production   Yield
Andaman and Nicobar Island                 NICOBARS       2007 21636.00  80640000.0 3727.12
Andaman and Nicobar Island                 NICOBARS       2008 43380.00  81900000.0 1887.97
Andaman and Nicobar Island                 NICOBARS       2009 43520.00  84970000.0 1952.44
Andaman and Nicobar Island                 NICOBARS       2000 18168.00  65100000.0 3583.22
Andaman and Nicobar Island                 NICOBARS       2001 18190.00  64430000.0 3542.06
Andaman and Nicobar Island                 NICOBARS       2002 18240.00  67490000.0 3700.11
Andaman and Nicobar Island                 NICOBARS       2003 18284.74  68580000.0 3750.67
Andaman and Nicobar Island                 NICOBARS       2004 18394.70  52380000.0 2847.56
Andaman and Nicobar Island                 NICOBARS       2005 13876.57  52030000.0 3749.49
Andaman and Nicobar Island                 NICOBARS       2006 14358.00  59370000.0 4134.98
Andaman and Nicobar Island                 NICOBARS       2010 14560.00  71300000.0 4896.98
Andaman and Nicobar Island                 NICOBARS       2011 14590.00  69700000.0 4777.24
Andaman and Nicobar Island                 NICOBARS       2012 14650.00  89800000.0 6129.69
Andaman and Nicobar Island                 NICOBARS       2013 14655.00  96200000.0 6564.31
Andaman and Nicobar Island                 NICOBARS       2014 14673.00  95300000.0 6494.92
Andaman and Nicobar Island                 NICOBARS       2015 14676.00  94500000.0 6439.08
Andaman and Nicobar Island                 NICOBARS       2016 14840.00  96200000.0 6482.48
Andaman and Nicobar Island                 NICOBARS       2017 13695.00  98130000.0 7165.39
Andaman and Nicobar Island                 NICOBARS       2018 13728.00  70360000.0 5125.29
Andaman and Nicobar Island                 NICOBARS       2019 15728.00  89060000.0 5662.51
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2000  6992.00  23900000.0 3418.19
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2001  7015.00  25250000.0 3599.43
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2006  3575.00  15400000.0 4307.69
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2010  3668.00  12700000.0 3462.38
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2011  3668.00  15600000.0 4253.00
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2012  3675.00  17800000.0 4843.54
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2013  3685.00  16800000.0 4559.02
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2014  3675.00  17400000.0 4734.69
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2015  3675.00  19500000.0 5306.12
Andaman and Nicobar Island NORTH AND MIDDLE ANDAMAN       2016  3675.00  20000000.0 5442.18

In [316]:
# ============================================
# FEATURE ENGINEERING
# ============================================

import numpy as np
import pandas as pd

model_df = final_dataset_v2[
    [
        "State",
        "District",
        "Crop",
        "Crop_Year",
        "Season",
        "Area",
        "Rainfall",
        "Temperature",
        "Yield"
    ]
].copy()

# Clean categorical columns
for col in ["State", "District", "Crop", "Season"]:
    model_df[col] = (
        model_df[col]
        .astype(str)
        .str.strip()
    )

# Numeric columns
numeric_cols = [
    "Crop_Year",
    "Area",
    "Rainfall",
    "Temperature",
    "Yield"
]

for col in numeric_cols:
    model_df[col] = pd.to_numeric(
        model_df[col],
        errors="coerce"
    )

# Remove invalid rows
model_df = model_df.dropna()

model_df = model_df[
    (model_df["Area"] > 0) &
    (model_df["Rainfall"] >= 0) &
    (model_df["Yield"] > 0)
].copy()

# Log-transform target
model_df["Log_Yield"] = np.log1p(
    model_df["Yield"]
)

print("Final model data:", model_df.shape)

print(
    model_df[
        [
            "Crop",
            "State",
            "District",
            "Season",
            "Crop_Year",
            "Area",
            "Rainfall",
            "Temperature",
            "Yield",
            "Log_Yield"
        ]
    ].head()
)

print("\nLog target statistics:")
print(
    model_df["Log_Yield"].describe()
)

Final model data: (252851, 10)
        Crop                       State        District      Season  \
35  Arecanut  Andaman and Nicobar Island  SOUTH ANDAMANS  Whole Year
36  Arecanut  Andaman and Nicobar Island  SOUTH ANDAMANS  Whole Year
37  Arecanut  Andaman and Nicobar Island  SOUTH ANDAMANS  Whole Year
38  Arecanut  Andaman and Nicobar Island  SOUTH ANDAMANS  Whole Year
39  Arecanut  Andaman and Nicobar Island  SOUTH ANDAMANS  Whole Year

    Crop_Year     Area     Rainfall  Temperature  Yield  Log_Yield
35       2002  3105.00  2535.595301    26.670068   1.70   0.993252
36       2003  3118.00  2394.140488    26.726048   1.66   0.978326
37       2004  3160.67  3068.546323    26.806391   1.26   0.815365
38       2005  3250.78  3837.727716    26.861734   0.94   0.662688
39       2006  2000.00  3021.143015    26.625411   1.18   0.779325

Log target statistics:
count    252851.000000
mean          1.081381
std           1.122770
min           0.009950
25%           0.451076
50%           0.703098
75%           1.232560
max          10.566201
Name: Log_Yield, dtype: float64

In [317]:
from sklearn.model_selection import train_test_split

# Features
X = model_df[
    [
        "State",
        "District",
        "Crop",
        "Season",
        "Crop_Year",
        "Area",
        "Rainfall",
        "Temperature"
    ]
].copy()

# Target
y = model_df["Log_Yield"].copy()

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (252851, 8)
y shape: (252851,)

In [318]:
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

print("X_train:", X_train.shape)
print("X_test :", X_test.shape)
print("y_train:", y_train.shape)
print("y_test :", y_test.shape)

X_train: (202280, 8)
X_test : (50571, 8)
y_train: (202280,)
y_test : (50571,)

In [319]:
!pip install catboost

Requirement already satisfied: catboost in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (1.2.10)
Requirement already satisfied: graphviz in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (0.21)
Requirement already satisfied: matplotlib in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (3.11.1)
Requirement already satisfied: numpy<3.0,>=1.16.0 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (2.5.2)
Requirement already satisfied: pandas<4.0,>=0.24 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (3.0.5)
Requirement already satisfied: scipy in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (1.18.0)
Requirement already satisfied: plotly in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (6.9.0)
Requirement already satisfied: six in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in D:\Shubham Project\smart-crop-ai-project\smart-crop-ai\venv\Lib\site-packages (from plotly->catboost) (2.24.0)

In [321]:
import catboost

print("CatBoost version:", catboost.__version__)

CatBoost version: 1.2.10

In [2]:
import sys
!{sys.executable} -m pip install catboost

Collecting catboost
  Using cached catboost-1.2.10-cp314-cp314-win_amd64.whl.metadata (1.5 kB)
Collecting graphviz (from catboost)
  Using cached graphviz-0.21-py3-none-any.whl.metadata (12 kB)
Requirement already satisfied: matplotlib in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from catboost) (3.11.1)
Requirement already satisfied: numpy<3.0,>=1.16.0 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from catboost) (2.5.2)
Requirement already satisfied: pandas<4.0,>=0.24 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from catboost) (3.0.5)
Requirement already satisfied: scipy in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from catboost) (1.18.0)
Collecting plotly (from catboost)
  Using cached plotly-6.9.0-py3-none-any.whl.metadata (9.0 kB)
Requirement already satisfied: six in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from catboost) (1.17.0)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from pandas<4.0,>=0.24->catboost) (2026.3)
Requirement already satisfied: contourpy>=1.0.1 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (1.3.3)
Requirement already satisfied: cycler>=0.10 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (0.12.1)
Requirement already satisfied: fonttools>=4.28.2 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (4.63.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (1.5.0)
Requirement already satisfied: packaging>=20.0 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (26.3)
Requirement already satisfied: pillow>=9 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (12.3.0)
Requirement already satisfied: pyparsing>=3 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from matplotlib->catboost) (3.3.2)
Requirement already satisfied: narwhals>=1.15.1 in c:\Users\Lenovo\Downloads\smart-crop-ai\venv\Lib\site-packages (from plotly->catboost) (2.24.0)
Using cached catboost-1.2.10-cp314-cp314-win_amd64.whl (101.7 MB)
Using cached graphviz-0.21-py3-none-any.whl (47 kB)
Using cached plotly-6.9.0-py3-none-any.whl (9.9 MB)
Installing collected packages: plotly, graphviz, catboost

   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ---------------------------------------- 0/3 [plotly]
   ------------- -------------------------- 1/3 [graphviz]
   ------------- -------------------------- 1/3 [graphviz]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   -------------------------- ------------- 2/3 [catboost]
   ---------------------------------------- 3/3 [catboost]

Successfully installed catboost-1.2.10 graphviz-0.21 plotly-6.9.0

In [320]:
import catboost
print(catboost.__version__)

1.2.10

In [322]:
import numpy as np
import pandas as pd

model_df = final_dataset_v2[
    [
        "State",
        "District",
        "Crop",
        "Crop_Year",
        "Season",
        "Area",
        "Rainfall",
        "Temperature",
        "Yield"
    ]
].copy()

for col in ["State", "District", "Crop", "Season"]:
    model_df[col] = (
        model_df[col]
        .astype(str)
        .str.strip()
    )

for col in [
    "Crop_Year",
    "Area",
    "Rainfall",
    "Temperature",
    "Yield"
]:
    model_df[col] = pd.to_numeric(
        model_df[col],
        errors="coerce"
    )

model_df = model_df.dropna()

model_df = model_df[
    (model_df["Area"] > 0) &
    (model_df["Rainfall"] >= 0) &
    (model_df["Yield"] > 0)
].copy()

model_df["Log_Yield"] = np.log1p(
    model_df["Yield"]
)

print("Final model data:", model_df.shape)

Final model data: (252851, 10)

In [323]:
X = model_df[
    [
        "State",
        "District",
        "Crop",
        "Season",
        "Crop_Year",
        "Area",
        "Rainfall",
        "Temperature"
    ]
]

y = model_df["Log_Yield"]

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42
)

In [324]:
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

cat_features = [
    "State",
    "District",
    "Crop",
    "Season"
]

model = CatBoostRegressor(
    iterations=1000,
    learning_rate=0.05,
    depth=8,
    loss_function="RMSE",
    eval_metric="RMSE",
    random_seed=42,
    verbose=100
)

model.fit(
    X_train,
    y_train,
    cat_features=cat_features,
    eval_set=(X_test, y_test),
    early_stopping_rounds=100
)

0:	learn: 1.0776289	test: 1.0715086	best: 1.0715086 (0)	total: 220ms	remaining: 3m 39s
100:	learn: 0.2976811	test: 0.2897122	best: 0.2897122 (100)	total: 9.25s	remaining: 1m 22s
200:	learn: 0.2690775	test: 0.2631873	best: 0.2631873 (200)	total: 20.6s	remaining: 1m 21s
300:	learn: 0.2555864	test: 0.2515169	best: 0.2515169 (300)	total: 30.8s	remaining: 1m 11s
400:	learn: 0.2458497	test: 0.2438831	best: 0.2438831 (400)	total: 39.7s	remaining: 59.3s
500:	learn: 0.2381585	test: 0.2381006	best: 0.2381006 (500)	total: 49.1s	remaining: 48.9s
600:	learn: 0.2322515	test: 0.2334967	best: 0.2334967 (600)	total: 58.4s	remaining: 38.8s
700:	learn: 0.2278926	test: 0.2304694	best: 0.2304694 (700)	total: 1m 7s	remaining: 28.8s
800:	learn: 0.2238369	test: 0.2275713	best: 0.2275713 (800)	total: 1m 16s	remaining: 19.1s
900:	learn: 0.2204278	test: 0.2253941	best: 0.2253941 (900)	total: 1m 26s	remaining: 9.48s
999:	learn: 0.2173874	test: 0.2233603	best: 0.2233603 (999)	total: 1m 35s	remaining: 0us

bestTest = 0.2233603252
bestIteration = 999

CatBoostRegressor(depth=8, eval_metric='RMSE', iterations=1000, learning_rate=0.05, loss_function='RMSE', random_seed=42, verbose=100)

In [325]:
# ============================================
# CATBOOST EVALUATION
# ============================================

from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
import numpy as np

# Predict log(Yield)
pred_log = model.predict(X_test)

# Convert back to original Yield
pred_yield = np.expm1(pred_log)
actual_yield = np.expm1(y_test)

# Metrics
mae = mean_absolute_error(
    actual_yield,
    pred_yield
)

rmse = np.sqrt(
    mean_squared_error(
        actual_yield,
        pred_yield
    )
)

r2 = r2_score(
    actual_yield,
    pred_yield
)

print("================================")
print("       CATBOOST RESULTS")
print("================================")
print(f"MAE  : {mae:.4f}")
print(f"RMSE : {rmse:.4f}")
print(f"R²   : {r2:.4f}")

================================
       CATBOOST RESULTS
================================
MAE  : 18.3038
RMSE : 302.3466
R²   : 0.8690

In [326]:
comparison = X_test.copy()

comparison["Actual_Yield"] = actual_yield
comparison["Predicted_Yield"] = pred_yield

comparison["Error"] = (
    comparison["Actual_Yield"] -
    comparison["Predicted_Yield"]
)

print(
    comparison[
        [
            "Crop",
            "State",
            "District",
            "Actual_Yield",
            "Predicted_Yield",
            "Error"
        ]
    ].head(20).to_string(index=False)
)

                 Crop          State            District  Actual_Yield  Predicted_Yield     Error
            Arhar/Tur      Karnataka             RAICHUR          0.27         0.229407  0.040593
            Sugarcane  Uttar Pradesh               GONDA         57.71        62.621809 -4.911809
            Groundnut         Odisha             BARGARH          1.31         1.298381  0.011619
           Niger seed      Karnataka              HAVERI          0.22         0.386461 -0.166461
         Dry chillies        Gujarat            VADODARA          0.75         0.798929 -0.048929
                 Moth      Rajasthan           RAJSAMAND          0.40         0.406754 -0.006754
    Moong(Green Gram)         Odisha           SAMBALPUR          0.58         0.467929  0.112071
                 Rice  Uttar Pradesh GAUTAM BUDDHA NAGAR          2.44         2.911145 -0.471145
                Jowar Madhya Pradesh             SHAHDOL          2.15         1.406014  0.743986
                 Gram Madhya Pradesh               SIDHI          0.59         0.644825 -0.054825
                Mesta        Tripura              GOMATI          7.92         8.098820 -0.178820
                 Ragi          Bihar         MUZAFFARPUR          0.69         0.858749 -0.168749
               Potato  Uttar Pradesh           BALRAMPUR         26.58        17.128377  9.451623
Peas & beans (Pulses)    Uttarakhand       TEHRI GARHWAL          0.55         0.743590 -0.193590
                 Rice          Assam          DIMA HASAO          2.66         2.048935  0.611065
                Maize   Chhattisgarh            BILASPUR          1.32         1.469732 -0.149732
        Small millets    Maharashtra          GADCHIROLI          1.00         0.509491  0.490509
               Masoor  Uttar Pradesh              RAMPUR          0.95         0.782227  0.167773
            Sunflower      Rajasthan               AJMER          0.38         0.724815 -0.344815
                 Rice    West Bengal             BIRBHUM          3.33         3.146981  0.183019

In [327]:

# ============================================
# ROBUST EVALUATION
# ============================================

evaluation = pd.DataFrame({
    "Actual": actual_yield,
    "Predicted": pred_yield
})

# Normal-yield records
normal = evaluation[
    evaluation["Actual"] <= 100
].copy()

mae_normal = mean_absolute_error(
    normal["Actual"],
    normal["Predicted"]
)

rmse_normal = np.sqrt(
    mean_squared_error(
        normal["Actual"],
        normal["Predicted"]
    )
)

r2_normal = r2_score(
    normal["Actual"],
    normal["Predicted"]
)

print("Records with Yield <= 100:", len(normal))

print("\n===== NORMAL YIELD RESULTS =====")
print(f"MAE  : {mae_normal:.4f}")
print(f"RMSE : {rmse_normal:.4f}")
print(f"R²   : {r2_normal:.4f}")

Records with Yield <= 100: 50093

===== NORMAL YIELD RESULTS =====
MAE  : 0.9421
RMSE : 3.1066
R²   : 0.9187

In [328]:
importance = pd.DataFrame({
    "Feature": X_train.columns,
    "Importance": model.get_feature_importance()
})

importance = importance.sort_values(
    "Importance",
    ascending=False
)

print(
    importance.to_string(index=False)
)

    Feature  Importance
       Crop   62.452724
      State   14.224932
     Season   10.676863
  Crop_Year    3.843248
       Area    3.209292
   District    2.025888
Temperature    1.817918
   Rainfall    1.749135

In [329]:
import os

os.makedirs("../models", exist_ok=True)

model.save_model(
    "../models/crop_yield_catboost.cbm"
)

print("Model saved successfully.")

Model saved successfully.

In [330]:
import os

model_path = "../models/crop_yield_catboost.cbm"

print("Exists:", os.path.exists(model_path))

if os.path.exists(model_path):
    print(
        "Size:",
        round(os.path.getsize(model_path) / (1024 * 1024), 2),
        "MB"
    )

Exists: True
Size: 19.76 MB

In [331]:
import json

model_config = {
    "features": [
        "State",
        "District",
        "Crop",
        "Season",
        "Crop_Year",
        "Area",
        "Rainfall",
        "Temperature"
    ],
    "categorical_features": [
        "State",
        "District",
        "Crop",
        "Season"
    ],
    "target": "Yield",
    "target_transform": "log1p",
    "prediction_transform": "expm1"
}

with open(
    "../models/model_config.json",
    "w"
) as f:
    json.dump(
        model_config,
        f,
        indent=4
    )

print("Configuration saved.")

Configuration saved.

In [332]:
from catboost import CatBoostRegressor
import numpy as np

loaded_model = CatBoostRegressor()

loaded_model.load_model(
    "../models/crop_yield_catboost.cbm"
)

print("Model loaded successfully.")

Model loaded successfully.

In [333]:
test_row = X_test.iloc[[0]].copy()

print("Input:")
print(test_row)

pred_log = loaded_model.predict(test_row)

predicted_yield = np.expm1(pred_log[0])

print("\nPredicted Yield:", predicted_yield)
print("Actual Yield:", np.expm1(y_test.iloc[0]))

Input:
            State District       Crop  Season  Crop_Year     Area    Rainfall  \
114813  Karnataka  RAICHUR  Arhar/Tur  Kharif       2002  12569.0  379.748344

        Temperature
114813    27.406035

Predicted Yield: 0.22940702600834706
Actual Yield: 0.27

In [334]:
import os
import shutil

os.makedirs("../backend/model", exist_ok=True)

shutil.copy(
    "../models/crop_yield_catboost.cbm",
    "../backend/model/crop_yield_catboost.cbm"
)

shutil.copy(
    "../models/model_config.json",
    "../backend/model/model_config.json"
)

print("Model copied to backend.")

Model copied to backend.

In [335]:
print(
    os.path.exists(
        "../backend/model/crop_yield_catboost.cbm"
    )
)

print(
    os.path.exists(
        "../backend/model/model_config.json"
    )
)

True
True

In [336]:
# =========================================================
# CREATE DISTRICT CLIMATE LOOKUP
# =========================================================

import pandas as pd
import os

climate_lookup = (
    climate
    .groupby("District", as_index=False)
    .agg(
        Rainfall=("Rainfall", "mean"),
        Temperature=("Temperature", "mean")
    )
)

print("Climate lookup:", climate_lookup.shape)
print(climate_lookup.head())

KeyError: 'District'

In [337]:
print("Shape:", climate.shape)
print("Columns:")
print(climate.columns.tolist())
print("\nFirst 5 rows:")
print(climate.head())

Shape: (735, 14712)
Columns:

In [338]:
for name in [
    "climate",
    "climate_long",
    "climate_geo_reference"
]:
    if name in globals():
        df = globals()[name]
        print("\n==============================")
        print(name)
        print("Shape:", df.shape)
        print("Columns:", df.columns.tolist())

==============================
climate
Shape: (735, 14712)

In [339]:
# =========================================================
# CREATE CLIMATE LOOKUP FROM FINAL MODEL DATA
# =========================================================

climate_lookup = (
    final_dataset_v2[
        [
            "State",
            "District",
            "Rainfall",
            "Temperature"
        ]
    ]
    .dropna(subset=["State", "District", "Rainfall", "Temperature"])
    .groupby(
        ["State", "District"],
        as_index=False
    )
    .agg(
        Rainfall=("Rainfall", "mean"),
        Temperature=("Temperature", "mean")
    )
)

print("Climate lookup shape:", climate_lookup.shape)

print(
    climate_lookup.head(10).to_string(index=False)
)

Climate lookup shape: (614, 4)
                     State       District    Rainfall  Temperature
Andaman and Nicobar Island SOUTH ANDAMANS 3230.281034    26.974286
            Andhra Pradesh       ADILABAD 1071.718488    27.272061
            Andhra Pradesh      ANANTAPUR  628.394081    27.141506
            Andhra Pradesh       CHITTOOR  956.421988    26.871419
            Andhra Pradesh  EAST GODAVARI 1168.035166    27.168619
            Andhra Pradesh         GUNTUR  841.775323    28.596489
            Andhra Pradesh     KARIMNAGAR  975.029301    27.620658
            Andhra Pradesh        KRISHNA  991.694588    28.637239
            Andhra Pradesh        KURNOOL  659.795739    27.701029
            Andhra Pradesh          MEDAK  971.309218    26.805089

In [340]:
print(
    climate_lookup[
        (climate_lookup["State"] == "Karnataka") &
        (climate_lookup["District"] == "RAICHUR")
    ].to_string(index=False)
)

    State District   Rainfall  Temperature
Karnataka  RAICHUR 619.339563    27.235532

In [341]:
import os

os.makedirs("../backend/data", exist_ok=True)

climate_lookup.to_csv(
    "../backend/data/climate_lookup.csv",
    index=False
)

print("Saved successfully.")
print(
    "Path:",
    "../backend/data/climate_lookup.csv"
)

Saved successfully.
Path: ../backend/data/climate_lookup.csv

In [342]:
import os

path = "../backend/data/climate_lookup.csv"

print("Exists:", os.path.exists(path))

if os.path.exists(path):
    print(
        "Rows:",
        len(climate_lookup)
    )

Exists: True
Rows: 614

In [343]:
print(climate_lookup.shape)

print(
    climate_lookup[
        (climate_lookup["State"] == "Karnataka") &
        (climate_lookup["District"] == "RAICHUR")
    ]
)

(614, 4)
         State District    Rainfall  Temperature
242  Karnataka  RAICHUR  619.339563    27.235532